<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_cer.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Home Ground's places for a bed sown with spires (`Cer`), in each of its three beds.
 *
 * The grain: spires in a stand, three across at 0.40 m and nine rows 0.45 m
 * apart, twenty-seven a bed. The rows follow the bed's line, which sways in a
 * lazy S (`_home_ground.py` says how), and run square to it. Bed by bed, west
 * to east as the table draws it, and in each bed in `HomeGround.Slot`'s order:
 * from the north end, row by row, west to east along each row. A bed fills from
 * both ends, so this is the rule's order, not a fill order.
 */
final class HomeGroundCerTable
{
    public const NAME = 'home_ground_cer';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['bed', 'index'];

    /** The places of each feature variant, in fill order: [x, z, bed, index]. */
    public const PLACES = [
        [
            [-2.055, -1.867, 0, 0],
            [-1.662, -1.793, 0, 1],
            [-1.269, -1.719, 0, 2],
            [-2.124, -1.386, 0, 3],
            [-1.726, -1.348, 0, 4],
            [-1.328, -1.310, 0, 5],
            [-2.145, -0.894, 0, 6],
            [-1.745, -0.899, 0, 7],
            [-1.345, -0.904, 0, 8],
            [-2.112, -0.402, 0, 9],
            [-1.715, -0.450, 0, 10],
            [-1.318, -0.498, 0, 11],
            [-2.032, 0.077, 0, 12],
            [-1.641, -0.006, 0, 13],
            [-1.250, -0.089, 0, 14],
            [-1.925, 0.528, 0, 15],
            [-1.537, 0.432, 0, 16],
            [-1.149, 0.335, 0, 17],
            [-1.855, 0.889, 0, 18],
            [-1.456, 0.873, 0, 19],
            [-1.056, 0.858, 0, 20],
            [-1.894, 1.239, 0, 21],
            [-1.502, 1.319, 0, 22],
            [-1.110, 1.399, 0, 23],
            [-1.976, 1.716, 0, 24],
            [-1.578, 1.762, 0, 25],
            [-1.181, 1.809, 0, 26],
            [-0.429, -1.844, 1, 0],
            [-0.035, -1.777, 1, 1],
            [0.359, -1.709, 1, 2],
            [-0.509, -1.396, 1, 3],
            [-0.114, -1.334, 1, 4],
            [0.281, -1.272, 1, 5],
            [-0.549, -0.877, 1, 6],
            [-0.149, -0.886, 1, 7],
            [0.251, -0.894, 1, 8],
            [-0.496, -0.367, 1, 9],
            [-0.102, -0.439, 1, 10],
            [0.291, -0.510, 1, 11],
            [-0.396, 0.091, 1, 12],
            [-0.006, 0.001, 1, 13],
            [0.383, -0.090, 1, 14],
            [-0.300, 0.518, 1, 15],
            [0.092, 0.440, 1, 16],
            [0.484, 0.362, 1, 17],
            [-0.253, 0.896, 1, 18],
            [0.147, 0.886, 1, 19],
            [0.547, 0.876, 1, 20],
            [-0.275, 1.278, 1, 21],
            [0.120, 1.335, 1, 22],
            [0.516, 1.392, 1, 23],
            [-0.356, 1.704, 1, 24],
            [0.038, 1.777, 1, 25],
            [0.431, 1.850, 1, 26],
            [1.183, -1.805, 2, 0],
            [1.580, -1.761, 2, 1],
            [1.978, -1.717, 2, 2],
            [1.114, -1.396, 2, 3],
            [1.506, -1.317, 2, 4],
            [1.898, -1.238, 2, 5],
            [1.048, -0.850, 2, 6],
            [1.448, -0.872, 2, 7],
            [1.847, -0.894, 2, 8],
            [1.148, -0.329, 2, 9],
            [1.535, -0.431, 2, 10],
            [1.922, -0.533, 2, 11],
            [1.251, 0.090, 2, 12],
            [1.642, 0.006, 2, 13],
            [2.033, -0.078, 2, 14],
            [1.323, 0.500, 2, 15],
            [1.720, 0.449, 2, 16],
            [2.117, 0.398, 2, 17],
            [1.351, 0.901, 2, 18],
            [1.751, 0.897, 2, 19],
            [2.151, 0.893, 2, 20],
            [1.331, 1.303, 2, 21],
            [1.728, 1.346, 2, 22],
            [2.126, 1.390, 2, 23],
            [1.267, 1.718, 2, 24],
            [1.660, 1.791, 2, 25],
            [2.054, 1.865, 2, 26],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [];
}
