<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_cer.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Home Ground's places for a bed sown with spires (`Cer`), in each of its three beds.
 *
 * The grain: spires in a stand, three across at 0.40 m and nine rows 0.45 m
 * apart, twenty-seven a bed. The rows follow the bed's line, which sways in a
 * lazy S (`_home_ground.py` says how), and run square to it. Bed by bed, west
 * to east as the table draws it, and in each bed in `HomeGround.Slot`'s order:
 * from the north end, row by row, west to east along each row. A bed fills from
 * both ends, so this is the rule's order, not a fill order.
 */
final class HomeGroundCerTable
{
    public const NAME = 'home_ground_cer';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['bed', 'index'];

    /** The places of each feature variant, in fill order: [x, z, bed, index]. */
    public const PLACES = [
        [
            [-2.081, -1.846, 0, 0],
            [-1.685, -1.793, 0, 1],
            [-1.288, -1.741, 0, 2],
            [-2.131, -1.373, 0, 3],
            [-1.732, -1.346, 0, 4],
            [-1.333, -1.319, 0, 5],
            [-2.145, -0.891, 0, 6],
            [-1.745, -0.896, 0, 7],
            [-1.345, -0.902, 0, 8],
            [-2.121, -0.410, 0, 9],
            [-1.722, -0.447, 0, 10],
            [-1.324, -0.484, 0, 11],
            [-2.062, 0.061, 0, 12],
            [-1.667, 0.000, 0, 13],
            [-1.272, -0.062, 0, 14],
            [-1.990, 0.507, 0, 15],
            [-1.595, 0.444, 0, 16],
            [-1.200, 0.381, 0, 17],
            [-1.954, 0.900, 0, 18],
            [-1.554, 0.891, 0, 19],
            [-1.155, 0.883, 0, 20],
            [-1.976, 1.286, 0, 21],
            [-1.580, 1.340, 0, 22],
            [-1.183, 1.394, 0, 23],
            [-2.033, 1.750, 0, 24],
            [-1.635, 1.787, 0, 25],
            [-1.236, 1.823, 0, 26],
            [-0.419, -1.834, 1, 0],
            [-0.022, -1.790, 1, 1],
            [0.376, -1.746, 1, 2],
            [-0.472, -1.385, 1, 3],
            [-0.074, -1.343, 1, 4],
            [0.324, -1.301, 1, 5],
            [-0.500, -0.887, 1, 6],
            [-0.100, -0.894, 1, 7],
            [0.300, -0.901, 1, 8],
            [-0.467, -0.396, 1, 9],
            [-0.070, -0.445, 1, 10],
            [0.327, -0.493, 1, 11],
            [-0.402, 0.060, 1, 12],
            [-0.006, 0.001, 1, 13],
            [0.389, -0.058, 1, 14],
            [-0.337, 0.501, 1, 15],
            [0.059, 0.446, 1, 16],
            [0.455, 0.391, 1, 17],
            [-0.303, 0.903, 1, 18],
            [0.097, 0.894, 1, 19],
            [0.497, 0.885, 1, 20],
            [-0.318, 1.307, 1, 21],
            [0.080, 1.343, 1, 22],
            [0.479, 1.380, 1, 23],
            [-0.373, 1.740, 1, 24],
            [0.024, 1.790, 1, 25],
            [0.421, 1.840, 1, 26],
            [1.238, -1.819, 2, 0],
            [1.637, -1.785, 2, 1],
            [2.036, -1.752, 2, 2],
            [1.188, -1.390, 2, 3],
            [1.584, -1.338, 2, 4],
            [1.981, -1.287, 2, 5],
            [1.146, -0.883, 2, 6],
            [1.546, -0.891, 2, 7],
            [1.946, -0.898, 2, 8],
            [1.197, -0.377, 2, 9],
            [1.591, -0.443, 2, 10],
            [1.986, -0.510, 2, 11],
            [1.273, 0.062, 2, 12],
            [1.668, 0.000, 2, 13],
            [2.063, -0.062, 2, 14],
            [1.328, 0.486, 2, 15],
            [1.726, 0.446, 2, 16],
            [2.124, 0.406, 2, 17],
            [1.351, 0.899, 2, 18],
            [1.751, 0.895, 2, 19],
            [2.151, 0.892, 2, 20],
            [1.334, 1.312, 2, 21],
            [1.733, 1.345, 2, 22],
            [2.132, 1.378, 2, 23],
            [1.287, 1.741, 2, 24],
            [1.683, 1.792, 2, 25],
            [2.080, 1.843, 2, 26],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [];
}
