<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_fen.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Home Ground's places for a bed sown with umbels (`Fen`), in each of its three beds.
 *
 * The fennel's family: umbels, two across at 0.60 m and seven rows 0.60 m
 * apart, fourteen a bed. The rows follow the bed's line, which sways in a lazy
 * S (`_home_ground.py` says how), and run square to it. Bed by bed, west to east
 * as the table draws it, and in each bed in `HomeGround.Slot`'s order: from the
 * north end, row by row, west to east along each row. A bed fills from both
 * ends, so this is the rule's order, not a fill order.
 */
final class HomeGroundFenTable
{
    public const NAME = 'home_ground_fen';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['bed', 'index'];

    /** The places of each feature variant, in fill order: [x, z, bed, index]. */
    public const PLACES = [
        [
            [-1.982, -1.833, 0, 0],
            [-1.387, -1.754, 0, 1],
            [-2.040, -1.208, 0, 2],
            [-1.440, -1.184, 0, 3],
            [-2.033, -0.576, 0, 4],
            [-1.434, -0.617, 0, 5],
            [-1.964, 0.045, 0, 6],
            [-1.371, -0.046, 0, 7],
            [-1.871, 0.632, 0, 8],
            [-1.276, 0.553, 0, 9],
            [-1.860, 1.166, 0, 10],
            [-1.263, 1.217, 0, 11],
            [-1.933, 1.759, 0, 12],
            [-1.336, 1.814, 0, 13],
            [-0.320, -1.823, 1, 0],
            [0.277, -1.757, 1, 1],
            [-0.387, -1.216, 1, 2],
            [0.211, -1.170, 1, 3],
            [-0.384, -0.567, 1, 4],
            [0.214, -0.621, 1, 5],
            [-0.303, 0.045, 1, 6],
            [0.290, -0.044, 1, 7],
            [-0.220, 0.629, 1, 8],
            [0.376, 0.561, 1, 9],
            [-0.208, 1.179, 1, 10],
            [0.391, 1.209, 1, 11],
            [-0.274, 1.752, 1, 12],
            [0.322, 1.827, 1, 13],
            [1.338, -1.811, 2, 0],
            [1.936, -1.760, 2, 1],
            [1.268, -1.224, 2, 2],
            [1.864, -1.155, 2, 3],
            [1.271, -0.553, 2, 4],
            [1.866, -0.631, 2, 5],
            [1.372, 0.047, 2, 6],
            [1.965, -0.046, 2, 7],
            [1.440, 0.617, 2, 8],
            [2.039, 0.574, 2, 9],
            [1.444, 1.178, 2, 10],
            [2.043, 1.212, 2, 11],
            [1.386, 1.754, 2, 12],
            [1.981, 1.830, 2, 13],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [];
}
