<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_fen.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Home Ground's places for a bed sown with umbels (`Fen`), in each of its three beds.
 *
 * The fennel's family: umbels, two across at 0.60 m and seven rows 0.60 m
 * apart, fourteen a bed. The rows follow the bed's line, which sways in a lazy
 * S (`_home_ground.py` says how), and run square to it. Bed by bed, west to east
 * as the table draws it, and in each bed in `HomeGround.Slot`'s order: from the
 * north end, row by row, west to east along each row. A bed fills from both
 * ends, so this is the rule's order, not a fill order.
 */
final class HomeGroundFenTable
{
    public const NAME = 'home_ground_fen';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['bed', 'index'];

    /** The places of each feature variant, in fill order: [x, z, bed, index]. */
    public const PLACES = [
        [
            [-1.957, -1.849, 0, 0],
            [-1.367, -1.738, 0, 1],
            [-2.037, -1.216, 0, 2],
            [-1.438, -1.181, 0, 3],
            [-2.029, -0.574, 0, 4],
            [-1.431, -0.625, 0, 5],
            [-1.934, 0.056, 0, 6],
            [-1.347, -0.069, 0, 7],
            [-1.794, 0.645, 0, 8],
            [-1.209, 0.509, 0, 9],
            [-1.768, 1.117, 0, 10],
            [-1.178, 1.227, 0, 11],
            [-1.876, 1.728, 0, 12],
            [-1.281, 1.797, 0, 13],
            [-0.331, -1.827, 1, 0],
            [0.261, -1.726, 1, 1],
            [-0.433, -1.219, 1, 2],
            [0.164, -1.151, 1, 3],
            [-0.423, -0.547, 1, 4],
            [0.172, -0.626, 1, 5],
            [-0.298, 0.069, 1, 6],
            [0.286, -0.067, 1, 7],
            [-0.178, 0.634, 1, 8],
            [0.415, 0.541, 1, 9],
            [-0.161, 1.160, 1, 10],
            [0.437, 1.212, 1, 11],
            [-0.257, 1.722, 1, 12],
            [0.333, 1.832, 1, 13],
            [1.282, -1.794, 2, 0],
            [1.879, -1.728, 2, 1],
            [1.182, -1.224, 2, 2],
            [1.772, -1.115, 2, 3],
            [1.206, -0.506, 2, 4],
            [1.789, -0.647, 2, 5],
            [1.349, 0.069, 2, 6],
            [1.936, -0.057, 2, 7],
            [1.437, 0.625, 2, 8],
            [2.035, 0.571, 2, 9],
            [1.442, 1.176, 2, 10],
            [2.041, 1.219, 2, 11],
            [1.366, 1.736, 2, 12],
            [1.955, 1.846, 2, 13],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [];
}
