<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/quiet_room.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Quiet Garden's asymmetric room: one, five, three and one, the pool off the middle toward the bench.
 *
 * Marcus, 2 October 2026 (RESEARCH.md, *The Quiet Garden*, option A). The ten
 * dry places of a room stand as:
 *
 * - the specimen beside the bench (group 0), where it has stood since 21 September;
 * - a group of five in the far corner, across the water: what the bench looks at (group 1);
 * - a group of three along the side to the bench's left, a third of the way down it (group 2);
 * - one plant alone across the lawn from the five, which repeats its colour: the echo (group 3).
 *
 * The pool lies off the middle toward the bench, longer across the bench's view
 * than along it, with a bay on the bench's side that three stepping stones lead
 * into from the seat (`stones`). Its two places (group 4) are the pool's own and
 * lie along its length; the live garden never sends this area a lily, so they
 * stay empty.
 *
 * Within a group the places are listed nearest the corner first, then
 * farthest-first, and `stand` says which are the back of the group (1) and which
 * its arms (0): the five has two at the back, the three one. A rule that takes
 * the first free place of the stand it wants leaves every count of a group
 * looking like a clump rather than a row begun at one end. The room is turned
 * and mirrored by its plot's number, eight ways, so no two rooms side by side
 * are laid alike.
 */
final class QuietRoomTable
{
    public const NAME = 'quiet_room';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['group', 'stand'];

    /** The places of each feature variant, in fill order: [x, z, group, stand]. */
    public const PLACES = [
        [
            [-1.950, -0.950, 0, 0],
            [1.949, 1.695, 1, 1],
            [0.744, 1.420, 1, 0],
            [1.796, 0.656, 1, 0],
            [1.119, 0.788, 1, 0],
            [1.351, 1.356, 1, 1],
            [1.790, -1.457, 2, 1],
            [1.577, -0.367, 2, 0],
            [1.433, -0.952, 2, 0],
            [-1.700, 1.360, 3, 0],
            [0.018, -0.578, 4, 0],
            [-0.618, 0.058, 4, 0],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [
        'pool' => [
            [true, [
                [0.461, -1.021], [0.481, -0.999], [0.501, -0.976], [0.518, -0.951], [0.534, -0.925], [0.548, -0.898],
                [0.560, -0.869], [0.569, -0.839], [0.576, -0.808], [0.581, -0.776], [0.583, -0.743], [0.584, -0.710],
                [0.585, -0.676], [0.584, -0.641], [0.584, -0.606], [0.583, -0.570], [0.581, -0.533], [0.578, -0.495],
                [0.572, -0.457], [0.564, -0.419], [0.552, -0.380], [0.539, -0.342], [0.524, -0.303], [0.507, -0.264],
                [0.490, -0.226], [0.471, -0.187], [0.451, -0.148], [0.429, -0.109], [0.405, -0.071], [0.380, -0.034],
                [0.354, 0.003], [0.326, 0.039], [0.296, 0.075], [0.265, 0.109], [0.232, 0.141], [0.198, 0.173],
                [0.163, 0.203], [0.127, 0.233], [0.091, 0.261], [0.054, 0.288], [0.018, 0.315], [-0.018, 0.342],
                [-0.053, 0.370], [-0.088, 0.399], [-0.123, 0.427], [-0.158, 0.453], [-0.195, 0.477], [-0.232, 0.499],
                [-0.270, 0.520], [-0.308, 0.538], [-0.347, 0.555], [-0.385, 0.570], [-0.423, 0.583], [-0.461, 0.595],
                [-0.499, 0.605], [-0.536, 0.613], [-0.573, 0.620], [-0.610, 0.624], [-0.646, 0.627], [-0.681, 0.627],
                [-0.716, 0.626], [-0.750, 0.623], [-0.783, 0.620], [-0.815, 0.615], [-0.846, 0.609], [-0.876, 0.601],
                [-0.906, 0.591], [-0.934, 0.579], [-0.961, 0.565], [-0.986, 0.549], [-1.009, 0.531], [-1.031, 0.512],
                [-1.051, 0.491], [-1.069, 0.469], [-1.086, 0.445], [-1.100, 0.420], [-1.112, 0.393], [-1.122, 0.366],
                [-1.130, 0.337], [-1.136, 0.308], [-1.141, 0.279], [-1.145, 0.249], [-1.148, 0.218], [-1.150, 0.187],
                [-1.150, 0.155], [-1.150, 0.122], [-1.148, 0.088], [-1.146, 0.054], [-1.144, 0.019], [-1.140, -0.017],
                [-1.135, -0.053], [-1.125, -0.091], [-1.111, -0.129], [-1.094, -0.169], [-1.073, -0.208], [-1.049, -0.248],
                [-1.021, -0.286], [-0.990, -0.322], [-0.955, -0.355], [-0.919, -0.386], [-0.882, -0.414], [-0.845, -0.440],
                [-0.809, -0.465], [-0.775, -0.489], [-0.742, -0.512], [-0.712, -0.533], [-0.683, -0.552], [-0.657, -0.572],
                [-0.632, -0.592], [-0.608, -0.614], [-0.586, -0.638], [-0.563, -0.664], [-0.541, -0.693], [-0.517, -0.723],
                [-0.492, -0.756], [-0.465, -0.789], [-0.437, -0.823], [-0.409, -0.858], [-0.378, -0.892], [-0.345, -0.925],
                [-0.310, -0.956], [-0.275, -0.986], [-0.240, -1.014], [-0.205, -1.041], [-0.169, -1.065], [-0.133, -1.086],
                [-0.097, -1.103], [-0.060, -1.117], [-0.025, -1.127], [0.011, -1.135], [0.046, -1.141], [0.081, -1.145],
                [0.116, -1.146], [0.150, -1.146], [0.183, -1.144], [0.216, -1.141], [0.248, -1.135], [0.279, -1.128],
                [0.309, -1.119], [0.338, -1.108], [0.365, -1.094], [0.391, -1.078], [0.416, -1.060], [0.439, -1.041],
            ]],
        ],
        'stones' => [
            [false, [
                [-1.477, -1.398], [-1.060, -1.127], [-0.793, -0.710],
            ]],
        ],
    ];
}
