<?php
declare(strict_types=1);

// Generated by tools/layouts/generate.py from tools/layouts/tables/quiet_room.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

/**
 * The Quiet Garden's asymmetric room: one, five, three and one, the pool off the middle toward the bench.
 *
 * Marcus, 2 October 2026 (RESEARCH.md, *The Quiet Garden*, option A). The ten
 * dry places of a room stand as:
 *
 * - the specimen beside the bench (group 0), where it has stood since 21 September;
 * - a group of five in the far corner, across the water: what the bench looks at (group 1);
 * - a group of three along the side to the bench's left, a third of the way down it (group 2);
 * - one plant alone across the lawn from the five, which repeats its colour: the echo (group 3).
 *
 * The pool lies off the middle toward the bench, longer across the bench's view
 * than along it, with a bay on the bench's side that three stepping stones lead
 * into from the seat (`stones`). Its two places (group 4) are the pool's own and
 * lie along its length; the live garden never sends this area a lily, so they
 * stay empty.
 *
 * Within a group the places are listed nearest the corner first, then
 * farthest-first, and `stand` says which are the back of the group (1) and which
 * its arms (0): the five has two at the back, the three one. A rule that takes
 * the first free place of the stand it wants leaves every count of a group
 * looking like a clump rather than a row begun at one end. The room is turned
 * and mirrored by its plot's number, eight ways, so no two rooms side by side
 * are laid alike.
 */
final class QuietRoomTable
{
    public const NAME = 'quiet_room';

    /** What each tag of a place is, in order. */
    public const FIELDS = ['group', 'stand'];

    /** The places of each feature variant, in fill order: [x, z, group, stand]. */
    public const PLACES = [
        [
            [-1.950, -0.950, 0, 0],
            [1.941, 1.468, 1, 1],
            [0.851, 1.838, 1, 0],
            [1.778, 0.874, 1, 0],
            [1.429, 1.423, 1, 1],
            [0.940, 1.334, 1, 0],
            [1.512, -0.969, 2, 1],
            [1.592, -1.456, 2, 0],
            [1.226, -0.593, 2, 0],
            [-1.700, 1.360, 3, 0],
            [0.018, -0.578, 4, 0],
            [-0.618, 0.058, 4, 0],
        ],
    ];

    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */
    public const CURVES = [
        'pool' => [
            [true, [
                [0.461, -1.021], [0.481, -0.999], [0.501, -0.976], [0.518, -0.951], [0.534, -0.925], [0.548, -0.898],
                [0.560, -0.869], [0.569, -0.839], [0.576, -0.808], [0.581, -0.776], [0.583, -0.743], [0.584, -0.710],
                [0.585, -0.676], [0.584, -0.641], [0.584, -0.606], [0.583, -0.570], [0.581, -0.533], [0.578, -0.495],
                [0.572, -0.457], [0.564, -0.419], [0.552, -0.380], [0.539, -0.342], [0.524, -0.303], [0.507, -0.264],
                [0.490, -0.226], [0.471, -0.187], [0.451, -0.148], [0.429, -0.109], [0.405, -0.071], [0.380, -0.034],
                [0.354, 0.003], [0.326, 0.039], [0.296, 0.075], [0.265, 0.109], [0.232, 0.141], [0.198, 0.173],
                [0.163, 0.203], [0.127, 0.233], [0.091, 0.261], [0.054, 0.288], [0.018, 0.315], [-0.018, 0.342],
                [-0.053, 0.370], [-0.088, 0.399], [-0.123, 0.427], [-0.158, 0.453], [-0.195, 0.477], [-0.232, 0.499],
                [-0.270, 0.520], [-0.308, 0.538], [-0.347, 0.555], [-0.385, 0.570], [-0.423, 0.583], [-0.461, 0.595],
                [-0.499, 0.605], [-0.536, 0.613], [-0.573, 0.620], [-0.610, 0.624], [-0.646, 0.627], [-0.681, 0.627],
                [-0.716, 0.626], [-0.750, 0.623], [-0.783, 0.620], [-0.815, 0.615], [-0.846, 0.609], [-0.876, 0.601],
                [-0.906, 0.591], [-0.934, 0.579], [-0.961, 0.565], [-0.986, 0.549], [-1.009, 0.531], [-1.031, 0.512],
                [-1.051, 0.491], [-1.069, 0.469], [-1.086, 0.445], [-1.100, 0.419], [-1.112, 0.393], [-1.122, 0.366],
                [-1.130, 0.337], [-1.136, 0.308], [-1.141, 0.279], [-1.145, 0.249], [-1.148, 0.218], [-1.150, 0.187],
                [-1.150, 0.155], [-1.150, 0.122], [-1.148, 0.088], [-1.146, 0.054], [-1.144, 0.019], [-1.140, -0.017],
                [-1.135, -0.054], [-1.126, -0.091], [-1.115, -0.129], [-1.100, -0.169], [-1.083, -0.208], [-1.063, -0.248],
                [-1.039, -0.287], [-1.013, -0.324], [-0.984, -0.359], [-0.953, -0.393], [-0.920, -0.424], [-0.887, -0.454],
                [-0.855, -0.483], [-0.824, -0.511], [-0.793, -0.539], [-0.764, -0.565], [-0.735, -0.590], [-0.706, -0.614],
                [-0.678, -0.638], [-0.651, -0.663], [-0.624, -0.689], [-0.597, -0.716], [-0.569, -0.744], [-0.541, -0.773],
                [-0.511, -0.802], [-0.480, -0.832], [-0.449, -0.862], [-0.417, -0.892], [-0.383, -0.921], [-0.348, -0.949],
                [-0.313, -0.976], [-0.277, -1.001], [-0.241, -1.026], [-0.205, -1.049], [-0.169, -1.071], [-0.133, -1.089],
                [-0.097, -1.105], [-0.061, -1.117], [-0.025, -1.127], [0.011, -1.135], [0.046, -1.141], [0.081, -1.145],
                [0.116, -1.146], [0.150, -1.146], [0.183, -1.144], [0.216, -1.141], [0.248, -1.135], [0.279, -1.128],
                [0.309, -1.119], [0.338, -1.108], [0.365, -1.094], [0.391, -1.078], [0.416, -1.060], [0.439, -1.041],
            ]],
        ],
        'stones' => [
            [false, [
                [-1.477, -1.398], [-1.081, -1.149], [-0.835, -0.753],
            ]],
        ],
    ];
}
