// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_beds.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

extension PlaceTable {
    /// The Home Ground's three beds: where each one's middle is, and the line it runs along.
    ///
    /// Lazy beds that follow the land (Marcus, 2 October 2026; RESEARCH.md, option
    /// A): three beds 1.2 m wide, their middles 1.60 m apart with paths of 0.40 m
    /// between, from z = -2.1 (north) to 2.1, swaying together in a lazy S 0.15 m
    /// either way, each straying a little off it as a spade leaves a ridge. The curves `bed0`, `bed1` and `bed2` are each bed's
    /// middle, west to east as the table draws it, north end first; the page raises
    /// a bed 0.6 m either side of its line. One place to a bed, its middle, for the
    /// bed's number. A plot is drawn as it stands or mirrored, by its number
    /// (`HomeGround.variants`), which sways the beds the other way.
    public static let homeGroundBeds = PlaceTable(
        name: "home_ground_beds",
        fields: ["bed"],
        variants: [
            [
                Place(x: -1.641, z: -0.006, tags: [0]),
                Place(x: -0.006, z: 0.001, tags: [1]),
                Place(x: 1.642, z: 0.006, tags: [2]),
            ],
        ],
        curves: [
            "bed0": [
                Curve(closed: false, points: [
                    Spot(x: -1.600, z: -2.104), Spot(x: -1.600, z: -2.113), Spot(x: -1.609, z: -2.064),
                    Spot(x: -1.618, z: -2.014), Spot(x: -1.628, z: -1.965), Spot(x: -1.638, z: -1.916),
                    Spot(x: -1.648, z: -1.867), Spot(x: -1.657, z: -1.818), Spot(x: -1.666, z: -1.768),
                    Spot(x: -1.675, z: -1.719), Spot(x: -1.684, z: -1.670), Spot(x: -1.692, z: -1.620),
                    Spot(x: -1.699, z: -1.571), Spot(x: -1.706, z: -1.521), Spot(x: -1.713, z: -1.471),
                    Spot(x: -1.719, z: -1.422), Spot(x: -1.724, z: -1.372), Spot(x: -1.729, z: -1.322),
                    Spot(x: -1.733, z: -1.272), Spot(x: -1.736, z: -1.222), Spot(x: -1.739, z: -1.172),
                    Spot(x: -1.742, z: -1.122), Spot(x: -1.744, z: -1.072), Spot(x: -1.745, z: -1.022),
                    Spot(x: -1.745, z: -0.971), Spot(x: -1.745, z: -0.921), Spot(x: -1.745, z: -0.871),
                    Spot(x: -1.743, z: -0.821), Spot(x: -1.741, z: -0.771), Spot(x: -1.739, z: -0.721),
                    Spot(x: -1.736, z: -0.671), Spot(x: -1.732, z: -0.621), Spot(x: -1.728, z: -0.571),
                    Spot(x: -1.723, z: -0.521), Spot(x: -1.718, z: -0.471), Spot(x: -1.712, z: -0.422),
                    Spot(x: -1.705, z: -0.372), Spot(x: -1.698, z: -0.322), Spot(x: -1.691, z: -0.273),
                    Spot(x: -1.682, z: -0.223), Spot(x: -1.674, z: -0.174), Spot(x: -1.665, z: -0.125),
                    Spot(x: -1.655, z: -0.075), Spot(x: -1.645, z: -0.026), Spot(x: -1.635, z: 0.023),
                    Spot(x: -1.624, z: 0.072), Spot(x: -1.613, z: 0.121), Spot(x: -1.601, z: 0.169),
                    Spot(x: -1.590, z: 0.218), Spot(x: -1.578, z: 0.267), Spot(x: -1.566, z: 0.316),
                    Spot(x: -1.554, z: 0.364), Spot(x: -1.542, z: 0.413), Spot(x: -1.530, z: 0.461),
                    Spot(x: -1.518, z: 0.510), Spot(x: -1.506, z: 0.559), Spot(x: -1.495, z: 0.608),
                    Spot(x: -1.484, z: 0.657), Spot(x: -1.474, z: 0.706), Spot(x: -1.466, z: 0.755),
                    Spot(x: -1.460, z: 0.805), Spot(x: -1.457, z: 0.855), Spot(x: -1.455, z: 0.905),
                    Spot(x: -1.453, z: 0.955), Spot(x: -1.453, z: 1.005), Spot(x: -1.456, z: 1.055),
                    Spot(x: -1.462, z: 1.105), Spot(x: -1.470, z: 1.155), Spot(x: -1.479, z: 1.204),
                    Spot(x: -1.489, z: 1.253), Spot(x: -1.499, z: 1.302), Spot(x: -1.509, z: 1.351),
                    Spot(x: -1.519, z: 1.400), Spot(x: -1.528, z: 1.450), Spot(x: -1.538, z: 1.499),
                    Spot(x: -1.547, z: 1.548), Spot(x: -1.555, z: 1.598), Spot(x: -1.563, z: 1.647),
                    Spot(x: -1.570, z: 1.697), Spot(x: -1.577, z: 1.746), Spot(x: -1.582, z: 1.796),
                    Spot(x: -1.587, z: 1.846), Spot(x: -1.592, z: 1.896), Spot(x: -1.595, z: 1.946),
                    Spot(x: -1.598, z: 1.996), Spot(x: -1.599, z: 2.046), Spot(x: -1.600, z: 2.096),
                ]),
            ],
            "bed1": [
                Curve(closed: false, points: [
                    Spot(x: 0.000, z: -2.100), Spot(x: -0.001, z: -2.050), Spot(x: -0.005, z: -2.000),
                    Spot(x: -0.010, z: -1.950), Spot(x: -0.016, z: -1.901), Spot(x: -0.023, z: -1.851),
                    Spot(x: -0.031, z: -1.802), Spot(x: -0.039, z: -1.753), Spot(x: -0.048, z: -1.703),
                    Spot(x: -0.057, z: -1.654), Spot(x: -0.066, z: -1.605), Spot(x: -0.075, z: -1.556),
                    Spot(x: -0.084, z: -1.507), Spot(x: -0.093, z: -1.457), Spot(x: -0.102, z: -1.408),
                    Spot(x: -0.110, z: -1.359), Spot(x: -0.118, z: -1.309), Spot(x: -0.125, z: -1.260),
                    Spot(x: -0.132, z: -1.210), Spot(x: -0.137, z: -1.161), Spot(x: -0.142, z: -1.111),
                    Spot(x: -0.146, z: -1.061), Spot(x: -0.148, z: -1.011), Spot(x: -0.150, z: -0.961),
                    Spot(x: -0.150, z: -0.911), Spot(x: -0.149, z: -0.861), Spot(x: -0.147, z: -0.811),
                    Spot(x: -0.144, z: -0.761), Spot(x: -0.140, z: -0.711), Spot(x: -0.135, z: -0.661),
                    Spot(x: -0.129, z: -0.612), Spot(x: -0.123, z: -0.562), Spot(x: -0.115, z: -0.513),
                    Spot(x: -0.107, z: -0.463), Spot(x: -0.098, z: -0.414), Spot(x: -0.088, z: -0.365),
                    Spot(x: -0.078, z: -0.316), Spot(x: -0.067, z: -0.267), Spot(x: -0.057, z: -0.218),
                    Spot(x: -0.046, z: -0.170), Spot(x: -0.034, z: -0.121), Spot(x: -0.023, z: -0.072),
                    Spot(x: -0.012, z: -0.023), Spot(x: -0.001, z: 0.025), Spot(x: 0.011, z: 0.074),
                    Spot(x: 0.022, z: 0.123), Spot(x: 0.033, z: 0.171), Spot(x: 0.044, z: 0.220),
                    Spot(x: 0.055, z: 0.269), Spot(x: 0.066, z: 0.318), Spot(x: 0.077, z: 0.367),
                    Spot(x: 0.087, z: 0.416), Spot(x: 0.097, z: 0.465), Spot(x: 0.106, z: 0.514),
                    Spot(x: 0.114, z: 0.563), Spot(x: 0.122, z: 0.613), Spot(x: 0.129, z: 0.662),
                    Spot(x: 0.135, z: 0.712), Spot(x: 0.140, z: 0.762), Spot(x: 0.144, z: 0.811),
                    Spot(x: 0.146, z: 0.861), Spot(x: 0.147, z: 0.911), Spot(x: 0.148, z: 0.961),
                    Spot(x: 0.147, z: 1.011), Spot(x: 0.146, z: 1.061), Spot(x: 0.143, z: 1.111),
                    Spot(x: 0.140, z: 1.161), Spot(x: 0.136, z: 1.211), Spot(x: 0.130, z: 1.261),
                    Spot(x: 0.124, z: 1.310), Spot(x: 0.117, z: 1.360), Spot(x: 0.109, z: 1.409),
                    Spot(x: 0.100, z: 1.459), Spot(x: 0.091, z: 1.508), Spot(x: 0.081, z: 1.557),
                    Spot(x: 0.071, z: 1.606), Spot(x: 0.062, z: 1.655), Spot(x: 0.052, z: 1.704),
                    Spot(x: 0.042, z: 1.753), Spot(x: 0.033, z: 1.802), Spot(x: 0.024, z: 1.851),
                    Spot(x: 0.017, z: 1.901), Spot(x: 0.010, z: 1.950), Spot(x: 0.005, z: 2.000),
                    Spot(x: 0.002, z: 2.050), Spot(x: 0.000, z: 2.100),
                ]),
            ],
            "bed2": [
                Curve(closed: false, points: [
                    Spot(x: 1.600, z: -2.096), Spot(x: 1.600, z: -2.046), Spot(x: 1.598, z: -1.996),
                    Spot(x: 1.596, z: -1.946), Spot(x: 1.593, z: -1.896), Spot(x: 1.589, z: -1.846),
                    Spot(x: 1.584, z: -1.796), Spot(x: 1.579, z: -1.746), Spot(x: 1.573, z: -1.696),
                    Spot(x: 1.566, z: -1.646), Spot(x: 1.558, z: -1.597), Spot(x: 1.550, z: -1.547),
                    Spot(x: 1.541, z: -1.498), Spot(x: 1.532, z: -1.449), Spot(x: 1.522, z: -1.399),
                    Spot(x: 1.513, z: -1.350), Spot(x: 1.503, z: -1.301), Spot(x: 1.493, z: -1.252),
                    Spot(x: 1.484, z: -1.203), Spot(x: 1.474, z: -1.153), Spot(x: 1.466, z: -1.104),
                    Spot(x: 1.458, z: -1.054), Spot(x: 1.451, z: -1.005), Spot(x: 1.446, z: -0.955),
                    Spot(x: 1.446, z: -0.905), Spot(x: 1.449, z: -0.854), Spot(x: 1.454, z: -0.805),
                    Spot(x: 1.461, z: -0.755), Spot(x: 1.469, z: -0.706), Spot(x: 1.479, z: -0.656),
                    Spot(x: 1.490, z: -0.607), Spot(x: 1.502, z: -0.559), Spot(x: 1.514, z: -0.510),
                    Spot(x: 1.527, z: -0.461), Spot(x: 1.540, z: -0.413), Spot(x: 1.552, z: -0.364),
                    Spot(x: 1.565, z: -0.316), Spot(x: 1.578, z: -0.267), Spot(x: 1.590, z: -0.219),
                    Spot(x: 1.602, z: -0.170), Spot(x: 1.614, z: -0.121), Spot(x: 1.625, z: -0.072),
                    Spot(x: 1.636, z: -0.023), Spot(x: 1.647, z: 0.026), Spot(x: 1.657, z: 0.075),
                    Spot(x: 1.667, z: 0.124), Spot(x: 1.676, z: 0.173), Spot(x: 1.685, z: 0.223),
                    Spot(x: 1.694, z: 0.272), Spot(x: 1.702, z: 0.321), Spot(x: 1.709, z: 0.371),
                    Spot(x: 1.716, z: 0.421), Spot(x: 1.723, z: 0.470), Spot(x: 1.729, z: 0.520),
                    Spot(x: 1.734, z: 0.570), Spot(x: 1.738, z: 0.620), Spot(x: 1.742, z: 0.670),
                    Spot(x: 1.745, z: 0.720), Spot(x: 1.748, z: 0.770), Spot(x: 1.750, z: 0.820),
                    Spot(x: 1.751, z: 0.871), Spot(x: 1.752, z: 0.921), Spot(x: 1.751, z: 0.971),
                    Spot(x: 1.750, z: 1.021), Spot(x: 1.749, z: 1.071), Spot(x: 1.746, z: 1.121),
                    Spot(x: 1.744, z: 1.171), Spot(x: 1.740, z: 1.221), Spot(x: 1.736, z: 1.271),
                    Spot(x: 1.731, z: 1.321), Spot(x: 1.726, z: 1.371), Spot(x: 1.720, z: 1.421),
                    Spot(x: 1.713, z: 1.471), Spot(x: 1.706, z: 1.520), Spot(x: 1.699, z: 1.570),
                    Spot(x: 1.691, z: 1.620), Spot(x: 1.682, z: 1.669), Spot(x: 1.674, z: 1.718),
                    Spot(x: 1.665, z: 1.768), Spot(x: 1.656, z: 1.817), Spot(x: 1.646, z: 1.866),
                    Spot(x: 1.637, z: 1.916), Spot(x: 1.627, z: 1.965), Spot(x: 1.617, z: 2.014),
                    Spot(x: 1.608, z: 2.063), Spot(x: 1.600, z: 2.113), Spot(x: 1.600, z: 2.104),
                ]),
            ],
        ]
    )
}
