// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_beds.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

extension PlaceTable {
    /// The Home Ground's three beds: where each one's middle is, and the line it runs along.
    ///
    /// Lazy beds that follow the land (Marcus, 2 October 2026; RESEARCH.md, option
    /// A): three beds 1.2 m wide, their middles 1.65 m apart, from z = -2.1 (north)
    /// to 2.1, swaying together in a lazy S, each straying a little off it as a
    /// spade leaves a ridge. The curves `bed0`, `bed1` and `bed2` are each bed's
    /// middle, west to east as the table draws it, north end first; the page raises
    /// a bed 0.6 m either side of its line. One place to a bed, its middle, for the
    /// bed's number. A plot is drawn as it stands or mirrored, by its number
    /// (`HomeGround.variants`), which sways the beds the other way.
    public static let homeGroundBeds = PlaceTable(
        name: "home_ground_beds",
        fields: ["bed"],
        variants: [
            [
                Place(x: -1.667, z: 0.000, tags: [0]),
                Place(x: -0.006, z: 0.001, tags: [1]),
                Place(x: 1.668, z: 0.000, tags: [2]),
            ],
        ],
        curves: [
            "bed0": [
                Curve(closed: false, points: [
                    Spot(x: -1.650, z: -2.103), Spot(x: -1.652, z: -2.053), Spot(x: -1.657, z: -2.003),
                    Spot(x: -1.663, z: -1.953), Spot(x: -1.670, z: -1.903), Spot(x: -1.677, z: -1.853),
                    Spot(x: -1.683, z: -1.803), Spot(x: -1.690, z: -1.754), Spot(x: -1.696, z: -1.704),
                    Spot(x: -1.702, z: -1.654), Spot(x: -1.708, z: -1.604), Spot(x: -1.714, z: -1.554),
                    Spot(x: -1.719, z: -1.504), Spot(x: -1.723, z: -1.454), Spot(x: -1.728, z: -1.404),
                    Spot(x: -1.731, z: -1.354), Spot(x: -1.735, z: -1.303), Spot(x: -1.738, z: -1.253),
                    Spot(x: -1.740, z: -1.203), Spot(x: -1.742, z: -1.153), Spot(x: -1.743, z: -1.102),
                    Spot(x: -1.745, z: -1.052), Spot(x: -1.745, z: -1.002), Spot(x: -1.745, z: -0.952),
                    Spot(x: -1.745, z: -0.901), Spot(x: -1.744, z: -0.851), Spot(x: -1.743, z: -0.801),
                    Spot(x: -1.742, z: -0.751), Spot(x: -1.740, z: -0.700), Spot(x: -1.737, z: -0.650),
                    Spot(x: -1.734, z: -0.600), Spot(x: -1.731, z: -0.550), Spot(x: -1.727, z: -0.500),
                    Spot(x: -1.723, z: -0.450), Spot(x: -1.718, z: -0.400), Spot(x: -1.713, z: -0.350),
                    Spot(x: -1.707, z: -0.300), Spot(x: -1.701, z: -0.250), Spot(x: -1.695, z: -0.200),
                    Spot(x: -1.689, z: -0.150), Spot(x: -1.682, z: -0.100), Spot(x: -1.675, z: -0.050),
                    Spot(x: -1.667, z: -0.001), Spot(x: -1.659, z: 0.049), Spot(x: -1.652, z: 0.099),
                    Spot(x: -1.643, z: 0.148), Spot(x: -1.635, z: 0.198), Spot(x: -1.627, z: 0.248),
                    Spot(x: -1.619, z: 0.297), Spot(x: -1.611, z: 0.347), Spot(x: -1.603, z: 0.396),
                    Spot(x: -1.595, z: 0.446), Spot(x: -1.587, z: 0.496), Spot(x: -1.580, z: 0.545),
                    Spot(x: -1.573, z: 0.595), Spot(x: -1.567, z: 0.645), Spot(x: -1.563, z: 0.695),
                    Spot(x: -1.560, z: 0.745), Spot(x: -1.557, z: 0.796), Spot(x: -1.555, z: 0.846),
                    Spot(x: -1.554, z: 0.896), Spot(x: -1.554, z: 0.946), Spot(x: -1.553, z: 0.997),
                    Spot(x: -1.553, z: 1.047), Spot(x: -1.555, z: 1.097), Spot(x: -1.558, z: 1.147),
                    Spot(x: -1.562, z: 1.197), Spot(x: -1.568, z: 1.247), Spot(x: -1.574, z: 1.297),
                    Spot(x: -1.581, z: 1.347), Spot(x: -1.587, z: 1.397), Spot(x: -1.594, z: 1.447),
                    Spot(x: -1.601, z: 1.497), Spot(x: -1.608, z: 1.546), Spot(x: -1.614, z: 1.596),
                    Spot(x: -1.620, z: 1.646), Spot(x: -1.626, z: 1.696), Spot(x: -1.631, z: 1.746),
                    Spot(x: -1.636, z: 1.796), Spot(x: -1.640, z: 1.846), Spot(x: -1.643, z: 1.896),
                    Spot(x: -1.646, z: 1.947), Spot(x: -1.648, z: 1.997), Spot(x: -1.649, z: 2.047),
                    Spot(x: -1.650, z: 2.097),
                ]),
            ],
            "bed1": [
                Curve(closed: false, points: [
                    Spot(x: 0.000, z: -2.100), Spot(x: -0.001, z: -2.050), Spot(x: -0.003, z: -2.000),
                    Spot(x: -0.007, z: -1.949), Spot(x: -0.011, z: -1.899), Spot(x: -0.015, z: -1.849),
                    Spot(x: -0.021, z: -1.799), Spot(x: -0.026, z: -1.749), Spot(x: -0.032, z: -1.699),
                    Spot(x: -0.038, z: -1.649), Spot(x: -0.044, z: -1.599), Spot(x: -0.050, z: -1.550),
                    Spot(x: -0.056, z: -1.500), Spot(x: -0.062, z: -1.450), Spot(x: -0.067, z: -1.400),
                    Spot(x: -0.073, z: -1.350), Spot(x: -0.078, z: -1.300), Spot(x: -0.083, z: -1.250),
                    Spot(x: -0.088, z: -1.200), Spot(x: -0.092, z: -1.150), Spot(x: -0.095, z: -1.099),
                    Spot(x: -0.097, z: -1.049), Spot(x: -0.099, z: -0.999), Spot(x: -0.100, z: -0.949),
                    Spot(x: -0.100, z: -0.899), Spot(x: -0.099, z: -0.848), Spot(x: -0.097, z: -0.798),
                    Spot(x: -0.095, z: -0.748), Spot(x: -0.093, z: -0.698), Spot(x: -0.089, z: -0.647),
                    Spot(x: -0.085, z: -0.597), Spot(x: -0.081, z: -0.547), Spot(x: -0.076, z: -0.497),
                    Spot(x: -0.070, z: -0.447), Spot(x: -0.064, z: -0.397), Spot(x: -0.057, z: -0.348),
                    Spot(x: -0.050, z: -0.298), Spot(x: -0.043, z: -0.248), Spot(x: -0.036, z: -0.198),
                    Spot(x: -0.028, z: -0.149), Spot(x: -0.021, z: -0.099), Spot(x: -0.014, z: -0.049),
                    Spot(x: -0.006, z: 0.001), Spot(x: 0.001, z: 0.050), Spot(x: 0.009, z: 0.100),
                    Spot(x: 0.016, z: 0.150), Spot(x: 0.023, z: 0.199), Spot(x: 0.031, z: 0.249),
                    Spot(x: 0.038, z: 0.299), Spot(x: 0.045, z: 0.349), Spot(x: 0.053, z: 0.398),
                    Spot(x: 0.060, z: 0.448), Spot(x: 0.066, z: 0.498), Spot(x: 0.072, z: 0.548),
                    Spot(x: 0.078, z: 0.598), Spot(x: 0.083, z: 0.648), Spot(x: 0.088, z: 0.698),
                    Spot(x: 0.091, z: 0.748), Spot(x: 0.094, z: 0.798), Spot(x: 0.096, z: 0.848),
                    Spot(x: 0.097, z: 0.899), Spot(x: 0.098, z: 0.949), Spot(x: 0.098, z: 0.999),
                    Spot(x: 0.097, z: 1.050), Spot(x: 0.096, z: 1.100), Spot(x: 0.094, z: 1.150),
                    Spot(x: 0.091, z: 1.200), Spot(x: 0.088, z: 1.250), Spot(x: 0.084, z: 1.301),
                    Spot(x: 0.080, z: 1.351), Spot(x: 0.074, z: 1.401), Spot(x: 0.069, z: 1.451),
                    Spot(x: 0.062, z: 1.500), Spot(x: 0.056, z: 1.550), Spot(x: 0.049, z: 1.600),
                    Spot(x: 0.042, z: 1.650), Spot(x: 0.036, z: 1.700), Spot(x: 0.029, z: 1.750),
                    Spot(x: 0.023, z: 1.799), Spot(x: 0.017, z: 1.849), Spot(x: 0.012, z: 1.899),
                    Spot(x: 0.007, z: 1.949), Spot(x: 0.004, z: 2.000), Spot(x: 0.001, z: 2.050),
                    Spot(x: 0.000, z: 2.100),
                ]),
            ],
            "bed2": [
                Curve(closed: false, points: [
                    Spot(x: 1.650, z: -2.097), Spot(x: 1.650, z: -2.048), Spot(x: 1.649, z: -1.998),
                    Spot(x: 1.647, z: -1.948), Spot(x: 1.645, z: -1.899), Spot(x: 1.642, z: -1.849),
                    Spot(x: 1.638, z: -1.799), Spot(x: 1.634, z: -1.750), Spot(x: 1.629, z: -1.700),
                    Spot(x: 1.624, z: -1.651), Spot(x: 1.618, z: -1.602), Spot(x: 1.612, z: -1.552),
                    Spot(x: 1.606, z: -1.503), Spot(x: 1.600, z: -1.454), Spot(x: 1.593, z: -1.404),
                    Spot(x: 1.586, z: -1.355), Spot(x: 1.580, z: -1.306), Spot(x: 1.574, z: -1.257),
                    Spot(x: 1.568, z: -1.207), Spot(x: 1.562, z: -1.158), Spot(x: 1.557, z: -1.108),
                    Spot(x: 1.552, z: -1.059), Spot(x: 1.548, z: -1.009), Spot(x: 1.546, z: -0.960),
                    Spot(x: 1.546, z: -0.910), Spot(x: 1.547, z: -0.860), Spot(x: 1.549, z: -0.811),
                    Spot(x: 1.552, z: -0.761), Spot(x: 1.556, z: -0.711), Spot(x: 1.560, z: -0.662),
                    Spot(x: 1.566, z: -0.613), Spot(x: 1.573, z: -0.563), Spot(x: 1.580, z: -0.514),
                    Spot(x: 1.587, z: -0.465), Spot(x: 1.596, z: -0.416), Spot(x: 1.604, z: -0.367),
                    Spot(x: 1.613, z: -0.318), Spot(x: 1.622, z: -0.269), Spot(x: 1.631, z: -0.220),
                    Spot(x: 1.640, z: -0.171), Spot(x: 1.648, z: -0.122), Spot(x: 1.656, z: -0.073),
                    Spot(x: 1.664, z: -0.024), Spot(x: 1.672, z: 0.025), Spot(x: 1.679, z: 0.074),
                    Spot(x: 1.687, z: 0.123), Spot(x: 1.693, z: 0.172), Spot(x: 1.700, z: 0.222),
                    Spot(x: 1.707, z: 0.271), Spot(x: 1.713, z: 0.320), Spot(x: 1.718, z: 0.370),
                    Spot(x: 1.724, z: 0.419), Spot(x: 1.729, z: 0.469), Spot(x: 1.733, z: 0.518),
                    Spot(x: 1.737, z: 0.568), Spot(x: 1.741, z: 0.617), Spot(x: 1.744, z: 0.667),
                    Spot(x: 1.747, z: 0.716), Spot(x: 1.749, z: 0.766), Spot(x: 1.750, z: 0.816),
                    Spot(x: 1.751, z: 0.866), Spot(x: 1.752, z: 0.915), Spot(x: 1.751, z: 0.965),
                    Spot(x: 1.751, z: 1.015), Spot(x: 1.749, z: 1.064), Spot(x: 1.748, z: 1.114),
                    Spot(x: 1.745, z: 1.164), Spot(x: 1.743, z: 1.213), Spot(x: 1.739, z: 1.263),
                    Spot(x: 1.736, z: 1.312), Spot(x: 1.732, z: 1.362), Spot(x: 1.727, z: 1.412),
                    Spot(x: 1.722, z: 1.461), Spot(x: 1.717, z: 1.510), Spot(x: 1.712, z: 1.560),
                    Spot(x: 1.706, z: 1.609), Spot(x: 1.700, z: 1.659), Spot(x: 1.694, z: 1.708),
                    Spot(x: 1.688, z: 1.757), Spot(x: 1.682, z: 1.807), Spot(x: 1.675, z: 1.856),
                    Spot(x: 1.669, z: 1.905), Spot(x: 1.663, z: 1.954), Spot(x: 1.657, z: 2.004),
                    Spot(x: 1.652, z: 2.053), Spot(x: 1.650, z: 2.103),
                ]),
            ],
        ]
    )
}
