// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_fen.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

extension PlaceTable {
    /// The Home Ground's places for a bed sown with umbels (`Fen`), in each of its three beds.
    ///
    /// The fennel's family: umbels, two across at 0.60 m and seven rows 0.60 m
    /// apart, fourteen a bed. The rows follow the bed's line, which sways in a lazy
    /// S (`_home_ground.py` says how), and run square to it. Bed by bed, west to east
    /// as the table draws it, and in each bed in `HomeGround.Slot`'s order: from the
    /// north end, row by row, west to east along each row. A bed fills from both
    /// ends, so this is the rule's order, not a fill order.
    public static let homeGroundFen = PlaceTable(
        name: "home_ground_fen",
        fields: ["bed", "index"],
        variants: [
            [
                Place(x: -1.957, z: -1.849, tags: [0, 0]),
                Place(x: -1.367, z: -1.738, tags: [0, 1]),
                Place(x: -2.037, z: -1.216, tags: [0, 2]),
                Place(x: -1.438, z: -1.181, tags: [0, 3]),
                Place(x: -2.029, z: -0.574, tags: [0, 4]),
                Place(x: -1.431, z: -0.625, tags: [0, 5]),
                Place(x: -1.934, z: 0.056, tags: [0, 6]),
                Place(x: -1.347, z: -0.069, tags: [0, 7]),
                Place(x: -1.794, z: 0.645, tags: [0, 8]),
                Place(x: -1.209, z: 0.509, tags: [0, 9]),
                Place(x: -1.768, z: 1.117, tags: [0, 10]),
                Place(x: -1.178, z: 1.227, tags: [0, 11]),
                Place(x: -1.876, z: 1.728, tags: [0, 12]),
                Place(x: -1.281, z: 1.797, tags: [0, 13]),
                Place(x: -0.331, z: -1.827, tags: [1, 0]),
                Place(x: 0.261, z: -1.726, tags: [1, 1]),
                Place(x: -0.433, z: -1.219, tags: [1, 2]),
                Place(x: 0.164, z: -1.151, tags: [1, 3]),
                Place(x: -0.423, z: -0.547, tags: [1, 4]),
                Place(x: 0.172, z: -0.626, tags: [1, 5]),
                Place(x: -0.298, z: 0.069, tags: [1, 6]),
                Place(x: 0.286, z: -0.067, tags: [1, 7]),
                Place(x: -0.178, z: 0.634, tags: [1, 8]),
                Place(x: 0.415, z: 0.541, tags: [1, 9]),
                Place(x: -0.161, z: 1.160, tags: [1, 10]),
                Place(x: 0.437, z: 1.212, tags: [1, 11]),
                Place(x: -0.257, z: 1.722, tags: [1, 12]),
                Place(x: 0.333, z: 1.832, tags: [1, 13]),
                Place(x: 1.282, z: -1.794, tags: [2, 0]),
                Place(x: 1.879, z: -1.728, tags: [2, 1]),
                Place(x: 1.182, z: -1.224, tags: [2, 2]),
                Place(x: 1.772, z: -1.115, tags: [2, 3]),
                Place(x: 1.206, z: -0.506, tags: [2, 4]),
                Place(x: 1.789, z: -0.647, tags: [2, 5]),
                Place(x: 1.349, z: 0.069, tags: [2, 6]),
                Place(x: 1.936, z: -0.057, tags: [2, 7]),
                Place(x: 1.437, z: 0.625, tags: [2, 8]),
                Place(x: 2.035, z: 0.571, tags: [2, 9]),
                Place(x: 1.442, z: 1.176, tags: [2, 10]),
                Place(x: 2.041, z: 1.219, tags: [2, 11]),
                Place(x: 1.366, z: 1.736, tags: [2, 12]),
                Place(x: 1.955, z: 1.846, tags: [2, 13]),
            ],
        ],
        curves: [:]
    )
}
