// Generated by tools/layouts/generate.py from tools/layouts/tables/home_ground_fen.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

extension PlaceTable {
    /// The Home Ground's places for a bed sown with umbels (`Fen`), in each of its three beds.
    ///
    /// The fennel's family: umbels, two across at 0.60 m and seven rows 0.60 m
    /// apart, fourteen a bed. The rows follow the bed's line, which sways in a lazy
    /// S (`_home_ground.py` says how), and run square to it. Bed by bed, west to east
    /// as the table draws it, and in each bed in `HomeGround.Slot`'s order: from the
    /// north end, row by row, west to east along each row. A bed fills from both
    /// ends, so this is the rule's order, not a fill order.
    public static let homeGroundFen = PlaceTable(
        name: "home_ground_fen",
        fields: ["bed", "index"],
        variants: [
            [
                Place(x: -1.982, z: -1.833, tags: [0, 0]),
                Place(x: -1.387, z: -1.754, tags: [0, 1]),
                Place(x: -2.040, z: -1.208, tags: [0, 2]),
                Place(x: -1.440, z: -1.184, tags: [0, 3]),
                Place(x: -2.033, z: -0.576, tags: [0, 4]),
                Place(x: -1.434, z: -0.617, tags: [0, 5]),
                Place(x: -1.964, z: 0.045, tags: [0, 6]),
                Place(x: -1.371, z: -0.046, tags: [0, 7]),
                Place(x: -1.871, z: 0.632, tags: [0, 8]),
                Place(x: -1.276, z: 0.553, tags: [0, 9]),
                Place(x: -1.860, z: 1.166, tags: [0, 10]),
                Place(x: -1.263, z: 1.217, tags: [0, 11]),
                Place(x: -1.933, z: 1.759, tags: [0, 12]),
                Place(x: -1.336, z: 1.814, tags: [0, 13]),
                Place(x: -0.320, z: -1.823, tags: [1, 0]),
                Place(x: 0.277, z: -1.757, tags: [1, 1]),
                Place(x: -0.387, z: -1.216, tags: [1, 2]),
                Place(x: 0.211, z: -1.170, tags: [1, 3]),
                Place(x: -0.384, z: -0.567, tags: [1, 4]),
                Place(x: 0.214, z: -0.621, tags: [1, 5]),
                Place(x: -0.303, z: 0.045, tags: [1, 6]),
                Place(x: 0.290, z: -0.044, tags: [1, 7]),
                Place(x: -0.220, z: 0.629, tags: [1, 8]),
                Place(x: 0.376, z: 0.561, tags: [1, 9]),
                Place(x: -0.208, z: 1.179, tags: [1, 10]),
                Place(x: 0.391, z: 1.209, tags: [1, 11]),
                Place(x: -0.274, z: 1.752, tags: [1, 12]),
                Place(x: 0.322, z: 1.827, tags: [1, 13]),
                Place(x: 1.338, z: -1.811, tags: [2, 0]),
                Place(x: 1.936, z: -1.760, tags: [2, 1]),
                Place(x: 1.268, z: -1.224, tags: [2, 2]),
                Place(x: 1.864, z: -1.155, tags: [2, 3]),
                Place(x: 1.271, z: -0.553, tags: [2, 4]),
                Place(x: 1.866, z: -0.631, tags: [2, 5]),
                Place(x: 1.372, z: 0.047, tags: [2, 6]),
                Place(x: 1.965, z: -0.046, tags: [2, 7]),
                Place(x: 1.440, z: 0.617, tags: [2, 8]),
                Place(x: 2.039, z: 0.574, tags: [2, 9]),
                Place(x: 1.444, z: 1.178, tags: [2, 10]),
                Place(x: 2.043, z: 1.212, tags: [2, 11]),
                Place(x: 1.386, z: 1.754, tags: [2, 12]),
                Place(x: 1.981, z: 1.830, tags: [2, 13]),
            ],
        ],
        curves: [:]
    )
}
