// Generated by tools/layouts/generate.py from tools/layouts/tables/quiet_room.py.
// Do not edit: change the spec, then run python3 tools/layouts/generate.py.

extension PlaceTable {
    /// The Quiet Garden's asymmetric room: one, five, three and one, the pool off the middle toward the bench.
    ///
    /// Marcus, 2 October 2026 (RESEARCH.md, *The Quiet Garden*, option A). The ten
    /// dry places of a room stand as:
    ///
    /// - the specimen beside the bench (group 0), where it has stood since 21 September;
    /// - a group of five in the far corner, across the water: what the bench looks at (group 1);
    /// - a group of three along the side to the bench's left, a third of the way down it (group 2);
    /// - one plant alone across the lawn from the five, which repeats its colour: the echo (group 3).
    ///
    /// The pool lies off the middle toward the bench, longer across the bench's view
    /// than along it, with a bay on the bench's side that three stepping stones lead
    /// into from the seat (`stones`). Its two places (group 4) are the pool's own and
    /// lie along its length; the live garden never sends this area a lily, so they
    /// stay empty.
    ///
    /// Within a group the places are listed nearest the corner first, then
    /// farthest-first, and `stand` says which are the back of the group (1) and which
    /// its arms (0): the five has two at the back, the three one. A rule that takes
    /// the first free place of the stand it wants leaves every count of a group
    /// looking like a clump rather than a row begun at one end. The room is turned
    /// and mirrored by its plot's number, eight ways, so no two rooms side by side
    /// are laid alike.
    public static let quietRoom = PlaceTable(
        name: "quiet_room",
        fields: ["group", "stand"],
        variants: [
            [
                Place(x: -1.950, z: -0.950, tags: [0, 0]),
                Place(x: 1.949, z: 1.695, tags: [1, 1]),
                Place(x: 0.744, z: 1.420, tags: [1, 0]),
                Place(x: 1.796, z: 0.656, tags: [1, 0]),
                Place(x: 1.119, z: 0.788, tags: [1, 0]),
                Place(x: 1.351, z: 1.356, tags: [1, 1]),
                Place(x: 1.790, z: -1.457, tags: [2, 1]),
                Place(x: 1.577, z: -0.367, tags: [2, 0]),
                Place(x: 1.433, z: -0.952, tags: [2, 0]),
                Place(x: -1.700, z: 1.360, tags: [3, 0]),
                Place(x: 0.018, z: -0.578, tags: [4, 0]),
                Place(x: -0.618, z: 0.058, tags: [4, 0]),
            ],
        ],
        curves: [
            "pool": [
                Curve(closed: true, points: [
                    Spot(x: 0.461, z: -1.021), Spot(x: 0.481, z: -0.999), Spot(x: 0.501, z: -0.976),
                    Spot(x: 0.518, z: -0.951), Spot(x: 0.534, z: -0.925), Spot(x: 0.548, z: -0.898),
                    Spot(x: 0.560, z: -0.869), Spot(x: 0.569, z: -0.839), Spot(x: 0.576, z: -0.808),
                    Spot(x: 0.581, z: -0.776), Spot(x: 0.583, z: -0.743), Spot(x: 0.584, z: -0.710),
                    Spot(x: 0.585, z: -0.676), Spot(x: 0.584, z: -0.641), Spot(x: 0.584, z: -0.606),
                    Spot(x: 0.583, z: -0.570), Spot(x: 0.581, z: -0.533), Spot(x: 0.578, z: -0.495),
                    Spot(x: 0.572, z: -0.457), Spot(x: 0.564, z: -0.419), Spot(x: 0.552, z: -0.380),
                    Spot(x: 0.539, z: -0.342), Spot(x: 0.524, z: -0.303), Spot(x: 0.507, z: -0.264),
                    Spot(x: 0.490, z: -0.226), Spot(x: 0.471, z: -0.187), Spot(x: 0.451, z: -0.148),
                    Spot(x: 0.429, z: -0.109), Spot(x: 0.405, z: -0.071), Spot(x: 0.380, z: -0.034),
                    Spot(x: 0.354, z: 0.003), Spot(x: 0.326, z: 0.039), Spot(x: 0.296, z: 0.075),
                    Spot(x: 0.265, z: 0.109), Spot(x: 0.232, z: 0.141), Spot(x: 0.198, z: 0.173),
                    Spot(x: 0.163, z: 0.203), Spot(x: 0.127, z: 0.233), Spot(x: 0.091, z: 0.261),
                    Spot(x: 0.054, z: 0.288), Spot(x: 0.018, z: 0.315), Spot(x: -0.018, z: 0.342),
                    Spot(x: -0.053, z: 0.370), Spot(x: -0.088, z: 0.399), Spot(x: -0.123, z: 0.427),
                    Spot(x: -0.158, z: 0.453), Spot(x: -0.195, z: 0.477), Spot(x: -0.232, z: 0.499),
                    Spot(x: -0.270, z: 0.520), Spot(x: -0.308, z: 0.538), Spot(x: -0.347, z: 0.555),
                    Spot(x: -0.385, z: 0.570), Spot(x: -0.423, z: 0.583), Spot(x: -0.461, z: 0.595),
                    Spot(x: -0.499, z: 0.605), Spot(x: -0.536, z: 0.613), Spot(x: -0.573, z: 0.620),
                    Spot(x: -0.610, z: 0.624), Spot(x: -0.646, z: 0.627), Spot(x: -0.681, z: 0.627),
                    Spot(x: -0.716, z: 0.626), Spot(x: -0.750, z: 0.623), Spot(x: -0.783, z: 0.620),
                    Spot(x: -0.815, z: 0.615), Spot(x: -0.846, z: 0.609), Spot(x: -0.876, z: 0.601),
                    Spot(x: -0.906, z: 0.591), Spot(x: -0.934, z: 0.579), Spot(x: -0.961, z: 0.565),
                    Spot(x: -0.986, z: 0.549), Spot(x: -1.009, z: 0.531), Spot(x: -1.031, z: 0.512),
                    Spot(x: -1.051, z: 0.491), Spot(x: -1.069, z: 0.469), Spot(x: -1.086, z: 0.445),
                    Spot(x: -1.100, z: 0.420), Spot(x: -1.112, z: 0.393), Spot(x: -1.122, z: 0.366),
                    Spot(x: -1.130, z: 0.337), Spot(x: -1.136, z: 0.308), Spot(x: -1.141, z: 0.279),
                    Spot(x: -1.145, z: 0.249), Spot(x: -1.148, z: 0.218), Spot(x: -1.150, z: 0.187),
                    Spot(x: -1.150, z: 0.155), Spot(x: -1.150, z: 0.122), Spot(x: -1.148, z: 0.088),
                    Spot(x: -1.146, z: 0.054), Spot(x: -1.144, z: 0.019), Spot(x: -1.140, z: -0.017),
                    Spot(x: -1.135, z: -0.053), Spot(x: -1.125, z: -0.091), Spot(x: -1.111, z: -0.129),
                    Spot(x: -1.094, z: -0.169), Spot(x: -1.073, z: -0.208), Spot(x: -1.049, z: -0.248),
                    Spot(x: -1.021, z: -0.286), Spot(x: -0.990, z: -0.322), Spot(x: -0.955, z: -0.355),
                    Spot(x: -0.919, z: -0.386), Spot(x: -0.882, z: -0.414), Spot(x: -0.845, z: -0.440),
                    Spot(x: -0.809, z: -0.465), Spot(x: -0.775, z: -0.489), Spot(x: -0.742, z: -0.512),
                    Spot(x: -0.712, z: -0.533), Spot(x: -0.683, z: -0.552), Spot(x: -0.657, z: -0.572),
                    Spot(x: -0.632, z: -0.592), Spot(x: -0.608, z: -0.614), Spot(x: -0.586, z: -0.638),
                    Spot(x: -0.563, z: -0.664), Spot(x: -0.541, z: -0.693), Spot(x: -0.517, z: -0.723),
                    Spot(x: -0.492, z: -0.756), Spot(x: -0.465, z: -0.789), Spot(x: -0.437, z: -0.823),
                    Spot(x: -0.409, z: -0.858), Spot(x: -0.378, z: -0.892), Spot(x: -0.345, z: -0.925),
                    Spot(x: -0.310, z: -0.956), Spot(x: -0.275, z: -0.986), Spot(x: -0.240, z: -1.014),
                    Spot(x: -0.205, z: -1.041), Spot(x: -0.169, z: -1.065), Spot(x: -0.133, z: -1.086),
                    Spot(x: -0.097, z: -1.103), Spot(x: -0.060, z: -1.117), Spot(x: -0.025, z: -1.127),
                    Spot(x: 0.011, z: -1.135), Spot(x: 0.046, z: -1.141), Spot(x: 0.081, z: -1.145),
                    Spot(x: 0.116, z: -1.146), Spot(x: 0.150, z: -1.146), Spot(x: 0.183, z: -1.144),
                    Spot(x: 0.216, z: -1.141), Spot(x: 0.248, z: -1.135), Spot(x: 0.279, z: -1.128),
                    Spot(x: 0.309, z: -1.119), Spot(x: 0.338, z: -1.108), Spot(x: 0.365, z: -1.094),
                    Spot(x: 0.391, z: -1.078), Spot(x: 0.416, z: -1.060), Spot(x: 0.439, z: -1.041),
                ]),
            ],
            "stones": [
                Curve(closed: false, points: [
                    Spot(x: -1.477, z: -1.398), Spot(x: -1.060, z: -1.127), Spot(x: -0.793, z: -0.710),
                ]),
            ],
        ]
    )
}
