"""Writing a table as Swift, PHP and JavaScript: the same numbers, three spellings.

Every number is written from whole millimetres as a decimal with three places,
so the three languages each read the same decimal and round it to the same
double, and no float is ever formatted by Python. A place on an axis is `0.000`,
never `-0.000`.
"""

MARK = 'Generated by tools/layouts/generate.py from tools/layouts/tables/'


def camel(stem):
    head, *rest = stem.split('_')
    return head + ''.join(w[:1].upper() + w[1:] for w in rest)


def pascal(stem):
    return ''.join(w[:1].upper() + w[1:] for w in stem.split('_'))


def num(q):
    """Whole millimetres as metres: -912 is `-0.912`."""
    sign = '-' if q < 0 else ''
    a = abs(q)
    return f'{sign}{a // 1000}.{a % 1000:03d}'


def _header(stem, comment='//'):
    return (f'{comment} {MARK}{stem}.py.\n'
            f'{comment} Do not edit: change the spec, then run python3 tools/layouts/generate.py.\n')


def _doc(text, prefix):
    lines = text.strip().splitlines() if text else []
    return ''.join(f'{prefix}{line}'.rstrip() + '\n' for line in lines)


def _chunks(items, size):
    return [items[i:i + size] for i in range(0, len(items), size)]


def swift(table):
    """`Packages/SeedCore/Sources/SeedCore/WebGardens/Tables/<Name>.swift`."""
    s = table
    out = [_header(s.stem), '\n', 'extension PlaceTable {\n', _doc(s.doc, '    /// ')]
    out.append(f'    public static let {camel(s.stem)} = PlaceTable(\n')
    out.append(f'        name: "{s.stem}",\n')
    out.append('        fields: [' + ', '.join(f'"{f}"' for f in s.fields) + '],\n')
    out.append('        variants: [\n')
    for places in s.variants:
        out.append('            [\n')
        for x, z, tags in places:
            out.append(f'                Place(x: {num(x)}, z: {num(z)}, tags: [{", ".join(str(t) for t in tags)}]),\n')
        out.append('            ],\n')
    out.append('        ],\n')
    if not s.curves:
        out.append('        curves: [:]\n')
    else:
        out.append('        curves: [\n')
        for name, variants in s.curves.items():
            out.append(f'            "{name}": [\n')
            for closed, points in variants:
                out.append(f'                Curve(closed: {"true" if closed else "false"}, points: [\n')
                for row in _chunks(points, 3):
                    out.append('                    ' + ' '.join(f'Spot(x: {num(x)}, z: {num(z)}),' for x, z in row) + '\n')
                out.append('                ]),\n')
            out.append('            ],\n')
        out.append('        ]\n')
    out.append('    )\n}\n')
    return ''.join(out)


def php(table):
    """`Server/.api/tables/<Name>Table.php`."""
    s = table
    fields = ', '.join(f"'{f}'" for f in s.fields)
    out = ['<?php\ndeclare(strict_types=1);\n\n', _header(s.stem), '\n']
    out.append('/**\n' + _doc(s.doc, ' * ') + ' */\n')
    out.append(f'final class {pascal(s.stem)}Table\n{{\n')
    out.append(f"    public const NAME = '{s.stem}';\n\n")
    out.append(f'    /** What each tag of a place is, in order. */\n')
    out.append(f'    public const FIELDS = [{fields}];\n\n')
    out.append(f'    /** The places of each feature variant, in fill order: [x, z, {", ".join(s.fields) or "no tags"}]. */\n')
    out.append('    public const PLACES = [\n')
    for places in s.variants:
        out.append('        [\n')
        for x, z, tags in places:
            out.append('            [' + ', '.join([num(x), num(z)] + [str(t) for t in tags]) + '],\n')
        out.append('        ],\n')
    out.append('    ];\n\n')
    out.append('    /** Each curve by name: one [closed, [[x, z], ...]] per feature variant. */\n')
    if not s.curves:
        out.append('    public const CURVES = [];\n')
    else:
        out.append('    public const CURVES = [\n')
        for name, variants in s.curves.items():
            out.append(f"        '{name}' => [\n")
            for closed, points in variants:
                out.append(f'            [{"true" if closed else "false"}, [\n')
                for row in _chunks(points, 6):
                    out.append('                ' + ' '.join(f'[{num(x)}, {num(z)}],' for x, z in row) + '\n')
                out.append('            ]],\n')
            out.append('        ],\n')
        out.append('    ];\n')
    out.append('}\n')
    return ''.join(out)


def js(table):
    """`Server/assets/js/tables/<stem>.js`."""
    s = table
    out = [_header(s.stem), '//\n', _doc(s.doc, '// '), '\n']
    out.append(f'export const {camel(s.stem)} = Object.freeze({{\n')
    out.append(f"  name: '{s.stem}',\n")
    out.append('  fields: [' + ', '.join(f"'{f}'" for f in s.fields) + '],\n')
    out.append(f'  // The places of each feature variant, in fill order: [x, z, {", ".join(s.fields) or "no tags"}].\n')
    out.append('  places: [\n')
    for places in s.variants:
        out.append('    [\n')
        for x, z, tags in places:
            out.append('      [' + ', '.join([num(x), num(z)] + [str(t) for t in tags]) + '],\n')
        out.append('    ],\n')
    out.append('  ],\n')
    out.append('  // Each curve by name: one { closed, points } per feature variant.\n')
    out.append('  curves: {\n')
    for name, variants in s.curves.items():
        out.append(f'    {name}: [\n')
        for closed, points in variants:
            out.append(f'      {{ closed: {"true" if closed else "false"}, points: [\n')
            for row in _chunks(points, 6):
                out.append('        ' + ' '.join(f'[{num(x)}, {num(z)}],' for x, z in row) + '\n')
            out.append('      ] },\n')
        out.append('    ],\n')
    out.append('  },\n')
    out.append('});\n')
    return ''.join(out)
