import Foundation

/// The Serbian passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let serbian: [Passage] = [
        // MARK: - Почеци

        Passage(text: "Клијање почиње водом: семе се најпре напије, набубри и пукне по шаву, па тек онда пусти нешто напоље.", source: "Ботаника", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Прво што клица испусти јесте коренак, и он иде надоле. Нагоре се креће тек кад је нешто већ ухваћено.", source: "Ботаника", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ко коло води, тај и почиње.", source: "Народна пословица", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Киша кад хоће да падне, најприје почне капати.", source: "Народна пословица, збирка Вука Караџића", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Почети, зачети и начети имају исти корен. Један отвара посао, други живот, трећи хлеб — а сва три значе да оно што је било затворено више није.", source: "Српски језик", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Положајник је први који на Божић пређе кућни праг, и по томе каквог се дочека гата се каква ће бити цела година.", source: "Народни обичај", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ждребе се подигне на ноге у првом сату по рођењу, и прво што на њима уради јесте да пође за мајком.", source: "Зоологија", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Слово ј ушло је у српску ћирилицу 1818. године, Вуковим Рјечником, и око тог једног слова водила се потом деценијама препирка.", source: "Историја језика", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Пупољак се у пролеће прво ослободи љуспи које су га чувале преко зиме. Оно што испод њих испадне није лист него омотач.", source: "Ботаника", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Дрина нема извор. Она настаје тамо где се Тара и Пива састану, и од те тачке носи треће име.", source: "Географија", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Прво јаје офарбано на Велики четвртак зове се чуваркућа. Оно се не туче ни не једе, него остаје у кући до идућег Ускрса.", source: "Народни обичај", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Нула није најмањи број него место одакле се броји, и у рачун је ушла много касније од цифара око себе.", source: "Математика", theme: .beginnings, subtheme: .theFirstAct),

        Passage(text: "Свака вода с поточићи јака.", source: "Народна пословица, збирка Вука Караџића", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Семе оморике је ситно као зрно прашине, а стабло које из њега израсте иде и тридесет метара увис.", source: "Ботаника", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Багрем је у Србију донет из Северне Америке као украсно дрво. Данас од његовог цвета долази највише овдашњег меда.", source: "Пчеларство", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Кућа је најпре била кут — заклоњени угао. Отуда и кутак, и отуда што се за породицу каже цела кућа.", source: "Српски језик", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Свака од двеста земљаних кула у Ђавољој вароши стоји зато што јој је на врху један камен. Кад он падне, кула се за годину распе.", source: "Геологија", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Цело осиње гнездо потиче од једне матице која је сама преживела зиму. Све осе у њему су њене кћери.", source: "Ентомологија", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Пупољак липе је колики зрно пшенице, а кад се отвори, мирис пређе цео сокак.", source: "Ботаника", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Лепенски Вир је почео као неколико огњишта на обали Дунава. Изашло је насеље у коме је свака кућа окренута истој окуци реке.", source: "Археологија", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Град, ограда и градина су исти корен. Све троје је најпре значило само оно што је ограђено.", source: "Српски језик", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Стабљика жита је шупља, и због тога јача него да је пуна. Иста количина материје даље од средине држи више.", source: "Ботаника", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Из једног зрна пшенице израсте струк с више класова, а у сваком класу двадесетак нових зрна.", source: "Пољопривреда", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Малина се сади као прут дугачак с педаљ. Из тог прута иде роба због које је Србија годинама међу првима у свету.", source: "Пољопривреда", theme: .beginnings, subtheme: .smallToLarge),

        Passage(text: "Ко се мраза боји, нек не сади винограда.", source: "Народна пословица", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ако знамо шта је било, не знамо шта ће бити.", source: "Народна пословица, збирка Вука Караџића", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Пиши као што говориш, читај као што је написано. Правило постављено на почетку, због кога се српски правопис после није морао преправљати.", source: "Српски правопис", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Пастирску годину не отвара јануар него Ђурђевдан. Од тог дана стока излази на пашу, и одатле се броји све остало.", source: "Народни календар", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Кућни старешина није увек најстарији. Кад отац остари, преда старешинство најпаметнијем сину, макар био и најмлађи.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Где семе падне, ту ће и остати цео живот. О месту се одлучује једном, и не одлучује биљка него ветар.", source: "Ботаника", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Свака пузавица се вије само на једну страну, и та страна је одлика врсте — не гране на коју је наишла.", source: "Ботаника", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Најужи прстен у пресеченом пању јесте онај први. Колико год дрво порасло, он остаје најближи средини.", source: "Шумарство", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Крсна слава се не бира него наслеђује: син слави оно што је славио отац, а невеста прелази на славу куће у коју је дошла.", source: "Српски језик", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Боље је не почети него не дочети.", source: "Народна пословица, збирка Вука Караџића", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Поток бира страну на самом гребену. Неколико корака одлучује хоће ли његова вода стићи у Црно или у Јадранско море.", source: "Географија", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Пчеле саме одлуче да ће им требати нова матица, и то реше пре него што стара престане. Ларва коју изаберу до тада је била обична.", source: "Пчеларство", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: - Чекање

        Passage(text: "Мировање семена: семе неће да никне иако је све око њега како треба, зато што га нешто изнутра држи док се не промени.", source: "Ботаника", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Која воћка сама пада, не ваља је млатити.", source: "Народна пословица, збирка Вука Караџића", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Неким семенкама треба зима пре него што пристану да никну. Ако је не добију, чекају и другу годину, и трећу.", source: "Баштованство", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Кад неко замахне секиром на воћку која не рађа, други му дође и рече: не сијеци, родиће. На томе се стане, и то трипут.", source: "Народни обичај", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Стрпети се је свршени облик глагола трпети. Исти посао, само с крајем који се одавде већ види.", source: "Српски језик", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Пупољак се затвори у јесен и стоји готов целу зиму. Лист је у њему већ савијен и сложен, чека само топлоту.", source: "Ботаника", theme: .waiting, subtheme: .heldBack),
        Passage(text: "На Сретење медвед излази да види сенку. Ако је види, враћа се у брлог, и зима још није при крају.", source: "Народно веровање", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Дуња се остави на орман и не једе се одмах. Стоји док не омекша, а кућа за то време мирише на њу.", source: "Народни обичај", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Квочка на јајима седи двадесет један дан и не устаје дуже него што мора.", source: "Живинарство", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ко чека, тај и дочека.", source: "Народна пословица, збирка Вука Караџића", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Свитац је две године ларва под влажним лишћем, а светли свега неколико летњих вечери.", source: "Ентомологија", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Свашта има своје време, онда лепо личи.", source: "Јован Јовановић Змај (1833—1904)", theme: .waiting, subtheme: .heldBack),

        Passage(text: "Ако је кратак дан, дуга је година.", source: "Народна пословица, збирка Вука Караџића", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ако има много посла, има и дана.", source: "Народна пословица, збирка Вука Караџића", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "К'о плетиља она стара, дан што плете, ноћ опара.", source: "Лаза Костић (1841—1910)", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Тренућ ми је сваки сахат — моје време сад не иде.", source: "Његош, Ноћ скупља вијека", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Милутин Миланковић је рачунао како се Земљина оса и путања померају кроз стотине хиљада година, и рачунао је то оловком.", source: "Астрономија", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ревидирани јулијански календар, састављен 1923. године, разићи ће се с грегоријанским тек 2800.", source: "Астрономија", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Оморика је остатак шума старијих од леденог доба. Преживела је у уском појасу изнад Дрине и нигде више на свету.", source: "Ботаника", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Храст лужњак почне да рађа жир тек с четрдесетак година. Дотле само расте, и то се не да убрзати.", source: "Шумарство", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Сталагмит порасте отприлике један центиметар за сто година, капљицом по капљицом, и увек с истог места.", source: "Спелеологија", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Војвођанска равница лежи на лесу — прашини коју је ветар наносио десетинама хиљада година, слој преко слоја.", source: "Геологија", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Влашићи су стотинак звезда које путују заједно. Светлост којом их видимо кренула је пре више од четири столећа.", source: "Астрономија", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Кукавицу питају колико ће година, па броје колико пута кукне. Одговор се чека до краја, макар се дуго кукало.", source: "Народно веровање", theme: .waiting, subtheme: .theLongCount),

        Passage(text: "Уочи Богојављења неки стоје у пољу целу ноћ да виде кад се небо отвори. Кад се отвори, каже се, тражи се само једно.", source: "Народно веровање", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Рујну зору чека, да небом заруди.", source: "Војислав Илић (1862—1894)", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Чапља лови стојећи. Сатима не помери ни главу, а сам удар кљуном је бржи него што око стигне да види.", source: "Орнитологија", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Пудар је чувар винограда. Од краја лета до бербе спава у колиби међу чокотима и не ради ништа осим што гледа.", source: "Виноградарство", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Још су голе тихе равни и песма се још не хори.", source: "Војислав Илић (1862—1894)", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Млад сунцокрет окреће главу за сунцем целог дана. Кад процвета, стане и остане окренут истоку.", source: "Ботаника", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Шарпланинац не тера стадо него стоји уз њега. Цео дан не уради ништа, и то је тачно оно за шта је ту.", source: "Зоологија", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Роде се враћају на исто гнездо годинама. Гнездо расте одозго, слој по слој, и зна бити тешко колико и човек.", source: "Орнитологија", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Безбрижно пастир млад у звучне двојнице свира, а његов космати пас корача упоред с њим.", source: "Војислав Илић (1862—1894)", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Осматрачнице у шумама постоје зато што се с висине дим примети док је још дим, а не пожар.", source: "Шумарство", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Гледати и видети нису исти посао. Отуда у српском видело за светлост и видик за оно докле поглед стигне.", source: "Српски језик", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Снежни штап на планини стоји сам целу зиму, обележен на сваких десет центиметара. Цео посао је доћи до њега и прочитати га.", source: "Метеорологија", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: - Обнова

        Passage(text: "Ђурђевдан почиње пре сунца. Вода за купање сакупи се увече, преконоћ у њој стоји селен и остало биље, и тек ујутру ваља.", source: "Народни обичај", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ливада коси се два и три пута годишње, и трава од тога буде гушћа. Оно што је покошено расте из основе, а не с врха.", source: "Пољопривреда", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Врба се реже до пања сваке треће године ради прућа. Пањ од тога не пропада него се задебља и потера гушће.", source: "Шумарство", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Резидба винове лозе одузима јој и деведесет одсто прошлогодишњег раста. Без тога чокот подивља и грожђа буде мање.", source: "Виноградарство", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Гуштер репом плати бег. Нови нарасте, али је од хрскавице, а не од кости, и никад више није исти реп.", source: "Зоологија", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Јелен сваке зиме одбаци рогове и сваког пролећа израсте нове, веће. То је међу најбрже растућим ткивима које нека животиња прави.", source: "Зоологија", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Обновити је од нов: учинити поново новим. Реч не значи поправити него вратити у оно стање у ком је било пре свега.", source: "Српски језик", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Делиблатска пешчара је била покретни песак. Засадили су је боровима и багремом, и данас на њој расте шума.", source: "Шумарство", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Калемљење је спајање две биљке у једну. Корен остаје један, а оно што рађа долази с гране некога другог дрвета.", source: "Воћарство", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ајвар се пече у јесен, напољу, и никад за једну кућу. За тај посао се увек скупи више њих него што је потребно.", source: "Народни обичај", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Свака болест има свој лијек.", source: "Народна пословица, збирка Вука Караџића", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Кишо, мати, благодати! Падај, падај, прах утоли, дај живота гори, доли.", source: "Јован Јовановић Змај (1833—1904)", theme: .renewal, subtheme: .cutAndComeAgain),

        Passage(text: "Божић дође, зима прође.", source: "Народна пословица, збирка Вука Караџића", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "После дуге, мрачне зиме, к'о првенче младог цвећа, из влажне се земље диже први весник премалећа.", source: "Војислав Илић (1862—1894)", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Народна имена месеци иду за послом: гроздобер, шумопад, жетвар, лажитрава. Април је онај који трави обећа, па се одрекне.", source: "Народни календар", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Молимо се вишњем Богу, да удари росна киша, да пороси наша поља.", source: "Додолска песма, збирка Вука Караџића", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "У суши иду додоле: девојка обложена зеленим биљем игра пред кућом, а домаћица излије на њу пун котао воде.", source: "Народни обичај", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Пастирска година иде од Ђурђевдана до Митровдана. Оно између њих није година него зима, и не броји се исто.", source: "Народни календар", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Бабље лето је оно неколико топлих дана после првих хладних. Има их скоро сваке године, а увек изненаде.", source: "Метеорологија", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ласта се враћа у исто гнездо преко две хиљаде километара. Гнездо је од блата, и обично још стоји.", source: "Орнитологија", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Пролеће и премалеће су иста ствар речена двапут: једном као пролаз кроз зиму, једном као оно што долази пред лето.", source: "Српски језик", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Јесења сетва пшенице је рачун на зиму: клица никне, стане под снегом и дочека март већ ухваћена за земљу.", source: "Пољопривреда", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Живица зими изгледа мртва, а мртва је само спољашњост. Испод коре је зелено целе зиме.", source: "Ботаника", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "После краткодневице дан почне да расте по коју минуту. То се недељама не осети, а од тога иде све остало.", source: "Астрономија", theme: .renewal, subtheme: .theTurningYear),

        Passage(text: "Рамонда се на стени осуши до праха и стоји тако месецима. Кад падне киша, за неколико сати се врати у зелено.", source: "Ботаника", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Хајдучка трава носи то име зато што се стављала на ране. Стисне крвни суд, и крв стане брже него сама.", source: "Народна медицина", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Боквица расте где се највише гази, уз стазу и по утрини. Лист јој се одувек стављао на опекотину и на убод.", source: "Народна медицина", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Кора на дрвету не зараста као кожа. Дрво рану не затвара него је обраста, и та избочина остане заувек.", source: "Шумарство", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Оздравити значи вратити се у здраво, а здраво је стара реч за оно што је од доброг дрвета — цело, без пукотине.", source: "Српски језик", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Кост која се сломи и добро састави зараста јаче него што је била, и на том месту се више не ломи.", source: "Медицина", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Реке које су исправљене за пловидбу почеле су да се враћају у меандре чим им се допусти. Крива линија је стање мировања.", source: "Хидрологија", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Обедска бара је под заштитом од 1874. године, међу првим таквим местима у Европи. Заштита је значила само: пустите је.", source: "Заштита природе", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "После пожара прво никне оно чије је семе годинама лежало у земљи и чекало ватру да му разбије љуску. Тек за њима се враћа шума.", source: "Ботаника", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Помирити се и смирити се су иста реч с два префикса. Оба враћају у мир, једно с неким, друго са собом.", source: "Српски језик", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Кисело млеко се прави тако што се у ново дода мало од старог. Свака тегла води порекло од неке претходне.", source: "Домаћинство", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "И поток те чека вити, па ће боље жуборити.", source: "Јован Јовановић Змај (1833—1904)", theme: .renewal, subtheme: .madeWhole),

        // MARK: - Светлост

        Passage(text: "Даница и Вечерњача су иста звезда — планета Венера. Два имена је добила по томе у који је сат ко чека.", source: "Астрономија", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Тама долом, тама гором, наоколо све почива, само вода са жубором са камена што се слива.", source: "Бранко Радичевић (1824—1853)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Само што се кашто петли, само клепка што се чује, само с' онде малко светли, јер се данак приближује.", source: "Бранко Радичевић (1824—1853)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Сунце ј' прешло своје путе преко неба, њиве плаве, сад ће птице да ућуте, а звездице да се јаве.", source: "Јован Јовановић Змај (1833—1904)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ко рано устане, вас дан му добар настане.", source: "Народна пословица, збирка Вука Караџића", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Зора је именована од гледања: иста је основа у речима зора, зрети и назрети. Дан почиње оним што се тек разабере.", source: "Српски језик", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Сутон долази од глагола тонути. Није гашење него потапање, полако и с једне стране.", source: "Српски језик", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Од заласка сунца до потпуног мрака прође још сат и по. Тај се пут дели на три сумрака, и сваки од њих има своје име.", source: "Астрономија", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Птице почињу да певају пре него што се види ишта. Кос почиње први, а зеба и врабац знатно касније.", source: "Орнитологија", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ко рано рани, двије среће граби.", source: "Народна пословица, збирка Вука Караџића", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Слепи миш излази кад светлост падне испод одређене мере, а не у одређени сат. Зато сваке вечери излази нешто раније него претходне.", source: "Зоологија", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Уочи и предвече су сложенице од предлога. Српски има посебне речи за оно што је непосредно испред нечега.", source: "Српски језик", theme: .light, subtheme: .theEdgesOfTheDay),

        Passage(text: "Ко на брдо, ак' и мало, стоји, више види но онај под брдом.", source: "Његош, Горски вијенац", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Биљка броји ноћ, а не дан. По дужини мрака одлучује кад ће цветати, и зато је вештачка расвета збуни.", source: "Ботаника", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Пчела види светлост поларизовану, па и по облачном дану зна где је сунце. Небо јој је стално отворена карта.", source: "Ентомологија", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Прстенови у пресеченом стаблу нису године него светлост и вода: широк прстен значи добро лето, узак значи сушу.", source: "Шумарство", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Дуга се увек види под истим углом од четрдесет два степена према сунцу иза леђа. Зато сваки човек види своју.", source: "Физика", theme: .light, subtheme: .readingTheLight),
        Passage(text: "По боји жара се препознаје колико је ватра врела, и ковачи су по томе радили векове пре него што је постојао термометар.", source: "Ковачки занат", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Маховина не расте на северној страни дрвета зато што је север, него зато што је та страна дуже влажна.", source: "Ботаника", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Сунчани сат мери право сунчево време, које се од оног на ручном сату разилази и до петнаест минута, зависно од доба године.", source: "Астрономија", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Цветови детелине и зевалице се увече склапају и ујутру отварају. То се зове никтинастија и не зависи од топлоте него од светлости.", source: "Ботаника", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Виноград на јужној падини сазри и десетак дана раније него исти чокот на равном, на истој надморској висини.", source: "Виноградарство", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Мрак и мрачити стоје уз мрежу и мркнути. У истом гнезду речи су сумрак, помрчина и мркнути се — све је исто гашење.", source: "Српски језик", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Кад магла у јесен седне у долину, а брда остану ведра, то значи да је ваздух горе топлији него доле. Топлота је обрнута.", source: "Метеорологија", theme: .light, subtheme: .readingTheLight),

        Passage(text: "Дивно гора листа, дивно сунце сија, дивно река чиста зраке му одбија.", source: "Бранко Радичевић (1824—1853)", theme: .light, subtheme: .lightItself),
        Passage(text: "Плава луна ведрим зраком у прелести дивно тече испод поља звјезданије у прољећну тиху вече.", source: "Његош, Ноћ скупља вијека", theme: .light, subtheme: .lightItself),
        Passage(text: "Видело је стара српска реч за светлост, и долази од видети. Име јој није дато по томе шта јесте него по томе шта омогућава.", source: "Српски језик", theme: .light, subtheme: .lightItself),
        Passage(text: "Сунце је у словенским језицима по облику деминутив — мало сунце. Реч је од милоште, а односи се на звезду.", source: "Српски језик", theme: .light, subtheme: .lightItself),
        Passage(text: "Месечина није месечева светлост него сунчева, одбијена од површине која одбија мање од дванаестине онога што прими.", source: "Астрономија", theme: .light, subtheme: .lightItself),
        Passage(text: "Светлост са Сунца стигне за осам минута и двадесет секунди. Оно што видимо у подне десило се пре доручка на Сунцу.", source: "Астрономија", theme: .light, subtheme: .lightItself),
        Passage(text: "Свитац светли хладно: у његовој светлости готово да нема топлоте, што ниједан пламен не уме.", source: "Ентомологија", theme: .light, subtheme: .lightItself),
        Passage(text: "Небо је плаво зато што ваздух расипа кратке таласе јаче од дугих. Иста појава увече чини залазак црвеним.", source: "Физика", theme: .light, subtheme: .lightItself),
        Passage(text: "Зрак и зрачити стоје уз зрети и зеницу. Светлосни сноп је у српском именован од ока које га прима.", source: "Српски језик", theme: .light, subtheme: .lightItself),
        Passage(text: "Сутра долази од израза за јутро. Дан после овога именован је по свом свитању, а не по свом трајању.", source: "Српски језик", theme: .light, subtheme: .lightItself),
        Passage(text: "Пламен свеће је најврелији на својој спољној, готово невидљивој ивици, а најхладнији у тамној средини одмах изнад фитиља.", source: "Хемија", theme: .light, subtheme: .lightItself),
        Passage(text: "Ала је леп овај свет: онде поток, овде цвет.", source: "Јован Јовановић Змај (1833—1904)", theme: .light, subtheme: .lightItself),

        // MARK: - Ред

        Passage(text: "Боље је омјерити, па кројити.", source: "Народна пословица, збирка Вука Караџића", theme: .pattern, subtheme: .counted),
        Passage(text: "Дани у недељи су у српском бројеви: уторак је други, четвртак четврти, петак пети. Среда је она у средини.", source: "Српски језик", theme: .pattern, subtheme: .counted),
        Passage(text: "Месец је реч за небеско тело и за раздобље, и стоји уз мерити. Прво мерило времена било је оно што се види.", source: "Српски језик", theme: .pattern, subtheme: .counted),
        Passage(text: "Пиротски ћилим се тка тако да нема наличје. Обе стране су лице, и по томе се и данас препознаје прави.", source: "Ткање", theme: .pattern, subtheme: .counted),
        Passage(text: "Три је број који све решава: трипут се окреће славски колач, трипут се замахне на воћку, трипут се пољуби при сусрету.", source: "Народни обичај", theme: .pattern, subtheme: .counted),
        Passage(text: "Пресек стабљике трске је савршен круг, а пресек стабљике шаша троугао. По том једном податку се разликују на први додир.", source: "Ботаника", theme: .pattern, subtheme: .counted),
        Passage(text: "Пчела прави ћелију која има шест страна зато што шестоугао покрива раван без остатка, а троши најмање воска.", source: "Геометрија", theme: .pattern, subtheme: .counted),
        Passage(text: "Прекјуче и прекосутра су по једна реч. Српски има посебна имена за два дана уназад и два унапред, а даље не.", source: "Српски језик", theme: .pattern, subtheme: .counted),
        Passage(text: "Латице руже, јабуке и глога иду по пет. Цео тај род се на један поглед препознаје по броју, пре него по боји.", source: "Ботаника", theme: .pattern, subtheme: .counted),
        Passage(text: "Стара мера за жито био је варићак, а за њиву дан орања — колико се изоре за један дан. Мера је био посао, а не дужина.", source: "Мере и тегови", theme: .pattern, subtheme: .counted),
        Passage(text: "Опанак се плете од једног комада коже, без иједног шава по средини. Целу шару држи ред у коме је кожа пресечена.", source: "Обућарски занат", theme: .pattern, subtheme: .counted),
        Passage(text: "Гуслама је једна жица. Све што се на њима свира настаје од промене места прста, а не од промене жице.", source: "Музика", theme: .pattern, subtheme: .counted),

        Passage(text: "Двојнице су једна фрула са два канала. Један држи стални тон, други води мелодију, и обоје свира један човек.", source: "Музика", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Неуморна плетисанко, што плетиво плетеш танко међу јавом и мед сном.", source: "Лаза Костић (1841—1910)", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Брвнара се склапа без ексера. Греде се на угловима усецају једна у другу, и кућа држи саму себе сопственом тежином.", source: "Дрводељство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ћеремида на крову ради само у пару: једна окренута нагоре, суседна надоле преко ње. Ниједна сама не држи кишу.", source: "Градитељство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Камени мост држи се тако што сваки камен притиска суседни. Кад се извади средњи, падне цео лук, а док је он ту, ништа.", source: "Градитељство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Плетер је камена трака извајана тако да улази сама у себе без почетка и краја. Њиме су се украшавале најстарије овдашње цркве.", source: "Каменорезачки занат", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Основа и потка стоје под правим углом. Ниједна нит сама не држи ништа; тканина постоји само на местима где се укрштају.", source: "Ткање", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Пукотине у осушеном блату скоро увек се секу под правим углом, зато што свака нова пукотина ослобађа затегнутост претходне.", source: "Физика", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Кора платана се љушти у плочама које се уклапају као мапа. Испод сваке отпале плоче стоји већ готова следећа.", source: "Ботаника", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Шара на пиротском ћилиму има име: корњача, врбов лист, ђулови, српско коло. Име се учи заједно с начином како се тка.", source: "Ткање", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Усек, чеп и жљеб су имена за исто решење: два комада дрвета која се држе тако што једно улази у друго.", source: "Дрводељство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Тесање камена за суви зид не тражи малтер него стрпљење. Свака плоча се окреће док не нађе положај у коме више не клима.", source: "Каменорезачки занат", theme: .pattern, subtheme: .fittedTogether),

        Passage(text: "Речи којима цео свет именује кречњачки предео — понор, долина, увала, поље — словенске су речи ушле у науку.", source: "Географија", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Вуков Рјечник из 1818. има 26.270 речи. Друго издање, из 1852, има 47.427, и све су са означеним нагласком.", source: "Историја језика", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Српска ћирилица има тридесет слова и тридесет гласова. Ниједно слово не значи два гласа и ниједан глас нема два слова.", source: "Правопис", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Вокатив је падеж који постоји само зато што се неко дозива. Осталих шест каже нешто о свету, а он се обраћа.", source: "Граматика", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Панчићева оморика је описана 1876. и добила је име по човеку који је годинама тражио дрво за које су му људи причали.", source: "Ботаника", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Народна имена биљака често су читаве слике: мајчина душица, хајдучка трава, чуваркућа, дан и ноћ. Име каже шта биљка ради или где стоји.", source: "Народна ботаника", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Гусле имају једну жицу, и она је од коњске длаке. Од исте длаке је и гудало којим се по њој превлачи.", source: "Музика", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Свршени и несвршени вид су у српском два различита глагола, а не два времена. Писати и написати нису исти посао.", source: "Граматика", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Из Винче код Београда извађене су хиљаде знакова урезаних у глину пре више од шест хиљада година. Да ли је то писмо, још се расправља.", source: "Археологија", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Кумовска слама је овдашње име за Млечни пут: слама коју је кум просуо носећи је куму, па је Бог оставио на небу за спомен.", source: "Народна астрономија", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Влашићи, Косци, Кола: народна имена сазвежђа именују их по послу и по алату, а не по боговима.", source: "Народна астрономија", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Ћ и ч, ђ и џ су четири различита гласа и четири различита слова. Језик их држи одвојено тамо где их многи други спајају у два.", source: "Правопис", theme: .pattern, subtheme: .orderNamed),

        // MARK: - Тло

        Passage(text: "Чернозем је земља толико црна да јој је име само боја. Војвођански слој има и по метар дубине.", source: "Педологија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Кишна глиста годишње пропусти кроз себе земљу много тежу од себе саме, и оно што за њом остане боља је земља него оно што је узела.", source: "Педологија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Микориза: гљива обавије корен и продужи га стотинама пута. Дрво јој даје шећер, она му доноси воду.", source: "Ботаника", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "У једној грудви оранице живи више бића него што има људи на свету. Голим оком се од тога види једва понешто.", source: "Педологија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Земљи треба око стотину година да од стене начини један сантиметар оранице, а да се тај сантиметар однесе довољна је једна олуја.", source: "Педологија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Реч земља значи и тле и државу и планету. Између те три ствари српски не прави никакву разлику у речи.", source: "Српски језик", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Мирис земље после кише долази од једне материје коју праве бактерије у тлу. Човек је осети у количини од неколико делића на милијарду.", source: "Хемија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Детелина и грашак хране земљу у коју су посејани. На њиховом корењу живе бактерије које азот узимају право из ваздуха.", source: "Ботаника", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Крашко поље изгледа као обична равница, али вода из њега не отиче реком него пропада кроз камен, кроз отвор који се зове понор.", source: "Геологија", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ко има поља, има дио Бога.", source: "Народна пословица, збирка Вука Караџића", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ледина је земља коју нико није орао. Реч се употребљава и за оно што је остављено, и за оно што још није начето.", source: "Српски језик", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Рудна Глава у источној Србији је најстарији познати рудник бакра у Европи. Копало се пре седам хиљада година, роговима јелена.", source: "Археологија", theme: .ground, subtheme: .theSoilItself),

        Passage(text: "Завичај се изводи од завићи се — навићи се. То је, дословно, место на које се човек навикао.", source: "Српски језик", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Свака је квочка на свом гнијезду јака.", source: "Народна пословица, збирка Вука Караџића", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Огњиште значи место ватре, а користи се за читав дом. Кућа се именује по оном једном месту у њој које се не гаси.", source: "Српски језик", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Фрушка гора је била острво. Кад је Панонско море отекло, остала је као брдо усред равнице, и по томе се и данас види.", source: "Геологија", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Свака заветина се слави на једном брду или на једном лепом месту у селу, и то на истом сваке године.", source: "Народни обичај", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Пчела нађе кошницу по мирису и по томе где стоји. Ако се кошница помери за метар, вратиће се на старо место и тражити.", source: "Пчеларство", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Виноград даје другачије вино с две падине истог брда. Иста лоза, иста рука, а вино које се не може заменити.", source: "Виноградарство", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Село се и селити имају исти корен. Место где се стало именовано је глаголом за кретање које је стало.", source: "Српски језик", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ластавица која се излегла под једном стрехом враћа се, после зиме проведене у Африци, под ту исту стреху.", source: "Орнитологија", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Дунавски слив се простире на деветнаест земаља. Ниједан други речни слив на свету не додирује толико њих.", source: "Хидрологија", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Вајат је засебна зграда у авлији у којој спава млади брачни пар. Кућа с огњиштем била је заједничка, а вајат само њихов.", source: "Народни говор", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Атар је сва земља која припада једном селу, укључујући и оно што нико не обрађује. Село има границу и тамо где нема куће.", source: "Народни говор", theme: .ground, subtheme: .aPlaceYouAreFrom),

        Passage(text: "Труда мени није жао, перивој сам подигао.", source: "Бранко Радичевић (1824—1853)", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ко купус сади и крмачу храни, не боји се глади.", source: "Народна пословица, збирка Вука Караџића", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "На старом огњишту мирно пуцкара црвенкаст плам.", source: "Војислав Илић (1862—1894)", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Чуваркућа је биљка коју су садили на кров, да чува кућу од грома. Расте на голом црепу, без иједне капи са стране.", source: "Народна ботаника", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Порушит' га нисмо дали, ми смо вам га сачували.", source: "Јован Јовановић Змај (1833—1904)", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Међа између две њиве није ничија. Оре се до ње с обе стране, а сама остаје трава, и по томе се и препознаје.", source: "Пољопривреда", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Стари воћњак се одржава тако што се сваке године посади једно младо дрво. Воћњак тако никад није ни стар ни млад.", source: "Воћарство", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Башта и башча долазе од персијске речи за врт. Реч је до овдашњих плотова стигла преко Турске, и остала.", source: "Српски језик", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Салаш је кућа насред сопствене земље, без суседа. Војводина је пуна места која су цела село од једне куће.", source: "Народно градитељство", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Дудови по војвођанским друмовима засађени су у осамнаестом веку ради свилених буба. Свила је давно нестала, дудови су остали.", source: "Историја пољопривреде", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Чесма у селу је припадала свима и никоме. Одржавала се договором, и због тога је обично била и место где се стоји и разговара.", source: "Народни обичај", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ајвар, зимница и туршија су три имена за једну исту рачуницу: узети од лета онолико колико ће зими требати.", source: "Домаћинство", theme: .ground, subtheme: .aKeptPlace),

        // MARK: - Пут

        Passage(text: "Јавор баца семе с два крила која га заврте. Тим окретањем оно се задржи у ваздуху таман толико да га ветар однесе.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Чичак се хвата ситном куком на врху сваке бодље, и то не за земљу него за длаку и за вуну. Семе путује онолико колико и животиња на којој је.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Имела нема корен у земљи. Птица поједе бобицу, обрише кљун о грану, и биљка почне тамо где је кљун обрисан.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Семе боквице на киши постане лепљиво. Залепи се за ципелу и путује докле год се хода, а онда сиђе.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Сојка закопа неколико хиљада жирова на јесен и не нађе све. Од заборављених настају храстови далеко од матичног дрвета.", source: "Орнитологија", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Мрав носи семе кући због једног масног прираштаја на њему. Поједе тај део, а остало избаци на сметлиште, где је земља најбоља.", source: "Ентомологија", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Врба пусти семе које живи свега неколико дана. Ако за то време не падне на влажан песак, ништа од њега.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Маслачак има чекињасти падобран који га држи у ваздуху захваљујући малом вртлогу изнад њега. Тај вртлог је откривен тек недавно.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Кукуруз без човека не путује никуда. Клип не пуца сам, зрна се не одвајају, и биљка зависи од тога да неко дође.", source: "Пољопривреда", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Багремово семе има тврду љуску која мора да буде оштећена да би никло. У природи то раде вода, мраз и пролазак кроз животињу.", source: "Ботаника", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Орах пада право под дрво и ту би остао. Веверица га однесе и закопа, а закопа обично више него што ће појести.", source: "Зоологија", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Река носи семе низводно и никад узводно. Свака биљка уз воду шири се само на једну страну, док је нека птица не врати.", source: "Хидрологија", theme: .travel, subtheme: .howASeedGoes),

        Passage(text: "Ко полако иде, прије дома дође.", source: "Народна пословица, збирка Вука Караџића", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ако је и рђаво вријеме, путници путују.", source: "Народна пословица, збирка Вука Караџића", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ко лагано иде, даље ће отићи.", source: "Народна пословица, збирка Вука Караџића", theme: .travel, subtheme: .theRoad),
        Passage(text: "Стазица кривуда, поред липе води.", source: "Бранко Радичевић (1824—1853)", theme: .travel, subtheme: .theRoad),
        Passage(text: "Пут значи и друм и прилику: први пут, овај пут, сваки пут. Једна реч за место и за то колико се пута нешто десило.", source: "Српски језик", theme: .travel, subtheme: .theRoad),
        Passage(text: "Друм је грчка реч за трчање, ушла преко Византије. Пут који су Римљани направили овде је прво имао туђе име.", source: "Српски језик", theme: .travel, subtheme: .theRoad),
        Passage(text: "Најстарији путеви иду гребеном, а не долином. Горе је сувље, види се даље, и не мора се прелазити ниједна река.", source: "Географија", theme: .travel, subtheme: .theRoad),
        Passage(text: "Стока сама изгази стазу до воде, и та стаза увек иде најблажим успоном. Људи су после многе своје путеве направили по њима.", source: "Географија", theme: .travel, subtheme: .theRoad),
        Passage(text: "Кроз Ђердап се низводно пловило лако, а узводно су лађе вукли људи и коњи стазом усеченом у стену изнад воде.", source: "Историја пловидбе", theme: .travel, subtheme: .theRoad),
        Passage(text: "Конак је реч и за преноћиште и за једну ноћ пута. Дужина дана мерила се тиме где ће се спавати.", source: "Српски језик", theme: .travel, subtheme: .theRoad),
        Passage(text: "Кад путује преко земље, човек иде на конак у село где га мрак затече, пред најбољу кућу, и пита може ли ноћити.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ход'те ход'те, птице вите, да с' од пута одморите!", source: "Јован Јовановић Змај (1833—1904)", theme: .travel, subtheme: .theRoad),

        Passage(text: "Видик је оно докле се види, и то је на равном свега пет километара. Даље не постоји брдо него закривљеност.", source: "Географија", theme: .travel, subtheme: .farOff),
        Passage(text: "Ласта која се лети храни изнад Саве зимује у јужној Африци и пређе тај пут двапут годишње, сама, без икаквог вођства.", source: "Орнитологија", theme: .travel, subtheme: .farOff),
        Passage(text: "На овдашњим неолитским налазиштима нађен је накит од шкољки које живе само у топлом мору на југу. Неко их је донео преко свих тих брда.", source: "Археологија", theme: .travel, subtheme: .farOff),
        Passage(text: "Даљина се у народном говору мерила временом: на два сата хода, на дан пута. Растојање дуго није било дужина него трајање.", source: "Српски језик", theme: .travel, subtheme: .farOff),
        Passage(text: "Стазо вита, нес' ме преко они гора.", source: "Бранко Радичевић (1824—1853)", theme: .travel, subtheme: .farOff),
        Passage(text: "Роде из Војводине зимују у јужној Африци и лете дању, једрећи на топлом ваздуху. Преко широког мора не иду јер тамо тог ваздуха нема.", source: "Ихтиологија", theme: .travel, subtheme: .farOff),
        Passage(text: "Са Копаоника се по потпуно ведром дану виде брда удаљена преко сто педесет километара. Таквих дана буде неколико годишње.", source: "Географија", theme: .travel, subtheme: .farOff),
        Passage(text: "Реч туђ потиче од старе речи за народ, позајмљене још од Гота. Странац је, по пореклу, онај који припада другом народу.", source: "Српски језик", theme: .travel, subtheme: .farOff),
        Passage(text: "Белоглави суп с Увца прелети и три стотине километара за један дан, тражећи храну, па се увече врати на исту стену.", source: "Орнитологија", theme: .travel, subtheme: .farOff),
        Passage(text: "Паприка и кукуруз стигли су овамо из Америке, а данас се без њих не може замислити ниједан овдашњи ручак.", source: "Историја пољопривреде", theme: .travel, subtheme: .farOff),
        Passage(text: "Прекоморски и прекогранични су речи од предлога преко. У српском се даљина именује оним што је требало прећи.", source: "Српски језик", theme: .travel, subtheme: .farOff),
        Passage(text: "Магла на хоризонту није ваздух него ситна вода. Због ње се даљина увек чини плавља него што јесте, и то се зове ваздушна перспектива.", source: "Физика", theme: .travel, subtheme: .farOff),

        // MARK: - Сусрет

        Passage(text: "Срећа и сусрет су иста реч. Оно што се човеку догоди назива се, по пореклу, оним што му је дошло у сусрет.", source: "Српски језик", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ко мене: добро јутро! ја њему: добра ти срећа!", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ево иду, као звани, наши лањски сукућани.", source: "Јован Јовановић Змај (1833—1904)", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Дочекати је сложено од чекати. Исти глагол, а с префиксом значи да је онај кога се чекало стигао.", source: "Српски језик", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Сретење је име празника и значи сусрет: сусрет двоје старих људи с дететом у храму, по причи из које је дан добио име.", source: "Народни календар", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Дође момче црна ока на коњицу лака скока, поздрави ме, зборит оде: дајде, селе, мало воде!", source: "Бранко Радичевић (1824—1853)", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Раскрсница је место где се укрштају два пута, а не место где се један грана. Разлика је у томе да ли је неко долазио с друге стране.", source: "Српски језик", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Две реке које се састану не помешају се одмах. Сава и Дунав теку упоредо још километрима, у две боје, пре него што постану једно.", source: "Хидрологија", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Пчела која нађе пашу игра на саћу да каже осталима где је. Тај плес траје неколико секунди и садржи и правац и удаљеност.", source: "Ентомологија", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ко добро чини, боље дочека.", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .theMoment),
        Passage(text: "На прелу се преде ноћу, а долази и по које момче, те се с прељама разговара и шали.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Лептирићу, шаренчићу, ходи к мени амо!", source: "Јован Јовановић Змај (1833—1904)", theme: .meeting, subtheme: .theMoment),

        Passage(text: "Боље виде два ока него једно.", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Дрво се на дрво наслања, а човек на човека.", source: "Народна пословица", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Смоква и оса која је оплођује не могу једна без друге. Ниједна од њих се нигде на свету не среће сама.", source: "Ботаника", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Лишај је гљива и алга које живе као једно. Гледајући споља, нико их вековима није ни разликовао.", source: "Ботаника", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Многи цветови отпуштају полен пре него што им сопствени тучак сазри, тако да са собом не могу да се сретну.", source: "Ботаника", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Јабука не рађа од сопственог полена. У сваком воћњаку мора да стоји и друга сорта, иначе цветања буде а рода не.", source: "Воћарство", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Кад се пева на бас, потребна су два гласа: један води, други држи испод њега, и на самом крају се обојица нађу на истом тону.", source: "Музика", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Тестера с две ручке се не гура него вуче, наизменично. Ко покуша сам, само је закочи.", source: "Дрводељство", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Коло се хвата за руке. Онај ко води не води себе него оне који су га примили с обе стране.", source: "Народна игра", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Кључ и брава немају никакав смисао одвојено. Оба су направљена да описују један другог, и ништа више.", source: "Браварски занат", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Славуј песмом љуља луг. Ја га слушам и мој друг.", source: "Јован Јовановић Змај (1833—1904)", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Реч сусед је од предлога с и корена који значи седети. Комшија је, дословно, онај који седи с нама.", source: "Српски језик", theme: .meeting, subtheme: .twoThatNeedEachOther),

        Passage(text: "Добро дошао одговара се са боље те нашао. Гост не захваљује за поздрав него узвраћа већим.", source: "Народни обичај", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Можеш, брате, с драге воље и добро дошао.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Здраво је поздрав и придев у исти мах. Реч потиче од старог израза за оно што је од доброг дрвета, чврсто и без пукотине.", source: "Српски језик", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Кад Србин не зна нечије име, зовне га: еј, побратиме!", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Госту се прво изнесе кашичица слатког и чаша воде, и тек после тога се почиње разговор.", source: "Народни обичај", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Преко прага се не рукује и не додаје ништа. Ко долази, мора прво да уђе, а тек онда се поздравља.", source: "Народни обичај", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Хоћу, хоћу — драге воље, вода није скупа.", source: "Јован Јовановић Змај (1833—1904)", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Госту је у госта вазда јутро.", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ако је и црна крава, бијело млијеко даје.", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "На славу се долази и без позива. Кућа тога дана не позива никога зато што су сви већ позвани.", source: "Народни обичај", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Од Ускрса до Спасовдана се, кад се двојица сретну на путу, уместо добро јутро каже Христос васкрсе, и одговара Ваистину васкрсе.", source: "Народни обичај", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ко нема сокола, и кукавици се весели.", source: "Народна пословица, збирка Вука Караџића", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: - Род

        Passage(text: "Анастомоза је спајање два одвојена тока у један. Каже се за реке, за крвне судове и за жиле на листу.", source: "Медицина", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Два стабла која се додирују годинама могу да срасту у једно. Кора се на месту трљања излиже, а дрво испод ње се споји.", source: "Шумарство", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Моба је рад без плате: иде се газди да се пожање, само за јело и за пиће, и сваки се обуче као за празник.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Задруга је кућа у којој живи неколико породица заједно. Вук је записао једну од шездесет и двоје чељади под истим старешином.", source: "Народни живот", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Дружичало је други понедељак по Ускрсу. Тога дана се људи побратиме кроз врбов венац и мењају јаја, и то важи годину дана.", source: "Народни обичај", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Јасика дрхти и без ветра зато што јој је лисна дршка спљоштена управно на лист. Ниједна друга овдашња врста није тако везана.", source: "Ботаника", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Багремова шума расте из једног корена. Оно што изгледа као стотину дрвета обично је једна биљка која се проширила испод земље.", source: "Ботаника", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Свака крава своје теле лиже.", source: "Народна пословица, збирка Вука Караџића", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Кад се калем прими, спој се више не може раздвојити. Ткиво подлоге и ткиво племке израсту једно у друго.", source: "Воћарство", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Влакна у ужету не држе ништа појединачно. Уже држи зато што их је извијање притиснуло једно уз друго.", source: "Ужарски занат", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Свака тица своме јату иде.", source: "Народна пословица, збирка Вука Караџића", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Гљиве које ничу у кругу по ливади део су једног истог подземног организма. Круг сваке године буде шири за неколико педаља.", source: "Микологија", theme: .kinship, subtheme: .grownTogether),

        Passage(text: "Пријатељ значи и друг и родитеља снаје или зета. Породица која се приженила није родбина него — пријатељи.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Пријатељ је од глагола пријати. Тај је корен исти као у енглеској речи за пријатеља, и обе значе: онај који годи.", source: "Етимологија", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Стриц је очев брат, ујак мајчин, а теча је муж тетке. Три речи тамо где многи језици имају једну.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Јетрве су жене двојице браће, а заове су мужевљеве сестре. Свака врста снајиног односа има своје засебно име.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Кум се не бира за једном него се наслеђује: кумство иде с колена на колено и не раскида се лако.", source: "Народни обичај", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Побратим је онај с ким се човек побратимио, а у старим требницима постоји и посебна молитва која се тада читала.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Осим побратимити, у српском се може и посестрити, поочити и посинити. Свака рођачка веза може се и склопити, а не само наследити.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Сестра је по пореклу сложеница од своје и жена — она која је од своје куће. Реч је старија од сваког словенског језика.", source: "Етимологија", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Домаћин је од дом, а дом је исти корен као латинско domus. Тај се корен није мењао пет хиљада година.", source: "Етимологија", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Свастика је женина сестра, а пашеног је муж женине сестре. Однос између два човека који нису у роду ипак има име.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Комшија је турска реч, сусед словенска, а значе исто. Обе су остале у употреби, и не значе баш увек исту врсту близине.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Чељад је стара реч за све оне који живе у једној кући, без обзира на то ко им је ко. Броји се као једнина.", source: "Српски језик", theme: .kinship, subtheme: .theWordsForIt),

        Passage(text: "Пастир своју фрулу лаћа, песма крила разавила, раденик се с посла враћа, њега грле деца мила.", source: "Јован Јовановић Змај (1833—1904)", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "И позно у тавну ноћ разговор спокојно бруји.", source: "Војислав Илић (1862—1894)", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Кад вам од нас што затреба, само мени кажи.", source: "Јован Јовановић Змај (1833—1904)", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Белоглави супови се паре за цео живот и заједно подижу по једно младунче на две године. Оба родитеља седе на јајету.", source: "Орнитологија", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Реч друг значи и пратилац и онај који је други. Друштво је, по пореклу, стање у коме постоји неко други.", source: "Српски језик", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Боље је дијелити него просити.", source: "Народна пословица, збирка Вука Караџића", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Гавранов пар лови заједно и остаје заједно и ван сезоне парења. Кад једно нађе храну, дозива друго пре него што почне.", source: "Орнитологија", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Кад се на моби заврши њива, девојке направе барјаке од марама, па онако с барјацима иду кући певајући.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Кад двоје носе терет на мотки, тежина иде на онога који му је ближи. Изједначава се тако што се терет помера, а не људи.", source: "Народна пословица, збирка Вука Караџића", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Кад се гост наговара да остане на ручку, он на то одговара: свака сила проклета, а та благословена.", source: "Народни обичај", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Славуј пева ноћу док је сам. Кад нађе пару, ноћно певање престане, и остане само оно дневно.", source: "Физиологија", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Здравица се не пије сама. Реч је од здравље, и цео обичај постоји да би се то здравље некоме наглас пожелело.", source: "Народни обичај", theme: .kinship, subtheme: .twoPeople),

        // MARK: - Мир

        Passage(text: "Распрсне ли пупуљ цвјетни али кане роса с струка — све то слуху оштром грми.", source: "Његош, Ноћ скупља вијека", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Иш, пауне златопере! Не шетукај, не загучај, не шобоћи, не клопоћи.", source: "Успаванка, збирка Вука Караџића", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Од' отоле, јање моје! Не скакући, не блебећи, не буди ми Јова мога.", source: "Успаванка, збирка Вука Караџића", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "И ђерам шкрипи све и вода жуборећ' пада.", source: "Војислав Илић (1862—1894)", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Тиха вода бријег рони.", source: "Народна пословица, збирка Вука Караџића", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Тихо море као уље.", source: "Народна пословица, збирка Вука Караџића", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Тајац је нагла тишина која настане усред разговора. Има своју реч зато што се примећује, за разлику од обичне тишине.", source: "Српски језик", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Затишје пред буру није изостанак ветра него ваздух који олуја вуче увис уместо у страну. Тишина је део олује.", source: "Метеорологија", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Жубор, жагор, шумор, лепет и хук: за сваку врсту тихог звука постоји засебна реч, и све су настале опонашањем.", source: "Српски језик", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Снег упија звук. Свеж и растресит слој од неколико сантиметара прогута већину онога што га погоди, и због тога после снега све звучи затворено.", source: "Акустика", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Сова лети без звука зато што јој предња ивица пера има ситне зупце који разбијају вртлог. Плен је чује тек кад је касно.", source: "Орнитологија", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ко мудро мучи, лијепо говори.", source: "Народна пословица, збирка Вука Караџића", theme: .peace, subtheme: .quietAsASound),

        Passage(text: "Мир је у старом словенском значио и мир и свет и сеоску заједницу. Свет уређен и свет без свађе били су иста реч.", source: "Етимологија", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Мирбожати се значи изљубити се на Божић говорећи мир Божји. У Рисну се тога јутра у цркви помире многи који су дуго били у завади.", source: "Вук Ст. Караџић, Живот и обичаји народа српскога", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Недеља значи не-делање. Дан је именован по томе шта се тога дана не ради, а понедељак по томе да долази после њега.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Боље се наврх њиве договарати него се на увратинама карати.", source: "Народна пословица, збирка Вука Караџића", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Спокој и покој су од истог корена као и починути. Реч за тишину у човеку иста је као реч за одмор после посла.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "И мирна Босна каже се кад је расправа завршена. Читава реченица која значи само: и то је то, више се не враћамо на њу.", source: "Народни говор", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Помирити и измирити нису исто. Прво је оставити свађу, друго је поравнати рачун, и у српском се то не меша.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Предах је реч за прекид посла, а састављена је од дах. Одмор је именован по томе што се у њему стигне удахнути.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Светковати значи не радити због празника. Реч је од свет у значењу свето, а не од свет у значењу цео свет — то су две различите старе речи.", source: "Народни календар", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Доста је по пореклу до сита. Реч којом се посао зауставља каже, дословно, да је поједено таман.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Мирити, помирити, смирити, умирити и примирити: пет глагола од исте основе, и сваки зауставља другу врсту немира.", source: "Српски језик", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Гусле немају прагове. Прст не притиска жицу до врата него је само дотакне са стране, и тон због тога никад није сасвим чист.", source: "Музика", theme: .peace, subtheme: .theWordsForStopping),

        Passage(text: "Све грли мир и сан.", source: "Војислав Илић (1862—1894)", theme: .peace, subtheme: .atEase),
        Passage(text: "Тишина се блага лије по сеоцу нашем широм, вече иде да покрије све уморне благим миром.", source: "Јован Јовановић Змај (1833—1904)", theme: .peace, subtheme: .atEase),
        Passage(text: "Под нашим је кровом мирно, нико није у вас дирно.", source: "Јован Јовановић Змај (1833—1904)", theme: .peace, subtheme: .atEase),
        Passage(text: "Копрена дубоког мира увија поља и равни.", source: "Војислав Илић (1862—1894)", theme: .peace, subtheme: .atEase),
        Passage(text: "Мерак је уживање у нечему за то само, без сврхе и без журбе. Реч је дошла с истока и није имала овдашњег претходника.", source: "Српски језик", theme: .peace, subtheme: .atEase),
        Passage(text: "Пландовање је одмор стоке у подне, у хладу, кад је сунце прејако за пашу. Реч се сад једнако употребљава и за људе.", source: "Сточарство", theme: .peace, subtheme: .atEase),
        Passage(text: "Мачка преде на око двадесет пет титраја у секунди, и то ради и кад је сама. Звук није намењен ником посебно.", source: "Зоологија", theme: .peace, subtheme: .atEase),
        Passage(text: "Испод ораха слабо шта расте. Дрво из корена испушта материју која другим биљкама смета, па је земља око њега увек чиста.", source: "Ботаника", theme: .peace, subtheme: .atEase),
        Passage(text: "Кајмак се хвата с површине млека које стоји мирно. Ако се посуда за то време помери, кајмака нема.", source: "Народни обичај", theme: .peace, subtheme: .atEase),
        Passage(text: "Клонуо почива свет.", source: "Војислав Илић (1862—1894)", theme: .peace, subtheme: .atEase),
        Passage(text: "Крава лежи и прежива четири до осам сати дневно. То је прави посао њеног дана, и не може се убрзати.", source: "Сточарство", theme: .peace, subtheme: .atEase),
        Passage(text: "Одмор је од морити. Оно што одмор ради јесте да склања умор, а не да додаје снагу.", source: "Српски језик", theme: .peace, subtheme: .atEase),
    ]
}
