import Foundation

/// The Lithuanian passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let lithuanian: [Passage] = [
        // MARK: - Beginnings
        Passage(text: "Dygti lietuviškai sakoma ir apie sėklą, ir apie vaiko dantis: abu prasikala iš vidaus, ir nė vieno negalima paskubinti.", source: "Lietuvių kalba", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Daigas yra tai, kas jau prasikalė, bet dar neturi nė vieno tikro lapo. Jam sodininkai skiria atskirą lysvę, vadinamą daigynu.", source: "Sodininkystė", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Sėkla pirmiausia leidžia šaknelę žemyn ir tik paskui stiebiasi aukštyn. Pirmas augalo judesys yra į tamsą, o ne į šviesą.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pumpuras sudėliojamas dar rudenį. Perpjovus ankstyvo pavasario beržo pumpurą, viduje randami visi būsimi lapai, tik labai maži.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Lietuvos vardas pirmą kartą užrašytas 1009 metais Kvedlinburgo analuose — viena eilute, tarp kitų tų metų įvykių.", source: "Istorija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pirmoji lietuviška knyga yra Martyno Mažvydo katekizmas, išspausdintas 1547 metais Karaliaučiuje.", source: "Knygų istorija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "To katekizmo lietuviškos prakalbos eilučių pirmosios raidės sudeda autoriaus vardą. Pirmoji knyga pasirašė save akrostichu.", source: "Knygų istorija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Lazdynas pražysta anksčiau už visus kitus medžius — dar be lapų, vasarį, ir jo žirginiai kabo ant nuogų šakų.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Vieversys pakyla giedoti pirmas iš viso lauko: dar pilkame arime, kai pakraščiuose tebeguli sniego lopiniai.", source: "Alauda arvensis", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Gandrinės — kovo dvidešimt penktoji, diena, kurią laukiama pirmųjų sugrįžtančių gandrų.", source: "Kalendorinės šventės", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ledonešis: pavasarį upės ledas pajuda ir eina žemyn su srove. Tą dieną prie upės eidavo pažiūrėti visas kaimas.", source: "Papročiai", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pradžia yra iš pradėti, o pradas senojoje kalboje reiškė tai, iš ko viskas kyla.", source: "Etimologija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Vienas rugio grūdas duoda varpą, o varpoje jų būna keturios dešimtys ar daugiau. Pasėtas po vieną, grįžta sauja.", source: "Žemdirbystė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Stelmužės ąžuolą Zarasų krašte apkabinti reikia aštuonių ar devynių žmonių, susikibusių rankomis.", source: "Stelmužės ąžuolas", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Gintaras prasideda nuo vieno sakų lašo, nuvarvėjusio nuo pušies prieš keturiasdešimt milijonų metų.", source: "Geologija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Nemuną prie ištakų galima peržengti, o į marias jis įteka toks platus, kad rūke kito kranto nesimato.", source: "Geografija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Bičių šeima pradedama nuo vienos motinėlės. Iki vasaros vidurio avilyje jų būna kelios dešimtys tūkstančių.", source: "Bitininkystė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Lašas po lašo ir akmenį pratašo.", source: "Lietuvių patarlė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kuršių nerija supustyta iš smėlio grūdelių, kuriuos vėjas nešė nuo jūros. Kopos ten aukštesnės už daugelį Lietuvos kalvų.", source: "Kuršių nerija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Gilė telpa vaiko saujoje, o iš jos išaugęs medis paskui šimtmetį stovi vienas lauko viduryje.", source: "Botanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Liepžiedis mažesnis už nagą, bet vienos žydinčios liepos bitėms užtenka labiau nei viso aplinkinio lauko.", source: "Bitininkystė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Linų sėmenėlis mažesnis už smėlio grūdą, o iš vieno lauko išeina tiek drobės, kad prikraunama kraičio skrynia.", source: "Linininkystė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kregždė neša po vieną purvo kąsnelį. Lizdas prie sijos prilipdomas iš kelių tūkstančių tokių kąsnelių.", source: "Hirundo rustica", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Rugsėjį pasėtas laukas per žiemą atrodo kaip plika velėna, o rugpjūtį iš jo pjaunama visų metų duona.", source: "Žemdirbystė", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Rugsėjis vardą gavo nuo rugių sėjos. Kas pasėta rugsėjį, ta duona valgoma kitų metų rugpjūtį.", source: "Etimologija", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kaip pasiklosi, taip išsimiegosi.", source: "Lietuvių patarlė", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Skiepijant obelį, skiepas nulemia, kokie bus obuoliai, o poskiepis — koks bus medis. Abu dalykai išsprendžiami vieną rytą.", source: "Sodininkystė", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Pamatas leidžiamas žemiau įšalo linijos. Visa, kas paskui statoma, remiasi tuo, ko niekas daugiau nebematys.", source: "Statyba", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Vardadienis kaime švęstas labiau nei gimtadienis. Svarbiau buvo, kaip tave pavadino, nei kurią dieną gimei.", source: "Papročiai", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Sutartinę pradeda vienas balsas, ir jo pasirinktas aukštis lieka visai giesmei. Kiti derinasi prie to, kas nuskambėjo pirmas.", source: "Sutartinės", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Krosnis mūrijama pirmiau už sienas. Nuo jos vietos priklauso, kur bus durys, kur langas ir kur miegos seniausias namų žmogus.", source: "Statyba", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Linas sėjamas tankiai, kad augtų aukštas ir vienastiebis. Retai pasėtas jis šakojasi, ir pluošto iš jo nebebus.", source: "Linininkystė", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kūčių vakarienė pradedama nuo kalėdaičio. Kol jis nepalaužtas, prie stalo dar niekas nevalgo.", source: "Kūčios", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Naują avilį bitininkas atsuka landa į rytus. Bitės kelsis su pirma saule, ir tai nusprendžiama dar prieš joms atsirandant.", source: "Bitininkystė", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Jonas Jablonskis 1901 metais išleido gramatiką, kuri nulėmė, kaip lietuvių kalba bus rašoma toliau.", source: "Kalbotyra", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Pirmaisiais metais ąžuolo šaknis nusileidžia giliau, nei stiebas pakyla. Todėl senas medis atlaiko vėją, kurio jaunas dar nepažįsta.", source: "Miškininkystė", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: - Waiting
        Passage(text: "Sėklos ramybės būsena: sąlygos jau tinkamos, o sėkla vis tiek nedygsta, nes stabdo save iš vidaus.", source: "Botanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Kai kurias sėklas visą žiemą laiko drėgname smėlyje rūsyje. Be šalčio jos nepatikės, kad pavasaris tikras.", source: "Sodininkystė", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Šermukšnio uogos kartuoja tol, kol jų nepakanda šalna. Skynėjai laukia ne prinokimo, o pirmųjų šalnų.", source: "Sorbus aucuparia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ištraukti linai dar ne pluoštas. Jie klojami ant pievos ir paliekami savaitėms, kol rasa atleidžia stiebą nuo siūlo.", source: "Linininkystė", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Raugas stovi puodelyje ant lentynos ir atrodo, kad nieko neveikia. Iš tikrųjų jis dirba visą parą, tik labai lėtai.", source: "Duonkepystė", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Kantrybė yra iš kęsti. Kantrus žmogus lietuviškai ne laukia, o iškenčia laukimą.", source: "Etimologija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Lietuviškai nėščia moteris sako laukiasi. Laukimas čia ne tai, ką ji daro, o tai, kas ji tuo metu yra.", source: "Lietuvių kalba", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ežys žiemai susisuka po lapų krūva ir taip suretina širdies plakimą, kad palietus atrodytų šaltas.", source: "Erinaceus", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Šikšnosparniai žiemoja senų rūsių skliautuose kabodami galva žemyn ir taip praleidžia pusę metų beveik nejudėdami.", source: "Zoologija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ąžuolas gilių neduoda nė keturiasdešimt metų. Visą tą laiką jis tik auga.", source: "Miškininkystė", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Užšalusi upė iš viršaus atrodo sustojusi, bet po ledu vanduo teka visą žiemą tuo pačiu greičiu.", source: "Hidrologija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Įšalas laikosi dar ilgai po to, kai paviršius atšyla. Artojas kasa duobutę pažiūrėti, ar žemė jau paleido.", source: "Žemdirbystė", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Aukštapelkė auga maždaug milimetrą per metus. Metro storio durpė reiškia tūkstantį metų samanos.", source: "Pelkėtyra", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Čepkelių raistas Dzūkijoje pradėjo kauptis pasitraukus ledynui ir tebesikaupia iki šiol.", source: "Čepkelių raistas", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Lietuvių kalbos žodyno medžiaga rinkta nuo 1902 metų, o paskutinis, dvidešimtas, tomas išėjo 2002-aisiais.", source: "Kalbotyra", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Į tą žodyną suėjo apie penkis milijonus kortelių, kurias per šimtmetį siuntė keli tūkstančiai rinkėjų iš viso krašto.", source: "Kalbotyra", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ąžuolas gyvena ilgiau už jį pasodinusį sodą: kol medis subręsta, aplinkinės obelys jau būna pakeistos du kartus.", source: "Miškininkystė", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Liepa prie sodybos dažnai išstovi ilgiau už patį namą. Senose sodybvietėse iš toli matyti būtent ji.", source: "Miškininkystė", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Kopos Kuršių nerijoje slinko po kelis metrus per metus ir per kelis šimtmečius užpustė ištisus kaimus.", source: "Kuršių nerija", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Amžius lietuviškai reiškia ir žmogaus gyvenimą, ir šimtą metų. Tas pats žodis matuoja ir vieną, ir kitą.", source: "Lietuvių kalba", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Metai lietuviškai yra daugiskaita. Vieno meto nėra, nors kalbama apie vienerius.", source: "Lietuvių kalba", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Kryžių kalne kryžių niekas nėra suskaičiavęs iki galo. Kiekvienas skaičiavimas pasensta, kol baigiamas.", source: "Kryžių kalnas", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Durpėje oro beveik nėra, todėl ten patekęs medis nesupūva. Iškelti juodo ąžuolo rąstai gulėjo tūkstantį ir daugiau metų.", source: "Pelkėtyra", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Pušis, pasodinta nerijoje prieš pusantro šimto metų, vis dar laikoma jauna. Ta giria dar tik pradėta.", source: "Miškininkystė", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Stebėtis ir stebuklas yra vienos šaknies. Stebuklas lietuviškai yra tai, prieš ką sustoji ir žiūri.", source: "Etimologija", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Gandras pievoje stovi ilgai ir nejuda. Jis nemedžioja bėgdamas, o laukia, kol pelėnas pats pasirodys.", source: "Ciconia ciconia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Pilkasis garnys stovi vandenyje ant vienos kojos tiek ilgai, kad žuvys nustoja jį laikyti gyvu.", source: "Ardea cinerea", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Budėti reiškia neužmigti tada, kai visi kiti miega. Iš to paties žodžio ir budinti — pažadinti kitą.", source: "Lietuvių kalba", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Piemuo lauke praleisdavo visą dieną nieko neveikdamas, išskyrus vieną dalyką: žiūrėdamas, kad banda neišeitų iš ganyklos.", source: "Kaimo darbai", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Rūpintojėlis yra dažniausia lietuviška medžio skulptūra: sėdintis, ranka galvą parėmęs, nieko neveikiantis ir viską matantis.", source: "Liaudies skulptūra", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ventės Rago stotis nuo 1929 metų per rudenį sugauna ir užžieduoja dešimtis tūkstančių paukščių. Visas darbas yra žiūrėti ir žymėti.", source: "Ventės Ragas", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Prie avilio bitininkas nieko nedaro: pastovi prie landos ir iš to, kaip bitės skrenda, sužino, kas vyksta viduje.", source: "Bitininkystė", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Medžiotojo bokštelis statomas ne prie tako, o šalia jo, ir jo vienintelė paskirtis yra leisti žmogui ilgai nejudėti.", source: "Miško darbai", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Sargas ir saugoti yra vienos šaknies. Sargybą lietuviškai galima eiti ir prie vartų, ir prie ligonio.", source: "Etimologija", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Molėtų observatorijoje dirbama naktimis ir laukiama giedros. Per debesuotą mėnesį neužfiksuojama nieko.", source: "Astronomija", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Žvalgytis reiškia dairytis aplinkui be jokio konkretaus tikslo. Tam lietuvių kalba turi atskirą veiksmažodį.", source: "Lietuvių kalba", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: - Renewal
        Passage(text: "Atolas — žolė, atžėlusi po pirmosios šienapjūtės. Antrajam pjovimui lietuvių kalba turi savo žodį.", source: "Žemdirbystė", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Atžala reiškia ir jauną ūglį nuo kelmo, ir žmogaus vaiką. Tas pats žodis abiem atvejais.", source: "Lietuvių kalba", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Karklas kertamas kasmet iki pat kelmo, ir kasmet nuo jo atauga tiesios vytelės, kokių pintinei ir reikia.", source: "Amatai", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Beržo sula leidžiama pragręžus nedidelę skylutę. Ją užkimšus medis užgyja, ir kitą pavasarį iš to paties beržo semiama vėl.", source: "Kaimo darbai", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nupjauta dilgėlė atauga per porą savaičių. Pavasarinei sriubai jos skinamos kelis kartus per tą patį sezoną.", source: "Urtica dioica", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Kartą per metus šienaujama pieva būna gėlėtesnė už tą, kurios niekas neliečia. Pjovimas čia ne pabaiga, o sąlyga.", source: "Pievotyra", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Skiepyti lietuviškai sakoma ir apie obelį, ir apie žmogų. Abiem atvejais įskiepijama svetima pradžia, kuri paskui auga sava.", source: "Lietuvių kalba", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ražiena po pjūties atrodo tuščia, bet grūdų ten lieka tiek, kad paukščiai maitintųsi ištisas savaites.", source: "Žemdirbystė", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nendrė stogui pjaunama žiemą nuo ledo. Tinka tik atželianti, o šaknys lieka nepaliestos ir kitąmet duoda naują.", source: "Amatai", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nugenėtas iki kamieno gluosnis atrodo suluošintas, o po metų būna vešlesnis nei buvęs.", source: "Sodininkystė", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nukirtus medį, kelmas dar daug metų lieka gyvas. Iš jo pakraščių kylančias atžalas maitina senosios šaknys.", source: "Miškininkystė", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Karnos nuo liepos lupamos siauromis juostomis, paliekant tarpus. Taip nuluptas medis auga toliau ir po kelerių metų tinka vėl.", source: "Amatai", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Birželis pavadintas nuo beržo, liepa — nuo liepų žiedų. Lietuviški mėnesių vardai yra ne skaičiai ir ne dievai, o tai, kas darosi lauke.", source: "Etimologija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Spalis vardą gavo nuo spalių — linų stiebo trupinių, kurie lieka linus mynant. Mėnuo pavadintas darbo atliekomis.", source: "Etimologija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Gruodas yra sušalusi grumstuota žemė. Mėnuo pavadintas tuo, kaip tuo metu atrodo laukas po koja.", source: "Etimologija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Lapkritis pasakytas dviem žodžiais ir jokio paaiškinimo nereikalauja.", source: "Lietuvių kalba", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Rugpjūtis ir rugsėjis stovi vienas šalia kito: pirmą rugiai pjaunami, antrą sėjami. Metai apsisuka per keturias savaites.", source: "Žemdirbystė", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Per Užgavėnes Lašininis grumiasi su Kanapiniu, ir Kanapinis visada nugali. Be to žiema iš kiemo neišeitų.", source: "Užgavėnės", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Tą pačią dieną sudeginama Morė — šiaudinė lėlė vežime. Vienintelis laužas metuose, kūrenamas tam, kad kas nors pasibaigtų.", source: "Užgavėnės", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Rasos, arba Joninės, švenčiamos trumpiausią naktį. Vainikai leidžiami upe, o ugnis laikoma neužgesusi iki aušros.", source: "Joninės", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Gegutė kukuoja iki Joninių ir paskui nutyla. Kaimuose pagal tai žinodavo, kad vasara persivertė.", source: "Cuculus canorus", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Pavasaris lietuviškai yra pa-vasaris: metų laikas, pavadintas ne savo vardu, o tuo, kas ateis po jo.", source: "Etimologija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ruduo ir rudas yra vienos šaknies. Metų laikas pavadintas spalva.", source: "Etimologija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Donelaičio poema suskirstyta į keturias dalis — po vieną kiekvienam metų laikui — ir prasideda pavasariu, ne sausiu.", source: "Kristijonas Donelaitis, Metai, 1818", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Sveikas lietuviškai reiškia ir nesergantį, ir nesudužusį. Sveikas indas ir sveikas žmogus sakomi tuo pačiu žodžiu.", source: "Lietuvių kalba", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Gyti, gyvas ir gydyti yra vienos šaknies. Pasveikti lietuviškai reiškia grįžti į gyva.", source: "Etimologija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Medis žaizdos neužtaiso — jis ją apaugina. Sužalota vieta lieka viduje, o naujas medis auga aplink.", source: "Dendrologija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Atsigauti pažodžiui reiškia atgauti save. Lietuviškai sveikstama ne į priekį, o atgal.", source: "Lietuvių kalba", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Per Žolinę nešamos surištos lauko žolynų puokštės. Paskui jos džiovinamos ir laikomos namie ligos atvejui.", source: "Žolinė", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Vaistažolė sudėta iš vaisto ir žolės. Vaistų kilmė čia pasakyta tiesiai pačiame žodyje.", source: "Lietuvių kalba", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Pavasarinė sula gerta kaip stiprinamasis ir laikyta geriausiu vaistu po ilgos žiemos be nieko šviežio.", source: "Kaimo papročiai", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Pirtis pavadinta nuo perti — nuo vantos, o ne nuo karščio. Svarbiausias veiksmas ten yra beržo lapų prisilietimas.", source: "Etimologija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Sulūžęs kaulas suauga stipresnis toje vietoje, kur lūžo. Kitą kartą jis lūžta greta, o ne ten pat.", source: "Anatomija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Atgaiva yra iš gaivinti. Atsigaivinti lietuviškai galima ir vandeniu, ir pavėsiu, ir žinia.", source: "Lietuvių kalba", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Į kirtavietę pirmi ateina beržai. Po dvidešimties metų iš plikos vietos vėl būna miškas.", source: "Miškininkystė", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Žaibo perskeltas ąžuolas dažnai lieka gyvas: perskilęs kamienas apauga iš vidaus, ir medis stovi toliau.", source: "Dendrologija", theme: .renewal, subtheme: .madeWhole),

        // MARK: - Light
        Passage(text: "Rytai ir vakarai lietuviškai yra tie patys žodžiai kaip rytas ir vakaras. Pasaulio kryptys pavadintos paros dalimis.", source: "Lietuvių kalba", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pietūs reiškia ir pasaulio kryptį, ir vidurdienio valgį. Kryptis pavadinta pagal tai, kur tuo metu stovi saulė.", source: "Lietuvių kalba", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pusryčiai yra pusė ryto, o vakarienė — vakaras. Abu valgiai pavadinti paros dalimi, o ne tuo, kas dedama į lėkštę.", source: "Etimologija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Aušrinė yra rytinė žvaigždė, matoma prieš saulę. Senojoje pasaulėžiūroje ji turėjo vardą kaip žmogus.", source: "Mitologija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pirmasis lietuviškas laikraštis 1883 metais pavadintas Aušra, nes ėjo tada, kai spauda lotyniškomis raidėmis buvo uždrausta.", source: "Spaudos istorija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Aušros vartai Vilniuje yra vienintelė išlikusi miesto sienos anga, pavadinta ta puse, iš kurios ateina rytas.", source: "Vilnius", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Per Jonines Vilniuje saulė nusileidžia apie dešimtą vakaro, o šiaurinis dangaus kraštas taip ir nepajuoduoja iki ryto.", source: "Astronomija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gruodžio pabaigoje Vilniuje šviesu maždaug septynias valandas. Likusi paros dalis praeina prie lempos.", source: "Astronomija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Brėkšmė ir sutemos nėra tas pats: pirmoji eina šviesyn, antroji tamsyn, o atrodo panašiai.", source: "Lietuvių kalba", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Parnidžio kopos saulės laikrodis Nidoje pastatytas ant smėlio ir rodo ne tik valandą, bet ir metų laiką.", source: "Nida", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Jau saulelė vėl atkopdama budino svietą.", source: "Kristijonas Donelaitis, Metai, 1818", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Vakarinė ir Aušrinė yra ta pati planeta, matoma dviem paros galais. Senoji kalba davė jai du vardus ir neapsiriko: matė du dalykus.", source: "Astronomija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Saulėgrąža pavadinta saulės grąža: jauna ji sukasi paskui saulę, o pražydusi sustoja atsisukusi į rytus.", source: "Helianthus annuus", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Beržo sula pradeda tekėti ne nuo šilumos, o nuo skirtumo: reikia, kad diena būtų šilta, o naktis dar šalta.", source: "Medžių fiziologija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gausi rasa iškrenta tik giedrą naktį. Todėl sunki rasa rytą kaime buvo laikoma giedros dienos ženklu.", source: "Orų spėjimas", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Bitės neišskrenda, kol oras neįšyla maždaug iki dešimties laipsnių. Bitininkas dieną įvertina pažiūrėjęs į landą.", source: "Bitininkystė", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Miško gėlės pražysta, kol medžiai dar be lapų. Žibuoklė ir plukė spėja pasinaudoti šviesa, kuri vėliau iki žemės nebenusileis.", source: "Botanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Vidurdienio šešėlis Lietuvoje žiemą kelis kartus ilgesnis nei vasarą. Be jokio prietaiso pagal jį matyti metų laikas.", source: "Astronomija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gandrai išskrenda dar šiltą rugpjūtį. Juos išveja trumpėjanti diena, o ne šaltis.", source: "Ciconia ciconia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Rugiai sėjami rudenį taip, kad iki šalčių spėtų sukrauti lapus. Per anksti pasėti peraugs, per vėlai — nespės.", source: "Žemdirbystė", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ant nerijos saulė teka virš marių ir leidžiasi į jūrą. Iš vieno taško per dieną matomi abu vandenys.", source: "Kuršių nerija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Dienos šviesoje gintaras atrodo medaus spalvos, o pakeltas prieš saulę praleidžia ją kiaurai ir parodo, kas jame įstrigo.", source: "Gintaras", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Voratinkliai rugsėjo rytą matomi tik tol, kol ant jų laikosi rasa. Nudžiūvę jie dingsta iš akių, nors niekur nedingsta.", source: "Stebėjimas", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Kai kurios pievos gėlės užsiveria prieš lietų, o kitos užsimerkia vakarop, dar prieš saulei nusileidžiant.", source: "Botanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Dievas ir diena kilę iš to paties seno žodžio, reiškusio šviesų dangų. Tas pats kamienas yra sanskrito devas ir lotynų deus.", source: "Etimologija", theme: .light, subtheme: .lightItself),
        Passage(text: "Saulė lietuvių kalboje moteriškos giminės, o Mėnulis vyriškos. Liaudies dainose jie susituokia ir susipyksta.", source: "Tautosaka", theme: .light, subtheme: .lightItself),
        Passage(text: "Ugnis lietuviškai ir agnis sanskrito kalboje yra tas pats žodis. Tarp jų tik trys tūkstančiai metų.", source: "Etimologija", theme: .light, subtheme: .lightItself),
        Passage(text: "Iki krikšto Vilniuje kūrenta nuolatinė šventoji ugnis. Kronikininkai rašė, kad ją prižiūrėjo tam paskirti žmonės ir kad ji negesdavo.", source: "Istorija", theme: .light, subtheme: .lightItself),
        Passage(text: "Žiburys, žibintas ir žibuoklė yra vienos šaknies. Žibėti lietuviškai gali ir lempa, ir miško gėlė.", source: "Etimologija", theme: .light, subtheme: .lightItself),
        Passage(text: "Jonvabalis pavadintas Joninių vardu, nes šviečia tuo metu, kai naktys trumpiausios ir jo šviesai lieka mažiausiai laiko.", source: "Lampyris noctiluca", theme: .light, subtheme: .lightItself),
        Passage(text: "Spindulys yra iš spindėti. Šviesos ruožas lietuviškai pavadintas veiksmažodžiu, o ne daiktu.", source: "Lietuvių kalba", theme: .light, subtheme: .lightItself),
        Passage(text: "Šviesus sakoma ir apie dieną, ir apie plaukus, ir apie žmogaus protą. Šviesuolis lietuviškai yra mokytas žmogus.", source: "Lietuvių kalba", theme: .light, subtheme: .lightItself),
        Passage(text: "Šiaurės pašvaistė Lietuvoje matoma retai, gal kartą per keletą metų, ir tada apie ją kalba visas kraštas.", source: "Astronomija", theme: .light, subtheme: .lightItself),
        Passage(text: "Pilnatis ant sniego duoda tiek šviesos, kad lauke galima įžiūrėti laikrodį. Be sniego tos pačios pilnaties neužtenka.", source: "Optika", theme: .light, subtheme: .lightItself),
        Passage(text: "Sniegas atspindi beveik visą krintančią šviesą, todėl žiemą pro langą į kambarį jos patenka daugiau iš apačios nei iš dangaus.", source: "Optika", theme: .light, subtheme: .lightItself),
        Passage(text: "Blėsti reiškia gesti pamažu. Lietuvių kalba tam turi atskirą veiksmažodį, kitokį nei užgesti iš karto.", source: "Lietuvių kalba", theme: .light, subtheme: .lightItself),

        // MARK: - Pattern
        Passage(text: "Sutartinės skirstomos į dvejines, trejines ir keturines pagal tai, kiek žmonių jas gali sudainuoti. Pavadinimas yra skaičius.", source: "Sutartinės", theme: .pattern, subtheme: .counted),
        Passage(text: "Devynis kartus atmatuok, dešimtą kirpk.", source: "Lietuvių patarlė", theme: .pattern, subtheme: .counted),
        Passage(text: "Devyni lietuvių pasakose ir užkalbėjimuose yra dažniausias skaičius. Devynios galybės iki šiol reiškia tiesiog labai daug.", source: "Tautosaka", theme: .pattern, subtheme: .counted),
        Passage(text: "Ant Kūčių stalo dedama dvylika patiekalų — po vieną kiekvienam metų mėnesiui.", source: "Kūčios", theme: .pattern, subtheme: .counted),
        Passage(text: "Lietuviški skaitvardžiai nuo dviejų iki dešimties beveik sutampa su sanskrito, nors abu kraštai niekada nesusisiekė.", source: "Kalbotyra", theme: .pattern, subtheme: .counted),
        Passage(text: "Lietuvių kalba turi septynis linksnius. Septintasis, šauksmininkas, vartojamas tik kreipiantis į kitą.", source: "Gramatika", theme: .pattern, subtheme: .counted),
        Passage(text: "Rugių pėdai lauke statomi į gubas, ir gubos dydis kiekvienoje apylinkėje būdavo nusistovėjęs skaičius.", source: "Žemdirbystė", theme: .pattern, subtheme: .counted),
        Passage(text: "Savaitės dienos suskaičiuotos: pirmadienis, antradienis ir taip iki šeštadienio. Septintoji vadinasi sekmadienis, nuo seno žodžio sekmas.", source: "Etimologija", theme: .pattern, subtheme: .counted),
        Passage(text: "Bitė per vieną skrydį aplanko kelias dešimtis žiedų, o šaukštui medaus reikia kelių tūkstančių tokių skrydžių.", source: "Bitininkystė", theme: .pattern, subtheme: .counted),
        Passage(text: "Eglės kankorėžio žvyneliai išsidėstę dviem priešingomis spiralėmis, ir jų kiekis abiem kryptimis beveik visada skirtingas.", source: "Botanika", theme: .pattern, subtheme: .counted),
        Passage(text: "Lietuvos ežerų skaičius skirtinguose šaltiniuose skiriasi tūkstančiais, nes viskas priklauso nuo to, nuo kokio dydžio bala jau vadinama ežeru.", source: "Geografija", theme: .pattern, subtheme: .counted),
        Passage(text: "Gandro lizde paprastai užauga trys ar keturi jaunikliai. Penki būna retai, ir tokį lizdą kaime žinodavo visi.", source: "Ciconia ciconia", theme: .pattern, subtheme: .counted),
        Passage(text: "Sutartinę dainuoja du ar trys balsai, kiekvienas su savo žodžiais. Jie sutampa ne unisonu, o per sekundę, ir tas trynimasis yra visa esmė.", source: "Sutartinės", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Šiaudinis sodas rišamas iš rugio šiaudelių, suvertų į briaunainius. Jis kabinamas virš stalo ir lėtai sukasi nuo kambario oro.", source: "Liaudies menas", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Rišant tokį sodą niekas neklijuojama. Visa konstrukcija laikosi vien tuo, kad ilgiai atmatuoti teisingai.", source: "Liaudies menas", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Vilniaus verba suvyniojama iš džiovintų žolių, suveržtų sluoksniais aplink lazdelę. Kiekvienas sluoksnis prilaiko ankstesnįjį.", source: "Vilniaus verbos", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Rąstinis namas kertėse sunerimas be nė vienos vinies. Rąstai laiko vienas kitą savo svoriu.", source: "Statyba", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Margučiai skutinėjami adata. Rašto nebeištaisysi, todėl visa linija turi būti sugalvota prieš pradedant.", source: "Velykų papročiai", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Juostos raštas audžiamas skaičiuojant siūlus. Suklydus vienu siūlu, raštas nuslenka, ir tai matyti per visą juostos ilgį.", source: "Audimas", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Korys sudėtas iš šešiakampių, nes šešiakampiai priglunda vienas prie kito be tarpų ir sunaudoja mažiausiai vaško.", source: "Bitininkystė", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Kryždirbystės saulutės kalamos iš geležies strypelių, sulenktų spinduliais aplink vieną tašką. Jų kiekį kalvis pasirenka pats.", source: "Kryždirbystė", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Klumpė skobiama pagal vieną koją. Kairė ir dešinė nesikeičia vietomis, todėl ir dėvisi nevienodai.", source: "Amatai", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Šiaudinis stogas dengiamas nuo apačios į viršų, ir kiekvienas kūlelis pridengia ankstesniojo pririšimą. Kraigas užspaudžia viską iš karto.", source: "Statyba", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Pintinė pinama be jokio rišiklio. Kiekvieną vytelę prilaiko dvi kaimyninės, o paskutinė užkišama po pirmąja.", source: "Amatai", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Nosinės raidės ą, ę, į, ų žymi garsą, kurio lietuvių kalba nebetaria jau šimtmečius. Raidė prisimena tai, ko lūpos jau nebedaro.", source: "Kalbotyra", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Linksnių pavadinimai lietuviškai nėra skoliniai: kilmininkas klausia iš kur, naudininkas — kam, įnagininkas — kuo. Terminas pats save paaiškina.", source: "Gramatika", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Jonas Jablonskis savaitės dienoms davė vardus pagal skaičius. Iki tol sakyta panedėlis, utarnykas ir sereda.", source: "Kalbotyra", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Didysis žodynas aprašo apie pusę milijono žodžių, tarp jų ir tokių, kurių šiandien nebevartoja niekas.", source: "Kalbotyra", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Upių vardai yra seniausias žemėlapio sluoksnis. Baltiškų upėvardžių randama toli į rytus nuo dabartinės Lietuvos.", source: "Vardyno tyrimai", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kazimieras Būga iš upių vardų atstatė, kur kadaise gyventa baltų. Vardai išliko ilgiau nei kalba, kuria jie duoti.", source: "Kalbotyra", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Tas pats lietuviškas žodis gali reikšti du dalykus pagal tai, kaip ištęsiamas kirčiuotas skiemuo. Raštas to skirtumo dažnai nerodo.", source: "Kalbotyra", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kiekviena kalendoriaus diena Lietuvoje turi vardus. Vardadienis randamas nežiūrint į niekieno gimimo datą.", source: "Papročiai", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Graikai gintarą vadino elektron. Iš to paties žodžio vėliau pavadinta elektra, nes patrintas gintaras traukia plauką.", source: "Etimologija", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Augalai turi ir liaudinius, ir mokslinius vardus, ir jie nesutampa. Viena gėlė kaimuose gali turėti penkis skirtingus vardus.", source: "Botanika", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Daiktavardis lietuviškai turi giminę, ir tai tas pats žodis kaip giminystė tarp žmonių.", source: "Gramatika", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kirtis lietuvių kalboje šokinėja per žodžio formas, todėl žodynuose prie kiekvieno žodžio dar rašomas kirčiuotės numeris.", source: "Gramatika", theme: .pattern, subtheme: .orderNamed),

        // MARK: - Ground
        Passage(text: "Žmogus ir žemė yra vienos šaknies. Lietuviškai žmogus pavadintas tuo, ant ko stovi.", source: "Etimologija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Dirvožemis sudėtas iš dirvos ir žemės. Pats žodis sako, kad tai ne bet kokia žemė, o ta, kuri dirbama.", source: "Lietuvių kalba", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Akmenys Lietuvos laukuose atkeliavo su ledynu iš Skandinavijos. Kiekvienas riedulys čia yra svečias iš kito krašto.", source: "Geologija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Puntukas Anykščiuose guli miške nuo ledynmečio ir sveria daugiau nei du šimtus tonų. Jo niekas niekada nepajudino.", source: "Puntukas", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Žemaitija reiškia žemą kraštą, Aukštaitija — aukštą. Abi sritys pavadintos ne žmonėmis, o tuo, kaip ten guli žemė.", source: "Vardyno tyrimai", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Dzūkijos smėlyje rugiai auga prastai, o grybai geriau nei bet kur kitur. Kraštas maitinosi tuo, ką davė smėlis.", source: "Dzūkija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Pelkė, raistas, liūnas, bala ir tyrai reiškia penkis skirtingus šlapios žemės pavidalus.", source: "Lietuvių kalba", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Durpė medį išlaiko todėl, kad ten nepatenka oras. Iš pelkės iškelta mediena būna juoda ir sunkesnė už vandenį.", source: "Pelkėtyra", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Velėna yra viršutinis žemės sluoksnis su gyvomis šaknimis. Ją nuplėšus, po apačia lieka jau nebe dirva.", source: "Dirvožemio mokslas", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Merkinės molis degamas be deguonies, todėl puodai išeina juodi. Ta pati žemė kitur duotų raudonus.", source: "Puodininkystė", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Sliekai per metus išvelka į paviršių keliolika tonų žemės iš hektaro. Laukas pamažu apsiverčia be jokio plūgo.", source: "Dirvožemio mokslas", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Arti lietuviškai ir arare lotyniškai yra tas pats žodis. Abi kalbos jį paveldėjo, o ne pasiskolino.", source: "Etimologija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Gimtinė yra iš gimti, o tėvynė iš tėvo. Lietuvių kalba skiria vietą, kurioje gimei, nuo krašto, kuriam priklausai.", source: "Etimologija", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Tėviškė reiškia ne kraštą, o vieną konkrečią sodybą. Į tėviškę važiuojama, o ne prisimenama.", source: "Lietuvių kalba", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Gimtoji kalba pasakyta per gimimą, o ne per motiną: kalba, su kuria gimei.", source: "Lietuvių kalba", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kiekvienas paukštis savo lizdą giria.", source: "Lietuvių patarlė", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Namie ir sienos padeda.", source: "Lietuvių patarlė", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Prie kiekvienos senos sodybos po langu būdavo darželis su rūtomis. Dainose rūta reiškia namus taip pat aiškiai kaip stogas.", source: "Tautosaka", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Šulinys su svirtimi matėsi iš toli ir rodė, kad ten sodyba. Svirtis dažnai stovėjo ilgiau už patį namą.", source: "Kaimo statyba", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Vilnius pavadintas nuo Vilnios upės, o Vilnia — nuo vilnies. Miesto vardas reiškia bangavimą.", source: "Vardyno tyrimai", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Sodyba nėra vienas pastatas. Troba, klėtis, tvartas ir svirnas statomi keturkampiu, o vidurys lieka kiemas.", source: "Kaimo statyba", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Klėtyje laikytas grūdas ir kraičio skrynia. Vasarą ten miegodavo jaunimas, nes tai buvo vėsiausias pastatas kieme.", source: "Kaimo statyba", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Europos geografinis vidurys 1989 metais apskaičiuotas prie Purnuškių, netoli Vilniaus. Ten pastatytas paprastas akmuo.", source: "Geografija", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Po 1557 metų valakų reformos kaimai buvo pertvarkyti į vieną gatvę, o laukai į ilgas juostas. Daugelis kaimų tebeatrodo taip.", source: "Istorija", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Darželis po langu buvo mergaitės atsakomybė: rūtos, bijūnai ir našlaitės, aptverti tvorele nuo vištų.", source: "Kaimo papročiai", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Rūsyje obuoliai dedami ant šiaudų po vieną, kad nesiliestų. Kartą per savaitę juos peržiūri ir sugedusį išima.", source: "Sodininkystė", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Drevinė bitininkystė: bitės laikomos pušies drevėje, o medį ženklina savininko rėžis. Statutas už drevės gadinimą numatė bausmę.", source: "Bitininkystės istorija", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Klėtis statoma ant akmenų, kad grūdai nesiliestų su drėgna žeme. Nuo to priklauso, ar sėkla išliks iki pavasario.", source: "Kaimo statyba", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Nerijos pušynas pasodintas ranka devynioliktame amžiuje, kad sustabdytų smėlį. Jis prižiūrimas iki šiol.", source: "Kuršių nerija", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kauno ąžuolynas yra vienas didžiausių miesto ąžuolynų Europoje. Jis stovi ne todėl, kad išliko, o todėl, kad buvo saugotas.", source: "Kaunas", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Prieš Vėlines kapinės sutvarkomos visos iš eilės, ir tą vakarą visoje šalyje dega žvakės.", source: "Vėlinės", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kraitis pradedamas krauti gerokai anksčiau, nei prireikia. Drobė audžiama po truputį kasmet ir dedama į skrynią.", source: "Papročiai", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Šiaudinį stogą kas keletą metų reikia perkraigti, o visą pakeisti — kartą per kelias dešimtis metų. Iki tol jį nuolat lopo.", source: "Kaimo statyba", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Senos obelys genimos kas žiemą, kad viduje liktų vietos. Neišgenėta obelis duoda daugiau vaisių, bet smulkesnių.", source: "Sodininkystė", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Piliakalniai šienaujami, kad neužaugtų medžiais. Be to kasmetinio pjovimo jų formos po dešimtmečio nebesimatytų.", source: "Paveldosauga", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Žuvinto pelkė saugoma nuo 1937 metų ir yra vienas seniausių rezervatų šiame krašte.", source: "Žuvintas", theme: .ground, subtheme: .aKeptPlace),

        // MARK: - Travel
        Passage(text: "Pienė pavadinta nuo pieno — dėl balto syvo stiebe. Jos sėklos su pūkeliais nuskrenda toliau nei bet kurios lauko gėlės.", source: "Taraxacum", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Klevo sėkla turi du sparnelius ir krisdama sukasi. Sukimasis ją nuneša nuo motininio medžio kelias dešimtis metrų.", source: "Acer platanoides", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Beržas per metus išbarsto milijonus sėklų, kiekviena lengvesnė už dulkę. Todėl beržas pirmas ateina į bet kokią plikę.", source: "Betula", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Alksnio sėklos plūduriuoja ir plaukia pasroviui. Todėl alksnynai beveik visada driekiasi palei upę.", source: "Alnus glutinosa", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rugiagėlė atkeliavo kartu su rugiais, kaip piktžolė sėkloje. Kur nustoja augti rugiai, ten baigiasi ir ji.", source: "Centaurea cyanus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Šermukšnio uogas žiemą lesa svirbeliai ir nuneša sėklas dešimtis kilometrų. Pati uoga jiems rūpi gal valandą.", source: "Bombycilla garrulus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Amalo sėkla lipni. Paukštis, nusivalęs snapą į šaką, ją ten ir pasodina.", source: "Viscum album", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Varputis apskritai neskuba sėti. Jis plinta šaknimis po žeme ir per vasarą nueina kelis metrus be jokios sėklos.", source: "Elymus repens", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kadagio uogas lesa strazdai, todėl kadagiai auga ten, kur jie pailsėjo — dažnai eilėmis palei tvoras.", source: "Juniperus communis", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kai kurių pievos gėlių sėklinė dėžutė sausėdama susitraukia ir išsviedžia sėklas per porą metrų nuo savęs.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Vandens lelijos sėklos plūduriuoja kelias dienas ir tik paskui nugrimzta. Per tas dienas jos nueina visą ežerą.", source: "Nymphaea", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Lipikas kimba į karvės šoną ir keliauja tiek, kiek ta karvė tą dieną nueina. Laukas taip pasėjamas be jokio vėjo.", source: "Galium aparine", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Viešas, viešėti, vaišės ir viešpats yra vienos šaknies, reiškusios gyvenvietę. Vieškelis tada — kelias, priklausantis visiems.", source: "Etimologija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Koplytstulpiai statyti kryžkelėse. Keliaujantis žinodavo, kur pasukti, ne iš ženklo, o iš to, kieno stulpas ten stovi.", source: "Kryždirbystė", theme: .travel, subtheme: .theRoad),
        Passage(text: "Nemunu iki Klaipėdos plukdyti sieliai — surišti rąstų plaustai. Sielininkai grįždavo namo pėsti, kartais kelias savaites.", source: "Sielininkystė", theme: .travel, subtheme: .theRoad),
        Passage(text: "Gintaro kelias vedė nuo Baltijos iki Adrijos. Vietos kapuose randama romėniškų monetų, atkeliavusių tuo pačiu keliu atgal.", source: "Archeologija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Knygnešiai per Prūsijos sieną nešė lietuviškas knygas keturiasdešimt metų, kol spauda lotyniškomis raidėmis buvo uždrausta.", source: "Spaudos istorija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Pakeleivis yra tas, kurį sutinki kelyje ir su kuriuo dalį kelio eini kartu. Tam lietuvių kalba turi vieną žodį.", source: "Lietuvių kalba", theme: .travel, subtheme: .theRoad),
        Passage(text: "Vilniaus Kalvarijos yra vaikščiojamas kelias tarp kalvų. Jį pereiti užtrunka kelias valandas, o sustojimai sužymėti iš anksto.", source: "Vilnius", theme: .travel, subtheme: .theRoad),
        Passage(text: "Gintaro gabalėliai išmetami į krantą po šiaurės vakarų audros. Jų ieškoti einama kitą rytą anksti, kol dar niekas nepraėjo.", source: "Palanga", theme: .travel, subtheme: .theRoad),
        Passage(text: "Pirmasis geležinkelis šiame krašte nutiestas 1861 metais, o Paneriuose jam prakastas tunelis, veikiantis iki šiol.", source: "Istorija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kelias ir kelti yra vienos šaknies. Išeiti į kelią ir pakilti lietuviškai sakoma beveik tais pačiais žodžiais.", source: "Etimologija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Prie senų kelių medžiai sodinti abipus tam, kad žiemą matytųsi, kur kelias, kai jį užpusto.", source: "Kelių istorija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Iki gerų kelių atstumas kaime matuotas ne kilometrais, o laiku: iki miestelio buvo pusdienis, iki kaimyno — parūkymas.", source: "Kaimo papročiai", theme: .travel, subtheme: .theRoad),
        Passage(text: "Gandras žiemoja Afrikoje ir pavasarį grįžta į tą patį lizdą. Kelias į vieną pusę trunka apie mėnesį.", source: "Ciconia ciconia", theme: .travel, subtheme: .farOff),
        Passage(text: "Ventės Rage užžieduoti paukščiai vėliau surandami Afrikoje ir Artimuosiuose Rytuose. Apie tai sužinoma iš laiško, atėjusio po metų.", source: "Ventės Ragas", theme: .travel, subtheme: .farOff),
        Passage(text: "Baltijos gintaro randama Mikėnų kapuose Graikijoje. Jis ten atkeliavo maždaug prieš tris su puse tūkstančio metų.", source: "Archeologija", theme: .travel, subtheme: .farOff),
        Passage(text: "Lietuvių kalba išlaikė formų, kurios kitur išnyko. Kai kuriuos jos žodžius paprasčiau palyginti su sanskritu nei su kaimynų kalbomis.", source: "Kalbotyra", theme: .travel, subtheme: .farOff),
        Passage(text: "Kas nori išgirsti, kaip kalbėjo indoeuropiečiai, tenuvažiuoja pasiklausyti lietuvio valstiečio.", source: "Antoine Meillet (1866–1936), pasakyta paprastai", theme: .travel, subtheme: .farOff),
        Passage(text: "Užjūris lietuviškai yra viena vieta. Viskas, kas anapus jūros, telpa į vieną žodį.", source: "Lietuvių kalba", theme: .travel, subtheme: .farOff),
        Passage(text: "Toli, tolis ir tolimas yra iš to paties. Tolis reiškia ne atstumą, o tai, kas matyti pačiame krašte.", source: "Lietuvių kalba", theme: .travel, subtheme: .farOff),
        Passage(text: "Gervės rudenį pakyla vakare ir skrenda naktį. Jų balsas girdimas dar ilgai po to, kai jų nebematyti.", source: "Grus grus", theme: .travel, subtheme: .farOff),
        Passage(text: "Marios reiškia ne jūrą, o užpelkėjusią lagūną už nerijos. Kuršių marios saldžios, nors už kelių šimtų metrų jau sūru.", source: "Kuršių marios", theme: .travel, subtheme: .farOff),
        Passage(text: "Žuvininkas erelis čia peri, o žiemą praleidžia Afrikoje. Pirmus dvejus metus jaunas paukštis ten ir lieka, negrįždamas.", source: "Pandion haliaetus", theme: .travel, subtheme: .farOff),
        Passage(text: "Laiškai iš Amerikos kaime būdavo skaitomi garsiai visiems susirinkusiems. Vienas laiškas atstodavo visų naujienas.", source: "Kaimo papročiai", theme: .travel, subtheme: .farOff),
        Passage(text: "Nuo Parnidžio kopos jūros horizontas nutolęs apie dvidešimt kilometrų. Toliau nieko nematyti ne dėl rūko, o dėl žemės išlinkimo.", source: "Nida", theme: .travel, subtheme: .farOff),

        // MARK: - Meeting
        Passage(text: "Sutikti lietuviškai reiškia ir susidurti su žmogumi, ir sutarti su juo. Tas pats žodis abiem atvejams.", source: "Lietuvių kalba", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Pasitikti yra išeiti ir laukti ateinančio, o sutikti — užeiti jį netyčia. Lietuvių kalba tuos du dalykus skiria.", source: "Lietuvių kalba", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Susitikti turi sangrąžinę dalelytę. Vienam susitikti neįmanoma, žodis pats reikalauja dviejų.", source: "Gramatika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Santaka yra vieta, kur dvi upės susilieja. Kaune Neris įteka į Nemuną, ir nuo tos vietos abi vadinamos vienu vardu.", source: "Geografija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Akimirka pažodžiui yra akies mirktelėjimas. Trumpiausią laiko vienetą lietuvių kalba matuoja akimi.", source: "Etimologija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Bitė ir žiedas susitinka kelioms sekundėms. Per tą laiką abu gauna tai, dėl ko atėjo.", source: "Bitininkystė", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Pirmas gegutės kukavimas girdimas vieną kartą ir nebūna pakartojamas. Arba tą akimirką klausei, arba ne.", source: "Cuculus canorus", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Sutartinėje du balsai susitinka per sekundę, ir tada girdisi mušimas — garsas, kurio nė vienas balsas atskirai neturi.", source: "Sutartinės", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Tekantis mėnulis ir besileidžianti saulė danguje sutampa kelioms minutėms. Viena kyla, kita leidžiasi, ir abi matyti vienu metu.", source: "Astronomija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Netikėtai yra iš tikėtis. Tai, ko nesitikėjai, lietuviškai pavadinta per lūkestį, o ne per staigumą.", source: "Etimologija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Per ledonešį du ledo laukai susiduria ir sustoja. Upė tada kelias valandas stovi, kol pralaužia pati save.", source: "Hidrologija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Rankos paspaudimas turguje buvo ne pasisveikinimas, o sandoris. Paspaudus rankas, atsisakyti jau nebebuvo galima.", source: "Papročiai", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Raudonojo dobilo žiedas per gilus bitei. Jį apdulkina kamanė, kurios liežuvis ilgesnis, ir be kamanių dobilas sėklų neduotų.", source: "Trifolium pratense", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Baravykas auga tik prie tam tikrų medžių. Jo grybiena suaugusi su šaknimis, ir nė vienas be kito ten taip gerai neaugtų.", source: "Boletus edulis", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Kerpė yra du organizmai viename: dumblis gamina maistą, grybas laiko formą ir drėgmę. Atskirti tokioje vietoje jie neišgyventų.", source: "Biologija", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Alksnio šaknyse gyvena bakterijos, imančios azotą iš oro. Todėl po alksniu geriau auga ir tai, kas pačiam alksniui nerūpi.", source: "Alnus glutinosa", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Raugas yra mielių ir bakterijų draugija. Nei vienos, nei kitos atskirai duonos nepakels ir neparūgštins.", source: "Duonkepystė", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Sutartinės vienam sudainuoti negalima — ne todėl, kad būtų sunku, o todėl, kad viena partija yra tik pusė.", source: "Sutartinės", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Gandrui reikia pievos su pelėnais, o pievai reikia, kad ją šienautų. Kai kaimas nustoja šienauti, gandras išsikelia.", source: "Ciconia ciconia", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Kadagys turi vyriškus ir moteriškus krūmus atskirai. Uogos būna tik ant vienų, o be kitų jų nebūtų visai.", source: "Juniperus communis", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Grikių laukas be bičių duoda mažai grūdų, o bitės iš grikių gauna tamsų medų. Todėl avilius vasarą vežasi į laukus.", source: "Bitininkystė", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Jaučiai kinkomi po du į vieną jungą. Jei vienas eina greičiau, vaga išeina kreiva, todėl porą rinkdavo iš anksto.", source: "Kaimo darbai", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Dvirankiu pjūklu pjaunama tik traukiant. Stumti negali nė vienas, todėl abu turi paleisti tuo pačiu momentu.", source: "Miško darbai", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Prie namų sodinamos bent dvi skirtingų veislių obelys. Viena pati savęs neapdulkina, ir vaisių iš jos nebus.", source: "Sodininkystė", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Svečias į namus — Dievas į namus.", source: "Lietuvių patarlė", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Pasisveikinimas sveiki nėra linkėjimas geros dienos. Tai linkėjimas būti sveikam, pasakomas kiekvieną kartą iš naujo.", source: "Lietuvių kalba", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Labas ir labai yra vienos šaknies. Senasis labas reiškė geras, todėl pasisveikinimas pažodžiui yra vienas žodis: gerai.", source: "Etimologija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Dirbančiam lauke praeivis šaukdavo Padėk Dieve. Tai buvo ne malda, o būdas nepraeiti tylomis.", source: "Kaimo papročiai", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Svečias, svetimas ir svetainė yra vienos šaknies. Kambarys svečiams ir žodis nepažįstamam kilę iš to paties.", source: "Etimologija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Atėjusiam ant stalo dedama duona ir druska. Net jei nieko daugiau nebūdavo, tie du dalykai turėjo būti.", source: "Papročiai", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Išeinantį palydėdavo bent iki vartų, o artimą — iki kaimo galo. Palydėti reiškė nueiti su juo dalį jo kelio.", source: "Papročiai", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Talka: kaimynai suvažiuoja padėti pjauti ar statyti, pinigų neima, o vakare visi sėda prie stalo. Skola grąžinama kita talka.", source: "Kaimo papročiai", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Per Kūčias kalėdaitis laužomas su kiekvienu prie stalo atskirai, ir kiekvienam pasakoma kas nors savo.", source: "Kūčios", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Tą patį vakarą paliekama tuščia lėkštė ir kėdė tiems, kurių tais metais prie stalo nėra.", source: "Kūčios", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Į vardadienį eidavo neprašyti. Diena žinoma iš kalendoriaus, todėl kvietimo nereikėjo.", source: "Papročiai", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Garbingiausia vieta prie stalo yra užstalė — toliausiai nuo durų. Atėjusį sodindavo ten, o ne prie krašto.", source: "Papročiai", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: - Kinship
        Passage(text: "Suaugti reiškia ir tapti suaugusiu žmogumi, ir dviem šakoms suaugti į vieną. Lietuviškai užaugama suaugant.", source: "Lietuvių kalba", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Du šalia augantys medžiai, metų metus trynęsi žieve, galiausiai suauga. Nuo tos vietos jie dalijasi syvais.", source: "Dendrologija", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Skiepytos obels riba matoma kamiene visą gyvenimą kaip randas. Virš jos vienas medis, žemiau — kitas.", source: "Sodininkystė", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Obuolys nuo obels netoli rieda.", source: "Lietuvių patarlė", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Visas drebulių guotas dažnai yra vienas augalas. Jie susiję šaknimis po žeme ir rudenį pagelsta tą pačią dieną.", source: "Populus tremula", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Šeimyna senuose namuose reiškė visus, kas valgo prie to paties stalo, įskaitant samdinius. Šeima buvo mažesnė už šeimyną.", source: "Lietuvių kalba", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Giminė reiškia ir giminaičius, ir žodžio giminę gramatikoje. Abu iš gimti.", source: "Etimologija", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Po mišku grybiena driekiasi ištisai ir sujungia medžių šaknis. Per ją medžiai gali perduoti vienas kitam maisto.", source: "Miško ekologija", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Pynė laikosi tuo, kad nė viena sruoga neina tiesiai. Visos trys pakaitomis eina per kitas.", source: "Papročiai", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Klevo ir liepos šaknys po ta pačia pieva persipina taip, kad iškasti vieną medį nepajudinus kito nebeįmanoma.", source: "Dendrologija", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Bičių šeima veikia kaip vienas kūnas. Nuo šeimos atskirta bitė negyvena nė kelių dienų.", source: "Bitininkystė", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Vestuvėse jaunųjų rankos surišamos juosta. Ta juosta paskui laikoma namie, ir jos niekas neatriša.", source: "Vestuvių papročiai", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Bičiulis kilęs iš bitės. Bičiuliais vadinti du žmonės, laikę bites kartu ir dalijęsi medumi; iš to atsirado paprastas žodis draugui.", source: "Etimologija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Bičiulystė buvo tikra sutartis: perduodamos bitės, dalijamasi priežiūra ir vašku, o santykis galiodavo ir vaikams.", source: "Bitininkystės istorija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Dieveris yra vyro brolis. Beveik tas pats žodis yra ir sanskrite, ir senojoje graikų kalboje; lietuvių kalba jo taip ir neatsisakė.", source: "Kalbotyra", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Marti, žentas, uošvis, anyta, svainis — kiekvienam iš jų yra savas žodis, o ne priesaga prie kito.", source: "Lietuvių kalba", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Pusbrolis ir pusseserė pažodžiui yra pusė brolio ir pusė sesers. Giminystė čia tiesiog išmatuota.", source: "Lietuvių kalba", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Sesuo, brolis, sūnus ir duktė lietuviškai beveik nepakitę nuo tų laikų, kai tie patys žodžiai skambėjo daugelyje Europos kalbų.", source: "Kalbotyra", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Krikštatėviai vaiko tėvams tampa kūmais. Tai giminystė, sudaryta susitarimu, ir ji turi savo vardą.", source: "Papročiai", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Dainose beveik viskas mažybinis: bernelis, mergelė, žirgelis, rūtelė. Mažybinė forma ten reiškia ne dydį, o santykį.", source: "Tautosaka", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ištekėti sakoma tik apie moterį ir yra iš tekėti — plaukti taip, kaip teka vanduo. Vyras tuo tarpu veda.", source: "Etimologija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Tėvai lietuviškai yra tėvo daugiskaita. Motina į tą žodį įeina, nors jos ten nesigirdi.", source: "Lietuvių kalba", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Vaikaitis reiškia anūką ir sudarytas iš vaiko. Kartas lietuvių kalba skaičiuoja tuo pačiu žodžiu.", source: "Lietuvių kalba", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Šeimininkas ir šeimininkė yra iš šeimos. Namų šeimininkas lietuviškai ne valdo, o laiko šeimą.", source: "Etimologija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Lietuvių kalboje išliko dviskaita: mudu, judu ir jiedu reiškia tiksliai du, ir daugiskaita čia netinka.", source: "Gramatika", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Abu ir abi turi savo linksniavimą, atskirą nuo skaitvardžio du. Lietuviškai du ir abu nėra tas pats.", source: "Gramatika", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Susižvalgyti reiškia vienu metu pažvelgti vienas į kitą ir abiem tai suprasti. Tam yra vienas veiksmažodis.", source: "Lietuvių kalba", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Susikalbėti reiškia ne pakalbėti, o pasiekti, kad abu suprastų. Be antro žmogaus tas veiksmažodis neveikia.", source: "Lietuvių kalba", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Girnas malant sukdavo dviese, kiekvienas viena ranka ant rankenos. Sukti reikia tolygiai, kitaip grūdas neišsimala.", source: "Kaimo darbai", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Gervės poroje šoka: viena pakelia sparnus, kita pakartoja. Poros laikosi daug metų iš eilės.", source: "Grus grus", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dvejinę sutartinę dainuoja lygiai du žmonės. Jei prisideda trečias, tai jau kita giesmė ir kitas pavadinimas.", source: "Sutartinės", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kreipiantis į vieną sakoma tu, o į du — jūs. Dviskaitos formos šiandien girdimos jau tik tarmėse.", source: "Gramatika", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Pora reiškia ir du daiktus, ir du žmones. Poruotis sakoma apie paukščius, o susiporuoti — apie darbą.", source: "Lietuvių kalba", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Gulbės laikosi poromis ištisus metus ir žiemą plaukioja greta, net kai visa kita banda susimaišo.", source: "Cygnus olor", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kalėdaitį laužia du žmonės iš karto: kiekvienas laiko savo galą, ir nė vienas nelaužia vienas sau.", source: "Kūčios", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dviese ilgą rąstą nešti lengviau ne todėl, kad svoris pusiau, o todėl, kad rąstas nustoja svirti.", source: "Miško darbai", theme: .kinship, subtheme: .twoPeople),

        // MARK: - Peace
        Passage(text: "Ošimas yra garsas, kurį daro vėjas pušyne arba jūra iš toli. Jo negalima priskirti nė vienam atskiram daiktui.", source: "Lietuvių kalba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Šlamesys sakomas apie lapus ir rugius, šnaresys — apie sausą popierių ar drabužį. Lietuvių kalba girdi juos kaip du garsus.", source: "Lietuvių kalba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Čiurlenimas yra mažo upelio garsas. Jam yra atskiras žodis, nors paties upelio dažnai net nesimato.", source: "Lietuvių kalba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Gausti sakoma apie varpą, apie bites avilyje ir apie vėją kamine. Visais trimis atvejais garsas žemas ir be pradžios.", source: "Lietuvių kalba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Sutartinėje du balsai skiriasi sekunde, ir dėl to atsiranda mušimas — lėtas garso banguojimas, girdimas tik stovintiems arti.", source: "Sutartinės", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Šnabždant balso stygos nevirpa, todėl šnabždesys neturi aukščio. Sušnabždėti melodijos neįmanoma.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Nuo dvidešimt antros iki septintos valandos Lietuvoje galioja nakties tyla. Tai ne mandagumas, o teisės aktas.", source: "Teisė", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Dzūkijos pušynuose po kojomis guli storas spyglių sluoksnis. Jame nuskęsta žingsnio garsas, ir žmonės ten netyčia ima kalbėti tyliau.", source: "Dzūkijos šilai", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Gervių šauksmas rudenį per pelkę girdimas už kelių kilometrų — ne todėl, kad jos garsios, o todėl, kad tarp jų ir ausies nieko nėra.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Tyla yra būsena, o tylėti — veiksmas. Lietuviškai žmogus gali tylėti ir ten, kur aplinkui triukšminga.", source: "Lietuvių kalba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Aidas atsiranda tik tada, kai garsas turi į ką atsimušti. Lygioje pelkėje jo nebūna, ir šauksmas dingsta ten pat, kur gimė.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Miestelio varpas girdimas toliau, nei matomas bokštas. Tarpai tarp dūžių ilgesni už patį garsą.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Taika, taikyti ir taikytis yra to paties kamieno. Taikyti reiškia pritaikyti vieną prie kito, o taika — kad tai pavyko.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Susitaikyti yra sangrąžinis žodis. Vienam susitaikyti neišeina: forma reikalauja abiejų pusių iš karto.", source: "Gramatika", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Santarvė ir sutartis kilę iš sutarti — sugyventi ir susikalbėti. Iš to paties ir sutartinė, giesmė, kuri privalo sutapti.", source: "Etimologija", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Paliaubos lietuvių kalboje neturi vienaskaitos. Vienos paliaubos nebūna, kaip nebūna ir vienų žirklių.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Liautis reiškia sustoti pačiam, o ne būti sustabdytam. Veiksmažodis sangrąžinis, ir kitaip jo pasakyti negalima.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Melno taika pasirašyta 1422 metais, ir jos nubrėžta siena išbuvo penkis šimtus vienerius metus.", source: "Istorija", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Atleisti reiškia ir dovanoti kaltę, ir atleisti veržlę. Abu atvejai yra tas pats judesys: paleisti įtempimą.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Dovanoti reiškia ir padovanoti daiktą, ir atleisti. Sakant dovanok, prašoma, kad kaltė būtų padovanota atgal.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Gana yra vienas žodis ir kartu visas sakinys. Juo sustabdomas ir vaikų kivirčas, ir per ilgai užsitęsęs darbas.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Nurimti reiškia pereiti į ramybę, o rimtis yra ta būsena, kurioje jau esi. Vieną galima padaryti, kitos negalima.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Taikdarys yra tas, kuris taiką daro. Žodis sudėtas taip pat paprastai kaip stalius ar kalvis.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Nesantaika yra santaikos neigimas. Pirma egzistuoja sugyvenimas, o nesutarimas gaunamas pridėjus priešdėlį.", source: "Lietuvių kalba", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Ramus lietuviškai ir ramate sanskrite yra tas pats senas žodis, reiškęs nurimti. Jis išliko abiejuose kalbos galuose.", source: "Etimologija", theme: .peace, subtheme: .atEase),
        Passage(text: "Poilsis yra daiktavardis iš ilsėtis, o ilsėtis lietuviškai galima tik savęs: veiksmažodis sangrąžinis.", source: "Gramatika", theme: .peace, subtheme: .atEase),
        Passage(text: "Atokvėpis yra iš atsikvėpti: trumpas tarpas, per kurį atgaunamas kvapas. Pertrauka čia matuojama kvėpavimu.", source: "Lietuvių kalba", theme: .peace, subtheme: .atEase),
        Passage(text: "Jaukus ir jaukinti yra vienos šaknies. Jauki vieta lietuviškai yra ta, kuri jau prijaukinta.", source: "Etimologija", theme: .peace, subtheme: .atEase),
        Passage(text: "Ant krosnies senuose namuose buvo įrengtas gultas. Ten miegodavo patys seniausi ir patys jauniausi, o kiti tik sėsdavo greta.", source: "Kaimo statyba", theme: .peace, subtheme: .atEase),
        Passage(text: "Po pirties sėdima priemenėje ir nieko nekalbama. Ta valanda laikoma pirties dalimi lygiai taip pat kaip karštis.", source: "Pirties papročiai", theme: .peace, subtheme: .atEase),
        Passage(text: "Suolas prie sienos statytas į pietų pusę. Sėdint ten po darbo saulė krinta tiesiai, o vėjas eina virš galvos.", source: "Kaimo statyba", theme: .peace, subtheme: .atEase),
        Passage(text: "Dykas reiškia ir laisvas, ir tuščias, ir nemokamas. Dykinėti tada yra daryti tai, kas nieko nekainuoja.", source: "Lietuvių kalba", theme: .peace, subtheme: .atEase),
        Passage(text: "Lopšys kabintas ant sijos ir supamas virvute nuo motinos kojos. Rankos likdavo laisvos, o vaikas užmigdavo pats.", source: "Kaimo papročiai", theme: .peace, subtheme: .atEase),
        Passage(text: "Vakaronė buvo vakaras be tikslo: verpiama, dainuojama, ir niekas nieko nebaigia. Kitą dieną tie patys žmonės vėl dirbo.", source: "Kaimo papročiai", theme: .peace, subtheme: .atEase),
        Passage(text: "Šuo prie durų atsigula skersai slenksčio. Iš ten mato ir kiemą, ir kambarį, ir jam nereikia nieko rinktis.", source: "Canis familiaris", theme: .peace, subtheme: .atEase),
        Passage(text: "Snausti reiškia miegoti ne visai. Lietuvių kalba turi žodį būsenai, kurioje žmogus vis dar girdi, kas darosi aplinkui.", source: "Lietuvių kalba", theme: .peace, subtheme: .atEase),
    ]
}
