import Foundation

/// The Icelandic passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let icelandic: [Passage] = [
        // MARK: Beginnings
        Passage(text: "Spírun: augnablikið þegar fræ hættir að vera forðabúr og verður planta. Því verður ekki snúið við.", source: "Grasafræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Hálfnað er verk þá hafið er.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Upphaf er sett saman úr upp og hefja. Í orðinu sjálfu felst að byrjun sé það að lyfta einhverju.", source: "Íslensk orðmyndun", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Á íslensku kviknar hvort tveggja, eldur og líf. Sama sögnin er höfð um bál sem tekur við sér og barn sem verður til.", source: "Íslenska", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Surtsey braut sjávarborðið 14. nóvember 1963. Gosið hafði þá staðið neðansjávar í nokkra daga án þess að nokkur sæi það.", source: "Jarðfræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Alþingi kom fyrst saman á Þingvöllum árið 930 og hefur starfað lengur en nokkurt annað þing sem enn situr.", source: "Saga", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Fyrsta bókin prentuð á íslensku var Nýja testamentið í þýðingu Odds Gottskálkssonar árið 1540.", source: "Prentsaga", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Rjúpuungi klekst alfiðraður og gengur úr hreiðrinu sama daginn. Fyrsta skrefið og fyrsti dagurinn eru eitt.", source: "Fuglafræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Jökulá verður til við sporðinn en ekki við upptök: vatnið heitir á frá þeirri stundu sem það kemur undan ísnum.", source: "Vatnafræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Brumhlíf springur á einum degi. Kvöldið áður var brumið lokað, og eftir þennan dag lokast það aldrei aftur.", source: "Grasafræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Eldgos hefst á sprungu sem opnast á fáeinum mínútum. Hraunið kemur á eftir, stundum vikum síðar.", source: "Jarðfræði", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Fyrsti dagur þorra heitir bóndadagur og fyrsti dagur góu konudagur. Tveir mánuðir í röð eiga upphafsdag með nafni.", source: "Tímatal", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Oft veltir lítil þúfa þungu hlassi.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Margur er knár þó hann sé smár.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Margt smátt gerir eitt stórt.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Barnið vex en brókin ekki.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Melgresi bindur foksand. Eitt strá heldur engu, en breiða af melgresi heldur heilli sandöldu kyrri.", source: "Landgræðsla", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Birkifræ er á stærð við títuprjónshaus. Úr því verður tré sem getur staðið í tvær aldir.", source: "Grasafræði", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Surtsey var einn gígur haustið 1963 og orðin á þriðja ferkílómetra þegar gosinu lauk fjórum árum síðar.", source: "Jarðfræði", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Varða á heiði er hlaðin úr steinum sem hver um sig kemst í eina hönd, og hún sést langar leiðir.", source: "Þjóðhættir", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Hraunbreiða byrjar sem sprunga á fáeina metra og getur endað sem þúsund ferkílómetrar af bergi.", source: "Jarðfræði", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Íslenska sauðkindin kom með fáeinum skipsförmum. Nú eru kindurnar á fjórða hundrað þúsund í landinu.", source: "Búfjárrækt", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Mosaþemba á hrauni vex um fáeina millimetra á ári. Þykk breiða er því aldargömul eða eldri.", source: "Vistfræði", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Lítill lækur undan hraunjaðri getur verið allt sem sést af vatni sem rennur neðanjarðar um heilan dal.", source: "Vatnafræði", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Hvað ungur nemur gamall temur.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ekki er ráð nema í tíma sé tekið.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Fyrra verkið vinnur hið síðara.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Hver er sinnar gæfu smiður.", source: "Íslenskur málsháttur", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ísland dregur nafn af hafís sem Flóki Vilgerðarson sá liggja í firði. Nafnið stendur enn þótt ísinn færi.", source: "Landnámabók", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Eyktamark bæjar var valið einu sinni: tindur eða varða sem sólin stóð yfir á tilteknum tíma. Eftir því var klukkan lesin um aldir.", source: "Þjóðhættir", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Landnámsmenn völdu sér bæjarstæði eftir vatni, beit og lendingu. Þau þrjú atriði ráða enn hvar bæir standa.", source: "Byggðasaga", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Það skulu vera lög í landi hér sem á skrám standa.", source: "Grágás", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Þegar tré er klippt fyrstu árin ræðst lögun stofnsins næstu öld.", source: "Skógrækt", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Fyrsta lína ferskeytlu ræður stuðlunum. Sá sem byrjar vísuna ákveður hljóðin sem hinar línurnar verða að hlýða.", source: "Bragfræði", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Fyrsti dagur gormánaðar er fyrsti vetrardagur. Veturinn er talinn frá honum hvernig sem viðrar.", source: "Tímatal", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kenninafn barns er nafn foreldris með -son eða -dóttir. Það er gefið einu sinni og fylgir engri ætt.", source: "Nafnasiður", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: Waiting
        Passage(text: "Dvali: fræ sem neitar að spíra þótt allt sé rétt í kringum það, haldið aftur af sjálfu sér þar til eitthvað breytist.", source: "Grasafræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Melgresisfræ getur legið í sandi árum saman og beðið eftir sumri sem er nógu rakt.", source: "Grasafræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Rjúpan situr grafkyrr í snjónum meðan fálki fer hjá og hreyfir sig ekki fyrr en skugginn er farinn.", source: "Fuglafræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Goshver safnar hita undir yfirborðinu milli gosa. Strokkur bíður fáeinar mínútur, Geysir beið stundum árum saman.", source: "Jarðfræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Að stilla sig er sama sögn og að stilla hljóðfæri: að halda sér í réttum tón.", source: "Íslenska", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Í vetrardvala hægja hjartsláttur og andardráttur svo mjög að dýrið eyðir varla neinu og vaknar við hita en ekki við klukku.", source: "Dýrafræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Þorskur hrygnir ekki fyrr en hann er fimm til sjö vetra. Fram að því vex hann og bíður.", source: "Sjávarlíffræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Hafís berst ekki að landi fyrr en vindur og straumur leggjast á eitt. Hann getur legið úti fyrir vikum saman.", source: "Hafeðlisfræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Í moldinni er fræbanki. Sum þeirra fræja spíra fyrst þegar torfa er rist ofan af þeim.", source: "Grasafræði", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Að bíða byrjar er að liggja í höfn þar til vindurinn stendur rétt. Byr er hagstæður vindur og ekkert annað.", source: "Sjómál", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Svellalög liggja á túni fram á vor. Grasið undir þeim er lifandi en kemst hvergi fyrr en leysir.", source: "Landbúnaður", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Hangikjöt er reykt og látið hanga mánuðum saman áður en það er borðað. Nafnið segir aðeins hvað það gerir á meðan.", source: "Matarhefð", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Dropinn holar harðan stein.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Dagur og nótt bíða ekki eftir neinum.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Betra er seint en aldrei.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Koma dagar koma ráð.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Eykt er áttundi hluti sólarhringsins, um þrjár stundir, og hver eykt átti sitt nafn.", source: "Tímatal", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Fjallagrös vaxa fáeina millimetra á ári. Heiðin sem tínd er í ár er ekki tilbúin aftur fyrr en löngu síðar.", source: "Grasafræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ísinn neðst í Vatnajökli er mörg hundruð ára gamall. Snjórinn sem féll þar efst í fyrra á langa leið fyrir höndum.", source: "Jöklafræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Íslenskur hestur getur orðið yfir þrítugur og er oft í fullu fjöri um tvítugt.", source: "Búfjárrækt", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Hraun kólnar að utan á fáeinum vikum en heldur hita innst í mörg ár.", source: "Jarðfræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Handrit Grágásar eru frá miðri þrettándu öld og hafa verið lesin samfleytt síðan.", source: "Handritafræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Langvía verpir einu eggi á ári og byrjar ekki fyrr en um fimm vetra. Fuglabjarg endurnýjast hægt.", source: "Fuglafræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Mómýri geymir hvert lag af gróðri sem á hana féll. Einn sentimetri af mó getur verið heil öld.", source: "Jarðvegsfræði", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Fjallkóngur heitir sá sem stjórnar göngum. Hann rekur ekkert fé sjálfur heldur sér yfir alla leitina.", source: "Þjóðhættir", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Hjá heiðlóu liggja báðir foreldrar á egginu til skiptis í um þrjár vikur.", source: "Fuglafræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Sjón er sögu ríkari.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Bragð er að þá barnið finnur.", source: "Íslenskur málsháttur", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Veðurathugunarmenn um allt land lesa af mælum á sömu mínútu og skrá líka það sem þeir sjá út um gluggann.", source: "Veðurfræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Fálki situr kyrr á sama steini klukkustundum saman og hreyfir sig fyrst þegar hann sér eitthvað fara.", source: "Fuglafræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Vaka merkir bæði að sofa ekki og að gæta. Að vaka yfir túni var að verja það fyrir búfé fram á morgun.", source: "Íslenska", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Í skammdeginu sést sólin ekki á Ísafirði í tvo mánuði, og menn vita samt upp á dag hvenær hún kemur aftur.", source: "Veðurfræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Landvörður í friðlandi telur hreiður og skráir hvað hefur breyst. Starfið er að taka eftir.", source: "Náttúruvernd", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Jarðskjálftamælar senda tölur allan sólarhringinn. Oftast mæla þeir ekkert, og einmitt það er niðurstaðan.", source: "Jarðeðlisfræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Selur á skeri fylgist með báti alla leiðina fram hjá og fer fyrst í sjóinn ef stefnan breytist að honum.", source: "Dýrafræði", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Hleri er fjölin sem sett var fyrir glugga. Að standa á hleri er að hlusta þar sem fjölin er.", source: "Íslenska", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: Renewal
        Passage(text: "Nýir vendir sópa best.", source: "Íslenskur málsháttur", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Há heitir grasið sem sprettur upp aftur eftir slátt. Túnið er ekki búið þótt það hafi verið slegið.", source: "Landbúnaður", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Birki sem er höggvið við rót sendir upp marga stofna í stað eins, og þar verður kjarr sem áður stóð tré.", source: "Skógrækt", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ull er klippt af kind einu sinni á ári og er komin aftur næsta haust.", source: "Búfjárrækt", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Melgresi sem fennir í kaf skýtur nýjum sprotum upp gegnum sandinn og hækkar þannig hólinn sem það stendur á.", source: "Grasafræði", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Hraun sem rann fyrir tveimur öldum er þegar komið undir mosa. Gróðurinn byrjar á nöktu bergi og endar í lyngi.", source: "Vistfræði", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Skyr er gert með því að taka ögn af síðustu gerð og setja í nýja mjólk. Sami þráður hefur gengið mann fram af manni.", source: "Matarhefð", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Rjúpan skiptir alveg um lit tvisvar á ári, hvít á vetri og mósótt á sumri.", source: "Fuglafræði", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Sölnað lyng á haustheiði er ekki dautt. Það geymir í rótinni allt sem næsta vor þarf.", source: "Grasafræði", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Geysir hætti að gjósa um aldamótin 1900 og tók sig upp aftur eftir jarðskjálftana sumarið 2000.", source: "Jarðfræði", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Endurheimt votlendis felst í því að fylla í skurð. Mýrin kemur svo til baka af sjálfri sér.", source: "Náttúruvernd", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Torfveggur var hlaðinn upp á nýtt á fárra áratuga fresti úr sama torfi og sama grjóti. Húsið var hið sama og efnið nýtt.", source: "Húsagerð", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Sumardagurinn fyrsti er fyrsti fimmtudagur eftir 18. apríl. Þá hefst mánuðurinn harpa.", source: "Tímatal", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Í gamla íslenska tímatalinu eru árstíðirnar tvær, sumar og vetur, og mánuðirnir tólf með eigin nöfnum.", source: "Tímatal", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Vorið góða, grænt og hlýtt, græðir fjör um dalinn. Allt er nú sem orðið nýtt.", source: "Jónas Hallgrímsson, Vorvísur", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Sólin heim úr suðri snýr, sumri lofar hlýju.", source: "Jónas Hallgrímsson, Stökur", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Lóan kemur í lok mars og er talin fyrsti vorboðinn. Hún hefur þá vetursetið suður undir Gíbraltar.", source: "Fuglafræði", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Þorri hefst á föstudegi í þrettándu viku vetrar, á bilinu 19. til 25. janúar.", source: "Tímatal", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Allt er vænt sem vel er grænt.", source: "Íslenskur málsháttur", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Krían kemur um miðjan maí og er farin í ágúst. Koma hennar er víða talin upphaf sumarsins.", source: "Fuglafræði", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Fyrsti vetrardagur er á laugardegi á bilinu 21. til 27. október, og þá er gormánuður byrjaður.", source: "Tímatal", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Réttir eru haldnar í september þegar fé er sótt á fjall. Sama helgin ár eftir ár, í sömu rétt.", source: "Þjóðhættir", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Sauðburður stendur fáeinar vikur í maí og fer nærri því fram á sömu dögum hvert ár.", source: "Búfjárrækt", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Berjaspretta ræðst af vorinu en tínt er í ágúst. Heiðin verður blá á sama tíma og árið áður.", source: "Þjóðhættir", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Grasið þróast grænt í næði, glóðir þar sem runnu fyrr.", source: "Jónas Hallgrímsson, Fjallið Skjaldbreiður", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Batnandi manni er best að lifa.", source: "Íslenskur málsháttur", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Betri er hálfur skaði en allur.", source: "Íslenskur málsháttur", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Bein sem grær verður þykkast á brotstaðnum. Þar er það sterkara á eftir en það var.", source: "Læknisfræði", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Mosi grær yfir hraunsár á fáeinum áratugum og gerir svart berg grænt.", source: "Vistfræði", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Sár á birkiberki lokast með þykkri rönd sem sést alla ævi trésins.", source: "Grasafræði", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Uppgræðsla hófst á Íslandi með lögum árið 1907 og hefur staðið samfleytt síðan.", source: "Landgræðsla", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Að heilsa er dregið af heill, sem merkir óskaddaður. Að heilsa manni er í rót sinni að óska honum að vera heill.", source: "Orðsifjar", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Þegar mýri er endurheimt kemur vatnið fyrst, svo mosinn og síðast fuglinn.", source: "Náttúruvernd", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Í friðlandi er ekki gert við neitt. Landið er látið eitt og lagar sig sjálft.", source: "Náttúruvernd", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Súrsun í mysu geymir mat mánuðum saman. Það sem var að skemmast verður að vetrarforða.", source: "Matarhefð", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Hraunið sem rann yfir tún á átjándu öld er nú aftur grænt. Jarðvegurinn er nýr og staðurinn sá sami.", source: "Vistfræði", theme: .renewal, subtheme: .madeWhole),

        // MARK: Light
        Passage(text: "Morgunstund gefur gull í mund.", source: "Íslenskur málsháttur", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Drjúg eru morgunverkin.", source: "Íslenskur málsháttur", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Sólarkaffi er haldið á Ísafirði 25. janúar, daginn sem sólin kemur aftur yfir fjallið eftir tveggja mánaða fjarveru.", source: "Þjóðhættir", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Eyktarmörkin heita miðnætti, ótta, miður morgunn, dagmál, hádegi, nón, miður aftann og náttmál.", source: "Tímatal", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Um Jónsmessu sest sólin varla á Íslandi. Það rökkvar en verður ekki dimmt.", source: "Stjörnufræði", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ótta heitir tíminn klukkan þrjú að nóttu, dimmasta eyktin og sú sem á sitt eigið nafn.", source: "Tímatal", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Í desember er sólargangur í Reykjavík rúmar fjórar klukkustundir.", source: "Stjörnufræði", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Sólin gengur undir á ská en ekki beint niður hér norður frá, og því líður langur tími milli sólarlags og myrkurs.", source: "Stjörnufræði", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Rismál heitir eyktin klukkan sex að morgni, og nafnið segir hvað þá var gert.", source: "Tímatal", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Norðurljós sjást aðeins þegar er bæði heiðskírt og nógu dimmt. Þau eru þarna á daginn líka.", source: "Eðlisfræði", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Hádegishnúkur og Nónvarða eru algeng örnefni. Þau eru klukkur, hlaðnar eða skapaðar, sem sólin gengur yfir.", source: "Örnefni", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Náttmál klukkan níu voru merki um að dagsverki væri lokið og kvöldvakan gæti hafist.", source: "Þjóðhættir", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Skjár hét þurrkuð himna sem strengd var í gluggagat á torfbæ í stað glers. Sama orð er nú haft um tölvuskjá.", source: "Íslenska", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Holtasóley snýr blóminu eftir sólu allan daginn og safnar þannig hita í bikarinn.", source: "Grasafræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Vindstig voru lesin af sjónum: gárur, smáöldur, hvítfyssandi öldur. Augað mældi það sem enginn mælir var til fyrir.", source: "Veðurfræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Grös hér norður frá fara af stað eftir daglengd fremur en hita, og byrja á sama tíma þótt vorið sé kalt.", source: "Grasafræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ísblik er hvít rönd við sjóndeildarhring. Hafísinn kastar birtu upp í skýin og sést þannig áður en hann sést.", source: "Hafeðlisfræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Fjallið á móti lýsist upp löngu áður en sólin kemur yfir það sem stendur á milli. Birtan berst á undan henni.", source: "Stjörnufræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gíll heitir ljósblettur framan við sólina og úlfur sá sem eltir hana. Þeir verða til í ískristöllum hátt í lofti.", source: "Veðurfræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Skuggar á Íslandi eru langir jafnvel um hádegi, því sólin fer aldrei mjög hátt á loft.", source: "Stjörnufræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Skyggni er mælt í kílómetrum og skráð með vindi og hita. Það hversu langt sést er talið til veðurs.", source: "Veðurfræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Miðnætursól er ekki sól sem stendur kyrr. Hún strýkst við sjóndeildarhringinn og fer upp aftur.", source: "Stjörnufræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gufustrókurinn sást langt að löngu áður en hveraskálin kom í ljós. Reykjavík dregur nafn af sömu sjón.", source: "Örnefni", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Auga sem hefur verið í myrkri í hálftíma greinir margfalt daufara ljós en það sem nýkomið er inn.", source: "Sjónfræði", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Eldur er bestur með ýta sonum og sólar sýn.", source: "Hávamál", theme: .light, subtheme: .lightItself),
        Passage(text: "Norðurljós verða til þegar hlaðnar agnir frá sólinni rekast á lofthjúpinn í rúmlega hundrað kílómetra hæð.", source: "Eðlisfræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Græni liturinn í norðurljósum kemur frá súrefni, og sá rauði frá sama efni miklu ofar.", source: "Eðlisfræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Ljósið frá sólinni er átta mínútur á leiðinni til jarðar.", source: "Stjörnufræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Grútarlampi var ljósgjafinn í baðstofunni: lýsi og fífukveikur, og birtan náði rétt yfir borðið.", source: "Þjóðhættir", theme: .light, subtheme: .lightItself),
        Passage(text: "Fífa var höfð í kveikinn af því að hún dregur í sig lýsið og brennur jafnt.", source: "Þjóðhættir", theme: .light, subtheme: .lightItself),
        Passage(text: "Rafmagn er dregið af raf, sem er gulbrúnt harpix. Sama hugmynd býr í gríska orðinu elektron.", source: "Orðsifjar", theme: .light, subtheme: .lightItself),
        Passage(text: "Eldgos lýsir upp ský. Bjarminn sést tugi kílómetra þótt gosið sjálft sé á bak við fjall.", source: "Jarðfræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Vitaljós er ekki sterkara en venjuleg pera. Það sem sést langt að er linsan sem safnar því í eina rák.", source: "Ljósfræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Snjór endurkastar allt að níu tíundu hlutum þess ljóss sem á hann fellur. Þess vegna er bjart úti þótt himinn sé grár.", source: "Eðlisfræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Maurildi heitir það þegar svifdýr í sjónum lýsa við minnstu hreyfingu.", source: "Sjávarlíffræði", theme: .light, subtheme: .lightItself),
        Passage(text: "Ísjaki er blár af því að ísinn drekkur í sig rauða ljósið og skilar því bláa.", source: "Eðlisfræði", theme: .light, subtheme: .lightItself),

        // MARK: Pattern
        Passage(text: "Þjóð veit þá þrír vita.", source: "Íslenskur málsháttur", theme: .pattern, subtheme: .counted),
        Passage(text: "Gamla tímatalið telur tólf mánuði með nöfnum og skýtur sumarauka inn svo að árið gangi upp.", source: "Tímatal", theme: .pattern, subtheme: .counted),
        Passage(text: "Ferskeytla er fjórar línur. Fyrsta og þriðja hafa fjóra bragliði, önnur og fjórða þrjá.", source: "Bragfræði", theme: .pattern, subtheme: .counted),
        Passage(text: "Í oddalínu eru tveir stuðlar og í þeirri jöfnu einn höfuðstafur, fremst. Hljóðið er talið, ekki bara heyrt.", source: "Bragfræði", theme: .pattern, subtheme: .counted),
        Passage(text: "Vindstigin eru tólf og hvert þeirra á íslenskt nafn, frá logni upp í fárviðri.", source: "Veðurfræði", theme: .pattern, subtheme: .counted),
        Passage(text: "Íslenski hesturinn hefur fimm gangtegundir: fet, brokk, stökk, tölt og skeið.", source: "Búfjárrækt", theme: .pattern, subtheme: .counted),
        Passage(text: "Landnámabók telur upp meira en fjögur hundruð landnámsmenn og segir hvar hver þeirra tók land.", source: "Landnámabók", theme: .pattern, subtheme: .counted),
        Passage(text: "Að telja í tylftum er eldra en tugakerfið hér. Tylft er tólf og lifir enn í málinu.", source: "Íslenska", theme: .pattern, subtheme: .counted),
        Passage(text: "Sjaldséðir eru hvítir hrafnar.", source: "Íslenskur málsháttur", theme: .pattern, subtheme: .counted),
        Passage(text: "Þegar ein báran rís er önnur vís.", source: "Íslenskur málsháttur", theme: .pattern, subtheme: .counted),
        Passage(text: "Íslensk ær ber oftast tveimur lömbum. Tvílembd ær þykir venjuleg en ekki heppni.", source: "Búfjárrækt", theme: .pattern, subtheme: .counted),
        Passage(text: "Rímnahættir skipta hundruðum og hver þeirra á sitt nafn. Þeir eru allir taldir upp í bragfræðiritum.", source: "Bragfræði", theme: .pattern, subtheme: .counted),
        Passage(text: "Fjárrétt er hringur með geirum út frá. Hringurinn heitir almenningur og geirarnir dilkar, einn fyrir hvern bæ.", source: "Búfjárrækt", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Stuðull og höfuðstafur festa tvær ljóðlínur saman. Hljóðið sem byrjar er endurtekið uns það lendir á réttum stað.", source: "Bragfræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Klömbruhleðsla heitir það þegar torfstrengir eru lagðir á víxl svo að veggurinn verður eins og fiskbein.", source: "Húsagerð", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Stuðlaberg brotnar í sexhyrninga af því að kólnandi hraun dregst saman jafnt í allar áttir.", source: "Jarðfræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Í vaðmáli er uppistaða og ívaf. Hvorugt er dúkur eitt sér.", source: "Vefnaður", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Lopapeysa er prjónuð í hring, og axlastykkið er munstrað þannig að úrtakan felist í munstrinu.", source: "Prjón", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Fjallagrös eru flétta: sveppur og þörungur sem hvorugur lifir einn, en saman þekja þeir heilar heiðar.", source: "Grasafræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Grjóthleðsla án steinlíms heldur af því að hver steinn hvílir á tveimur og ber tvo.", source: "Húsagerð", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Í skarsúð leggst hvert borð yfir jaðar þess næsta. Báturinn heldur vatni án þess að nokkuð sé þétt.", source: "Bátasmíði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Kenning er tvö orð sett saman sem merkja það þriðja. Hvorugt segir það eitt og sér.", source: "Bragfræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Samsett orð í íslensku eru gerð úr heilum orðum en ekki bútum. Jökulhlaup er jökull og hlaup og ekkert þar á milli.", source: "Málfræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Þúfa myndast þegar frost lyftir jarðvegi sem sest ekki alveg aftur. Þúfnabreiða er landslag úr endurteknu smáatriði.", source: "Jarðvegsfræði", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Verkið lofar meistarann.", source: "Íslenskur málsháttur", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Tölva var mynduð af tala eftir sömu gerð og orðin völva og slöngva. Sigurður Nordal setti hana fram árið 1965.", source: "Nýyrði", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Þota er dregin af sögninni að þjóta og þyrla af því að þyrla. Farartækin heita eftir því hvað þau gera.", source: "Nýyrði", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Sími er gamalt orð um þráð og var tekið upp aftur þegar landið fékk talsamband við umheiminn.", source: "Orðsifjar", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Ný orð eru hér oftast smíðuð úr orðum sem fyrir eru, í stað þess að tökuorð sé fellt að málinu.", source: "Málstefna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Lögsögumaður Alþingis geymdi lögin í minni sér og sagði þriðjung þeirra upp á Lögbergi ár hvert.", source: "Saga", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Jökulhlaup er íslenskt orð sem hefur verið tekið upp í jarðfræði um allan heim.", source: "Jarðfræði", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Geysir er nafn á einum tilteknum hver í Haukadal. Af því er komið alþjóðlega orðið yfir goshveri.", source: "Örnefni", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Örnefni hér eru að miklu leyti lýsingar: Breiðafjörður, Langjökull, Djúpivogur, Sandvík.", source: "Örnefni", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Mannanafnanefnd var sett á fót árið 1991 og sker úr um hvort nýtt eiginnafn fari á mannanafnaskrá.", source: "Nafnasiður", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Í Snorra-Eddu eru heiti og kenningar taldar upp í röð svo að skáld geti flett upp á réttu orði.", source: "Bragfræði", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Hraun heitir apalhraun ef það er úfið og helluhraun ef það er slétt. Sama bergið, tvö nöfn eftir því hvernig það rann.", source: "Jarðfræði", theme: .pattern, subtheme: .orderNamed),

        // MARK: Ground
        Passage(text: "Íslenskur jarðvegur er að mestu foksandur og vikur sem gras hefur bundið. Hann er ungur og laus í sér.", source: "Jarðvegsfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mór er jarðvegur úr plöntum sem aldrei rotnuðu til fulls, af því að vatnið hélt loftinu frá þeim.", source: "Jarðvegsfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Öskulag frá einu gosi liggur eins og lína um allt land og er notað til að tímasetja það sem liggur ofan á því og undir.", source: "Jarðfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Landnámslagið er ljóst öskulag frá árinu 871 og skilur að það sem var fyrir landnám og það sem kom eftir.", source: "Jarðfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mold sem tekur öld að verða til getur fokið burt á einu vori ef gróðurþekjan rofnar.", source: "Landgræðsla", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Í íslenskri jörð er bundið kolefni margra árþúsunda. Framræst mýri lætur það aftur út í loftið.", source: "Jarðvegsfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Áburður úr fjósi var borinn á túnið og hvergi annars staðar. Þess vegna var túnið grænna en allt í kring.", source: "Landbúnaður", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Tún er sama orð og enska town: upphaflega girt svæði kringum bæ, ekki bærinn sjálfur.", source: "Orðsifjar", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Bragð af lambakjöti fer eftir beitilandinu. Kjöt af fé sem gengur í fjöru er annað en kjöt af heiðum.", source: "Búfjárrækt", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Hraun verður að mold með því að mosi sest á það og deyr. Fyrsta kynslóðin býr til þá næstu.", source: "Vistfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Undir birkiskógi liggur sveppanet sem tengir trén saman og flytur næringu milli þeirra.", source: "Vistfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Vikur flýtur á vatni. Gjóska úr Heklugosum hefur borist með ám langar leiðir frá fjallinu.", source: "Jarðfræði", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Heima er best.", source: "Íslenskur málsháttur", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Bú er betra, þótt lítið sé. Halur er heima hver.", source: "Hávamál", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Þið þekkið fold með blíðri brá og bláum tindi fjalla.", source: "Jónas Hallgrímsson, Íslandsminni", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Fífilbrekka, gróin grund, grösug hlíð með berjalautum.", source: "Jónas Hallgrímsson, Dalvísa", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Mörg bæjarnöfn eru þau sömu og í Landnámabók. Sami staður hefur heitið því sama í ellefu hundruð ár.", source: "Byggðasaga", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Til er að fólk sé kennt við bæ: Jón í Hlíð, Guðrún á Sandi. Staðurinn kemur þá í stað ættarnafns.", source: "Nafnasiður", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Í sveitum er bærinn sjálfur heimilisfang. Nafn hans dugar og pósturinn ratar.", source: "Þjóðhættir", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Eyktamörk voru bundin einum bæ. Sama fjallið sagði annan tíma frá næsta bæ.", source: "Þjóðhættir", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Afrétt er land sem enginn á einn en allir hafa rétt til. Féð gengur þar á sumrin og er sótt á haustin.", source: "Landbúnaður", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Hestur sem er fluttur út frá Íslandi kemur ekki aftur. Hann á aðeins eina heimferð.", source: "Búfjárrækt", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Landnámsmaður helgaði sér land með því að bera eld um það, og kona með því að leiða kvígu um það á einum degi.", source: "Landnámabók", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Hlaðið er flötin fyrir framan bæinn. Þar er tekið á móti gestum og þaðan er þeim fylgt úr hlaði.", source: "Þjóðhættir", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Umgengni lýsir innri manni.", source: "Íslenskur málsháttur", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Álagablettur er reitur sem ekki má slá, tína ber í eða raska. Sums staðar er engin saga til um hvers vegna.", source: "Þjóðtrú", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Friðland er svæði sem er friðlýst með lögum til verndar tilteknum tegundum eða vistgerðum.", source: "Náttúruvernd", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Faðir og vinur alls, sem er, annastu þennan græna reit.", source: "Jónas Hallgrímsson, Hulduljóð", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Túngarður úr torfi og grjóti skildi að tún og úthaga. Innan hans var slegið, utan hans beitt.", source: "Húsagerð", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Í æðarvarpi ræður kollan. Dúnn er ekki tekinn fyrr en ungarnir eru farnir úr hreiðrinu.", source: "Æðarrækt", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Skrúður í Dýrafirði var gerður árið 1909 til að sýna að hér mætti rækta grænmeti. Honum er enn haldið við.", source: "Garðyrkjusaga", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Þingvellir urðu þjóðgarður árið 1928, fyrsta svæðið á Íslandi sem var friðlýst.", source: "Náttúruvernd", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Varnarlínur skipta landinu í hólf og fé fer ekki milli þeirra. Girðingin er til að vernda það sem innan hennar er.", source: "Búfjárrækt", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Handritin komu heim frá Kaupmannahöfn á árunum 1971 til 1997 og eru geymd við raka og hita sem eru mældir daglega.", source: "Handritafræði", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Í heimagarði hér vaxa kartöflur, rabarbari og ribs. Þrennt sem þrífst þar sem margt annað gerir það ekki.", source: "Garðyrkja", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Að hlú að einhverju er upphaflega að bera skjól að rót svo að frostið nái henni ekki.", source: "Íslenska", theme: .ground, subtheme: .aKeptPlace),

        // MARK: Travel
        Passage(text: "Öndvegissúlum var varpað fyrir borð þegar land sást, og sest að þar sem þær rak á land.", source: "Landnámabók", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Sæbaunir frá hitabeltinu berast með Golfstraumnum á íslenskar fjörur. Þær voru kallaðar lausnarsteinar og geymdar.", source: "Þjóðtrú", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Farfugl ber fræ í fiðri og í maga. Það sem sest á heiði í maí lagði af stað sunnan úr álfunni.", source: "Vistfræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Vikur flýtur á sjó og getur borist landa á milli áður en hann mettast og sekkur.", source: "Jarðfræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mosagró eru svo létt að þau berast með vindi yfir heilt haf. Mosi var meðal þess fyrsta sem nam land á Surtsey.", source: "Vistfræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Fyrsta blómplantan sem fannst á Surtsey var fjörukál, og fræið hafði borist þangað með sjónum.", source: "Vistfræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ax af melgresi brotnar af og veltur með sandinum uns það stöðvast í laut. Þar byrjar næsta breiða.", source: "Grasafræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ærin ratar á sama fjall ár eftir ár. Lambið lærir leiðina af móður sinni fyrsta sumarið.", source: "Búfjárrækt", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rekaviður á íslenskum fjörum kemur frá Síberíu og er þrjú til fjögur ár á leiðinni gegnum Norður-Íshafið.", source: "Hafeðlisfræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Krían fer suður með ströndum Afríku en kemur norður um mitt Atlantshaf. Hringurinn liggur ekki sömu leið báðar áttir.", source: "Fuglafræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bláberjalyng dreifir sér mest með rótarskotum en berst líka langar leiðir í fuglsmaga.", source: "Grasafræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Hrossagaukurinn hefur vetursetu á Írlandi og kemur aftur á sömu mýrina að vori.", source: "Fuglafræði", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kemst þó hægt fari.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .theRoad),
        Passage(text: "Þeir fiska sem róa.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .theRoad),
        Passage(text: "Sá einn veit sem reynir.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .theRoad),
        Passage(text: "Öll vötn renna til sjávar.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .theRoad),
        Passage(text: "Sá kennir öðrum vaðið sem undan ríður.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .theRoad),
        Passage(text: "Vörður voru hlaðnar á fjallvegum þannig að næsta varða sæist frá þeirri sem staðið var við.", source: "Þjóðhættir", theme: .travel, subtheme: .theRoad),
        Passage(text: "Þjóðleiðir lágu um vöð og skörð en ekki stystu leið. Brúarlausar ár réðu því hvar menn fóru.", source: "Samgöngusaga", theme: .travel, subtheme: .theRoad),
        Passage(text: "Hringvegurinn varð heill árið 1974 þegar brúað var yfir Skeiðará.", source: "Samgöngusaga", theme: .travel, subtheme: .theRoad),
        Passage(text: "Tölt er gangtegund þar sem alltaf er fótur í jörð. Þess vegna hristist sá ekki sem situr.", source: "Búfjárrækt", theme: .travel, subtheme: .theRoad),
        Passage(text: "Áfangastaður merkti fyrst staðinn þar sem áð var: þar sem hestum var beitt og menn hvíldust á miðri leið.", source: "Íslenska", theme: .travel, subtheme: .theRoad),
        Passage(text: "Vegleysa er land þar sem enginn vegur liggur. Í kvæðum er farið um háa vegleysu og komist samt.", source: "Íslenska", theme: .travel, subtheme: .theRoad),
        Passage(text: "Nú andar suðrið sæla vindum þýðum.", source: "Jónas Hallgrímsson, Ég bið að heilsa", theme: .travel, subtheme: .theRoad),
        Passage(text: "Fjarlægðin gerir fjöllin blá og mennina mikla.", source: "Íslenskur málsháttur", theme: .travel, subtheme: .farOff),
        Passage(text: "En til góðs vinar liggja gagnvegir, þótt hann sé firr farinn.", source: "Hávamál", theme: .travel, subtheme: .farOff),
        Passage(text: "Þú stóðst á tindi Heklu hám og horfðir yfir landið fríða.", source: "Jónas Hallgrímsson, Til herra Páls Gaimard", theme: .travel, subtheme: .farOff),
        Passage(text: "Ó, heilsið öllum heima rómi blíðum um hæð og sund í drottins ást og friði.", source: "Jónas Hallgrímsson, Ég bið að heilsa", theme: .travel, subtheme: .farOff),
        Passage(text: "Krían flýgur lengst allra dýra: frá varpstöðvum við heimskautsbaug suður að Suðurskautslandinu og aftur til baka.", source: "Fuglafræði", theme: .travel, subtheme: .farOff),
        Passage(text: "Vesturfarar héldu til Kanada eftir 1870. Í Manitoba tala elstu afkomendur þeirra enn íslensku.", source: "Saga", theme: .travel, subtheme: .farOff),
        Passage(text: "Yfir Grænlandssund eru um þrjú hundruð kílómetrar, styttra en akstursleiðin frá Reykjavík austur á Egilsstaði.", source: "Landafræði", theme: .travel, subtheme: .farOff),
        Passage(text: "Loftið hér er á miðri leið milli Evrópu og Norður-Ameríku. Flugvélar mætast yfir landinu án þess að nokkur sjái.", source: "Landafræði", theme: .travel, subtheme: .farOff),
        Passage(text: "Á heiðskírum degi sést Snæfellsjökull frá Reykjavík, um hundrað kílómetra yfir flóann.", source: "Landafræði", theme: .travel, subtheme: .farOff),
        Passage(text: "Hillingar geta borið Grænland upp fyrir sjóndeildarhringinn svo að það sjáist af Vestfjörðum.", source: "Ljósfræði", theme: .travel, subtheme: .farOff),
        Passage(text: "Bréf milli Kaupmannahafnar og Íslands voru vikur á leiðinni og komu aðeins með skipum að sumri.", source: "Samgöngusaga", theme: .travel, subtheme: .farOff),
        Passage(text: "Næsta stjarna á eftir sólinni er svo langt undan að ljósið frá henni er fjögur ár á leiðinni hingað.", source: "Stjörnufræði", theme: .travel, subtheme: .farOff),

        // MARK: Meeting
        Passage(text: "Hvað er svo glatt sem góðra vina fundur, er gleðin skín á vonarhýrri brá?", source: "Jónas Hallgrímsson, Vísur Íslendinga", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Nú hittir vinur vin á grænu engi.", source: "Jónas Hallgrímsson, Hulduljóð", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Allir brosa á sama tungumáli.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Fundur merkir hvort tveggja, að finna og að hittast. Sama orðið gengur um hvorugt annað en hitt.", source: "Íslenska", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Sá á fund sem finnur.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Í réttum hittast þeir sem búa sitt hvorum megin við heiðina og sjást ekki þess á milli.", source: "Þjóðhættir", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Á göngustíg hér er heilsað þeim sem gengur á móti, líka þótt hvorugur þekki hinn.", source: "Íslenskir siðir", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Á sumardaginn fyrsta er sagt gleðilegt sumar við hvern sem verður á vegi manns.", source: "Íslenskir siðir", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Þegar hraun rennur í sjó rís gufustrókur sem sést langt að. Það er staðurinn þar sem tvennt mætist.", source: "Jarðfræði", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Tvær ár sem koma saman halda oft lit sínum lengi eftir mótin, hvor sínum megin í sama farvegi.", source: "Vatnafræði", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Á Þingvöllum komu menn úr öllum landsfjórðungum saman einu sinni á ári og riðu svo heim aftur.", source: "Saga", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Þar sem tveir skriðjöklar mætast myndast dökk grjótrák á milli þeirra. Hún heitir urðarrönd og sést alla leið niður.", source: "Jöklafræði", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Æ sér gjöf til gjalda.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Allar gjafir þiggja laun.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Betur sjá augu en auga.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Viðurgefendur og endurgefendur erust lengst vinir.", source: "Hávamál", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Æðarbóndinn ver varpið fyrir vargi og fær dúninn í staðinn. Hvorugt gengur án hins.", source: "Æðarrækt", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Í rótum smára búa bakteríur sem binda köfnunarefni. Plantan fæðir þær og þær fæða hana.", source: "Grasafræði", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Blómið hitnar af því að fylgja sólinni, og flugan sækir í hlýjuna og ber frjóið á milli.", source: "Grasafræði", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Kind ein á fjalli leitar uppi aðra. Féð rekur sig sjálft saman í hópa löngu áður en gengið er.", source: "Búfjárrækt", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Tveir hestar í haga standa á víxl hlið við hlið og bíta flugur hvor af öðrum.", source: "Dýrafræði", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Til að ferskeytla gangi upp þarf bæði rím og stuðla. Annað án hins er engin vísa.", source: "Bragfræði", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ær sem missir annað tvílembinginn tekur oft við lambi frá annarri, ef bóndinn ber lyktina á milli.", source: "Búfjárrækt", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Uppistaðan er strengd og ívafið gengur á milli. Hvorugur þráðurinn veit hvað hann er að verða.", source: "Vefnaður", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Elds er þörf þeim er inn er kominn og á kné kalinn.", source: "Hávamál", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Vatns er þörf þeim er til verðar kemur, þerru og þjóðlaðar.", source: "Hávamál", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Geði skaltu við þann blanda og gjöfum skipta, fara að finna oft.", source: "Hávamál", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Með hálfum hleif og með höllu keri fékk eg mér félaga.", source: "Hávamál", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Glöggt er gests augað.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Taka skal viljann fyrir verkið.", source: "Íslenskur málsháttur", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Takk fyrir síðast er kveðja sem snýr aftur á bak. Þakkað er fyrir síðustu samveru áður en byrjað er á nýrri.", source: "Íslenskir siðir", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Sæll og sæl duga bæði þegar komið er og þegar farið er. Sama orðið gildir í báða enda.", source: "Íslenska", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Gestum var fylgt úr hlaði og oft nokkurn spöl áleiðis. Heimferðin byrjaði í fylgd.", source: "Þjóðhættir", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ekki er þérað á íslensku. Sami háttur er hafður við alla, hvort sem menn þekkjast eða ekki.", source: "Íslenska", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Í heitum potti er talað við þann sem sest hjá. Það er hluti af því að setjast.", source: "Íslenskir siðir", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Góður dagur er boðinn en ekki óskaður. Á íslensku er kveðjan rétt fram eins og hún sé hlutur.", source: "Íslenska", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: Kinship
        Passage(text: "Líkur sækir líkan heim.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Sjaldan fellur eplið langt frá eikinni.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Íslendingabók geymir ættir nær allra landsmanna frá landnámi. Tveir sem hittast geta flett upp sameiginlegum forföður.", source: "Ættfræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Birkiskógur breiðist út með rótarskotum. Það sem lítur út eins og margar hríslur getur verið ein planta.", source: "Grasafræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Tvær greinar sem nuddast saman árum saman geta gróið í eina og skipst á safa upp frá því.", source: "Grasafræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Íslenska sauðkindin er sami stofn og kom með landnámsmönnum og hefur ekki blandast öðrum í þúsund ár.", source: "Búfjárrækt", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Íslenski hesturinn og norski lynghesturinn eru af einum stofni sem skildi að fyrir þúsund árum.", source: "Búfjárrækt", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Færeyska og íslenska eru svo náskyldar að lesa má aðra á bók þegar hin er kunn.", source: "Málfræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Systkini er orð yfir börn sömu foreldra án þess að kyn sé nefnt. Það er myndað af systur en nær yfir bæði.", source: "Íslenska", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Tvílembingar þekkja hvor annan á lykt og halda saman fram á haust.", source: "Búfjárrækt", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Þar sem tvær ár renna saman heita ármót. Neðan þeirra ber vatnið eitt nafn.", source: "Landafræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Í mosaþembu er engin stök jurt. Þéttleikinn heldur rakanum, og því lifir hún öll eða engin.", source: "Vistfræði", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Frændi er í rót sinni lýsingarháttur af sögn sem merkti að elska. Sama orð varð friend í ensku.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Sifjar merkir mægðir og skyldleika og er sama orð og fornenska sibb, sem merkti bæði frið og frændsemi.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Félagi er sá sem leggur fé sitt í lag með öðrum. Í orðinu sjálfu er sameignin.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Frændi nær hér yfir alla karlkyns ættingja aðra en föður, son og bróður. Orðið spannar miklu meira en enska cousin.", source: "Íslenska", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Sifjum er þá blandað, hver er segja ræður einum allan hug.", source: "Hávamál", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Maður er manns gaman.", source: "Hávamál", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Gaman er sama orð og game í ensku. Það merkti fyrst gleðina af því að vera með öðrum.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Hjón eru tveir sem eiga heimili saman. Hjú er eintalan og nær yfir hvern þann sem á heimilinu er.", source: "Íslenska", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Nágranni er sá sem býr nær. Granni einn og sér merkir aðeins þann sem er nálægur.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Fóstbræðralag var skyldleiki sem menn völdu sér. Fóstbróðir varð bróðir án þess að vera það.", source: "Saga", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Skyldleiki og skylda eru af einni rót: að vera einhverjum skyldur og að vera honum skyldugur.", source: "Orðsifjar", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Mjúk er móðurhöndin.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ber er hver að baki nema sér bróður eigi.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ástarhugir oftast saman rata.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Fátt segir af einum.", source: "Íslenskur málsháttur", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ungur var eg forðum, fór eg einn saman: þá varð eg villur vega.", source: "Hávamál", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Vin sínum skal maður vinur vera og gjalda gjöf við gjöf. Hlátur við hlátri skyli höldar taka.", source: "Hávamál", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Á kvöldvöku las einn upphátt meðan hinir kembdu og spunnu. Sagan var verk þeirra allra.", source: "Þjóðhættir", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Að kveðast á er að yrkja til skiptis, þar sem annar tekur upp þráðinn þar sem hinn sleppti honum.", source: "Bragfræði", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Tveir sem róa á sama báti verða að taka í árar á sama augnabliki, ella snýst hann í hring.", source: "Sjómál", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Lundinn heldur sama maka ár eftir ár og snýr aftur í sömu holu.", source: "Fuglafræði", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Hér búa færri en fjögur hundruð þúsund manns. Tveir sem hittast eiga oftast sameiginlegan kunningja.", source: "Mannfjöldi", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Í vikivaka héldust allir í hendur í hring og einn kvað fyrir hina.", source: "Þjóðhættir", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Samtal er sett saman úr sam og tali: að tala saman, ekki að tala til.", source: "Íslenska", theme: .kinship, subtheme: .twoPeople),

        // MARK: Peace
        Passage(text: "Hljóð er það sem heyrist, en hljóður merkir þögull, og að biðja sér hljóðs er að biðja um þögn.", source: "Íslenska", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Völuspá hefst á því að völvan biður sér hljóðs. Fyrsta orð kvæðisins er beiðni um þögn.", source: "Eddukvæði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Logn er af rót sem merkti bjart. Orðið er dregið af því hvernig kyrr sjór lítur út, ekki af því hvernig hann hljómar.", source: "Orðsifjar", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Fyrstu fjögur vindstigin heita logn, andvari, kul og gola. Fjögur nöfn á því sem varla heyrist.", source: "Veðurfræði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Hrossagaukurinn hneggjar með stélfjöðrunum en ekki með röddinni. Hljóðið verður til í loftinu milli þeirra.", source: "Fuglafræði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Leynist straumur í lygnu vatni.", source: "Íslenskur málsháttur", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Logndrífa er snjókoma í logni. Flygsurnar falla beint niður og ekkert heyrist.", source: "Veðurorð", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Nýfallinn snjór drekkur í sig hljóðið milli kristallanna. Landið verður hljóðlátara eftir fyrstu fönn.", source: "Hljóðfræði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ungt hraun er svo gropið að það endurkastar illa. Í hrauni er lítið um bergmál.", source: "Jarðfræði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Mosaþemba gefur eftir undir fæti og tekur af öll fótatök. Á Þingvöllum heyrist varla gengið.", source: "Vistfræði", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Næði merkir bæði ró og tóm. Að hafa næði er að hafa hvort tveggja, tímann og kyrrðina.", source: "Íslenska", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Oft má satt kyrrt liggja.", source: "Íslenskur málsháttur", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Grið er friður sem er veittur og tekur gildi um leið og hann er sagður. Griðastaður er staður þar sem enginn má hreyfa við manni.", source: "Lagamál", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Sátt og sættast eru af einni rót. Friður milli tveggja er á íslensku eitthvað sem er gert, ekki eitthvað sem gerist.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Friður, frjáls og frændi eru öll af sömu germönsku rót, þeirri sem merkti að elska og að telja til sinna.", source: "Orðsifjar", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Sá vægir sem vitið hefur meira.", source: "Íslenskur málsháttur", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Vopnahlé er vopn og hlé. Hlé merkir bæði hvíld og skjól, sama skjólið og skipið leitar í undan vindi.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Þinghelgi hét friðurinn sem lá yfir þingstaðnum meðan þing stóð. Að rjúfa hann var þyngra brot en sama verk annars staðar.", source: "Lagamál", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Tryggð merkir bæði traust og formlegan frið. Tryggðamál voru orðin sem sögð voru þegar sætt var gerð.", source: "Lagamál", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Friðland merkti áður land þar sem maður var óhultur. Nú merkir það land þar sem lífríkið er óhult.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Að ganga til náða er að leggjast til hvíldar. Náðir er fleirtöluorð sem lifir nær eingöngu í þessu sambandi.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Hlémegin heitir sú hlið fjalls sem vindurinn nær ekki til. Þar er hvorki rok né logn heldur skjól.", source: "Veðurfræði", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Sáttmáli er mál sem sátt er gerð með. Orðið gengur jafnt um samninga ríkja og samkomulag tveggja manna.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Frið er samið á íslensku, með sömu sögn og lag eða texti. Hann er verk sem einhver vann.", source: "Íslenska", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Kyrrt er hrauns á breiðum boga, blundar land í þráðri ró.", source: "Jónas Hallgrímsson, Fjallið Skjaldbreiður", theme: .peace, subtheme: .atEase),
        Passage(text: "Hægur er dúr á daggarnótt. Dreymi þig ljósið, sofðu rótt!", source: "Jónas Hallgrímsson, Hulduljóð", theme: .peace, subtheme: .atEase),
        Passage(text: "Frelsi er fé betra.", source: "Íslenskur málsháttur", theme: .peace, subtheme: .atEase),
        Passage(text: "Værð er ekki svefn. Værð er að vera vakandi og hafa ekkert sem rekur á eftir.", source: "Íslenska", theme: .peace, subtheme: .atEase),
        Passage(text: "Undu svo glaðir við sitt.", source: "Jónas Hallgrímsson, Ísland", theme: .peace, subtheme: .atEase),
        Passage(text: "Sögnin að una er skyld orðinu yndi. Að una við sitt er að láta sér nægja það sem maður hefur.", source: "Orðsifjar", theme: .peace, subtheme: .atEase),
        Passage(text: "Í heitum potti er setið kyrr. Sundlaugin er til að synda í, potturinn ekki.", source: "Íslenskir siðir", theme: .peace, subtheme: .atEase),
        Passage(text: "Þetta reddast er sagt þegar ekkert verður að gert í bili. Það er ekki spá heldur leyfi til að hætta að hugsa um það.", source: "Íslenskt orðatiltæki", theme: .peace, subtheme: .atEase),
        Passage(text: "Lognmolla er sett saman úr logni og mollu og lýsir degi sem er bæði kyrr og þungur.", source: "Veðurorð", theme: .peace, subtheme: .atEase),
        Passage(text: "Skjól er það sem stöðvar vind. Það var metið jafn mikils og útsýnið þegar bæjarstæði var valið.", source: "Þjóðhættir", theme: .peace, subtheme: .atEase),
        Passage(text: "Að slaka á er dregið af reipi. Það sem var strekkt fær að hanga.", source: "Íslenska", theme: .peace, subtheme: .atEase),
        Passage(text: "Sauðfé leggst niður og jórtrar þegar það er satt. Það er merkið um að ekkert sé að.", source: "Búfjárrækt", theme: .peace, subtheme: .atEase),
    ]
}
