import Foundation

/// The Maltese passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let maltese: [Passage] = [
        // MARK: - Beginnings
        Passage(text: "Inbiet: iż-żerriegħa tinfetaħ u l-ewwel għerq jinżel ’l isfel qabel ma jitla’ xejn ’il fuq. Dan il-pass isir darba biss.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Il-kelma Milied ġejja mill-Għarbi għat-twelid. Il-festa ġġorr isem l-att li jiftaħ kollox, mhux isem dak li ġara wara.", source: "Etimoloġija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Il-flieles ifaqqsu bis-saħħa ta’ sinna ċkejkna fuq il-munqar. Ftit jiem wara li joħorġu, dik is-sinna taqa’, għax ma tiswa għal xejn iżjed.", source: "Żooloġija", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Il-fjura tal-kappar tinfetaħ ma’ nżul ix-xemx u sa nofsinhar tal-għada tkun mitmuma. Tiftaħ darba, u ma terġax tingħalaq.", source: "Kappar", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ħafna żrieragħ selvaġġi jibqgħu taħt il-ħamrija bla ma jiċċaqilqu għal snin sħaħ, u jinbtu biss malli tinqaleb l-art u jmisshom id-dawl.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "L-eqdem kitba bil-Malti li waslet għandna hija poeżija ta’ nutar tas-seklu ħmistax, misjuba f’reġistru antik fl-1966.", source: "Storja tal-Ilsien Malti", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Il-fkieren tal-baħar ifaqqsu bil-lejl u jaqbdu lejn l-iżjed nokta mdawla fuq ix-xefaq. Dik il-mixja jagħmluha darba f’ħajjithom.", source: "Caretta caretta", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Iż-żerriegħa u ż-żriegħ jinkitbu bl-istess tliet konsonanti. Dak li tagħmel u dak li tħalli warajk huma l-istess kelma, imqiegħda mod ieħor.", source: "Għerq Semitiku", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "L-ewwel xita ta’ wara sajf twil ftit li xejn issaqqi: l-art tkun daqshekk iebsa li l-ilma jibqa’ għaddej minn fuqha. Il-ħarifa tibda bit-tieni waħda.", source: "Agrikoltura", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Il-bajda tal-ħuttafa toqgħod madwar ħmistax-il jum taħt ommha. Il-qoxra tinqasam minn ġewwa, u qatt minn barra.", source: "Hirundo rustica", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "L-ewwel telgħa tal-moħriet fuq għalqa hija l-unika waħda li ma jkollhiex ma’ xiex timxi. Kull waħda ta’ warajha timxi ma’ dik ta’ qabel.", source: "Biedja", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Fuq iż-żewġ naħat tal-pruwa tal-luzzu titpitter għajn. Id-dgħajsa toħroġ mill-port b’wiċċ li jħares ’il quddiem qabel ma jħares is-sajjied.", source: "Drawwa Maltija", theme: .beginnings, subtheme: .theFirstAct),

        Passage(text: "Bidu tajjeb nofs ix-xogħol.", source: "Qawl Malti", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Min jibda tajjeb għandu nofs it-triq.", source: "Qawl Malti", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kull bidu huwa qawwi.", source: "Qawl Malti", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Il-ġurnata minn filgħodu turik.", source: "Qawl Malti", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Iżra’ tajjeb u fil-waqt biex ma jibdielek qatt.", source: "Qawl Malti", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Min ibiddel l-imkien ibiddel il-vintura.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Fejn tmajt insib il-ġebel, sibt tafal merħi.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Meta titħawwel siġra taż-żebbuġ, il-post jintgħażel darba għal mitt sena. L-għeruq imorru fond wisq biex il-ħsieb jerġa’ jinbidel.", source: "Olea europaea", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Il-ħajt tas-sejjieħ jinbena bla tafal u bla siment. Il-forma tal-ewwel filliera tibqa’ tinħass sa fuq nett.", source: "Ħitan tar-raba’", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "L-artiklu Malti jinbidel skont l-ittra li tmiss miegħu: id-dar, ix-xemx, is-sliem, iż-żmien. L-ewwel ħoss ta’ kelma jgħid kif tissejjaħ.", source: "Grammatika Maltija", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Is-sena tal-bidwi Malti tibda f’Settembru u mhux f’Jannar, għax din taħdem mix-xita ’l quddiem u mhux min-numri.", source: "Kalendarju tar-raba’", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Il-Malti jinkiteb bl-alfabett Latin għalkemm hu lsien Semitiku. Dik l-għażla, li ttieħdet ilu ħafna, tispjega kif tidher kull kelma llum.", source: "Ortografija", theme: .beginnings, subtheme: .whatAStartSettles),

        Passage(text: "Fil-Malti l-ħafna jiġi qabel il-wieħed: minn ward toħroġ warda, minn ħaxix toħroġ ħaxixa. Il-waħda hija dik li jkollha xi ħaġa miżjuda magħha.", source: "Grammatika Maltija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Mill-għerq k-t-b joħorġu kiteb, ktieb, kitba, kittieb u miktub. Tliet konsonanti jżommu familja sħiħa ta’ kliem.", source: "Għerq Semitiku", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Bil-qatra l-qatra timtela l-ġarra.", source: "Qawl Malti", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Bil-paċenzja u ż-żejt, iljunfant ħexa nemla.", source: "Qawl Malti", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Iż-żerriegħa tal-ħarrub hija tant indaqs bejn waħda u oħra li n-negozjanti tal-qedem użawha bħala użin. Minnha ħareġ il-karat.", source: "Ceratonia siliqua", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kappar li jinqala’ mix-xaqq ta’ ħajt jibda b’żerriegħa mħollija minn għasfur. Wara ftit snin ikun qed iżomm il-ġebel bl-għeruq tiegħu.", source: "Botanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Il-blat ta’ dawn il-gżejjer huwa magħmul minn frak ta’ ħlejjaq tal-baħar iżgħar minn ras ta’ labra. Kollox mibni fuq dak il-frak.", source: "Ġeoloġija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Fjura waħda tas-sagħtar tagħti daqsxejn ta’ ħlewwa. Ix-xagħri kollu flimkien jagħti l-għasel li dawn il-gżejjer ilhom magħrufa għalih.", source: "Thymbra capitata", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Il-bebbuxu tal-blat jibda daqs żerriegħa tal-ġulġlien. Il-qoxra tikber miegħu dawra dawra, u l-ebda dawra ma titħassar wara.", source: "Malakoloġija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kolonja sħiħa ta’ nemel tibda minn reġina waħda li tingħalaq għaliha taħt l-art sa ma jfaqqsu l-ewwel uliedha.", source: "Entomoloġija", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Il-ġebla tal-franka tinqata’ ratba biżżejjed biex taqtagħha b’sikkina, u tibbies fl-arja. Il-bini kollu tal-gżira ħareġ minn dik il-bidla.", source: "Ġebla tal-franka", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Ħabba fil-Malti hija żerriegħa, u kienet ukoll l-iżgħar munita li kien hemm. Meta xi ħaġa ma tiswiex ħabba, l-użin użat huwa dak ta’ żerriegħa waħda.", source: "Kejl antik", theme: .beginnings, subtheme: .smallToLarge),

        // MARK: - Waiting
        Passage(text: "Rqad taż-żerriegħa: meta ż-żerriegħa ma tinbitx għalkemm kollox lest għaliha. Iż-żamma ġejja minn ġewwa, u tinħall biss meta jinbidel xi ħaġa.", source: "Botanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Fil-Malti s-sabar huwa l-paċenzja, u s-sabbara hija l-pjanta li ddum snin sħaħ qabel tarmi zokk wieħed tal-fjuri. Iż-żewġ kelmiet ġejjin mill-istess għerq.", source: "Etimoloġija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Is-siġra tal-ħarrub tieħu snin twal qabel ma tagħti l-ewwel frott, u mbagħad tibqa’ tagħti għal iżjed minn mitt sena wara.", source: "Ceratonia siliqua", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Fix-xagħri hemm basla kbira li tibqa’ moħbija s-sajf kollu, tarmi z-zokk tal-fjuri f’Awwissu, u toħroġ il-weraq biss ferm wara.", source: "Drimia maritima", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Il-werżieq iqatta’ snin taħt l-art bħala larva u ftit ġimgħat biss fuq is-siġra. Il-ħoss li tisma’ fis-sajf ġej mill-aħħar biċċa ta’ ħajja twila.", source: "Entomoloġija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Fil-Furjana hemm ġibjuni tal-qamħ maqtugħin fil-blat u magħluqin b’ġebla waħda tonda. Il-qamħ kien jinżamm hemm ġew għal snin sħaħ.", source: "Il-Fosos", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ix-xita li tinżel fuq il-blat tal-gżira ma tasalx fil-qiegħ tal-ilma ħelu qabel ma jgħaddu s-snin. Il-bir jixrob minn xita li ħadd ma jiftakar.", source: "Idroloġija", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Il-fekruna tal-art tinżel taħt il-ħaxix f’Novembru u ma toħroġx qabel Marzu. F’dak iż-żmien qalbha tħabbat bil-bosta inqas mis-soltu.", source: "Testudo hermanni", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Il-Ġellewża u l-Ġirgentina huma żewġ dwieli li ma jitkabbrux barra minn dawn il-gżejjer. L-għeneb jinqata’ f’Awwissu, u l-inbid ma jinxtorobx dik is-sena.", source: "Vitikultura", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Il-bir tar-razzett jimtela bix-xita tax-xitwa u jinżamm magħluq. Min jiftħu kmieni wisq isib ruħu bla ilma f’Awwissu.", source: "Biedja", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Iż-żejt taż-żebbuġ ġdid ikun morr u mċajpar. Irid xhur bilwieqfa qabel ma jsaffi u l-frak jinżel waħdu fil-qiegħ.", source: "Żejt taż-żebbuġ", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Il-ġebla, malli tinqata’, titħalla fil-barriera qabel ma tintuża. Trid tibbies fl-arja qabel ma titla’ fuq ħajt, u dan ma jitgħaġġilx.", source: "Bini tal-ġebel", theme: .waiting, subtheme: .heldBack),

        Passage(text: "Min jistenna jithenna.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Bis-sabar u biż-żmien kollox jasal fit-tmiem.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Iż-żmien isajjar il-bajtar.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Iż-żmien lil ħadd ma jkellem u jgħaddi bla ma jsellem.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Wara ż-żriegħ jiġi l-inbiet u wara dan il-ħsad.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Min hu mgħaġġel jaqbillu jistenna.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "F’Santa Luċija l-jiem jitwalu b’pass ta’ tarbija.", source: "Qawl Malti", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "It-tempji ta’ Ġgantija f’Għawdex twaqqfu qabel il-piramidi u qabel Stonehenge. Ilhom wieqfa madwar ħamest elef u sitt mitt sena.", source: "Arkeoloġija", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Fil-Bidnija hemm siġar taż-żebbuġ li l-analiżi tqiegħed fi żmien ir-Rumani, u li kull sena għadhom jagħtu l-frott.", source: "Olea europaea", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Iċ-ċirku fl-injam ta’ siġra tax-xagħri jkun daqshekk irqiq li siġra ta’ mitt sena tista’ tkun żgħira daqs waħda ta’ tletin. Id-daqs ma jgħid xejn.", source: "Dendrokronoloġija", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Il-blat tal-globiġerina ta’ Malta ħa madwar għoxrin miljun sena biex ingħaqad, filwaqt li barriera tieħdu f’ġimgħat.", source: "Ġeoloġija", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Il-ġbejna friska ssir f’jum. Il-ġbejna tal-bżar trid tinxef fix-xibka ġimgħat sħaħ, u sadanittant ma jkun hemm xejn xi tara.", source: "Ġobon Malti", theme: .waiting, subtheme: .theLongCount),

        Passage(text: "Meta tara l-ħuttaf tkun ġejja x-xita.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Meta l-gru jgħaddi fil-għoli, ikun ġej il-maltemp.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Il-kwiekeb tegħmeż għandna r-riħ.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Meta fl-art jidħol il-gawwi, stenna riħ qawwi.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ħmura ta’ filgħodu lesti ż-żwiemel fejn joqogħdu.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Raff tas-sħab ragħad u beraq stenna.", source: "Qawl Malti", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Il-merill joqgħod fuq ponta ta’ blata u jkanta minn hemm fuq. Jibqa’ fl-istess post staġun sħiħ, u jara aktar milli jgħid.", source: "Monticola solitarius", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Min jistenna d-dgħajsa fil-port jara l-qlugħ qabel l-iskaf, għax il-wiċċ tal-baħar jitgħawweġ u jaħbi kollox ħlief l-ogħla biċċa.", source: "Ġeografija", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Il-fanal ta’ Ġordan f’Għawdex idur bla ma jieqaf. Min hu barra fuq il-baħar ma jgħoddx id-dawl imma l-waqfiet bejniethom.", source: "Navigazzjoni", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Min irabbi n-naħal jaf li x-xehda tinbena waħidha. Ix-xogħol tiegħu huwa li joqgħod iħares u ma jindaħalx qabel il-waqt.", source: "Trobbija tan-naħal", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Fil-passa tar-rebbiegħa, l-għasafar jinżlu fuq l-istess ftit siġar kull sena. Min irid jarahom ma jmurx ifittixhom; joqgħod taħt is-siġra.", source: "Ornitoloġija", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ir-riħ f’Malta għandu tmien ismijiet: Tramuntana, Grigal, Lvant, Xlokk, Nofsinhar, Lbiċ, Punent u Majjistral. Min joqgħod jara jkun jaf minn liema ġej.", source: "Ir-roża tal-irjieħ", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: - Renewal
        Passage(text: "U hekk waqgħet hi, imrammti! W erġa’ ibniha!", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Is-silla tinqata’ iżjed minn darba fis-sena u terġa’ tarmi kull darba. L-għeruq tagħha jħallu l-ħamrija aħjar milli sabuha.", source: "Hedysarum coronarium", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Żebbuġa maqtugħa mill-qiegħ terġa’ tarmi mill-għerq. Mill-istess siġra jistgħu joħorġu zkuk ġodda mitt sena wara.", source: "Olea europaea", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "It-tiżbir tad-dielja jsir fix-xitwa, meta d-dielja tidher mejta u ma jkun fadlilha ebda werqa. Iżjed ma tinqata’, iżjed tagħti.", source: "Vitikultura", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Il-ħajt tas-sejjieħ li jinbena mill-ġdid jitla’ bl-istess ġebel li kien fih. Ma jiżdied xejn; jinqaleb biss l-ordni.", source: "Ħitan tar-raba’", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Il-luzzu jinżebagħ mill-ġdid kull sena bl-istess kuluri, u l-għajn fuq il-pruwa tinqata’ ġdida fuq dik ta’ qabilha.", source: "Drawwa Maltija", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Bebbuxu li tinkiser il-qoxra tiegħu jsewwiha minn ġewwa bil-ġir li jiġbed mill-blat li jimxi fuqu. Il-marka tibqa’ tidher.", source: "Malakoloġija", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Il-gremxula tal-gżejjer tħalli denbha f’id min jaqbadha u trabbi ieħor. Dak li jitla’ mhux l-istess denb, u jidher li mhuwiex.", source: "Podarcis filfolensis", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Wara nar fix-xagħri, l-ewwel li terġa’ titla’ hija l-basla li tkun baqgħet fond taħt l-art. Il-fjuri jidhru qabel il-ħdura.", source: "Ekoloġija", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Blata li tinqata’ mill-mewġ tagħti wiċċ ġdid u niexef. Fi ftit staġuni dan jimtela bl-istess ħlejjaq li kienu fuq dak ta’ qabel.", source: "Bijoloġija tal-baħar", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Is-sagħtar li jinqata’ għall-ġbir jerġa’ jitla’ eħxen fis-sena ta’ wara. Il-ħsad tiegħu huwa wkoll it-tiżbir tiegħu.", source: "Thymbra capitata", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Il-kannizzata tas-sajd tinħall fl-aħħar tal-istaġun u l-injam tagħha jinżamm biex jerġa’ jintrabat sena wara. L-istess ħabel, sena oħra.", source: "Sajd", theme: .renewal, subtheme: .cutAndComeAgain),

        Passage(text: "Ir-rebbiegħa hi s-sebħ tas-sena, is-sajf nofsinhar, il-ħarifa l-Għarb u x-xitwa l-lejl.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Is-snin bħall-aħwa, ma jixxibhux.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Wara l-maltemp jiġi l-bnazzi.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Min jiżra’ fin-niket jaħsad fil-ferħ.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Is-siġra ma tagħmilx frott barra minn żmienha.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Il-ħdura u l-ward huma ż-żina tal-art.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Il-Milied bil-kappell, l-Għid bil-mantar, in-nies tiekol tajjeb u l-bhejjem tixtarr aħjar.", source: "Qawl Malti", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "L-erba’ staġuni għandhom ismijiet Semitiċi. Ix-xitwa hija l-istaġun tax-xita, u l-ħarifa dak li fih jinqata’ l-frott mis-siġra.", source: "Etimoloġija", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ix-xhur kollha ġejjin mit-Taljan, imma l-istaġuni le. Is-sena titqassam bi kliem antik u titkejjel bi kliem misluf.", source: "Kalendarju", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "L-Imnarja taqa’ fid-29 ta’ Ġunju, meta l-qamħ ikun diġà maħsud. Issir fil-Buskett, u l-kant idum sa ma jisbaħ.", source: "L-Imnarja", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Is-silla ħamra timla l-għelieqi f’Marzu u tinqata’ f’Mejju. L-istess biċċa raba’ tinbidel mill-aħmar għall-isfar fi ftit ġimgħat.", source: "Biedja", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Malli tinżel l-ewwel xita, għelieqi li jkunu ilhom xhur trab jiħdru f’ġimgħa. F’dawn il-gżejjer il-ħdura tiġi bil-bard u mhux bis-sħana.", source: "Meteoroloġija", theme: .renewal, subtheme: .theTurningYear),

        Passage(text: "L-irqad jagħmel il-ħmira.", source: "Qawl Malti", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Il-ħniena kienet u tkun, inkella m’hemmx iżjed dinja.", source: "Qawl Malti", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Il-verb sewwa jfisser fl-istess ħin li ssewwi ħaġa miksura u li tagħmel il-ħaġa sew. It-tiswija u s-sewwa huma l-istess kelma.", source: "Etimoloġija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ir-restawr tal-ġebel isir billi titneħħa l-biċċa mrekkna u titqiegħed waħda mnaqqxa apposta biex tidħol eżatt f’postha. Il-ħajt jibqa’ l-istess ħajt.", source: "Restawr", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Għadma miksura tissewwa b’għadma ġdida eħxen minn dik li kienet hemm qabel. Il-post tal-ksur isir l-iżjed wieħed b’saħħtu.", source: "Anatomija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Wara maltempata x-xtut jimtlew bil-weraq mejjet tal-posidonja. Dak mhuwiex ħmieġ: iżżomm ir-ramel f’postu sax-xitwa ta’ wara.", source: "Posidonia oceanica", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "In-naħal isewwi xehda mkissra fl-istess sura eżatta li kellha, mingħajr ma jkejjel u mingħajr ma jara d-disinn li qed jimxi fuqu.", source: "Trobbija tan-naħal", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Il-ġilda tissewwa b’ordni: l-ewwel jieqaf id-demm, imbagħad tingħalaq il-ferita, u fl-aħħar jerġa’ jitla’ l-kulur. It-tielet pass huwa l-itwal.", source: "Anatomija", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Il-ħalib li jaqbad isir ġbejna u l-ilma li jibqa’ jissejjaħ xorrox. Anke dak li jibqa’ għandu isem tiegħu.", source: "Ġobon Malti", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Il-blat jixrob ix-xita u jerġa’ jagħtiha lura f’nixxiegħa xhur wara. Kull post f’Malta li jibda bil-kelma Għajn ifakkar waħda minnhom.", source: "Toponomastika", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Is-siġra tal-għargħar, meta tinqata’, tarmi reżina li tagħlaq il-qatgħa waħidha u tibbies fuqha bħal għata.", source: "Tetraclinis articulata", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Meta tinżel ix-xita fuq għalqa maħruta, il-ħamrija titla’ mill-ġdid fuq wiċċ il-blat u terġa’ tinżamm fuqu mill-ħitan tal-ġenb.", source: "Konservazzjoni tar-raba’", theme: .renewal, subtheme: .madeWhole),

        // MARK: - Light
        Passage(text: "Żerniq: id-dawl li jitla’ qabel ma titla’ x-xemx. Il-kelma hija Semitika u ma tintużax għall-inżul; għal dak hemm kelma oħra.", source: "Malti", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Għabex: id-dawl ta’ wara nżul ix-xemx, meta l-affarijiet jidhru imma jitilfu l-kulur. La huwa dawl u lanqas dlam, u għandu isem tiegħu.", source: "Malti", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Xefaq: il-linja fejn jispiċċa l-baħar. Il-kelma ġejja mill-istess għerq bħall-ħmura li tibqa’ fis-sema wara li tinżel ix-xemx.", source: "Etimoloġija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "F’Sant’Andrija l-jiem jiqsaru b’pass ta’ tarbija.", source: "Qawl Malti", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Aringa filgħodu deheb, aringa f’nofsinhar fidda, aringa filgħaxija ram.", source: "Qawl Malti", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "F’Ġunju x-xemx tinżel wara t-tmienja u f’Diċembru qabel il-ħamsa. Hawn isfel il-lejl jaqa’ malajr wara, f’kull staġun.", source: "Astronomija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ir-rondun idur fis-sema fl-aħħar dawl tal-jum u jibqa’ jtir fil-għoli l-lejl kollu. Jorqod bla ma jinżel.", source: "Apus apus", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Fid-drawwa Maltija l-jum jibda bil-lejl ta’ qabel: lejlet il-festa tiġi qabel il-festa, u l-akbar lejl tas-sena huwa dak tal-erbgħa u għoxrin.", source: "Drawwa Maltija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Id-dlam ma jaqax f’daqqa: bejn nżul ix-xemx u l-lejl sħiħ hemm tliet gradi ta’ għabex, u n-navigaturi jħaddmu t-tieni wieħed biss.", source: "Navigazzjoni", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Il-qamar jitla’ madwar ħamsin minuta iżjed tard kull lejl. Min jistennieh fl-istess ħin ma jsibux darbtejn wara xulxin.", source: "Astronomija", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Il-Lvant u l-Punent huma fl-istess ħin żewġ naħat tas-sema u żewġ irjieħ. Fil-Malti l-post minn fejn jiġi d-dawl u dak minn fejn jiġi r-riħ għandhom l-istess isem.", source: "Ir-roża tal-irjieħ", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Il-ġebla tal-franka tibda l-ġurnata bajda u tispiċċaha lewn l-għasel. Hija l-istess ġebla; huwa l-anglu li nbidel.", source: "Ġebla tal-franka", theme: .light, subtheme: .theEdgesOfTheDay),

        Passage(text: "Fit-tempju t’isfel tal-Imnajdra, fl-ekwinozju x-xemx tidħol dritt fuq l-assi tal-bieb; fis-solstizji tolqot it-truf tal-ġebel tal-ġenb.", source: "Arkeoastronomija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Meta tidher il-qawsalla waqt il-maltemp ta’ filgħodu turi xita; ta’ filgħaxija bnazzi.", source: "Qawl Malti", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Iżra’ u laqqam f’qamar xiħ.", source: "Qawl Malti", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Qamar rieqed baħar imqajjem; qamar wieqaf baħar bnazzi.", source: "Qawl Malti", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Meta x-xemx tinżel fl-ixkora turi l-maltemp.", source: "Qawl Malti", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Fejn ix-xemx ma turix ma ssaħħanx.", source: "Qawl Malti", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Meta r-riħ ikun mix-Xlokk, ix-xemx tidher ħamra u l-arja mċajpra. It-trab li jagħmilha hekk ikun ġie mid-deżert fi ftit jiem.", source: "Meteoroloġija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "In-naħal jara dawl li aħna ma narawx. Fuq il-petali ta’ ħafna fjuri hemm marki li jidhru biss fl-ultravjola, u dawk huma t-triq lejn ġewwa.", source: "Entomoloġija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Il-lampara tiġbed il-ħut bid-dawl, iżda l-ħut ma jiġix għad-dawl innifsu. Jiġi għal dak li d-dawl ikun ġabar qablu.", source: "Sajd", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Il-kwiekeb jidhru jteptpu meta l-arja tkun taħdem; il-pjaneti ma jteptpux. Dik il-ferqa waħidha tgħid liema hi liema.", source: "Astronomija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Il-merill ikanta l-iżjed fl-ewwel dawl u fl-aħħar wieħed. Min irid jgħoddhom fil-wied joqgħod għal dawk iż-żewġ ħinijiet u mhux għall-oħrajn.", source: "Ornitoloġija", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Il-bidwi jħares lejn is-sħab u mhux lejn is-sema: sħab bit-truf ħorox iġib ir-riħ, u sħab ċatt ma jġib xejn ħlief dell.", source: "Meteoroloġija", theme: .light, subtheme: .readingTheLight),

        Passage(text: "Ix-xemx titla’ u tinżel għal kulħadd.", source: "Qawl Malti", theme: .light, subtheme: .lightItself),
        Passage(text: "Ix-xemx ma titgħattiex bl-għarbiel.", source: "Qawl Malti", theme: .light, subtheme: .lightItself),
        Passage(text: "Daħqa bżonjuża daqs ix-xemx.", source: "Qawl Malti", theme: .light, subtheme: .lightItself),
        Passage(text: "Ix-xemx liżar l-art.", source: "Qawl Malti", theme: .light, subtheme: .lightItself),
        Passage(text: "Fil-Malti hemm dawl u hemm dija. Id-dawl jiġi minn xi mkien; id-dija hija l-ħaġa nnifisha meta tkun qiegħda tiddi.", source: "Malti", theme: .light, subtheme: .lightItself),
        Passage(text: "Fl-ilsna Semitiċi kollha x-xemx hija femminili u l-qamar maskil. Il-Malti żamm dik il-qasma anke wara elf sena ta’ ġirien Latini.", source: "Grammatika Maltija", theme: .light, subtheme: .lightItself),
        Passage(text: "Id-dawl li jitlaq mix-xemx jasal fuq dawn il-gżejjer tmien minuti wara. Kull xemx li tara hija dik ta’ ftit qabel.", source: "Fiżika", theme: .light, subtheme: .lightItself),
        Passage(text: "Il-posidonja tikber biss sakemm jasal id-dawl. Taħt dik il-linja l-qiegħ jibqa’ ramel, u l-linja tinbidel skont kemm ikun ċar il-baħar.", source: "Bijoloġija tal-baħar", theme: .light, subtheme: .lightItself),
        Passage(text: "Fil-logħob tan-nar kull kulur ġej minn melħ ieħor: ir-ram jagħti l-aħdar, l-istronzju l-aħmar, u l-ħadid jagħti d-deheb.", source: "Kimika", theme: .light, subtheme: .lightItself),
        Passage(text: "Xi lejli tas-sajf il-baħar jixgħel blu meta tqalleb l-ilma bl-idejn. Dak id-dawl ġej minn ħlejjaq iżgħar minn granell ta’ ramel.", source: "Bijoluminexxenza", theme: .light, subtheme: .lightItself),
        Passage(text: "Id-dawl abjad huwa l-kuluri kollha ma’ xulxin. Il-qawsalla ma żżid xejn magħhom: taqsam biss dak li kien hemm minn dejjem.", source: "Ottika", theme: .light, subtheme: .lightItself),
        Passage(text: "Il-ġebel tal-gżira jixrob is-sħana tal-jum u jerġa’ jagħtiha lura bil-lejl. Ħajt jibqa’ jsaħħan sigħat wara li tinżel ix-xemx.", source: "Fiżika", theme: .light, subtheme: .lightItself),

        // MARK: - Pattern
        Passage(text: "Il-Malti għandu għadd għat-tnejn biss: mhux żewġ jiem imma jumejn, mhux żewġ sigħat imma sagħtejn. Bejn wieħed u ħafna hemm forma tagħha.", source: "Grammatika Maltija", theme: .pattern, subtheme: .counted),
        Passage(text: "Il-partijiet tal-ġisem li jiġu bil-koppja jieħdu dejjem dik il-forma: għajnejn, widnejn, idejn, riġlejn. Il-plural tagħhom huwa n-numru tal-par.", source: "Grammatika Maltija", theme: .pattern, subtheme: .counted),
        Passage(text: "Kelmtejn ma jfissirx żewġ kelmiet imma taħdita qasira. In-numru tnejn intuża biex ifisser ftit, u baqa’ jfisserha.", source: "Malti", theme: .pattern, subtheme: .counted),
        Passage(text: "Erba’ għajnejn aħjar minn tnejn.", source: "Qawl Malti", theme: .pattern, subtheme: .counted),
        Passage(text: "Ftehima bejn tnejn isseħħ f’jumejn, bejn tlieta tieħu xahrejn.", source: "Qawl Malti", theme: .pattern, subtheme: .counted),
        Passage(text: "Fejn jieklu erbgħa jieklu ħamsa.", source: "Qawl Malti", theme: .pattern, subtheme: .counted),
        Passage(text: "Is-salib li ġie mal-Ordni għandu erba’ dirgħajn u tmien ponot. It-tmienja jitqiesu bħala l-beatitudnijiet, u wkoll bħala l-għadd tal-lingwi tal-Ordni.", source: "Storja ta’ Malta", theme: .pattern, subtheme: .counted),
        Passage(text: "Il-lira Maltija kienet maqsuma f’mitt ċenteżmu u f’elf mil. Kien hemm munita żgħira daqs wieħed minn elf.", source: "Munita antika", theme: .pattern, subtheme: .counted),
        Passage(text: "It-tomna hija l-kejl tal-art, madwar elf u mija u erbgħa u għoxrin metru kwadru. Ir-raba’ għadu jitkellem biha sal-lum.", source: "Kejl tar-raba’", theme: .pattern, subtheme: .counted),
        Passage(text: "Il-qasba, il-kejl antik tat-tul, hija ftit iżjed minn żewġ metri. Il-qisien tal-għelieqi qodma nkitbu kollha biha.", source: "Kejl antik", theme: .pattern, subtheme: .counted),
        Passage(text: "In-naħal jibni ċ-ċelel b’sitt ġnub. Minn fost il-forom li jimlew wiċċ bla ma jħallu xaqq, dik hija l-waħda li tonfoq l-inqas xemgħa.", source: "Ġeometrija", theme: .pattern, subtheme: .counted),
        Passage(text: "Il-bidwi ma jgħoddx ix-xhur imma l-festi: minn San Mikiel għal San Martin, u minn San Martin sal-Milied. Il-kejl tas-sena huwa lista ta’ ismijiet.", source: "Kalendarju tar-raba’", theme: .pattern, subtheme: .counted),

        Passage(text: "Il-ħajt tas-sejjieħ jinbena bla tafal: kull ġebla titqiegħed fejn il-ġenb tagħha jaqbel ma’ ġenb ieħor. It-toqol waħdu jżommu wieqaf.", source: "Ħitan tar-raba’", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ix-xquq f’ħajt tas-sejjieħ mhumiex żball. Iħallu l-ilma u r-riħ jgħaddu, u għalhekk jibqa’ wieqaf fejn ħajt magħluq jaqa’.", source: "Ħitan tar-raba’", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-ħnejja żżomm għax kull ġebla timbotta lil ta’ maġenbha. Neħħi waħda u jaqgħu kollha; ħallihom kollha u ma taqa’ ebda waħda.", source: "Bini tal-ġebel", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-plural ħafna drabi ma jiżdiedx mat-tarf tal-kelma imma jinbena minn ġewwa: ktieb isir kotba, belt issir bliet, ħajt isir ħitan.", source: "Grammatika Maltija", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Iż-żewġ nofsijiet ta’ qoxra ta’ maskla jagħlqu eżatt fuq xulxin u fuq ebda oħra. L-ebda waħda ma taqbel ma’ dik ta’ ħaddieħor.", source: "Malakoloġija", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "It-tul ta’ ċerti fjuri u t-tul tal-ħalq tal-insett li jżurhom jaqblu bejniethom. Fjura fonda trid insett twil, u l-oħrajn jibqgħu barra.", source: "Bijoloġija", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Fil-bini megalitiku ta’ dawn il-gżejjer, il-ġebel il-kbir jinżamm wieqaf b’ġebel iżgħar imdaħħal madwaru. Iż-żgħir iżomm il-kbir.", source: "Arkeoloġija", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-ftira tinħadem b’toqba f’nofsha biex is-sħana tasal kullimkien fl-istess ħin. Il-forma tagħha hija parti mit-tisjir u mhux żina.", source: "Ħobż Malti", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-luzzu jinbena b’tavlar imqiegħed wieħed ma’ ieħor. Il-fetħa li tibqa’ bejniethom tingħalaq waħidha malli d-dgħajsa tinżel l-ilma.", source: "Bini tad-dgħajjes", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-Malti jġib flimkien grammatika Semitika ma’ kliem Sqalli u Ingliż. Sentenza waħda tista’ ġġorr tliet familji ta’ lsien bla ma tinqasam.", source: "Lingwistika", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ir-raba’ tal-gżejjer huwa maqsum f’għelieqi żgħar imdawrin bil-ħitan. Minn fuq, il-pajsaġġ jidher bħal ħaġa waħda mfarrka f’biċċiet li jmissu.", source: "Pajsaġġ", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Il-blat jinqata’ f’saffi ċatti wieħed fuq l-ieħor. Il-bini tal-qedem imxa ma’ dawk is-saffi u qatt ma qatagħhom bin-nofs.", source: "Ġeoloġija", theme: .pattern, subtheme: .fittedTogether),

        Passage(text: "L-għerf ma fihx tarf.", source: "Qawl Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Qamħa mimlija rasha mbaxxija.", source: "Qawl Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kif tkejjel ikejluk.", source: "Qawl Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "L-aħjar triq tan-nofs.", source: "Qawl Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Il-kliem jinbena minn għeruq ta’ tliet konsonanti mimlijin bil-vokali. Il-konsonanti jġorru t-tifsira, u l-vokali jġorru s-sura.", source: "Għerq Semitiku", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Il-verb jgħid min qed jagħmel il-ħaġa bla ma tissemma persuna: ktibt, kiteb, ktibna. Il-kelma waħidha biżżejjed biex tkun sentenza.", source: "Grammatika Maltija", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Fil-preżent il-Malti ma jġorrx il-verb ikun: ma tgħidx jien inkun hawn, imma jien hawn. In-nuqqas huwa parti mir-regola u mhux żball.", source: "Grammatika Maltija", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "M’hemmx verb wieħed li jfisser li għandek. Il-pussess jingħad bil-kelma għand, li tfisser ħdejn: dak li għandek huwa dak li qiegħed maġenbek.", source: "Grammatika Maltija", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "L-alfabett Malti għandu tletin ittra. Tnejn minnhom, għ u ie, jinkitbu b’żewġ sinjali iżda jgħoddu bħala ittra waħda.", source: "Ortografija", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Nofsinhar huwa fl-istess ħin nofs il-jum u n-naħa t’isfel tas-sema. Il-ħin u l-post jinqasmu bl-istess kelma.", source: "Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Il-kitba tal-Malti nqatgħet fl-1924 minn għaqda ta’ kittieba, u l-liġi ħaditha fl-1934. Qabel dakinhar kull min kiteb kiteb kif deherlu.", source: "Storja tal-Ilsien Malti", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Fil-Malti l-aġġettiv jimxi wara n-nom u jaqbel miegħu: dar kbira, ħajt twil, ġebla ħamra. Il-ħaġa tissemma qabel dak li jingħad fuqha.", source: "Grammatika Maltija", theme: .pattern, subtheme: .orderNamed),

        // MARK: - Ground
        Passage(text: "Hemm art bajda, w hemm art sewda u ħamra.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Għaliex l-iradi għal kull xiber sura.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ħamrija: il-kelma ġġorr l-istess għerq bħal aħmar. L-art ta’ dawn il-gżejjer hija ħamra, u ssemmiet għal dak u għal xejn iżjed.", source: "Etimoloġija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Fir-raba’ ħamri iżra’ kmieni u mwaħħar fil-bajjad.", source: "Qawl Malti", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Il-borma ma ssirx mingħajr nar, lanqas l-art tagħti mingħajr bżar.", source: "Qawl Malti", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "L-art tagħti kemm tagħmel magħha; ġid, hena u fuq kollox is-saħħa.", source: "Qawl Malti", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Jekk ma tagħtix l-art, lanqas ma jagħti l-baħar.", source: "Qawl Malti", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "F’ħafna għelieqi mtarrġa l-ħamrija nġabret bl-idejn u tqiegħdet fuq il-blat wara ħajt. Ma kinitx hemm; twasslet hemm.", source: "Biedja", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Taħt is-saff ta’ fuq hemm tafal blu li ma jħallix l-ilma jgħaddi. Fejn jispiċċa dak it-tafal, l-ilma joħroġ f’għajn.", source: "Ġeoloġija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Il-blat tal-globiġerina jixrob l-ilma bħal sponża u jerġa’ jagħtih lill-għeruq bil-mod. Ir-raba’ jixrob mill-ġebla ta’ taħtu.", source: "Ġeoloġija", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Iċ-ċentimetru ta’ ħamrija jieħu mijiet ta’ snin biex jinbena, u ġurnata xita qawwija tista’ tieħdu lejn il-baħar.", source: "Konservazzjoni tar-raba’", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ir-raba’ jissejjaħ bil-kulur tiegħu: il-ħamri u l-bajjad. Il-bidwi ma jgħidlekx x’fih l-art, jgħidlek biss x’lewn hi.", source: "Biedja", theme: .ground, subtheme: .theSoilItself),

        Passage(text: "Kull għasfur għandu l-bejta tiegħu.", source: "Qawl Malti", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ma jistrieħx il-bniedem ħlief f’daru.", source: "Qawl Malti", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Bejta li tgħajjex fiha dellilha u sewwiha.", source: "Qawl Malti", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ħafna rħula jibdew b’Ħal, li hija l-kelma raħal imqassra: Ħal Lija, Ħal Qormi, Ħal Safi. L-isem jgħid x’inhu l-post qabel ma jgħid liema.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Il-belt kapitali ssemmiet għall-bniedem li waqqafha, imma n-nies isejħulha l-Belt u xejn iżjed. Waħda biss ma teħtieġx isem.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Marsa hija l-kelma antika għal post fejn tirmi l-ankra. Marsaxlokk tfisser il-marsa tax-Xlokk, jiġifieri l-port li jħares lejn dak ir-riħ.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Wied huwa qiegħ niexef li jimtela biss bix-xita. Ħafna mill-ismijiet ta’ ġewwa jibdew bih: Wied il-Għasel, Wied iż-Żurrieq, Wied Qirda.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Għajn hija fl-istess ħin l-għajn tal-wiċċ u n-nixxiegħa tal-ilma. Iż-żewġ affarijiet jinfetħu, u l-lingwa ma tifridhomx.", source: "Malti", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "L-Imdina u r-Rabat huma żewġ ismijiet li jgħidu x’inhuma: il-belt magħluqa bis-swar, u dak li joqgħod barra l-ħajt tagħha.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "L-isem Għawdex ġej mill-isem antik li kellha l-gżira sew qabel il-Malti. Kull min għadda minnha ħalla l-isem kif sabu.", source: "Toponomastika", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "In-nies jgħidu li huma minn raħal, mhux minn gżira, u l-festa tgħid liema. Bejn żewġ irħula li jmissu, il-jum tal-festa ma jaqbilx.", source: "Drawwa Maltija", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Filfla hija l-iżgħar gżira tal-grupp, u fuqha tgħix gremxula li ma tinstabx imkien ieħor fid-dinja.", source: "Podarcis filfolensis", theme: .ground, subtheme: .aPlaceYouAreFrom),

        Passage(text: "Ġnien u ġenna huma l-istess kelma f’żewġ ilbiesi, mibnija fuq għerq li jfisser li tgħatti. Ġnien huwa post magħluq qabel ma jkun xi ħaġa oħra.", source: "Etimoloġija", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Il-ġibjun tar-razzett jinżamm magħluq b’ġebla waħda tonda. Il-liġi ilha titlob li kull dar ġdida jkollha bir taħtha sa minn żmien l-Ordni.", source: "Bini Malti", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Il-Ġebla tal-Ġeneral fi Dwejra kienet miżmuma bl-għassa u l-ġnub tagħha tqaċċtu ċatti, minħabba pjanta li kienet titqies mediċina.", source: "Storja ta’ Malta", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "L-Ipoġew ta’ Ħal Saflieni jilqa’ għadd żgħir ħafna ta’ nies kuljum, biex l-arja ta’ ġewwa ma tinbidilx. Jinżamm billi kważi ħadd ma jidħol.", source: "Ħal Saflieni", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Il-ġonna ta’ San Anton inżergħu fis-seklu sbatax bħala ġnien privat ta’ dar, u nfetħu għan-nies sekli wara. L-istess siġar baqgħu hemm.", source: "Storja ta’ Malta", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "L-Għadira u s-Simar huma żewġ artijiet mistagħdra mgħottija bil-qasab, magħluqa apposta biex l-għasafar li jkunu għaddejjin isibu fejn jieqfu.", source: "Riżervi naturali", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Il-girna hija kmajra tal-ġebel mibnija fl-għalqa bla siment, b’saqaf tond magħmul minn ġebel imqiegħed dawra dawra. Isservi ta’ kenn u ta’ maħżen.", source: "Bini rurali", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "F’għelieqi mtarrġa kull ħajt iżomm il-ħamrija ta’ għalqa waħda. Meta jaqa’ ħajt wieħed, l-għalqa ta’ fuqu tinżel fuq dik ta’ taħtu.", source: "Konservazzjoni tar-raba’", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ir-raba’ mikri jissejjaħ qbiela u jgħaddi minn missier għal iben. Bidwi jista’ jkun ilu jaħdem l-istess għalqa bla ma qatt kienet tiegħu.", source: "Qbiela", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "L-għeruq tas-siġar ta’ ġnien magħluq jiltaqgħu taħt l-art anke meta l-friegħi ma jmissux. Il-ħajt jaqsam biss dak li jidher.", source: "Botanika", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Il-Buskett huwa l-unika masġar ta’ dawn il-gżejjer. Tħawwel biex jinżamm mill-Gran Mastri, u baqa’ hemm wara li spiċċaw huma.", source: "Storja ta’ Malta", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Fil-ġonna tal-gżira l-ħajt jinbena għoli biex jaqta’ l-Majjistral. Dak li jitħawwel warajh ikun jista’ jikber wieqaf.", source: "Ġardinaġġ", theme: .ground, subtheme: .aKeptPlace),

        // MARK: - Travel
        Passage(text: "Il-bajtar tax-xewk ma tnissilx hawn: wasal mill-Amerika u tħawwel bħala ħajt ħaj bejn l-għelieqi. Illum ħadd ma jistħajjel il-gżejjer mingħajru.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Iż-żerriegħa tal-ħarrub tgħaddi sħiħa mill-imsaren tal-annimal li jiekol il-frotta, u titla’ fejn tinżel.", source: "Ceratonia siliqua", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Il-kappar jitla’ minn nofs ħajt għoli għax l-għasfur li jiekol il-frotta jieqaf hemm fuq u mhux fl-art.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Hemm żrieragħ li jżommu f’wiċċ il-baħar għal ġimgħat sħaħ bla ma jitilfu l-ħajja, u jinbtu fuq xatt li ma kienx tagħhom.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "L-għasafar tal-passa jġorru żrieragħ imwaħħla fit-tajn ta’ riġlejhom. Minn tajn imnaddaf minn sieq waħda kabbru pjanti sħaħ.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ħafna żrieragħ jaqbdu max-xagħar tan-nagħaġ bix-xewk. Merħla li tinżel il-wied iġġorr fuqha l-għalqa li tkun ħalliet warajha.", source: "Biedja", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ir-riħ tax-Xlokk iġorr trab mid-deżert sal-gżejjer fi ftit jiem. Ma’ dak it-trab jasal frak li huwa ħaj.", source: "Meteoroloġija", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Il-lampuka timxi mal-baħar sħun u tasal madwar il-gżejjer f’Settembru. Is-sajjieda ma jsegwuhiex; jarmu dell fuq il-wiċċ u jistennewha.", source: "Sajd", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ir-rondun jasal f’April u jitlaq f’Awwissu. Bejn dawk iż-żewġ dati kważi ma jinżel imkien ħlief fuq il-bejta.", source: "Apus apus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bosta għasafar jaqsmu l-baħar f’lejl wieħed u dawn il-gżejjer huma l-ewwel art li jsibu. Ħafna ma jiqfux; iserrħu ftit sigħat u jkomplu.", source: "Ornitoloġija", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Fekruna li tfaqqas fuq xatt terġa’ lura biex tbid fuq l-istess ramel snin wara. Kif iżżomm it-triq għadu ma ntqalx sew.", source: "Caretta caretta", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Il-qamħ u ż-żebbuġ ma tnisslux hawn. It-tnejn waslu bil-baħar u baqgħu, u l-biedja kollha tal-gżejjer ġejja minn xi mkien ieħor.", source: "Storja tal-biedja", theme: .travel, subtheme: .howASeedGoes),

        Passage(text: "Il-bieżel ma jsib l-ebda triq magħluqa.", source: "Qawl Malti", theme: .travel, subtheme: .theRoad),
        Passage(text: "It-triq tal-ħmar twasslek id-dar.", source: "Qawl Malti", theme: .travel, subtheme: .theRoad),
        Passage(text: "Min jimxi bir-riħ isib ruħu f’nofs it-triq.", source: "Qawl Malti", theme: .travel, subtheme: .theRoad),
        Passage(text: "Nitla’ u nerġa’ ninżel dejjem fil-baħar il-għoli.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .travel, subtheme: .theRoad),
        Passage(text: "F’Misraħ Għar il-Kbir hemm żewġ linji mħaffra fil-blat li jibqgħu sejrin mijiet ta’ metri, u f’postijiet jinżlu taħt il-baħar. X’kien jgħaddi fihom għadu ma ntqalx.", source: "Arkeoloġija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Il-mogħdijiet bejn l-għelieqi huma dojoq għax inqatgħu għall-ħmar u mhux għall-karru. It-triq tgħid liema annimal kien jgħaddi minnha.", source: "Pajsaġġ", theme: .travel, subtheme: .theRoad),
        Passage(text: "Il-qsim bejn iż-żewġ gżejjer jieħu madwar ħamsa u għoxrin minuta bil-vapur. Fuq gżira, dik hija l-unika triq li ma tiddependix minnek.", source: "Ġeografija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Il-verb siefer ifisser li tmur barra minn pajjiżek. Fuq gżira dan ifisser ħaġa waħda biss: li tieħu l-baħar.", source: "Malti", theme: .travel, subtheme: .theRoad),
        Passage(text: "Il-boxxla tal-baħar issemmi t-tmien irjieħ bl-istess ismijiet li n-nies jużaw fuq l-art. Min hu barra u min hu ġewwa jgħidu l-istess kelma.", source: "Navigazzjoni", theme: .travel, subtheme: .theRoad),
        Passage(text: "L-istess għasafar jaqsmu minn fuq il-gżejjer f’April u f’Settembru, imma jsuqu fi tnejn kontra xulxin. It-triq hija waħda; il-ħsieb le.", source: "Ornitoloġija", theme: .travel, subtheme: .theRoad),
        Passage(text: "Il-passiġġieri li waslu qabel ma kien hemm ajruport niżlu fil-port wara ġranet sħaħ ta’ baħar. It-triq lejn hawn kienet titkejjel bil-lejl u mhux bis-siegħa.", source: "Storja ta’ Malta", theme: .travel, subtheme: .theRoad),
        Passage(text: "Fil-Malti l-kelma triq isservi kemm għal dik li timxi fiha u kemm għall-mod kif issir ħaġa. Min isib triq isib ukoll kif.", source: "Malti", theme: .travel, subtheme: .theRoad),

        Passage(text: "Id-dinja bla tarf u l-baħar bla tmiem.", source: "Qawl Malti", theme: .travel, subtheme: .farOff),
        Passage(text: "L-ismijiet tal-irjieħ jgħidu minn fejn ġejjin u mhux fejn sejrin. Il-Grigal huwa r-riħ tal-Griegi, u l-Lbiċ għandu isem Għarbi.", source: "Ir-roża tal-irjieħ", theme: .travel, subtheme: .farOff),
        Passage(text: "F’ġranet ta’ arja nadifa jidher il-vulkan ta’ Sqallija minn fuq l-għoljiet tal-gżira, madwar disgħin kilometru ’l bogħod.", source: "Ġeografija", theme: .travel, subtheme: .farOff),
        Passage(text: "Il-ħuttafa li titrabba taħt saqaf hawn tqatta’ x-xitwa fl-Afrika u terġa’ lura lejn l-istess bejta fir-rebbiegħa ta’ wara.", source: "Hirundo rustica", theme: .travel, subtheme: .farOff),
        Passage(text: "L-ilma tal-Mediterran jinbidel kollu kemm hu darba kull madwar mitt sena, u dan isir minn fetħa waħda dejqa fil-Punent.", source: "Oċeanografija", theme: .travel, subtheme: .farOff),
        Passage(text: "Is-sallura titwieled f’baħar fin-naħa l-oħra tal-Atlantiku u tgħum sa hawn bħala frieħ. Ħadd għadu qatt ma raha tbid.", source: "Anguilla anguilla", theme: .travel, subtheme: .farOff),
        Passage(text: "Fis-seklu għoxrin għadd kbir ta’ Maltin telqu lejn l-Awstralja u l-Kanada. Il-festi tar-raħal tagħhom baqgħu jsiru hemm bl-istess ismijiet.", source: "Storja ta’ Malta", theme: .travel, subtheme: .farOff),
        Passage(text: "Il-baħar madwar il-gżejjer jinżel iżjed minn tliet mitt metru f’ċerti postijiet. Il-qiegħ ta’ hemm ma jara qatt id-dawl.", source: "Oċeanografija", theme: .travel, subtheme: .farOff),
        Passage(text: "L-isem tal-gżira jidher f’kitbiet Griegi u Latini sekli qabel ma nkiteb xi ħaġa bil-Malti. Kienet magħrufa barra qabel ma kitbet fuqha nnifisha.", source: "Storja ta’ Malta", theme: .travel, subtheme: .farOff),
        Passage(text: "Il-widnet il-baħar tikber biss fuq l-irdum ta’ dawn il-gżejjer. Għaliha, kull post ieħor fid-dinja qiegħed wisq ’il bogħod.", source: "Cheirolophus crassifolius", theme: .travel, subtheme: .farOff),
        Passage(text: "Xi kwiekeb li tidher tarahom fis-sema ilhom mitfija sekli. Id-dawl tagħhom għadu miexi u ma jafx bihom.", source: "Astronomija", theme: .travel, subtheme: .farOff),
        Passage(text: "Il-gżejjer jinsabu f’nofs baħar li jorbot tliet kontinenti. Kull ħaġa li waslet hawn ġiet minn naħa waħda jew oħra ta’ dik il-qasma.", source: "Ġeografija", theme: .travel, subtheme: .farOff),

        // MARK: - Meeting
        Passage(text: "Il-ħaj mal-ħaj jiltaqa’.", source: "Qawl Malti", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Xidew il-qada, ja ġirieni, talli nħadditkom.", source: "Pietru Caxaro, Il-Kantilena, seklu 15", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Il-kelma laqgħa ġejja mill-verb laqa’, li jfisser li tilqa’ lil xi ħadd ġewwa. Laqgħa hija l-ewwel u qabel kollox bieb miftuħ.", source: "Etimoloġija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Il-Ġimgħa hija kemm jum u kemm il-kelma għal sebat ijiem, u ġejja minn għerq li jfisser li tinġabar. Iż-żmien issemma għall-ġbir tan-nies.", source: "Etimoloġija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Fl-għana ta’ spirtu pront żewġ għannejja jridu jwieġbu lil xulxin fuq l-istess ritmu, u l-vers jinħadem fil-mument. Ħadd ma jaf x’se jgħid l-ieħor.", source: "Għana Malti", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Żewġ dgħajjes li jaslu wiċċ imb wiċċ fil-baħar iduru t-tnejn lejn il-lemin. Ir-regola tħallihom jgħaddu bla ma jkollhom bżonn jitkellmu.", source: "Navigazzjoni", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Fjura tal-bajtar tinfetaħ għal jum wieħed. Naħla li tasal dakinhar issibha; waħda li tasal l-għada ssib fjura oħra u qatt lil dik.", source: "Botanika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Meta żewġ mewġiet ġejjin minn żewġ naħat jaqbżu f’xulxin, jgħollu lil xulxin għal mument u mbagħad ikomplu kif kienu. Xejn ma jinbidel; kollox jogħla.", source: "Fiżika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Iż-żewġ għajnejn jaraw żewġ stampi ftit differenti, u l-moħħ jgħaqqadhom f’waħda. Il-fond huwa dak li joħroġ minn dik il-laqgħa.", source: "Anatomija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "L-eklissi tax-xemx isseħħ għax mill-art il-qamar u x-xemx jidhru kbar l-istess. Dak li jġibha huwa kumbinazzjoni ta’ distanza u xejn iżjed.", source: "Astronomija", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Iż-żewġ ġnub ta’ ħnejja jinbnew separati u jiltaqgħu fin-nofs. Sakemm ma jiltaqgħux, il-ħnejja ma żżomm xejn u tinżamm bl-injam.", source: "Bini tal-ġebel", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Il-verb iltaqa’ ma jaħdimx b’wieħed. Trid tgħid iltaqa’ ma’ xi ħadd, jew iltaqgħu; f’kull każ ikun hemm tnejn.", source: "Grammatika Maltija", theme: .meeting, subtheme: .theMoment),

        Passage(text: "Fid-dinja lkoll niġu bżonn xulxin.", source: "Qawl Malti", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Il-ħarrub għandu siġar irġiel u siġar nisa. Ħarruba waħda weħidha, kemm hi kemm hi kbira, ma tagħti xejn.", source: "Ceratonia siliqua", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Iż-żebbuġa tagħti aħjar meta jkun hemm varjetà oħra fil-qrib. Anke fejn tiflaħ tagħmel waħidha, tagħmel aħjar bi tnejn.", source: "Olea europaea", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "In-naħla u l-fjura ma jistgħux jgħaddu minn xulxin: waħda tiekol u l-oħra tinżera’. L-ebda waħda mit-tnejn ma tagħmel dak li trid weħidha.", source: "Bijoloġija", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Dak li jidher qisu tebgħa safra fuq il-ġebel huwa żewġ ħlejjaq f’waħda: fungu li jżomm, u alka li tiekol id-dawl. Waħedhom ma jgħixu fuq ebda ħajt.", source: "Bijoloġija", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Il-fjura tat-tin tinsab ġewwa l-frotta u ma tinfetaħx. Il-frotta u l-insett li jidħol fiha ilhom eluf ta’ snin ma jistgħux jgħaddu minn xulxin.", source: "Ficus carica", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Iż-żewġ ħitan ta’ terazza jżommu lil xulxin: dak ta’ fuq iżomm il-ħamrija, u dak ta’ taħt iżomm lil ta’ fuq milli jinżel.", source: "Konservazzjoni tar-raba’", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Il-kelma xulxin ma tistax tintuża b’wieħed. Hija kelma li teħtieġ tnejn qabel ma tibda tfisser xi ħaġa.", source: "Grammatika Maltija", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Il-baħar u l-art jiltaqgħu f’linja li tinbidel darbtejn kuljum. Kull waħda tieħu ftit mill-oħra u tagħti ftit lura.", source: "Ġeografija", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "In-naħal ma jsaħħanx waħdu fix-xitwa: jinġabar f’ballun u jiċċaqlaq bil-mod, biex kull waħda minnhom tasal għal ftit fin-nofs.", source: "Trobbija tan-naħal", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Il-ġbejna tinxef fuq xibka miftuħa: trid ir-riħ u trid il-melħ, u l-ebda wieħed minnhom ma jagħmel ix-xogħol tal-ieħor.", source: "Ġobon Malti", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Is-silla u l-batterji li jgħixu fl-għeruq tagħha jaħdmu flimkien: il-pjanta ttihom fejn joqogħdu, u huma jtuha n-nitroġenu mill-arja.", source: "Hedysarum coronarium", theme: .meeting, subtheme: .twoThatNeedEachOther),

        Passage(text: "Mis-sliem jiġi l-kliem u mill-kliem jiġu l-ħbieb.", source: "Qawl Malti", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Bil-kliem u s-sliem tasal kullimkien.", source: "Qawl Malti", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Min jiġi merħba bih, min ma jiġix Alla jhennih.", source: "Qawl Malti", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Loqma għalenija tiswa mija.", source: "Qawl Malti", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Merħba ġejja minn għerq li jfisser wisa’. Meta tgħid merħba lil xi ħadd, qed tgħidlu li hemm il-post.", source: "Etimoloġija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Il-verb sellem u n-nom sliem huma l-istess kelma f’żewġ forom. Li ssellem lil xi ħadd hu li tagħtih il-paċi f’idejh.", source: "Etimoloġija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Fl-Atti tal-Appostli jingħad li n-nies ta’ din il-gżira xegħlu nar u laqgħu lil kull min ħareġ mill-baħar, minħabba x-xita u l-bard.", source: "Atti tal-Appostli 28", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Fil-jiem tal-festa d-djar jimtlew bil-qagħaq tal-għasel u b’ħelu ieħor, u l-mistieden li jidħol ma jitħalliex joħroġ bla ma jiekol.", source: "Drawwa Maltija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "It-tweġiba għal grazzi hija ta’ xejn. Min irċieva jgħid li ma kien xejn, biex min ta ma jibqax b’xi ħaġa fuq min ħa.", source: "Drawwa Maltija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Il-bews fuq iż-żewġ ħaddejn huwa s-sliem tas-soltu bejn nies li jafu lil xulxin, anke jekk ikunu ltaqgħu darba biss qabel.", source: "Drawwa Maltija", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Il-liġi tal-baħar tobbliga lil kull bastiment li jisma’ sejħa biex jersaq. Huwa l-uniku dmir li ma jiddependix minn min qed isejjaħ.", source: "Liġi tal-baħar", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Fl-għana ta’ spirtu pront min iwieġeb irid iżomm il-mixja u l-qies ta’ min kien qablu. Ir-regola tobbligak tisma’ qabel ma tgħid.", source: "Għana Malti", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: - Kinship
        Passage(text: "Tilqim: fergħa ta’ siġra titqiegħed fuq zokk ta’ oħra u ż-żewġ qxur jingħaqdu. Wara ftit snin ma jibqax jidher fejn kienu tnejn.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Żewġ siġar li jikbru wisq qrib xulxin jistgħu jingħaqdu fejn jitħakku, u minn hemm ’il fuq jikbru bħala ħaġa waħda.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "L-għeruq ta’ siġar tal-istess xorta jingħaqdu taħt l-art u jaqsmu l-ilma bejniethom. Siġra li tidher weħidha mhijiex bilfors weħidha.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Il-posidonja tikber f’mergħa waħda, kull xitla marbuta ma’ dik ta’ ħdejha b’għerq twil. Biċċa qiegħ sħiħa tista’ tkun pjanta waħda.", source: "Posidonia oceanica", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "L-imħar li jitwaħħal ma’ blata jibqa’ hemm ħajtu kollha. Il-ġirien tiegħu jibnu fuqu sa ma l-blata kollha ssir saff wieħed.", source: "Bijoloġija tal-baħar", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Il-vina ta’ werqa tinqasam u terġa’ tingħaqad iżjed ’il quddiem. Jekk waħda tinqata’, l-ilma jsib triq oħra fl-istess werqa.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Żewġ irħula li jmissu jaqsmu l-istess ħitan tar-raba’, u ħajt wieħed ikun tat-tnejn. Min isewwih isewwi għaż-żewġ naħat f’daqqa.", source: "Ħitan tar-raba’", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Il-qroll jinbena minn ħlejjaq ċkejknin li jibqgħu mwaħħla ma’ xulxin. Dak li jħallu warajhom huwa d-dar ta’ dawk li jiġu warajhom.", source: "Bijoloġija tal-baħar", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Il-ħabel tas-sajjieda jinbrom minn tliet ħjut. Kull wieħed weħidu jinqata’ malajr; it-tlieta mibruma jerfgħu dgħajsa.", source: "Sajd", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Ħafna knejjes Maltin inbnew fuq oħrajn eqdem, u l-ġebel tal-qadima ntuża mill-ġdid fil-ġdida. Il-ħajt iġorr żewġ żminijiet f’daqqa.", source: "Storja ta’ Malta", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "L-ilma li jinżel f’wied jiġbor kull qatra li tkun niżlet fuq l-għoljiet ta’ madwaru. Il-wied huwa dak li jgħaqqad u mhux dak li jaqsam.", source: "Ġeografija", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kunjomijiet sħaħ jinsabu miġbura f’raħal wieħed. L-isem tal-familja jgħid minn fejn ġejt daqskemm jgħid ma’ min.", source: "Onomastika", theme: .kinship, subtheme: .grownTogether),

        Passage(text: "Mill-istess għerq joħorġu ħabba, ħabb, ħabib u mħabba. Iż-żerriegħa, li tħobb u l-ħabib jinkitbu bl-istess tliet ittri.", source: "Għerq Semitiku", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Il-verb għannaq ġej mill-kelma għonq. Li tgħannaq lil xi ħadd huwa li ddawwar dirgħajk ma’ għonqu, u l-kelma tgħid dak biss.", source: "Etimoloġija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ħanin, ħniena u tħannin ġejjin kollha minn għerq wieħed. Fil-Malti l-ħniena hija kelma tad-dar qabel ma tkun kelma tal-knisja.", source: "Etimoloġija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ħabib fil-bżonn, ħabib tal-kunjom.", source: "Qawl Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Il-ħabib dak li jaqbeż għalik.", source: "Qawl Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Il-ħabib ħobbu b’għewiedu.", source: "Qawl Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Qalb tfisser fl-istess ħin l-organu u n-nofs ta’ xi ħaġa: qalb in-nies ifisser f’nofshom. Min ikun fil-qalb ikun fin-nofs.", source: "Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ħuti ma tintużax biss għall-aħwa tad-demm imma wkoll għal min tqis daqshom. Il-kelma tinfetaħ iżjed milli tagħlaq.", source: "Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Flimkien hija mibnija fuq il-kelma mkien. Li tkun flimkien ma’ xi ħadd huwa li tkun fl-istess post miegħu, u xejn iżjed.", source: "Etimoloġija", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ġar tfisser min joqgħod ħdejk u xejn iżjed. Ma tgħid xejn dwar min hu, u xorta hija waħda mill-eqdem kelmiet tal-ilsien.", source: "Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Wens hija l-kumpanija li ttaffi n-nuqqas. Ma tissarrafx f’għajnuna: hija biss li ma tkunx waħdek.", source: "Malti", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Tarbija tfisser dak li għadu jitrabba. Il-kelma ma tgħidx kemm għandu żmien; tgħid biss li għad hemm min qed jieħu ħsiebu.", source: "Malti", theme: .kinship, subtheme: .theWordsForIt),

        Passage(text: "Waħdek ma tridx tkun lanqas il-ġenna.", source: "Qawl Malti", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Fil-għaqda s-saħħa.", source: "Qawl Malti", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kelma bejn tnejn; bejn tlieta, mnejn sa fejn.", source: "Qawl Malti", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Il-luzzu jinġibed ’il barra mill-ilma minn żewġ irġiel fuq l-istess ħabel: wieħed jiġbed u l-ieħor iżomm. Ħadd ma jista’ jagħmel it-tnejn.", source: "Sajd", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Tnejn li jimxu flimkien jaqbdu jimxu fl-istess pass wara ftit metri, bla ma jgħidu xejn u bla ma jindunaw.", source: "Fiżjoloġija", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Il-verb jista’ jġorr żewġ nies f’kelma waħda: għidtlu, tahielna, ġibhieli. Iż-żewġ naħat tal-ħaġa jinkitbu mwaħħla ma’ xulxin.", source: "Grammatika Maltija", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "F’ħafna rħula hemm żewġ każini tal-banda u żewġ festi. Nies tal-istess triq isibu ruħhom fuq żewġ naħat, u xorta jibqgħu ġirien.", source: "Drawwa Maltija", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Il-borma tal-Ħadd issir għal min ikun ġej u mhux għal min hemm. Il-kejl tal-ikel isir bit-tama u mhux bl-għadd.", source: "Drawwa Maltija", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "L-ismijiet jiqsaru meta jkun hemm min jafek: minn Ġużeppi joħroġ Żeppi, u minn Marija toħroġ Mari. It-tqassir huwa sinjal ta’ qrubija.", source: "Onomastika", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Meta jinbena ħajt tal-ġebel, wieħed jgħaddi l-ġebla u l-ieħor ipoġġiha. Min ipoġġi ma jarax x’ġej, u min jgħaddi ma jarax fejn sejra.", source: "Bini tal-ġebel", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Fl-għasafar li jtiru f’forma ta’ V, dak ta’ quddiem jinbidel kull ftit. Ħadd minnhom ma jerfa’ r-riħ għat-triq kollha.", source: "Ornitoloġija", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ġirien huma nies li jgħixu ħdejn xulxin bla ma jkunu għażlu lil xulxin. Ir-rabta tinbena mill-post u mhux mill-fehma.", source: "Malti", theme: .kinship, subtheme: .twoPeople),

        // MARK: - Peace
        Passage(text: "Il-Widna f’Magħtab hija ħajt tal-konkrit mgħawweġ mibni fis-snin tletin biex jinstemgħu l-ajruplani ġejjin qabel ma jidhru. Widna waħda kbira mibnija fl-art.", source: "Il-Widna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "L-Imdina tissejjaħ il-Belt Siekta. Il-karozzi ma jitħallewx jidħlu fiha, u dak li tisma’ hemm ġew huma l-passi fuq il-ġebel.", source: "L-Imdina", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "L-ittra q ma tinstemax bħala ħoss imma bħala waqfa: il-leħen jinqata’ għal mument u mbagħad jerġa’ jibda. Hemm ittra li hija toqba.", source: "Fonetika Maltija", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "L-għ fil-biċċa l-kbira tal-Malti tal-lum ma tinstemax: iżżomm il-vokali ta’ ħdejha twila u tibqa’ miktuba. Hija ittra li żżomm il-post ta’ ħoss li ma baqax.", source: "Fonetika Maltija", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Klomi hija l-kelma tas-sajjieda għall-kalma sħiħa tal-baħar, meta l-wiċċ ma jkollu ebda tikmixa. Hemm isem għal dak in-nuqqas ta’ moviment.", source: "Kliem tal-baħar", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Fl-Ipoġew ta’ Ħal Saflieni hemm kamra li fiha leħen baxx jibqa’ jdur mal-ħitan. Il-blat maqtugħ b’dak il-mod jerġa’ jagħti l-ħoss lura.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Il-barbaġann itir bla ħoss għax it-truf tar-rix tal-ġwienaħ tiegħu huma mimlijin ħjut irqaq. L-arja tinqasam bil-mod wisq biex tinstema’.", source: "Tyto alba", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ix-xogħol tal-bini ma jitħalliex isir fil-Ħdud u fil-festi pubbliċi. Hemm ġranet li fihom is-skiet mhuwiex għażla imma mniżżel fil-liġi.", source: "Liġi", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ħemda hija l-iżjed kelma tqila għall-kwiet: mhijiex nuqqas ta’ ħoss imma sakta li tinħass. Tintuża l-iżjed għal-lejl.", source: "Malti", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Skiet u kwiet ġew minn żewġ ilsna: waħda Semitika u l-oħra mit-Taljan. Il-Malti żamm it-tnejn: is-skiet huwa ta’ min ma jitkellimx, il-kwiet huwa ta’ post.", source: "Etimoloġija", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Kieku l-kliem kien ġawhar, is-skiet aħjar minnu.", source: "Qawl Malti", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Fuq baħar kalm il-ħsejjes tal-art jinstemgħu minn ferm ’il bogħod, għax l-ilma ma jferrixhomx. Is-sikta ta’ naħa tħalli l-ħoss tal-oħra jasal.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),

        Passage(text: "Aħjar paċi milli tagħmel paċi.", source: "Qawl Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Qalb tajba trid is-sliem.", source: "Qawl Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Aħjar kelma nieqsa minn kelma żejda.", source: "Qawl Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Il-paċi ġejja mil-Latin u s-sliem huwa Semitiku. Waħda tingħad fi tmiem ġlieda, l-oħra malli tiltaqa’ ma’ xi ħadd, u l-Malti żamm it-tnejn.", source: "Etimoloġija", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Is-sliem għalikom hija t-tislima antika, u t-tweġiba tagħha tagħti lura l-istess ħaġa. Min isellem ma jitlifx dak li jagħti.", source: "Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Fl-ewwel artiklu tal-Kostituzzjoni jingħad li l-pajjiż huwa newtrali u li jfittex il-paċi u s-sigurtà fost il-ġnus. Il-paċi tinsab fil-bidu nett.", source: "Kostituzzjoni ta’ Malta", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Bnazzi huwa t-temp li jikkalma wara l-maltemp. Mhijiex kelma għax-xemx imma għall-waqfien tar-riħ, u tingħad l-iżjed fuq il-baħar.", source: "Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Il-verb waqaf iservi wkoll biex tgħid li ħaġa hija f’postha: ħajt wieqaf huwa ħajt li għadu jżomm. Li tieqaf mhuwiex li taqa’.", source: "Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Il-verb ħafer ġej minn għerq li jfisser li tgħatti. Li taħfer huwa li tgħatti l-ħaġa, mhux li tħassarha.", source: "Etimoloġija", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Tregwa daħlet fil-Malti mit-Taljan u tfisser waqfien li jiġġedded. Ma tfissirx tmiem: tfisser li kollox jinżamm sakemm jerġa’ jibda.", source: "Malti", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Il-qanpiena ddoqq għall-Angelus f’nofsinhar, u dari x-xogħol fl-għelieqi kien jieqaf għal dak il-ħin. Il-ħoss kien is-sinjal biex jieqaf il-ħoss l-ieħor.", source: "Drawwa Maltija", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Ħalliha hemm huwa l-kliem li jagħlaq argument. Ma jsemmix min kellu raġun, u dak huwa l-punt tiegħu.", source: "Malti", theme: .peace, subtheme: .theWordsForStopping),

        Passage(text: "Fis-sajf zokk jitimgħek u blata traqqdek.", source: "Qawl Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Min hu għajjien jistrieħ.", source: "Qawl Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Ħobż u basal u strieħ xħin tasal.", source: "Qawl Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Kull kalanka port.", source: "Qawl Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Mistrieħ, riħ, ruħ u riħa ġejjin kollha minn għerq wieħed. Fil-Malti l-mistrieħ jaqsam l-ittri tiegħu mar-riħ u man-nifs.", source: "Għerq Semitiku", theme: .peace, subtheme: .atEase),
        Passage(text: "Serħan il-moħħ tfisser li l-ħsieb tqiegħed bilqiegħda. Il-kelma ġġib il-moħħ u l-ġisem taħt l-istess verb.", source: "Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Il-ħitan ħoxnin tal-ġebel iżommu d-dar friska f’Awwissu u sħuna f’Jannar. Ġewwa ma jinbidel kważi xejn meta barra jinbidel kollox.", source: "Bini Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Il-gallarija magħluqa bl-injam tħalli lil min hu ġewwa jara t-triq bla ma jidher. Hija post fejn tkun barra u ġewwa fl-istess ħin.", source: "Bini Malti", theme: .peace, subtheme: .atEase),
        Passage(text: "Iż-żebbuġa tissemma f’żewġ ismijiet ta’ postijiet: Ħaż-Żebbuġ, u ż-Żejtun, il-post taż-żejt. L-istess siġra qiegħda taħt iż-żewġ ismijiet.", source: "Toponomastika", theme: .peace, subtheme: .atEase),
        Passage(text: "Fl-għabex tas-sajf in-nies joħorġu s-siġġijiet fit-triq u joqogħdu barra l-bieb. Il-ħin ta’ wara nżul ix-xemx huwa l-ħin tat-taħdit bil-kwiet.", source: "Drawwa Maltija", theme: .peace, subtheme: .atEase),
        Passage(text: "Il-qattus jorqod fejn tinżel ix-xemx fuq il-ġebel u jiċċaqlaq mal-marka tagħha matul il-jum. Isib il-post billi jimxi warajha bil-mod.", source: "Żooloġija", theme: .peace, subtheme: .atEase),
        Passage(text: "Il-ħoss tal-mewġ fuq iċ-ċagħaq huwa dejjem l-istess u qatt l-istess. Min jorqod ħdejh jorqod għax ma jkun hemm xejn xi jgħodd.", source: "Akustika", theme: .peace, subtheme: .atEase),
    ]
}
