import Foundation

/// The Albanian passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let albanian: [Passage] = [
        // MARK: - Beginnings
        Passage(text: "Mbirja: çasti kur fara nuk është më depo ushqimi, po bimë. Nga ai çast nuk kthehet dot më prapa.", source: "Botanikë", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Fara e grurit nxjerr rrënjën para gjethes; bima e kap tokën përpara se të shohë dritën.", source: "Botanikë", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Në shqipe folja çel do të thotë edhe hap edhe lulëzoj: një derë çelet dhe një lule çel me të njëjtën fjalë.", source: "Shqipe", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Shprehja zë fill do të thotë nis. Fjalë për fjalë, ajo do të thotë të kapësh skajin e parë të një peri.", source: "Shqipe", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Libri i parë i njohur në gjuhën shqipe është Meshari i Gjon Buzukut, i shtypur më 1555. Prej tij ka mbetur një kopje e vetme.", source: "Histori e librit shqip", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Zogu që çan lëvozhgën e ka një dhëmb të vogël gëlqeror në majë të sqepit; ai bie pak ditë pasi zogu ka dalë.", source: "Zoologji", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Prag quhet guri i poshtëm i derës. Në shqipe fjala tregon edhe vetë banesën: kush e kalon pragun, ka hyrë.", source: "Shqipe", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Rrënja e parë del nga fara e drejtuar poshtë; bima e njeh poshtin pa e parë kurrë.", source: "Botanikë", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Gjethet e para të një fidani nuk u ngjajnë atyre që vijnë pas: ato dalin gati të gatshme nga brenda kokrrës.", source: "Botanikë", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Folja nis mban në shqipe dy punë: nis një punë dhe nis një letër. E para mbetet me ty, e dyta të lë.", source: "Shqipe", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ulliri i mbjellë nga kokrra nuk jep frut për shumë vjet; puna e tij e parë është vetëm të bëjë trung.", source: "Bujqësi", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Bleta zbuluese del nga zgjoi para të tjerave; ajo nuk mbledh gjë, po kthehet dhe u tregon të tjerave ku ka.", source: "Entomologji", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Nga një vrimë e vogël, rrjedh e gjithë fuçia.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Një shkëndijë ndez një mal.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Lisi nuk pritet me nji të rame.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Uji rrjedh pikë-pikë e ha gurin.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Fara e orkidesë është aq e imët sa duket pluhur; një kapsulë e vetme mund të mbajë qindra mijëra prej tyre.", source: "Botanikë", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Fjala farë vjen nga një rrënjë shumë e vjetër që do të thoshte shpërndaj; e njëjta rrënjë ka dhënë greqishten spóros.", source: "Etimologji", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Rrapi trashet aq sa disa veta bashkë nuk ia mbërthejnë trungun; fidani i tij nis sa një gisht.", source: "Botanikë", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Nga një degë shelgu e ngulur në baltë del një pemë e tërë: shelgu lëshon rrënjë nga vetë druri.", source: "Botanikë", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Një zgjua i madh ka një mëmë të vetme; prej saj dalin dhjetëra mijëra bletë.", source: "Entomologji", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kokrra e vetme që mbin jep një kalli me dhjetëra kokrra të reja, dhe prej andej nis një arë.", source: "Bujqësi", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Një polip i vetëm, sa maja e gishtit, e kopjon veten derisa shkëmbi që ndërton bëhet ishull.", source: "Biologji detare", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Bora e parë peshon sa asgjë; e njëjta borë, e shtypur me shekuj në një gropë mali, bëhet akull që lëviz.", source: "Gjeologji", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Mate punën jo me atë që mbjell, po me atë që korr.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Dita me diell duket që në mëngjes.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Zjarrit po nuk i fryve, nuk ndizet.", source: "Fjalë e urtë shqipe", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kongresi i Manastirit, në nëntor 1908, vendosi alfabetin me të cilin shkruhet ende sot shqipja: tridhjetë e gjashtë shkronja, të gjitha latine.", source: "Histori e gjuhës", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mënyra si krasitet një pemë në tri vitet e para vendos si do të qëndrojë trungu i saj pas pesëdhjetë vjetësh.", source: "Pemëtari", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Themeli nuk shihet pasi ngrihen muret, po asgjë mbi të nuk ndreqet dot pa e prishur atë.", source: "Ndërtim", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Në shqipe zakoni quhet edhe adet edhe dokë: mënyra si u bë një punë herën e parë dhe mënyra si bëhet përherë.", source: "Shqipe", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Thellësia e brazdës vendos gjithçka që vjen pas: fara e mbjellë tepër thellë del vonë ose nuk del fare.", source: "Bujqësi", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Shtrati i një lumi zgjidhet në mijëvjeçarët e parë; pastaj uji e ndjek atë vijë edhe kur toka rreth tij ndryshon.", source: "Gjeografi", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Frang Bardhi botoi më 1635 në Romë fjalorin e parë të shqipes, latinisht dhe shqip; prej tij nis fjalorishtja e kësaj gjuhe.", source: "Histori e gjuhës", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Emrat e bimëve në shqipe ruajnë përdorimin e parë: bar do të thotë njëkohësisht barishte dhe ilaç.", source: "Shqipe", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kongresi i Drejtshkrimit, mbajtur në Tiranë më 1972, vendosi një gjuhë të vetme letrare, të mbështetur në toskërishten.", source: "Histori e gjuhës", theme: .beginnings, subtheme: .whatAStartSettles),
        // MARK: - Waiting
        Passage(text: "Fjetja e farës: fara nuk mbin edhe kur ka ujë, dritë e ngrohtësi, sepse diçka brenda saj ende nuk ka lëshuar.", source: "Botanikë", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Disa fara malore duhet ta kalojnë dimrin në të ftohtë para se të pranojnë të mbijnë; pa dimër ato rrinë.", source: "Botanikë", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ariu në gjumin e dimrit e ul rrahjen e zemrës aq sa ajo mezi numërohet.", source: "Zoologji", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Shqipja ka dy folje pres: njëra do të thotë ndaj me thikë, tjetra do të thotë rri derisa të vijë dikush.", source: "Shqipe", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Vezët e disa peshqve rrinë gjallë në baltën e një pellgu edhe kur pellgu është tharë krejt.", source: "Zoologji", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Sythi i dimrit është një gjethe e ardhshme, e mbështjellë e mbyllur me luspa; ajo është gati që nga vjeshta.", source: "Botanikë", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Farat e ruajtura në të ftohtë mund të mbeten të afta të mbijnë pas dhjetëra vjetësh.", source: "Bujqësi", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Disa orkide nuk çelin pa takuar një kërpudhë të caktuar; ato nuk presin kohën, po një shok.", source: "Botanikë", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Folja mbahem në shqipe do të thotë të ndalosh veten pa të ndaluar kush tjetër.", source: "Shqipe", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Bora që rri e pashkrirë në hijen e një gremine mban brenda saj ujin e disa dimrave.", source: "Gjeologji", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Në vapë shumë bimë i mbyllin gojëzat e gjetheve dhe rrinë pa marrë frymë derisa të bjerë nxehtësia.", source: "Botanikë", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Kërmilli e mbyll guaskën me një cipë gëlqereje dhe rri ashtu muaj me radhë, derisa toka të lagësht.", source: "Zoologji", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Liqeni i Ohrit ka nisur të mbushet para një deri dy milionë vjetësh dhe ruan qindra lloje që nuk gjenden gjetkë.", source: "Gjeografi", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Gjinkalla e kalon pjesën më të gjatë të jetës nën dhe si larvë dhe pak javë mbi dhe si gjinkallë.", source: "Entomologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Disa ullinj të bregdetit numërohen me shekuj dhe vazhdojnë të japin kokrra.", source: "Bujqësi", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Një pikë ujë lë pas vetëm një cipë të hollë gëlqereje; për një centimetër shtalaktiti duhen shpesh më shumë se njëqind vjet.", source: "Gjeologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Shiu që bie sot mbi malësi mund të dalë në një burim pas dhjetëra vjetësh.", source: "Hidrogjeologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ti prite të paktën, prite dhe të shumtën.", source: "Fjalë e urtë shqipe", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Mosha e një peme lexohet në unazat e trungut; secila prej tyre është një verë e vetme.", source: "Dendrologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Fjala mot në shqipe do të thotë vit, dhe motmot do të thotë një vit i plotë, nga një ditë deri te po ajo ditë.", source: "Shqipe", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Bredhi rritet ngadalë në lartësi të mëdha; unazat e tij ngjeshen aq shumë sa numërohen vetëm me zmadhues.", source: "Dendrologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Peshku i thellësive jeton gjatë sepse i ftohti e ngadalëson gjithçka brenda tij.", source: "Biologji detare", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Guri gëlqeror i Bjeshkëve u bë në fundin e një deti të ngrohtë; majat që duken sot janë shtresa të atij fundi.", source: "Gjeologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Një lis mund të mbushë treqind vjet e të vazhdojë të japë lende; kokrra që e nisi ishte sa maja e gishtit.", source: "Dendrologji", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Qeni i bagëtisë nuk e ndjek kopenë, po rri me të dhe shikon larg saj; puna e tij është të vërejë, jo të vrapojë.", source: "Zoologji", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Kulla e malësisë ngrihet me mure guri dhe me dritare të vogla lart; prej tyre shihet gjithë lugina.", source: "Arkitekturë popullore", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Bufi rri i palëvizur mbi degë dhe e kthen kokën gati nga çdo anë pa e lëvizur trupin.", source: "Zoologji", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ai që mban bletët e kupton nga zhurma e zgjoit, disa ditë përpara, se një tufë po bëhet gati të ikë.", source: "Bletari", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Vëzhguesit e qiellit i presin orët pas mesnate, kur ajri qetësohet dhe yjet dridhen më pak.", source: "Astronomi", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Në errësirë një dritë e largët kapet më mirë me bishtin e syrit sesa duke e parë drejt.", source: "Fiziologji", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Delet i njohin fytyrat e njëra-tjetrës dhe i mbajnë mend ato për vite me radhë.", source: "Zoologji", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Kush pret të lindë hëna e re nuk sheh asgjë: hëna e re është pikërisht nata kur ajo nuk duket.", source: "Astronomi", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Dallëndyshja kthehet shpesh te folja e vjetshme; njerëzit e shtëpisë e presin dhe e njohin kur vjen.", source: "Ornitologji", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Në Elbasan, natën para katërmbëdhjetë marsit, ndizen zjarre dhe njerëzit rrinë zgjuar që të presin ditën e verës.", source: "Zakone", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Fari nuk shkon askund; e gjithë puna e tij është të rrijë në një vend dhe të ndizet çdo natë.", source: "Detari", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Kush e ruan një zjarr gjithë natën nuk mban flakën, po prushin; flaka kërkon punë, prushi kërkon vetëm vëmendje.", source: "Zakone", theme: .waiting, subtheme: .standingAndWatching),
        // MARK: - Renewal
        Passage(text: "Ulliri i vjetër, edhe kur i digjet trungu, lëshon filiza nga rrënjët dhe nis prej andej.", source: "Bujqësi", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Bari i kositur rritet sërish sepse pika nga e cila zgjatet nuk është maja, po baza e fletës.", source: "Botanikë", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Shelgu i shkurtuar çdo vit jep thupra të drejta; kush i pret ato, e mban pemën përherë të re.", source: "Zejtari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Manaferra e prerë deri në tokë kthehet vitin tjetër më e dendur se ç'ishte.", source: "Kopshtari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Dushku i krasitur me radhë ka mbajtur me dru fshatra të tëra pa u prerë ndonjëherë krejt.", source: "Pyjari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Folja përtërij në shqipe do të thotë e bëj sërish të ri; ajo mban brenda vetes fjalën i ri.", source: "Shqipe", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Hardhia hiqet çdo dimër gati e tëra; rrushi vjen vetëm nga druri që del atë vit.", source: "Vreshtari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Gjarpri e ndërron lëkurën i tëri, bashkë me cipën që i mbulon sytë.", source: "Zoologji", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Gështenja e moshuar nxjerr filiza rreth trungut të thatë; ato bëjnë një rreth pemësh aty ku ishte një.", source: "Pyjari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Rrënjët e fikut lëshojnë fidanë disa metra larg pemës; fiku përhapet nën dhe pa u parë.", source: "Botanikë", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Filiz quhet dega e njomë që del nga një trung i vjetër; kopshtari e njeh nga ngjyra më e çelët.", source: "Kopshtari", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Livadhi i lënë një verë pa u kositur kthen lulet që kishin humbur; farat i kishte mbajtur toka.", source: "Botanikë", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Dita e Verës kremtohet më katërmbëdhjetë mars; në Elbasan lidhet në dorë verorja, një pe i kuq dhe i bardhë.", source: "Zakone", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Vjeshta në shqipe e merr emrin nga folja vjel: stina quhet me emrin e punës që bëhet në të.", source: "Etimologji", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Pranvera quhet ashtu sepse është pranë verës; emri është bërë mbi latinishten prima vera.", source: "Etimologji", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Shqipja ka dy fjalë verë që shkruhen njësoj: stina dhe pija. E para vjen nga latinishtja, e dyta është e trashëguar.", source: "Etimologji", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Dimrit iu bëj hazër që në behar, e beharit që në dimër.", source: "Fjalë e urtë shqipe", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Me kangë në buzë e me hove të reja u zgjue agimi pranveruer.", source: "Migjeni, Sonet Pranveruer", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Nata e Buzmit: në malësi hidhet në vatër një trung i madh, që digjet ngadalë gjatë netëve më të gjata të vitit.", source: "Zakone", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Dallëndyshja mbërrin në mars dhe niset sërish në shtator; shpesh e njëjta fole përdoret vit pas viti.", source: "Ornitologji", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Gjethja skuqet vetëm pasi bima ka marrë prapë prej saj gjithçka që i duhej; ngjyra është shenja se puna mbaroi.", source: "Botanikë", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Barazimi i ditës me natën ndodh dy herë në vit: pas njërit vjen drita, pas tjetrit errësira.", source: "Astronomi", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Kur bie vesa e parë e ftohtë, bletët e ulin daljen dhe nisin të hanë nga ç'kanë vënë mënjanë.", source: "Bletari", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Sulltan Nevruzi kremtohet nga bektashinjtë më njëzet e dy mars, në kohën kur dita zë ta kalojë natën.", source: "Zakone", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Burimi i mirë duket në thatësirë.", source: "Fjalë e urtë shqipe", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Pema e plagosur nuk e mbyll plagën si lëkura jonë; ajo rritet rreth saj dhe e mbulon me dru të ri.", source: "Dendrologji", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Vesa nuk bie nga qielli: ajo mblidhet mbi gjethe kur ajri ftohet aq sa nuk e mban më ujin që ka.", source: "Meteorologji", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Fjala shëndet përdoret në shqipe edhe si përshëndetje: me shëndet i thuhet atij që niset dhe atij që vesh diçka të re.", source: "Shqipe", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Guaska e çarë e kërmillit ndreqet nga vetë kafsha; vija ku ishte e thyera mbetet e dukshme përjetë.", source: "Zoologji", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Uji i një kroi që zihet gjen shteg tjetër dhe del pak më poshtë; burimi nuk humbet, po zhvendoset.", source: "Hidrologji", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Folja shërohem përdoret njësoj për njeriun, për bagëtinë dhe për pemën e sëmurë.", source: "Shqipe", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ylberi shfaqet vetëm kur dielli është pas teje dhe shiu përpara; ai lëviz bashkë me atë që e shikon.", source: "Fizikë", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Toka që lihet një vit pa mbjellë quhet djerrë; ajo pushon dhe kthen fuqinë që kishte humbur.", source: "Bujqësi", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Dëmi i një dimri të ashpër shihet te ulliri vetëm dy vjet më pas, dhe po aq vonë shihet edhe të ndrequrit.", source: "Bujqësi", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Uji i turbullt lihet të rrijë dhe kthjellohet vetvetiu; asgjë nuk hiqet prej tij, veç kohës.", source: "Fizikë", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Bora e shkrirë e mban tokën me lagështi deri thellë; ara e mbjellë pas saj nuk kërkon shi për një kohë të gjatë.", source: "Bujqësi", theme: .renewal, subtheme: .madeWhole),
        // MARK: - Light
        Passage(text: "Agim quhet edhe koha kur dielli është ende nën vijën e horizontit, po drita mjafton për të punuar jashtë.", source: "Astronomi", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Muzgu zgjat më shumë në verë sesa në dimër, sepse dielli e pret horizontin me një kënd më të vogël.", source: "Astronomi", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Mëngjes në shqipe do të thotë njëkohësisht koha e parë e ditës dhe ushqimi që hahet atëherë.", source: "Shqipe", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Zogjtë nisin të këndojnë në një radhë gati të njëjtë çdo mëngjes; ata me sy më të mëdhenj nisin të parët.", source: "Ornitologji", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Në bregun e Jonit dielli hyn në det; në malësi ai hyn pas një maje dhe drita mbetet ende një copë herë mbi qiell.", source: "Gjeografi", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Me kangë në buzë u zgjue agimi dhe ia këndoi kangën diellit t' art.", source: "Migjeni, Sonet Pranveruer", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pas perëndimit vjen një kohë e shkurtër kur qielli mbetet i kaltër dhe toka është krejt e errët.", source: "Fotografi", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Kur perëndon, dielli duket më i madh se në mesditë, ndonëse nuk është; syri e mat me majat dhe çatitë përpara.", source: "Fizikë", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Lulet e natës i hapin petlat kur bie muzgu dhe i mbyllin në zbardhëllim; ora e tyre është drita, jo nxehtësia.", source: "Botanikë", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Vesa bie më e trashë pak para zbardhjes, kur nata ka arritur ftohtësinë e saj më të madhe.", source: "Meteorologji", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Në shqipe thuhet u gdhi dhe u ngrys për të njëjtin njeri: një fjalë për të zënë dritën dhe një për ta lëshuar.", source: "Shqipe", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Nëpër qafat e maleve drita e mëngjesit bie së pari në lugina; maja ndriçohet pas tyre.", source: "Gjeografi", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Bimët nuk e numërojnë dritën, po errësirën: koha e lulëzimit vendoset nga gjatësia e natës.", source: "Botanikë", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Që t'u ndrinj mir' e të shihni, njëri-tjatërin të njihni.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Bletët e shohin dritën ultraviolete, dhe lulet u kanë vijëzuar rrugën për te mjalti me ngjyra që ne nuk i dallojmë.", source: "Entomologji", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Nuk mbulohet dielli me shoshë.", source: "Fjalë e urtë shqipe", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Fjala dritë vjen nga një rrënjë e vjetër që do të thoshte shoh; e njëjta rrënjë ka dhënë fjalën sanskrite për shikimin.", source: "Etimologji", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ulliri e njeh vjeshtën nga netët e ftohta; kokrra nis të nxihet vetëm pasi temperatura bie.", source: "Bujqësi", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Një farë e mbjellë tepër thellë e ndien mungesën e diellit dhe zgjatet drejt tij para se të bëjë gjethe.", source: "Botanikë", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Deti duket i kaltër sepse uji e mban të kaltrën dhe e pi të kuqen; ngjyra nuk është e ujit, po e asaj që mbetet.", source: "Fizikë", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Në ujë të cekët drita kthehet nga fundi; parë nga lart, thellësia lexohet si një njollë më e errët.", source: "Detari", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Lulja e diellit e ndjek diellin vetëm sa është e re; kur çelet plotësisht, ajo mbetet e kthyer nga lindja.", source: "Botanikë", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gjatësia e hijes në mesditë ndryshon çdo ditë; matja e saj tregoi ditën më të gjatë e atë më të shkurtër shumë para orëve.", source: "Astronomi", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Retë e larta e kthejnë diellin në një rreth të zbehtë; ai rreth lexohet prej kohësh si shenjë shiu.", source: "Meteorologji", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Në mes tuaj kam qëndruar e jam duke përvëluar, që t'u ap pakëzë dritë, natënë t'ua bënj ditë.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .light, subtheme: .lightItself),
        Passage(text: "Fjala hënë vjen nga një rrënjë që do të thoshte ndrit; nga e njëjta rrënjë janë latinishtja candeo dhe sanskritishtja çandra.", source: "Etimologji", theme: .light, subtheme: .lightItself),
        Passage(text: "Yll në shqipe vjen nga një fjalë shumë e vjetër me kuptimin ai që digjet.", source: "Etimologji", theme: .light, subtheme: .lightItself),
        Passage(text: "Drita e diellit që na arrin tani është nisur para rreth tetë minutash.", source: "Astronomi", theme: .light, subtheme: .lightItself),
        Passage(text: "Xixëllonja ndez dritë pa nxehtësi; gati e gjithë fuqia që shpenzon del si shkëlqim.", source: "Entomologji", theme: .light, subtheme: .lightItself),
        Passage(text: "Rruga e Qumështit shihet me sy të lirë vetëm larg dritave; në bjeshkë ajo duket si një tym i bardhë përmbi.", source: "Astronomi", theme: .light, subtheme: .lightItself),
        Passage(text: "Flaka ndriçon nga grimcat e nxehta të blozës brenda saj; një flakë krejt e pastër jep pak shkëlqim.", source: "Fizikë", theme: .light, subtheme: .lightItself),
        Passage(text: "Nuk të ngroh zjarri i kashtës.", source: "Fjalë e urtë shqipe", theme: .light, subtheme: .lightItself),
        Passage(text: "Në një natë pa hënë syri i njeriut e dallon një qiri nga shumë kilometra larg, po nuk lexon dot një shkronjë.", source: "Fiziologji", theme: .light, subtheme: .lightItself),
        Passage(text: "Në disa netë deti ndriçon aty ku prishet uji; drita vjen nga gjallesa të imëta që ndizen kur trazohen.", source: "Biologji detare", theme: .light, subtheme: .lightItself),
        Passage(text: "Ylberi nuk është hark: ai është rreth i plotë, po gjysma e poshtme e tij bie nën horizont.", source: "Fizikë", theme: .light, subtheme: .lightItself),
        Passage(text: "Bora shkëlqen sepse çdo kristal i saj e kthen rrezen nga një anë tjetër; ajo nuk i shton asnjë ngjyrë.", source: "Fizikë", theme: .light, subtheme: .lightItself),
        // MARK: - Pattern
        Passage(text: "Njëzet në shqipe është një-zet dhe dyzet është dy-zet: numërimi i vjetër ka shkuar me njëzetëshe.", source: "Shqipe", theme: .pattern, subtheme: .counted),
        Passage(text: "Njëmbëdhjetë do të thotë një mbi dhjetë; deri te nëntëmbëdhjetë shqipja i ngjit numrat mbi dhjetën.", source: "Shqipe", theme: .pattern, subtheme: .counted),
        Passage(text: "Lulja e ullirit ka katër petla; ajo e qershisë ka pesë. Numri qëndron i njëjtë në gjithë familjen.", source: "Botanikë", theme: .pattern, subtheme: .counted),
        Passage(text: "Numri i petlave bie shpesh mbi radhën tre, pesë, tetë, trembëdhjetë, ku secili është shuma e dy të mëparshmëve.", source: "Botanikë", theme: .pattern, subtheme: .counted),
        Passage(text: "Gjethet rreth një kërcelli nuk vendosen kuturu: secila kthehet nga e mëparshmja me po atë kënd.", source: "Botanikë", theme: .pattern, subtheme: .counted),
        Passage(text: "Bleta e mat qelizën e hojës me trupin e vet; të gjitha dalin gati të njëjta pa u matur asnjëherë.", source: "Entomologji", theme: .pattern, subtheme: .counted),
        Passage(text: "Trungu i prerë i tregon vitet me unaza: të ngushtat janë vite thatësire, të gjerat vite me shi.", source: "Dendrologji", theme: .pattern, subtheme: .counted),
        Passage(text: "Një kalli gruri mban zakonisht rreth pesëdhjetë kokrra; nga një kokërr e mbjellë dalin disa kallinj.", source: "Bujqësi", theme: .pattern, subtheme: .counted),
        Passage(text: "Kanuni i Lekë Dukagjinit është ndarë në libra dhe në nyje, dhe brenda tyre numërohet paragraf pas paragrafi.", source: "Kanuni i Lekë Dukagjinit", theme: .pattern, subtheme: .counted),
        Passage(text: "Alfabeti i shqipes ka tridhjetë e gjashtë shkronja, nga të cilat nëntë shkruhen me dy shenja bashkë.", source: "Shqipe", theme: .pattern, subtheme: .counted),
        Passage(text: "Bletët nuk numërohen një nga një, po me korniza; një zgjua i plotë matet me peshë.", source: "Bletari", theme: .pattern, subtheme: .counted),
        Passage(text: "Në lagunën e Karavastasë folezon pelikani kaçurrel, dhe çerdhet e tij numërohen një nga një çdo pranverë.", source: "Ornitologji", theme: .pattern, subtheme: .counted),
        Passage(text: "Hoja e bletës është plot gjashtëkëndësha, sepse ashtu mbushet e gjithë hapësira pa mbetur asgjë jashtë.", source: "Gjeometri", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ndoqe fillin gjete lëmshin.", source: "Fjalë e urtë shqipe", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Guri i rrumbullkët nuk zë vend.", source: "Fjalë e urtë shqipe", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Xhubleta, fustani kumbonë i malësores, punohet me shirita të qepur mbi njëri-tjetrin; më 2022 ajo u mor në mbrojtje nga UNESCO.", source: "Etnografi", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Muri i thatë ngrihet pa llaç: gurët mbahen vetëm nga pesha dhe nga mënyra si preken.", source: "Ndërtim", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Kalldrëmi shtrohet me gurë të papunuar; secili prej tyre zë vendin që i lënë të tjerët rreth e rrotull.", source: "Arkitekturë", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ura me hark qëndron sepse gurët shtyjnë njëri-tjetrin; hiqe njërin dhe bie e tëra.", source: "Ndërtim", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Filigrani punohet me tela të hollë argjendi, të përdredhur dhe të vendosur aq afër sa e mbajnë njëri-tjetrin.", source: "Zejtari", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Shporta thuret duke kaluar një thupër sipër dhe një poshtë; e gjithë forca e saj vjen nga ai ndërrim.", source: "Zejtari", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Rrënjët e pemëve në një pyll takohen nën dhe dhe shkëmbejnë lëndë përmes fijeve të kërpudhave.", source: "Pyjari", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Çatia me rrasa guri e shtëpive të Thethit vendoset pa gozhdë; rrasat mbahen nga pjerrësia dhe nga njëra-tjetra.", source: "Arkitekturë popullore", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Në një valle të mbyllur duart lidhen dhe hapi bëhet i njëjtë; kush ndalet, i ndal të gjithë.", source: "Folklor", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Fjala kanun vjen nga greqishtja kanón, që do të thoshte shufër matëse, dhe më pas rregull.", source: "Etimologji", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Shqipja e vë nyjën në fund të emrit: mal bëhet mali. Ajo që gjuhët e tjera e nxjerrin përpara, shqipja e mban brenda.", source: "Shqipe", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Shqipja ka një mënyrë foljore që quhet habitore dhe përdoret kur diçka del ndryshe nga ç'e prisje: paska, qenka.", source: "Shqipe", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Ka edhe një mënyrë dëshirore, të bërë vetëm për urime: qofsh me shëndet, rrofsh, të lumtë.", source: "Shqipe", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Emri shqip për kohën, kohë, del nga e njëjta rrënjë e lashtë si fjala sllave ças.", source: "Etimologji", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Frang Bardhi botoi më 1635 në Romë një fjalor latinisht dhe shqip, të parin që u shtyp për këtë gjuhë.", source: "Histori e gjuhës", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Emri në shqipe ka pesë rasa dhe dy trajta, të shquarën dhe të pashquarën.", source: "Gramatikë", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kanuni nuk u shkrua nga një njeri i vetëm: Shtjefën Gjeçovi mblodhi gojë më gojë atë që zbatohej, dhe libri doli më 1933.", source: "Etnografi", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Fqinj vjen nga latinishtja vicinus; ai që rri pranë e ka emrin prej Romës.", source: "Etimologji", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Mbiemri shkon pas emrit dhe merr një nyjë të vetën: djalë i mirë, vajzë e mirë.", source: "Gramatikë", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Emrat e muajve mbajnë punët e tyre: qershor e ka nga qershia, korrik nga korrja.", source: "Shqipe", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Rendi i fjalëve në shqipe është i lirë, sepse mbaresat tregojnë vetë kush ia bën kujt.", source: "Gramatikë", theme: .pattern, subtheme: .orderNamed),
        // MARK: - Ground
        Passage(text: "Malin lëvroje për lisin, fushën për misrin.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mos u zër për degësh, po për rrënjësh.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Toka e kuqe e merr ngjyrën nga hekuri i ndryshkur brenda saj; ajo ngrohet shpejt dhe thahet shpejt.", source: "Pedologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Nën një pëllëmbë tokë jetojnë më shumë gjallesa sesa ka njerëz mbi gjithë botën.", source: "Pedologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "E njëjta hardhi jep verë tjetër në Berat dhe tjetër në Rrëzë; toka nuk lëviz bashkë me bimën.", source: "Vreshtari", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Gëlqerorja e Bjeshkëve e pi ujin shpejt; prandaj lart ka pak burime dhe poshtë ka shumë.", source: "Hidrogjeologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Krimbi i dheut kalon nëpër vetvete disa herë peshën e vet çdo vit dhe e lë tokën më të butë.", source: "Zoologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Fjala vend vjen nga folja vë: një vend është aty ku diçka është vënë.", source: "Etimologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Bimët bishtajore mbajnë në rrënjë kokrriza me baktere që e marrin azotin nga ajri dhe ia lënë dheut.", source: "Botanikë", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Plehu i vjetër nuk e ushqen bimën drejtpërdrejt; ai ushqen tokën, dhe toka ushqen bimën.", source: "Bujqësi", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Në shqipe dhé do të thotë edhe truall edhe atdhe; kur thuhet dheu im, thuhen të dyja bashkë.", source: "Shqipe", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Rëra, balta dhe argjila ndahen vetëm nga madhësia e kokrrizës; i njëjti shkëmb i jep të treja.", source: "Pedologji", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Maletë me gurë, fushat me bar shumë, aratë me grurë, më tutje një lumë.", source: "Andon Zako Çajupi, Fshati im", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ku i duket balta më e ëmbël se mjalta? Në vend të tij.", source: "Andon Zako Çajupi, Ku kemi lerë", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kur pi ujë, kujto burimin.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Fshati që duket s'do kallauz.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Arbëreshët e Italisë ikën në shekullin e pesëmbëdhjetë dhe e kanë folur shqipen në Kalabri e Siçili për më se pesëqind vjet.", source: "Histori", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Jeronim de Rada i botoi Këngët e Milosaos në Napoli më 1836, në gjuhën që stërgjyshërit e tij kishin marrë me vete.", source: "Letërsi", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Bjeshkë quhet mali i lartë ku bagëtia shkon në verë; e njëjta fjalë tregon malin dhe kullotën.", source: "Shqipe", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Berati quhet qyteti i një mbi një dritareve, sepse shtëpitë ngjiten njëra mbi tjetrën në faqen e kodrës.", source: "Arkitekturë", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Mall do të thotë dëshira për diçka që nuk e ke pranë; ajo mbahet për një vend njësoj si për një njeri.", source: "Shqipe", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Vendlindja në shqipe është një fjalë e vetme: vendi dhe lindja të ngjitura.", source: "Shqipe", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Shtëpitë e vjetra të Gjirokastrës janë ngritur me gur e me rrasa nga i njëjti mal ku ato qëndrojnë.", source: "Arkitekturë", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Arvanitasit e Greqisë e quajnë të folmen e tyre arbërisht, me emrin që kjo gjuhë kishte para se të quhej shqipe.", source: "Gjuhësi", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Vatra është vendi i zjarrit në mes të shtëpisë; fjala është e lashtë dhe dikur do të thoshte vetë zjarrin.", source: "Etimologji", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Gjithkush teshat i lan në shtëpinë e vet.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Shtëpinë e mbajnë të gjitha shtyllat.", source: "Fjalë e urtë shqipe", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kopshti nuk mbetet kopsht vetvetiu: lëre dy vjet pa dorë dhe ai kthehet në atë që ishte toka rreth tij.", source: "Kopshtari", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Muri i thatë rreth një are mbahet duke i vënë prapë gurët që bien; puna nuk mbaron kurrë, po nuk është e rëndë.", source: "Bujqësi", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ulliri kërkon të krasitet çdo dy vjet; pa dorë njeriu ai jep kokrra çdo vit e më pak.", source: "Bujqësi", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kroi kërkon pastrim: gjethet që bien brenda tij e mbyllin vrimën nga del uji.", source: "Bujqësi", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Bari i keq nuk mundet një herë e mirë; ai kthehet çdo vit dhe kopshtari kthehet bashkë me të.", source: "Kopshtari", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Butrinti mbeti nën ujë e nën baltë për shekuj; ajo baltë e ruajti derisa u zbulua sërish.", source: "Arkeologji", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Sipas besimit të vjetër shqiptar, ora e shtëpisë është shpirti që ruan një vend të caktuar dhe nuk lëviz me njerëzit.", source: "Folklor", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Vreshti pritet çdo dimër dhe lidhet çdo pranverë; nga këto dy punë varet rrushi i vitit.", source: "Vreshtari", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Parku i Vjosës u shpall më 2023 dhe është i pari në Evropë i bërë për një lumë të tërë, nga burimi deri në det.", source: "Mjedis", theme: .ground, subtheme: .aKeptPlace),
        // MARK: - Travel
        Passage(text: "Fara e panjës bie duke u rrotulluar; rrotullimi e mban në ajër aq gjatë sa era ta marrë me vete.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kapsula e lulëkuqes ka vrima lart; era e tund kërcellin dhe farat dalin prej saj si nga një kripore.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Manaferra dhe rrushi i egër udhëtojnë brenda zogjve; kokrra e vogël del e paprekur dhe bie larg pemës.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bishtajat e disa bimëve përdridhen kur thahen dhe i hedhin farat disa metra larg vetes.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Fara e dëllinjës kalon nëpër zorrët e zogut dhe mbin më mirë pasi ka kaluar.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ferrat kapen pas leshit të bagëtisë dhe zbresin nga bjeshka bashkë me kopenë.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Arra nuk shkon larg vetvetiu; ajo shkon aq sa e çon ketri që e fsheh dhe pastaj e harron.", source: "Zoologji", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Disa bimë bregdetare i kanë farat që notojnë me muaj në ujë të kripur dhe mbijnë sapo dalin në rërë.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bimët e gurishtes i lëshojnë farat me ujin e shiut që rrjedh; udha e tyre është një vijë uji.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Më të lehtat peshojnë aq pak sa një erë e mesme i mban në ajër me kilometra pa i lëshuar.", source: "Botanikë", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bletët nuk mbartin fara, po pjalm; udhëtimi i parë ndodh para se fara të jetë bërë.", source: "Entomologji", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Në zgavrën e një lisi gjendet ndonjëherë një grumbull i tërë kokrrash, sjellë aty nga një zog gjatë vjeshtës.", source: "Ornitologji", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Shkon një herë, bëhen gjurma; dy tri herë bëhet udhë.", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .theRoad),
        Passage(text: "Po nise një udhë, do kaptosh dhe sheshe, dhe male, dhe gurë.", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .theRoad),
        Passage(text: "Qentë le të lehin, karvanet të shkojnë përpara.", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kush mori udhë, dhe do të lodhet.", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .theRoad),
        Passage(text: "Fjala udhë vjen nga një rrënjë e vjetër që do të thoshte çoj; nga po ajo rrënjë vjen edhe fjala gjermane Weg.", source: "Etimologji", theme: .travel, subtheme: .theRoad),
        Passage(text: "Rrugë e ka prejardhjen nga një fjalë latine për rrudhën: nga rrudha u bë brazda dhe nga brazda rruga.", source: "Etimologji", theme: .travel, subtheme: .theRoad),
        Passage(text: "Via Egnatia e lidhte Durrësin me Selanikun dhe më tej me Bizantin; pjesë të saj shihen ende sot.", source: "Histori", theme: .travel, subtheme: .theRoad),
        Passage(text: "Në mal shtegu nuk shkon kurrë drejt: ai ndjek pjerrësinë që kali mund të ngjitet, jo vijën më të shkurtër.", source: "Gjeografi", theme: .travel, subtheme: .theRoad),
        Passage(text: "Folja shtegtoj vjen nga shteg dhe përdoret njësoj për njerëzit dhe për zogjtë.", source: "Shqipe", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ura e Mesit mbi Kir, afër Shkodrës, ka trembëdhjetë harqe dhe u ngrit për kuajt me barrë.", source: "Histori", theme: .travel, subtheme: .theRoad),
        Passage(text: "Fjala urë vjen nga një rrënjë që do të thoshte mbuloj; ura e mbulon atë që s'kalohet dot.", source: "Etimologji", theme: .travel, subtheme: .theRoad),
        Passage(text: "Endem do të thotë eci pa një cak të caktuar; fjala e ka rrënjën te një folje shumë e vjetër me kuptimin shkoj.", source: "Etimologji", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ngopet deti me lumenj?", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .farOff),
        Passage(text: "Deti ka ujë boll, po me u pi s'pihet.", source: "Fjalë e urtë shqipe", theme: .travel, subtheme: .farOff),
        Passage(text: "Fjala det vjen nga një rrënjë që do të thoshte i thellë; e njëjta rrënjë ka dhënë anglishten deep.", source: "Etimologji", theme: .travel, subtheme: .farOff),
        Passage(text: "Edhe ndër qiej fluturonj, edhe brënda në det qëndronj.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .travel, subtheme: .farOff),
        Passage(text: "Dallëndyshja që lë Shqipërinë në vjeshtë kalon Saharanë dhe e kalon dimrin në jug të Afrikës.", source: "Ornitologji", theme: .travel, subtheme: .farOff),
        Passage(text: "Ngjala e liqeneve tona shkon të pjellë në detin Sargaso, në anën tjetër të Atlantikut.", source: "Zoologji", theme: .travel, subtheme: .farOff),
        Passage(text: "Shqipja nuk ka gjuhë motër: ajo është e vetmja e degës së saj, si greqishtja dhe armenishtja e degëve të tyre.", source: "Gjuhësi", theme: .travel, subtheme: .farOff),
        Passage(text: "Nga majat e Bjeshkëve të Nemuna, në ditë të kthjellët, shihen male që qëndrojnë në tri shtete.", source: "Gjeografi", theme: .travel, subtheme: .farOff),
        Passage(text: "E Bukura e Dheut, në përrallat shqiptare, rri gjithnjë në një vend ku arrihet vetëm pas një udhe shumë të gjatë.", source: "Folklor", theme: .travel, subtheme: .farOff),
        Passage(text: "Mali i Tomorit duket nga fusha dhjetëra kilometra larg dhe ka shërbyer gjatë si shenjë orientimi.", source: "Gjeografi", theme: .travel, subtheme: .farOff),
        Passage(text: "Shkëlqimi i disa yjeve që duken sot është nisur para se të shtypej libri i parë në gjuhën shqipe.", source: "Astronomi", theme: .travel, subtheme: .farOff),
        Passage(text: "Arbëreshët e Italisë e quajnë veten arbëreshë, me emrin që kjo popullsi mbante para se të shpërndahej.", source: "Gjuhësi", theme: .travel, subtheme: .farOff),
        // MARK: - Meeting
        Passage(text: "Miku i mirë vjen nga porta.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Mirë se erdhe thotë i zoti i shtëpisë; miku përgjigjet mirë se të gjeta. Përshëndetja nuk plotësohet pa të dyja.", source: "Zakone", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Në Këngët e Milosaos, që Jeronim de Rada i botoi më 1836, i riu dhe vasha takohen te kroi: ai i kërkon një pikë ujë.", source: "Letërsi", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kur dy zëra këndojnë të njëjtën notë pak ndryshe, dëgjohet një rrahje e tretë që s'e bën asnjëri prej tyre.", source: "Akustikë", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Pjalmit i mjafton një prekje: kokrra që bie mbi pistil nis brenda pak orësh të lëshojë tubin drejt vezës.", source: "Botanikë", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kur dy tufa bletësh ndeshen në ajër, ato nuk përzihen: secila e njeh erën e vet.", source: "Entomologji", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Përplasja e dy masave ajri me nxehtësi të ndryshme e bën shiun; asnjëra prej tyre nuk do ta kishte bërë vetëm.", source: "Meteorologji", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Bleta që gjen lule kthehet dhe kërcen mbi hoje; nga këndi i asaj valleje të tjerat e marrin drejtimin.", source: "Entomologji", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Dy lumenj që bashkohen mbajnë zakonisht emrin e njërit, po vendi ku ndodh kjo ka gjithnjë një emër të vetin.", source: "Gjeografi", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Folja ndeshem përdoret edhe për njerëzit që takohen edhe për dy gjëra që përplasen.", source: "Shqipe", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Eklipsi ndodh sepse hëna dhe dielli, parë nga toka, duken pothuajse njësoj të mëdhenj; kjo është një rastësi e kohës sonë.", source: "Astronomi", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Aty ku takohen dy rryma deti mblidhet ushqim dhe pas tij vijnë peshqit; vija njihet nga shkuma mbi sipërfaqe.", source: "Detari", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Me një ka nuk bëhen pendë.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Peshku në det, kripa në tokë, po bashkohen në tigan.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mendja me mendjen, pjellin mëndje.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "S'bëhet lëmi me një kalli.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Punën nuk e bën një gisht, po e bën grushti.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Kur je veti i dytë, të ngoh dhe fryma e shokut.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Disa lloje fiku nuk lidhin pa një grerëz të imët që hyn brenda kokrrës; secila palë ka vetëm tjetrën.", source: "Botanikë", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Likeni nuk është një gjallesë, po dy: një kërpudhë dhe një alge që rrojnë si trup i vetëm.", source: "Biologji", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Lulja që çelet natën pret fluturën e natës; asnjëra nga të dyja nuk do të kishte kuptim pa tjetrën.", source: "Botanikë", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Shumica e pemëve e marrin ujin përmes kërpudhave në rrënjë dhe u japin atyre sheqer; asnjëra anë nuk rron mirë vetëm.", source: "Pyjari", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ulliri lulëzon shumë dhe lidh pak; kokrrat vijnë më mirë kur pranë tij rritet edhe një lloj tjetër ulliri.", source: "Bujqësi", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Në zgjua mëma nuk ushqehet dot vetë dhe punëtoret nuk pjellin; asnjëra prej tyre nuk bën dot jetë më vete.", source: "Entomologji", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Shpija e Shqyptarit âsht e Zotit e e mikut.", source: "Kanuni i Lekë Dukagjinit", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Mikut do t'i bâhet nderë: bukë e krypë e zêmer.", source: "Kanuni i Lekë Dukagjinit", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Miku nuk mund të hîjë në shpí, pá bâ zâ n'oborr.", source: "Kanuni i Lekë Dukagjinit", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Mikut i lëshohet vendi dhe i dëgjohet kuvendi.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Miku nuk vjen për thelë e lëng, po për fjalë e për kuvend.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kur të vjen nevojtari në derë, po s'pate gjë, jep një gotë ujë.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Rrugën për te miku, mos e lër të zërë bar.", source: "Fjalë e urtë shqipe", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Fjala mik vjen nga latinishtja amicus, dhe në shqipe ajo tregon njëkohësisht shokun dhe atë që troket në derë.", source: "Etimologji", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Emri i shtëpisë mendohet të vijë nga latinishtja hospitium, që ishte vendi ku pritej i huaji.", source: "Etimologji", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Urdhëro është fjala me të cilën ftohesh brenda ose të jepet diçka; fjalë për fjalë ajo do të thotë jep urdhër.", source: "Shqipe", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Buj do të thotë kaloj natën diku; prej saj mendohet të vijë bujar, që sot do të thotë dorëdhënë.", source: "Etimologji", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Në kullën e malësisë oda e miqve ishte dhoma më e mirë e shtëpisë dhe mbahej e shtruar edhe kur nuk pritej kush.", source: "Etnografi", theme: .meeting, subtheme: .theMannersOfIt),
        // MARK: - Kinship
        Passage(text: "Fjala vëlla nuk vjen nga emri i lashtë indoevropian i vëllait: ajo u bë brenda shqipes, nga rrënjët e fjalëve vetë dhe lind.", source: "Etimologji", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Motër vjen nga fjala e lashtë për nënën dhe do të thoshte ajo që ka të njëjtën mëmë.", source: "Etimologji", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Farefis është një fjalë e vetme, e bërë nga farë dhe fis.", source: "Shqipe", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Dy degë që fërkohen për vite mund të ngjiten dhe të bëhen një; pyjarët e quajnë këtë shartim i vetvetishëm.", source: "Dendrologji", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Rrënjët e dy pemëve të një lloji, kur takohen nën dhe, shpesh bashkohen dhe e ndajnë ujin mes tyre.", source: "Pyjari", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Me nji tra nuk mban shtëpia.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Hardhia shartohet mbi një rrënjë tjetër; pjesa e poshtme dhe ajo e sipërme mbeten dy bimë që rrojnë si një.", source: "Vreshtari", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Në një koloni korali gjallesat janë të lidhura me ind të përbashkët, dhe ushqimi i njërës kalon te tjetra.", source: "Biologji detare", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Vëllamëria ishte një lidhje e zgjedhur: dy veta bëheshin vëllezër pa qenë, dhe kanuni e njihte si të afërm.", source: "Etnografi", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kumbaria lidhte dy familje pa gjak: kumbari i fëmijës mbetej i afërt për gjithë jetën.", source: "Etnografi", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Krushq quhen ata që bashkohen me anë martese; fjala vjen nga latinishtja consocer.", source: "Etimologji", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Miqësi do të thotë edhe shoqëri edhe lidhje krushqie: dy familje që martohen bëhen miq.", source: "Shqipe", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Gjithë tuajt' i kam parë, mëm' e at' e fis e farë.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Përmbi za që lshon bylbyli, gjuha shqipe m'shungullon.", source: "Ndre Mjeda, Gjuha Shqype", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Geg' e tosk', malsi, jallia jan' nji komb.", source: "Ndre Mjeda, Gjuha Shqype", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Porsi kanga e zogut t'verës, qi vallzon n'blerim të prillit.", source: "Gjergj Fishta, Gjuha Shqipe", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ah! po; â' e ambël fjala e sajë, porsi gjumi m'nji kërthi.", source: "Gjergj Fishta, Gjuha Shqipe", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Shqipja e ndan vëllanë e babait nga vëllai i nënës: i pari është xhaxha, i dyti dajë.", source: "Shqipe", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Dy emra të vjetër të afrisë kanë ardhur drejt nga Roma: ungj nga avunculus dhe emtë nga amita.", source: "Etimologji", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Nip do të thotë njëkohësisht djali i vëllait dhe djali i djalit; fjala është nga më të lashtat e gjuhës.", source: "Shqipe", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Nderi, i shkruar që më 1555, e ka rrënjën te një fjalë shumë e vjetër me kuptimin faqe ose përballë.", source: "Etimologji", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Sipas besimit të vjetër, çdo njeri ka një orë të vetën: një shpirt që e shoqëron dhe që nuk shihet.", source: "Folklor", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Shoq do të thotë edhe shok edhe burrë i shtëpisë; fjala është marrë nga latinishtja socius.", source: "Etimologji", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Tungjatjeta, përshëndetja më e zakonshme shqipe, është shkurtim i një urimi: t'u ngjattë jeta.", source: "Shqipe", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Njeriu pa shokë, si muri pa tokë.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Pa djalë e pa gocë rrova, pa shok nuk rrova.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Njeriu ka nevojë më tepër për dashuri, se për lavdi.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Shokë bashkë, e bukë veç.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Shtëpia pa fëmijë, si nata pa yje.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Mikun nderoje dhe vëre në qoshe, po zot shtëpie të jesh vetë.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ku ka zemër ka dhe krahë.", source: "Fjalë e urtë shqipe", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Në bëhi shokë me mua, në më doni si u dua, njëri-tjetërin në doni.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kam qënë mik me njerinë, andaj i di e më dinë.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dy vetë që ecin bashkë e ndërrojnë hapin pa e vënë re dhe brenda pak minutash shkelin njësoj.", source: "Fiziologji", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Në vallen e mbyllur kërcimtarët mbahen për dore ose për brezi, dhe rrethi hapet vetëm që të hyjë dikush tjetër.", source: "Folklor", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Në sofrën e ulët hahet nga një enë e vetme; kush ulet aty ha të njëjtën gjellë me të tjerët.", source: "Etnografi", theme: .kinship, subtheme: .twoPeople),
        // MARK: - Peace
        Passage(text: "Lumi i thellë, s'ka ushëtimë.", source: "Fjalë e urtë shqipe", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Atje ku fle ujët, atje është më thellë.", source: "Fjalë e urtë shqipe", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Isoja është zëri i mbajtur poshtë të tjerëve në këngën shumëzërëshe të jugut; ai nuk ndryshon dhe nuk këputet.", source: "Muzikë popullore", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Iso-polifonia shqiptare u mor në mbrojtje nga UNESCO më 2005; ajo këndohet pa asnjë vegël, vetëm me zëra.", source: "Muzikë popullore", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Pupla e bufit ka buzë të grisura, që e ndajnë ajrin në rryma të imëta; prandaj fluturimi i tij nuk dëgjohet.", source: "Zoologji", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Bora e re e thith zhurmën: hapësirat mes kristaleve e marrin brenda dhe nuk e kthejnë.", source: "Fizikë", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Kanuni njihte një besë njëzet e katër orëshe dhe një tjetër njëmujore; sa kohë zgjaste, asgjë nuk lëvizte.", source: "Kanuni i Lekë Dukagjinit", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "I urtë në shqipe do të thotë edhe i mençur edhe i qetë; për një fëmijë që rri pa bërë zë thuhet se rri urtë.", source: "Shqipe", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Nën ujë zëri shkon shumë më shpejt se në ajër, po veshi ynë nuk e dallon më nga cila anë vjen.", source: "Fizikë", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Fëshfërima ndryshon sipas pemës: plepi bën një tingull të imët, sepse bishti i gjethes së tij është i sheshtë.", source: "Botanikë", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Në shpellat gëlqerore uji rrëshqet pa u ndier derisa bie nga një lartësi; vetëm atëherë e merr vesh kush.", source: "Gjeologji", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Në Syrin e Kaltër uji del me forcë nga një gropë karstike; zhytësit kanë zbritur rreth pesëdhjetë metra pa i gjetur fundin.", source: "Gjeografi", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Fjala paqe në shqipe vjen drejt nga latinishtja pax.", source: "Etimologji", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Pushim vjen nga folja pushoj, e marrë nga latinishtja pausare, që do të thoshte të ndalosh.", source: "Etimologji", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Armëpushim është një fjalë e vetme, e bërë duke ngjitur armë dhe pushim.", source: "Shqipe", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Besa është fjala e dhënë; kur jepet, ajo i ndal të gjitha mes dy palëve për aq kohë sa është dhënë.", source: "Kanuni i Lekë Dukagjinit", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Në Mesharin e Buzukut, të vitit 1555, besë është fjala që përkthen latinishten fides.", source: "Histori e gjuhës", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Besa ka hyrë e patjetërsuar në gjuhët fqinje, sepse nuk gjendej fjalë tjetër që ta mbante atë kuptim.", source: "Gjuhësi", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Studiuesit e lidhin besën me atë rrënjë të lashtë që ka dhënë latinishten fides, besimin që dy palë kanë te njëra-tjetra.", source: "Etimologji", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Pajtim do të thotë të vish sërish në ujdi; folja pajtohem përdoret edhe kur dy njerëz thjesht bien dakord.", source: "Shqipe", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Kuvend vjen nga latinishtja conventum dhe mban dy kuptime njëherësh: mbledhja dhe biseda.", source: "Etimologji", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Ndal dhe ndalem janë e njëjta folje: e ndal diçka tjetër, ose ndalem vetë.", source: "Shqipe", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Dijet e mëdha janë në fjalë të shkurtra.", source: "Fjalë e urtë shqipe", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Fjalë pak e punë shumë.", source: "Fjalë e urtë shqipe", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Jakëni rreth meje rrini, flisni, qeshni, hani, pini.", source: "Naim Frashëri, Fjalët e Qiririt", theme: .peace, subtheme: .atEase),
        Passage(text: "Xhiroja e mbrëmjes: njerëzit dalin pas punës dhe ecin lart e poshtë të njëjtës rrugë, pa shkuar askund.", source: "Zakone", theme: .peace, subtheme: .atEase),
        Passage(text: "Prehër, gjiri ku mbahet fëmija, vjen nga një rrënjë e vjetër që do të thoshte përpara.", source: "Etimologji", theme: .peace, subtheme: .atEase),
        Passage(text: "Kafeja pihet ngadalë dhe në filxhan të vogël; ajo është më shumë masë kohe sesa pije.", source: "Zakone", theme: .peace, subtheme: .atEase),
        Passage(text: "Nën hijen e një rrapi nxehtësia bie disa gradë; prandaj rrapi është mbjellë në mes të sheshit.", source: "Botanikë", theme: .peace, subtheme: .atEase),
        Passage(text: "Delja e ngopur shtrihet dhe ripërtypet; ripërtypja bëhet vetëm kur kafsha nuk ka frikë nga asgjë.", source: "Zoologji", theme: .peace, subtheme: .atEase),
        Passage(text: "Rehat, e ardhur nga turqishtja, thuhet për atë që nuk ka gjë për të bërë dhe as gjë për ta shqetësuar.", source: "Shqipe", theme: .peace, subtheme: .atEase),
        Passage(text: "Macja i mban veshët të lëvizshëm edhe kur fle; qetësia e saj nuk është mungesë vëmendjeje.", source: "Zoologji", theme: .peace, subtheme: .atEase),
        Passage(text: "Shtruar do të thotë edhe i pangutur edhe i vendosur në vend: një bisedë e shtruar dhe një sofër e shtruar.", source: "Shqipe", theme: .peace, subtheme: .atEase),
        Passage(text: "Pas ngrënies gjaku shkon drejt stomakut dhe njeriut i vjen gjumë; kjo nuk është përtaci, po punë e brendshme.", source: "Fiziologji", theme: .peace, subtheme: .atEase),
        Passage(text: "Në verë kopetë ngjiten në bjeshkë dhe rrinë aty deri në vjeshtë; për ata muaj e gjithë puna është vetëm të ruash.", source: "Blegtori", theme: .peace, subtheme: .atEase),
        Passage(text: "Gjumi nuk është një gjendje e vetme: brenda një nate ai kalon disa herë nëpër po atë radhë fazash.", source: "Fiziologji", theme: .peace, subtheme: .atEase),
    ]
}
