import Foundation

/// The Arabic passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let arabic: [Passage] = [
        // MARK: Beginnings
        Passage(text: "الإنبات: اللحظة التي تكفّ فيها البذرة عن كونها مخزونًا وتصير نباتًا. خطوة لا رجعة فيها.", source: "علم النبات", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الاستهلال من الجذر الذي جاء منه الهلال. صرخة المولود الأولى استهلال، ومطلع القصيدة استهلال، وأول ما يُرى من القمر هلال.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الفجر من فجّر أي شقّ؛ يقال فجّر الماء من الصخر. مطلع النهار في العربية انشقاق قبل أن يكون ضوءًا.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "أصبح فعلٌ معناه صار، وأصله دخول الصبح. ومن الجذر نفسه المصباح، فالصيرورة والضوء من أصل واحد.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "البذرة حين تشقّ غلافها تُخرج الجُذير قبل كل شيء: تنزل قبل أن تصعد.", source: "علم النبات", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الابتكار من الجذر ب ك ر، جذر البُكور والباكر والبِكر. الجديد في العربية شيءٌ جاء مبكرًا.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "النَّوْر هو الزهر الأبيض، من الجذر الذي جاء منه النور والمنارة. الشجرة إذا أزهرت قيل إنها نوّرت.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "أول ما يخرج من البذرة ليس ورقة بل فِلقة: غذاءٌ مخزون تحوّل إلى ما يشبه الورقة، ثم ذبل بعد أن أدّى عمله.", source: "علم النبات", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الصوص يفقس بسنٍّ صغيرة على منقاره لا عمل لها سوى كسر القشرة، وتسقط بعد الفقس بأيام.", source: "علم الحيوان", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "بزغ فعلٌ يُقال لطلوع الشمس ولظهور السنّ الأولى عند الطفل: بزغت الشمس، وبزغ النابُ.", source: "العربية", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الينبوع هو النقطة التي يخرج فيها الماء الجوفي إلى السطح أول مرة، ومن عندها يبدأ النهر اسمه.", source: "الجغرافيا", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "البرعم مغلقٌ بورقات متراكبة تُسمى الحراشف، وحين ينفتح لا يعود ينغلق.", source: "علم النبات", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "الزيادة في العربية تكبّر الكلمة دون أن تمسّ أصلها: من علم يأتي عالم ومعلوم ومعلّم وتعليم وعلامة.", source: "الصرف", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "من ثلاثة أحرف ك ت ب: كتب، وكتاب، ومكتبة، ومكتب، وكاتب، ومكتوب. جذرٌ واحد يُخرج مكتبةً كاملة.", source: "علم اللغة", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "حبة الخردل من أصغر ما يُزرع من البذور، والشجيرة التي تخرج منها تعلو عن قامة الإنسان.", source: "علم النبات", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "مستعمرة النمل كلها تبدأ بملكة واحدة مخصَّبة؛ وفي بعض الأنواع تبلغ بعد سنين ملايين الأفراد.", source: "علم الحشرات", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "الشعاب المرجانية تنمو بأن يستنسخ بوليبٌ واحد نفسه آلاف المرات، حتى تمتد كيلومترات.", source: "علم البحار", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "رُبَّ رميةٍ من غير رامٍ.", source: "مثل عربي", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "الفطر يبدأ بخيط واحد لا تراه العين، ومن هذا الخيط تنشأ شبكةٌ قد تمتد تحت هكتارات من الغابة.", source: "علم الفطريات", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "غرسة الزيتون تبقى سنين لا تكاد تُرى، ثم تعمّر بعد ذلك ألف سنة في بعض بساتين المتوسط.", source: "البستنة", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "الحصاة أصلٌ لعلم كامل: الإحصاء مشتق من الحصى، لأن العدّ كان يُضبط بالحجارة الصغيرة.", source: "العربية", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "القمح الذي يُخبز منه اليوم كان قبل عشرة آلاف سنة عشبًا بريًا في سفوح الهلال الخصيب.", source: "تاريخ الزراعة", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "من الجذر ن ب ت: نبت، ونبات، ومَنبِت. والمنبت هو الموضع الذي خرج منه الشيء أول مرة.", source: "العربية", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "الحرف الواحد في العربية قد يكون كلمة تامة: و، ك، ل، ب. أصغر ما في الكتابة يحمل معنى كاملًا.", source: "النحو العربي", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "في التأنّي السلامة وفي العجلة الندامة.", source: "مثل عربي", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "الجذر الثلاثي يسبق كل شيء في العربية: من س ل م يخرج السلام والسلامة والتسليم، ولا واحد منها يستطيع مغادرة جذره.", source: "علم اللغة", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "الشجرة التي تُقلَّم في سنيها الأولى تحمل أثر ذلك التقليم في جذعها بعد خمسين سنة.", source: "علم الغابات", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "الأساس طبقةٌ لا يراها أحد بعد أن يقوم البناء، ولا يستطيع أحد تغييرها بعد ذلك.", source: "الهندسة المعمارية", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "مجرى النهر في ألفه الأولى يختار خطًّا، ثم يجري عليه عشرة آلاف سنة.", source: "الجغرافيا", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "التربة التي تستقر فيها البذرة في أسبوعها الأول تحدد شكل جذورها بقية عمرها؛ الجذر يلتفّ حول ما وجده.", source: "علم النبات", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "العُرف اسمٌ لما اعتادت جماعةٌ أن تفعله لأن أول من فعله فعله كذلك.", source: "العربية", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "البذرة تحدد عمق جذرها قبل أن تحدد ارتفاع ساقها؛ ما ينزل أولًا يقرر ما يستطيع أن يعلو.", source: "علم النبات", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "النواة في العربية أصل الشيء ومختصره: نواة التمرة، ونواة الحكاية، ونواة الجماعة.", source: "العربية", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "أول مطر على تربة جافة يُطلق رائحةً مخزونة: زيوتٌ تركتها النباتات في التراب طوال الجفاف.", source: "علم التربة", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "البيت الأول في القصيدة العربية يفرض على كل ما بعده وزنه وقافيته؛ ما اختاره الشاعر أولًا لا يستطيع تغييره.", source: "العروض", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "بيض بعض السلاحف تحدد حرارة الرمل حوله ما سيخرج منه ذكرًا أو أنثى؛ عمق الحفرة يقرر ذلك لا البيضة.", source: "علم الحيوان", theme: .beginnings, subtheme: .whatAStartSettles),
        // MARK: Waiting
        Passage(text: "الكُمون: بذرةٌ تمتنع عن الإنبات وإن توفّر لها الماء والحرارة، لأن المانع فيها هي لا فيما حولها.", source: "علم النبات", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الصَّبِر نبات مرّ، والصبر احتمال، وكلاهما من ص ب ر. المرارة والاحتمال في العربية من أصل واحد.", source: "العربية", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الصبّار سُمّي بالصبر لأنه يعيش على ما خزّنه، ويحتمل الجفاف سنين لا يشرب فيها.", source: "علم النبات", theme: .waiting, subtheme: .heldBack),
        Passage(text: "بذور بعض نباتات الصحراء تبقى في التراب سنوات، ولا تنبت إلا إذا نزل من المطر قدرٌ بعينه لا أقلّ منه.", source: "علم النبات", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الدبّ في سباته يهبط نبضه إلى بضع ضربات في الدقيقة، ولا يأكل ولا يشرب طوال الشتاء.", source: "علم الحيوان", theme: .waiting, subtheme: .heldBack),
        Passage(text: "بذورٌ محفوظة في مصارف البذور تُزرع بعد تسعين سنة فتنبت كأن شيئًا لم يمرّ بها.", source: "علم الزراعة", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الكتمان من كتم، وهو حبس الشيء في الصدر لا إخفاؤه عن العين وحدها.", source: "العربية", theme: .waiting, subtheme: .heldBack),
        Passage(text: "يرقة الفراشة تقضي في شرنقتها شهورًا وهي تُحلّ نفسها إلى سائل، ثم تُعيد بناء نفسها هيئةً أخرى.", source: "علم الحشرات", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الإمساك في العربية فعلٌ إرادي: أمسك عن الشيء أي قبض على ما كان سائرًا وهو قادر على إرساله.", source: "العربية", theme: .waiting, subtheme: .heldBack),
        Passage(text: "بيض بعض أسماك البِرَك يبقى حيًّا في الطين شهورًا بعد أن تجفّ البركة كلها.", source: "علم الحيوان", theme: .waiting, subtheme: .heldBack),
        Passage(text: "من الجذر ح ب س: الحبس والحبيس والمحبس، وأصله إمساك الشيء عن الجريان، ومنه حبس الماء في الساقية.", source: "العربية", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الشجرة في الشتاء لا تنام: تغلق مسامّها وتخفض نسغها وتنتظر بجهدٍ لا يُرى من خارجها.", source: "علم النبات", theme: .waiting, subtheme: .heldBack),
        Passage(text: "الصبر مفتاح الفرج.", source: "مثل عربي", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "ما لا يُدرك كله لا يُترك جلّه.", source: "مثل عربي", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "حلقات الشجرة تسجل كل سنة مرّت بها: سنةٌ رطبة حلقة عريضة، وسنةٌ يابسة حلقة ضيقة.", source: "علم الغابات", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "الانتظار في العربية من ن ظ ر: أن تنتظر شيئًا هو أن تظلّ تنظر نحوه.", source: "العربية", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "نخلة التمر لا تحمل قبل خمس سنين ولا تُثمر تمامًا قبل عشر، ثم تُعطي بعد ذلك سبعين سنة.", source: "الزراعة", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "المهلة في العربية وقتٌ يُمنح؛ ولذلك يقال على مهلك، أي بالقدر الذي يكفيك من الزمن.", source: "العربية", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "بعض أشجار الأرز في جبال لبنان جاوزت الألف سنة، وهي ما زالت تُخرج مخاريط جديدة كل خريف.", source: "علم النبات", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "الرمل في الساعة الرملية لا يعرف الوقت؛ ما يقيسه هو مقدار ما تسع فتحةٌ ضيقة أن تمرره.", source: "تاريخ العلوم", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "من الجذر أ ج ل: الأجل والآجل والتأجيل، وأصله الوقت المضروب لشيء أن يقع فيه.", source: "العربية", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "الهابط في الكهف يطول سنتيمترًا واحدًا كل مئة سنة أو نحوها، قطرةً بعد قطرة.", source: "الجيولوجيا", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "الحَول في العربية سنة كاملة، من حال يحول أي دار ورجع إلى حيث ابتدأ.", source: "العربية", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "سرطان الناسك ينتظر أحيانًا عند صدفة أكبر منه حتى يأتي غيره، فيتبادلان البيوت على مهل.", source: "علم البحار", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "المراقبة من الرقبة: أن تراقب شيئًا هو في العربية أن تمدّ عنقك نحوه.", source: "العربية", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "المرصد والرصيد من جذر واحد ر ص د، وأصله القعود لانتظار شيء يمرّ.", source: "العربية", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "الناظر في الليل يرى النجم الخافت أوضح إذا نظر إلى جانبه لا إليه؛ طرف العين أحسّ بالضوء الضعيف من وسطها.", source: "علم البصريات", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "البلشون يقف في الماء بلا حركة دقائق طويلة، لأن أدنى حركة منه تُنذر السمك قبل أن يقترب.", source: "علم الطيور", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "الحرباء تحرّك كل عين على حدة، فترى جهتين في وقت واحد دون أن تدير رأسها.", source: "علم الحيوان", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "الرقيب في العربية من يحفظ الشيء بالنظر إليه لا باليد؛ ومنه المرقب، وهو الموضع العالي يُنظر منه.", source: "العربية", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "الترقّب صيغة تفعّل، وهي في العربية تدلّ على استمرار الفعل وتكلّفه؛ فالترقّب رقبةٌ متصلة لا نظرة.", source: "النحو العربي", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "البومة تدير رأسها حتى مئتين وسبعين درجة، لأن عينيها لا تدوران في محجريهما.", source: "علم الطيور", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "عبّاد الشمس الفتيّ يتبع الشمس نهارًا ثم يعود ليلًا إلى الشرق، فيصبح واقفًا في انتظار الشروق.", source: "علم النبات", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "الناظور في العربية من يحرس الزرع من فوق مرتفع، ومن الجذر نفسه المنظار الذي يقرّب البعيد.", source: "العربية", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "العنكبوت لا يرى فريسته، وإنما يقرأ اهتزاز الخيط فيعرف منه حجمها وموضعها.", source: "علم الحشرات", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "النورس فوق مركب الصيد يثبت في الهواء بلا رفرفة ما دامت الريح تصعد؛ الوقوف عنده طيران.", source: "علم الطيور", theme: .waiting, subtheme: .standingAndWatching),
        // MARK: Renewal
        Passage(text: "جديد في العربية من جدّ أي قطع؛ والثوب الجديد أصله المقطوع حديثًا من النول.", source: "العربية", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "القطع من الأصل لا ينهي الشجرة: كثير من الحور والصفصاف يُخرج من الجذع المقطوع براعم أقوى مما كان.", source: "علم الغابات", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "النعناع كلما قُطف تفرّع أكثر؛ القطف هو نفسه ما يجعله كثيفًا.", source: "البستنة", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "من الجذر ج ب ر: الجبيرة تُشدّ على العظم المكسور، والجبر في الحساب، وجبر الخاطر. الإصلاح في العربية لفظٌ واحد.", source: "العربية", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "الوزغ يترك ذيله في يد ما أمسك به، ثم يُنبت ذيلًا آخر أقصر من الأول وأغلظ.", source: "علم الحيوان", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "كروم العنب تُقصّ في الشتاء قصًّا شديدًا حتى تبدو خرابًا، وهذا القصّ نفسه هو ما يصنع عنقودها.", source: "الزراعة", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "البستاني يقصّ الوردة فوق برعمٍ متجه إلى الخارج، فينمو الغصن الجديد بعيدًا عن قلب الشجيرة.", source: "البستنة", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "نجم البحر يعيد إنبات ذراع كاملة، وفي بعض الأنواع ينبت من الذراع وحدها حيوانٌ تامّ.", source: "علم البحار", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "من الجذر ص ل ح: صلَح، وأصلح، والصلح، والصالح. إصلاح المكسور وإصلاح ما بين اثنين لفظٌ واحد.", source: "العربية", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "الحقل الذي يُترك بورًا سنةً يعود أخصب مما كان؛ الراحة في الزراعة ليست توقفًا عن العمل بل نوعٌ منه.", source: "الزراعة", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "الخيزران يُقطع من الأرض كل عام، وينبت في الموسم التالي إلى ارتفاعه الأول.", source: "علم النبات", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "الظفر والشعر ينموان من طبقة حيّة تحت سطحٍ ميت؛ ما نقصّه ليس هو ما ينمو.", source: "علم التشريح", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "أتاكَ الربيعُ الطلقُ يختالُ ضاحكًا، من الحُسنِ حتى كاد أن يتكلَّما.", source: "البحتري", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "دوام الحال من المحال.", source: "مثل عربي", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "العيد في العربية من عاد يعود: هو اليوم الذي يرجع. والعادة من الجذر نفسه.", source: "العربية", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الربيع والرُّبع والمربّع والأربعة كلها من ر ب ع؛ الفصل والكسر والشكل والعدد من جذر واحد.", source: "العربية", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الخريف في أصله اسم القِطاف لا اسم السقوط؛ خَرَف الثمر أي جناه من شجره.", source: "العربية", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الأرض تميل على محورها ثلاثًا وعشرين درجة ونصفًا، وهذه الميلة وحدها هي سبب الفصول.", source: "الفلك", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "أوراق الخريف تصفرّ لا لأن شيئًا يُضاف إليها بل لأن الأخضر ينسحب؛ الأصفر كان تحته طوال الصيف.", source: "علم النبات", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الوروار يعود إلى الحفرة نفسها في الضفة نفسها كل ربيع، بعد أن يقطع الصحراء ذهابًا وإيابًا.", source: "علم الطيور", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الاعتدالان الربيعي والخريفي هما اليومان اللذان يتساوى فيهما الليل والنهار في كل مكان على الأرض.", source: "الفلك", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الشجرة المتساقطة الأوراق تكوّن براعم السنة القادمة في الصيف السابق لها؛ ورقة الربيع كانت جاهزة قبل الخريف.", source: "علم النبات", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "القمر يتمّ دورته في تسعة وعشرين يومًا ونصف، ولذلك مضى التقويم القمري على شهور لا تثبت في فصل.", source: "الفلك", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "السلمون يبلغ النهر الذي خرج منه بحاسّة شمّ تعرف ماء مجرى بعينه من بين آلاف المجاري.", source: "علم البحار", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "الجبر في الحساب اسمٌ أخذه الخوارزمي من جبر العظم: ردّ ما انكسر إلى موضعه.", source: "تاريخ العلوم", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الرَّأب في العربية إصلاح الصدع؛ يقال رأب الإناء، ويقال رأب الصدع بين قوم.", source: "العربية", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "العظم المكسور يلتئم بنسيج أغلظ من الأصلي، فيصير موضع الكسر أقوى ما في العظم.", source: "الطب", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الشجرة المجروحة تُغلق جرحها بطبقات حوله ولا تشفيه؛ تبقى العقدة في الخشب دليلًا على ما مرّ.", source: "علم الغابات", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "من الجذر س ل م: سالم، وسليم، والسلامة. والسليم في العربية هو الشيء الذي لم ينقص منه شيء.", source: "العربية", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الصلح في القانون العربي عقدٌ قائم بذاته، يُنهي الخلاف برضا الطرفين لا بحكم قاضٍ.", source: "القانون", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الرَّتق في العربية ضدّ الفتق: رتَق الثوب أي أعاد إغلاق ما انفتح فيه حتى لا يُرى.", source: "العربية", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الجلد يعيد بناء نفسه كل شهر تقريبًا؛ الطبقة السطحية التي تلمسها اليوم لم تكن موجودة قبل أربعة أسابيع.", source: "علم التشريح", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "في علم الترميم قاعدةٌ أن يكون ما يُضاف مميَّزًا عن الأصل، حتى يبقى أثر الكسر مقروءًا بعد الإصلاح.", source: "علم الترميم", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "الغابة بعد الحريق تُخرج أولًا نباتات لا تُرى في غيرها؛ بعض بذورها لا تنفتح إلا بالحرارة.", source: "علم النبات", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "المرجان الأبيض ليس ميتًا بالضرورة: إذا عاد الماء إلى برودته رجعت إليه الطحالب ورجع لونه.", source: "علم البحار", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "العافية اسمٌ لكمال الصحة، وأصله من عفا يعفو: أن يُمحى الأثر ويعود الشيء كما كان.", source: "العربية", theme: .renewal, subtheme: .madeWhole),
        // MARK: Light
        Passage(text: "وللنسيمِ اعتلالٌ في أصائلِه، كأنه رقَّ لي فاعتلَّ إشفاقا.", source: "ابن زيدون", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الشفق والشفقة من جذر واحد ش ف ق: حمرة آخر النهار ورقّة القلب لفظهما من أصل.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "السَّحَر آخر الليل قبيل الفجر، ومن حروفه نفسها السِّحر.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الفجر الكاذب عمود ضوء يستطيل ثم يذهب ويعقبه سواد، والفجر الصادق بياضٌ يعترض الأفق ولا يعود.", source: "الفلك", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الغَسَق أول الظلمة بعد المغرب، والغَبَش آخرها قبل الصبح؛ للعربية اسمٌ لكل درجة من درجات العتمة.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الضحى ارتفاع الشمس بعد الشروق، والضاحية من الجذر نفسه: الأرض التي تصيبها الشمس أول ما تصيب.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الشمس تبدو بيضاوية عند الأفق لأن الهواء الكثيف يرفع طرفها الأسفل أكثر مما يرفع أعلاها.", source: "علم الأرصاد", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الشمس التي تُرى عند الغروب قد غابت فعلًا؛ انكسار الضوء في الهواء يُبقيها منظورة بعد نزولها.", source: "الفلك", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الغرب والغريب والمغرب من الجذر غ ر ب: موضع غياب الشمس واسمُ من غاب عن أهله من أصل واحد.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الشرق والإشراق والمشرق من ش ر ق، وأصلها بزوغ الشمس؛ ثم صار الإشراق يقال لكل ما يضيء من داخله.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "البلبل يبدأ الغناء قبل الفجر بنحو ساعة، وقبله يبدأ الشحرور؛ لكل طائر موضعه في ترتيب الصباح.", source: "علم الطيور", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "الأصيل آخر النهار، من الجذر أ ص ل نفسه الذي جاء منه الأصل والأصالة؛ آخر اليوم يحمل اسم أوله.", source: "العربية", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "ومَن يكُ ذا فمٍ مرٍّ مريضٍ، يجدْ مُرًّا به الماءَ الزُّلالا.", source: "المتنبي", theme: .light, subtheme: .readingTheLight),
        Passage(text: "النبات يقرر موعد إزهاره بقياس طول الليل لا طول النهار؛ يعدّ العتمة لا الضوء.", source: "علم النبات", theme: .light, subtheme: .readingTheLight),
        Passage(text: "عين الإنسان تحتاج نحو ثلاثين دقيقة في الظلام حتى تبلغ أقصى حساسيتها، وتفقد ذلك في ثانية واحدة من الضوء.", source: "علم البصريات", theme: .light, subtheme: .readingTheLight),
        Passage(text: "النحل يرى استقطاب الضوء في السماء، فيعرف موضع الشمس في يوم غائم كله.", source: "علم الحشرات", theme: .light, subtheme: .readingTheLight),
        Passage(text: "الأزرق في ريش كثير من الطيور ليس صبغة بل بنيةً دقيقة تعكس هذا الطول من الموج دون غيره.", source: "علم الطيور", theme: .light, subtheme: .readingTheLight),
        Passage(text: "من الجذر ن و ر: النور والنار والمنارة والتنوير؛ والمنارة في أصلها موضع النار يُهتدى به.", source: "العربية", theme: .light, subtheme: .readingTheLight),
        Passage(text: "أوراق الشجرة في الظل أعرض وأرقّ من أوراق الشجرة نفسها في الشمس؛ الورقة تُقاس بما يصلها.", source: "علم النبات", theme: .light, subtheme: .readingTheLight),
        Passage(text: "الرؤية في الليل تعتمد على خلايا لا تميّز الألوان، ولذلك يُقال إن كل الأشياء في الظلام رمادية.", source: "علم البصريات", theme: .light, subtheme: .readingTheLight),
        Passage(text: "البحّار العربي كان يقيس ارتفاع النجم عن الأفق بأداة تسمى الكمال: لوحٌ صغير وخيط فيه عقد بعدد الأصابع.", source: "تاريخ الملاحة", theme: .light, subtheme: .readingTheLight),
        Passage(text: "الظل الحادّ يعني شمسًا صافية، والظل اللين يعني غيمًا رقيقًا؛ حافة الظل تخبر بحال السماء.", source: "علم الأرصاد", theme: .light, subtheme: .readingTheLight),
        Passage(text: "الظِّل والمِظلّة وظلّ يظلّ من جذر واحد ظ ل ل؛ ومعنى ظلّ يفعل: بقي على فعله نهاره كله.", source: "العربية", theme: .light, subtheme: .readingTheLight),
        Passage(text: "عين القط تعكس الضوء من طبقة خلف الشبكية، فيمرّ الضوء على المستقبلات مرتين لا مرة.", source: "علم الحيوان", theme: .light, subtheme: .readingTheLight),
        Passage(text: "انظر إليه كزورقٍ من فضةٍ، قد أثقلته حمولةٌ من عنبرِ.", source: "ابن المعتز", theme: .light, subtheme: .lightItself),
        Passage(text: "الزُّهَرة اسم الكوكب، والزهرة اسم النَّوْر، والازدهار من الجذر نفسه ز ه ر.", source: "العربية", theme: .light, subtheme: .lightItself),
        Passage(text: "الضوء الذي نراه من الشمس غادرها قبل ثماني دقائق وبضع ثوانٍ.", source: "الفلك", theme: .light, subtheme: .lightItself),
        Passage(text: "ابن الهيثم أثبت أن البصر يقع بضوءٍ يدخل العين لا بشعاعٍ يخرج منها، وبنى على ذلك كتاب المناظر.", source: "تاريخ العلوم", theme: .light, subtheme: .lightItself),
        Passage(text: "المصباح والصبح من جذر واحد ص ب ح؛ الضوء المصنوع والضوء الأول اسمهما من أصل.", source: "العربية", theme: .light, subtheme: .lightItself),
        Passage(text: "قوس قزح لا موضع له في السماء: كل ناظرٍ يرى قوسه هو، والقوسان لا يلتقيان أبدًا.", source: "الفيزياء", theme: .light, subtheme: .lightItself),
        Passage(text: "اليراعة تصنع ضوءًا لا حرارة معه تقريبًا؛ تكاد كل طاقتها تخرج نورًا.", source: "علم الحشرات", theme: .light, subtheme: .lightItself),
        Passage(text: "فرّق اللغويون بين الضياء والنور: الضياء ما كان من الشيء نفسه، والنور ما استُمدّ من غيره.", source: "فقه اللغة", theme: .light, subtheme: .lightItself),
        Passage(text: "البحر يبدو أزرق لأن الماء يبتلع الأحمر أولًا؛ على عمق ثلاثين مترًا لا يبقى من الطيف أحمر يُرى.", source: "علم البحار", theme: .light, subtheme: .lightItself),
        Passage(text: "أول المنارات كانت نيرانًا تُشعل على الرؤوس العالية ليهتدي بها القادم من البحر.", source: "تاريخ العمارة", theme: .light, subtheme: .lightItself),
        Passage(text: "النجم الذي تراه الليلة قد يكون انطفأ؛ ما يصلك منه ضوءٌ غادره قبل مئات السنين.", source: "الفلك", theme: .light, subtheme: .lightItself),
        Passage(text: "الأبيض ليس لونًا مفردًا بل كل الألوان مجتمعة، ويفرّقها الموشور لأن كل لون ينكسر بزاوية تخصّه.", source: "الفيزياء", theme: .light, subtheme: .lightItself),
        // MARK: Pattern
        Passage(text: "خمسة من أسماء أيام الأسبوع في العربية أعدادٌ لا غير: الأحد والاثنان والثلاثاء والأربعاء والخميس.", source: "العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "الجمعة اسمها من الجمع، والسبت من السكون؛ يومان في السبعة ليسا عددًا.", source: "العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "الإحصاء من الحصى: العدّ كان يُضبط بحجارة صغيرة قبل أن يُضبط بالأرقام.", source: "العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "الشَّفع في العربية العدد الزوجي، وأصله ضمّ الشيء إلى مثله؛ والوتر الفرد، وأصله الخيط المفرد في القوس.", source: "العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "الكسر في الحساب هو الكسر نفسه في اللغة: عددٌ مكسور، أي جزء انفصل عن واحد صحيح.", source: "العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "الأرقام التي يكتب بها العالم اليوم انتقلت من الهند إلى العربية ثم إلى أوروبا، ولذلك سُمّيت هناك بالعربية.", source: "تاريخ العلوم", theme: .pattern, subtheme: .counted),
        Passage(text: "الأعداد في المخطوط العربي تُكتب من اليسار إلى اليمين وإن كانت الكتابة حولها من اليمين إلى اليسار.", source: "تاريخ الكتابة", theme: .pattern, subtheme: .counted),
        Passage(text: "عدد بتلات الزهرة يقع غالبًا على متتالية يكون فيها كل عدد مجموع العددين قبله: ثلاثة، خمسة، ثمانية، ثلاثة عشر.", source: "علم النبات", theme: .pattern, subtheme: .counted),
        Passage(text: "النحلة تصنع عيونًا سداسية لأن السداسي وحده يملأ السطح كله بأقلّ شمعٍ ممكن.", source: "علم الحشرات", theme: .pattern, subtheme: .counted),
        Passage(text: "العربية تحتفظ بصيغة للمثنى: عددٌ نحوي قائم بذاته، لا يُستعمل إلا لاثنين ولا يقبل ثالثًا.", source: "النحو العربي", theme: .pattern, subtheme: .counted),
        Passage(text: "صِفر معناها الخالي، ومنها جاءت كلمة الصفر في لغات أوروبا كلها.", source: "تاريخ العلوم", theme: .pattern, subtheme: .counted),
        Passage(text: "المقام في الموسيقى العربية يُبنى على أربعة وعشرين ربع نغمة في الديوان الواحد، لا اثنتي عشرة كما في السلّم الأوروبي.", source: "الموسيقى العربية", theme: .pattern, subtheme: .counted),
        Passage(text: "حرف العطف في النحو العربي اسمه من عطف يعطف، أي مال بحنوّ؛ الكلمة التي تصل اسمًا باسم مأخوذة من الميل نحو الآخر.", source: "النحو العربي", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "العاطفة والعطف وحرف العطف كلها من ع ط ف؛ الانحناء نحو الشيء أصلٌ لهذا كله.", source: "العربية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "الرصيف في العربية الحجر المصفوف، والرصيف أيضًا النظير الذي يقف إلى جانبك؛ لفظٌ واحد للاثنين.", source: "العربية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "النَّسَق انتظام الأشياء على نظمٍ واحد، ومنه عطف النسق في النحو: أن يتبع اسمٌ اسمًا في إعرابه.", source: "النحو العربي", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "القبة تُحمل على المقرنص: صفوفٌ من الحنايا الصغيرة تنقل الشكل من مربع القاعدة إلى دائرة القبة.", source: "تاريخ العمارة", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "الزليج يُقطع قطعةً قطعة باليد ثم يُركّب مقلوبًا، فلا يرى الصانع وجه عمله حتى يفرغ منه.", source: "الفنون التطبيقية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "الشجرتان المتجاورتان قد يلتحم غصناهما فيصيران غصنًا واحدًا يتغذى من الجذرين معًا.", source: "علم الغابات", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "المفصل في الذراع يسمى المِرفق، ومن الجذر نفسه الرفق والرفيق؛ ما يسمح للذراع أن تلين.", source: "العربية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "النظم في العربية أصله خرز اللؤلؤ في خيط، ثم صار اسمًا للشعر؛ الشاعر ناظمٌ قبل أن يكون شاعرًا.", source: "العربية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "سعف النخلة يخرج على لولب حول الجذع بزاوية ثابتة، فلا تحجب سعفةٌ ما تحتها عن الشمس.", source: "علم النبات", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "حجارة السور المبني بلا ملاط تمسك بعضها بثقلها وحدها، وكلما زاد الحمل ازداد شدّها.", source: "الهندسة", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "أوتار العود مشدودة أزواجًا، كل وترين على نغمة واحدة، ليخرج الصوت من اثنين لا من واحد.", source: "الموسيقى العربية", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "الجذر الثلاثي هو نظام العربية كله: ثلاثة أحرف تُصبّ في أوزان، فيخرج منها الفعل والاسم والمكان والآلة.", source: "علم اللغة", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الميزان الصرفي يزن الكلمة بثلاثة أحرف: فاء وعين ولام. فاعل ومفعول ومَفعِل، ثلاثة حروف تصف كل بناء في اللغة.", source: "الصرف", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الخليل بن أحمد الفراهيدي وضع علم العروض بعد أن أحصى أوزان الشعر العربي فوجدها خمسة عشر بحرًا.", source: "تاريخ اللغة", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الخليل نفسه رتّب أول معجم عربي، كتاب العين، لا على الألف بل على مخارج الحروف من الحلق إلى الشفة.", source: "تاريخ اللغة", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "المصدر في النحو اسمٌ ومعناه المنبع؛ سُمّي كذلك لأن الأفعال تصدر عنه.", source: "النحو العربي", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الأضداد بابٌ في المعجم العربي: كلماتٌ تحمل المعنى وضدّه، كالجَلَل للعظيم والحقير، والمولى للسيد وللمملوك.", source: "فقه اللغة", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "البَين من الأضداد: يقال بينهم للاجتماع، ويقال البَين للفراق، واللفظ واحد.", source: "فقه اللغة", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الرياضيات والروضة من جذر واحد ر و ض؛ الرياضة تدريب، والروضة أرضٌ رُوّضت بالماء.", source: "العربية", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "أبجد هوّز حطّي كلمن: ترتيبٌ للحروف أقدم من ترتيب الهجاء، وبه تُحسب قيم الحروف إلى اليوم.", source: "تاريخ الخط", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "النحو العربي يسمي المفعول به وما شابهه فضلةً، لا لأنه زائد بل لأن الجملة تقوم بدونه.", source: "النحو العربي", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "الجَذر في الحساب، والجِذر في النبات، والجذر في المعجم: كلمةٌ واحدة لثلاثة أشياء يُبنى عليها ما هو أكبر منها.", source: "العربية", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "القافية حرفٌ واحد يلتزمه الشاعر إلى آخر بيت، وبه تُسمّى القصيدة: لاميّة، أو نونيّة، أو دالية.", source: "العروض", theme: .pattern, subtheme: .orderNamed),
        // MARK: Ground
        Passage(text: "الفلّاح والفلاح من جذر واحد ف ل ح: أصله شقّ الأرض، ومنه صار النجاح فلاحًا.", source: "العربية", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "الحفنة الواحدة من التربة الحيّة تحوي من الكائنات أكثر مما على الأرض كلها من الناس.", source: "علم التربة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "التِّرب في العربية من وُلد معك في زمن واحد، وهو من التراب نفسه؛ كأنكما من ترابٍ واحد.", source: "العربية", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "الدُّبال هو ما تبقّى من الورق والخشب بعد أن حلّلته الأحياء الدقيقة؛ لونه الأسود هو خصوبة الأرض نفسها.", source: "علم التربة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "الطين لَبِنٌ إذا جُفّف وحجرٌ إذا شُوي؛ عمارة العراق القديمة كلها قامت على هذا الفرق.", source: "تاريخ العمارة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "جذور بعض النباتات تؤوي بكتيريا تثبّت نيتروجين الهواء في التربة؛ الحقل يخصب بما زُرع فيه لا بما أُضيف إليه.", source: "الزراعة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "الثرى في العربية التراب النديّ خاصة؛ ولا يقال ثرى لترابٍ يابس.", source: "العربية", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "دودة الأرض تمرّ عليها تربة الحقل كلها مرة كل بضع سنين، وما تخرجه أغنى مما ابتلعت.", source: "علم الحيوان", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "من الجذر ح ر ث: الحرث والمحراث والحارث؛ وشقّ الأرض بالمحراث أول ما ضاعف به الإنسان قوّته.", source: "تاريخ الزراعة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "السَّبَخة أرضٌ يعلوها الملح فلا تُنبت، ولها في العربية اسم مستقل لأن حالها ليست جفافًا.", source: "الجغرافيا", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "تكوين سنتيمتر واحد من التربة السطحية يستغرق ما بين مئة سنة وألف.", source: "علم التربة", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "الواحة ليست بئرًا في الرمل بل موضعًا تصل فيه طبقة ماء جوفية إلى السطح؛ النخل علامة عليها لا سبب لها.", source: "الجغرافيا", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "يا أهلَ أندلسٍ لله دَرُّكمُ، ماءٌ وظلٌّ وأنهارٌ وأشجارُ.", source: "ابن خفاجة الأندلسي", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "مسقط الرأس تعبيرٌ عربي للمكان الذي وُلد فيه المرء، ومعناه حرفيًّا الموضع الذي سقط فيه رأسه.", source: "العربية", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "المنبت في العربية موضع خروج النبات، ويقال للإنسان أيضًا: طيّب المنبت.", source: "العربية", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "اللهجة تُقرأ من نطق حرفين أو ثلاثة؛ القاف وحدها تفرّق بين مصر والشام والخليج والمغرب.", source: "علم اللهجات", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "الحمام الزاجل يعود إلى برجه من مئات الكيلومترات بقراءة المجال المغناطيسي وموضع الشمس.", source: "علم الطيور", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "ياء النسبة في العربية تُلحق بالاسم فتجعل صاحبها من المكان: دمشقيّ، بغداديّ، قيروانيّ.", source: "النحو العربي", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "الديار جمع دار، ويقال ديار فلان للمكان وإن لم يبق فيه بيت؛ الاسم يبقى بعد الجدار.", source: "العربية", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "أشجار الزيتون في بعض بساتين المتوسط أقدم من كل من زرعها ومن كل من قطف منها.", source: "علم النبات", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "الحيّ في المدينة العربية القديمة كان له بابٌ يُغلق ليلًا، فكان لكل حيّ ساكنوه المعروفون بأسمائهم.", source: "تاريخ العمارة", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "النحلة تعرف خليتها بالرائحة لا بالشكل؛ خلية جارتها مثلها تمامًا وهي لا تدخلها.", source: "علم الحشرات", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "الكنية والنسبة واللقب: الاسم العربي الكامل يحمل من أنت، ومن أهلك، ومن أين أنت، في سطر واحد.", source: "العربية", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "التمر المزروع في وادٍ بعينه يختلف طعمه عن التمر نفسه في وادٍ مجاور؛ الماء والملح يدخلان في الثمرة.", source: "الزراعة", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "الحديقة من أحدق أي أحاط؛ وهي في أصلها البستان المحوَّط. ومن الجذر نفسه حدقة العين.", source: "العربية", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الجنّة في العربية من جنّ أي ستر؛ سُمّي البستان جنّة لأن شجره يستر أرضه عن الشمس.", source: "العربية", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الروضة أرضٌ ذات ماءٍ ونبت، والرياض جمعها؛ ومن الجذر نفسه راض وترويض.", source: "العربية", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "البستان كلمة فارسية الأصل دخلت العربية قديمًا، وشاعت حتى صار الناس يحسبونها منها.", source: "تاريخ اللغة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الوقف نظامٌ قانوني يُخرج الأرض من التملك إلى الأبد ويُلزم بصرف غلّتها في وجهٍ واحد؛ بساتين كاملة حُفظت به قرونًا.", source: "القانون", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "البستان الأندلسي كان يُقسم أربعة أرباع بقناتين تتقاطعان عند بركة، وهذا التقسيم باقٍ في أحواض غرناطة.", source: "تاريخ العمارة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "السانية والناعورة والشادوف: ثلاث آلات لرفع الماء من مستوى إلى مستوى، وكلها تعمل بلا وقود.", source: "تاريخ التقانة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الفلج في عُمان قناةٌ جوفية تجرّ الماء عشرات الكيلومترات بانحدارٍ لطيف لا تراه العين.", source: "تاريخ التقانة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الحائط والإحاطة والمحيط من ح و ط؛ والمحيط في الجغرافيا هو الماء الذي يحيط باليابسة.", source: "العربية", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الحِمى في العربية أرضٌ يمنع صاحبها رعيها لتستريح؛ نظامٌ قديم لحفظ المرعى من أن يؤكل كله.", source: "تاريخ الزراعة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "البستان العربي مبنيّ من طبقتين: نخلٌ فوق يكسر الشمس، وشجرٌ تحته يعيش في ظلّه.", source: "الزراعة", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "الفناء في بيوت الشام والمغرب يُروى بماء الغسيل، فيبقى أخضر بلا بئر ولا ساقية.", source: "العمارة التقليدية", theme: .ground, subtheme: .aKeptPlace),
        // MARK: Travel
        Passage(text: "بذور القيقب مجنّحة، تدور في هبوطها كالمروحة فتتباعد عن أمها بمقدار ما تحملها الريح.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "جوز الهند يطفو على البحر شهورًا ثم ينبت على شاطئ لم تكن فيه نخلة قبله.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "بذور بعض النباتات تحمل جسمًا دهنيًا يشتهيه النمل، فيحمل البذرة كلها إلى العشّ ويأكل الدهن ويترك الباقي.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "الطائر الذي يبتلع الثمرة يهضم لبّها ولا يهضم بذرتها؛ رحلتها في جوفه هي ما يكسر غلافها.", source: "علم الطيور", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "أشواك الأرقطيون تعلق بصوف الغنم وبثياب الناس؛ ومن هذا التعلّق أُخذت فكرة الشريط اللاصق.", source: "تاريخ الاختراع", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "الريح تحمل حبوب اللقاح مئات الكيلومترات؛ لقاح الصنوبر يُعثر عليه فوق البحر بعيدًا عن أقرب غابة.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "البذرة من بذر، والتبذير من الجذر نفسه: نثر الشيء دون حساب.", source: "العربية", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "قرون بعض البقوليات تلتوي وهي تجفّ حتى تنفتق فجأة، فترمي حبّها بعيدًا عن الظل الذي تحتها.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "الأنهار تنقل البذور مع الطمي، ولذلك تتشابه نباتات الضفاف على طول المجرى الواحد ولو تباعدت.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "البذور التي تعبر أمعاء الحيوان تنبت في روثه، فتجد سمادها معها من أول يوم.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "النبات لا يرتحل إلا مرة واحدة في عمره: بين لحظة تركه أمّه ولحظة استقراره.", source: "علم النبات", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "سفينة تجارية واحدة تنقل في مياه توازنها بذورًا وكائنات دقيقة من ميناء إلى ميناء عبر المحيط.", source: "علم البيئة", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "الرفيق قبل الطريق.", source: "مثل عربي", theme: .travel, subtheme: .theRoad),
        Passage(text: "من سار على الدرب وصل.", source: "مثل عربي", theme: .travel, subtheme: .theRoad),
        Passage(text: "الطريق من طرق أي دقّ؛ والطريق ما دقّته الأقدام حتى انبسط. ومن الجذر نفسه المطرقة.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "المرحلة اليوم اسمٌ لكل طور، وأصلها مسافة يوم واحد بين منزلين على طريق القوافل.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "الدرب في العربية طريق ضيق، ومن الجذر نفسه التدريب: ما يُتقن بالتكرار كما يُشقّ الدرب بالمرور.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "الرَّحل ما يُوضع على ظهر الدابة، والرحلة من الجذر نفسه؛ السفر في العربية اسمه من أداته.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "طرق القوافل كانت تُقاس بالمناهل لا بالأميال: بين ماءٍ وماء مرحلة.", source: "تاريخ الجغرافيا", theme: .travel, subtheme: .theRoad),
        Passage(text: "ابن بطوطة خرج من طنجة وحده سنة ألف وثلاثمئة وخمس وعشرين للميلاد، ولم يعد إلا بعد نحو تسع وعشرين سنة.", source: "تاريخ الرحلات", theme: .travel, subtheme: .theRoad),
        Passage(text: "السفر من سفر أي كشف؛ يقال أسفر الصبح. والمسافر هو الذي ينكشف له ما كان مستورًا عنه.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "من الجذر س ف ر أيضًا: السفير، والسِّفر وهو الكتاب، والسُّفرة وهي ما يُحمل فيه الزاد.", source: "العربية", theme: .travel, subtheme: .theRoad),
        Passage(text: "الجمل يشرب نحو مئة لتر في عشر دقائق ثم يمشي أيامًا؛ وما في سنامه شحمٌ لا ماء.", source: "علم الحيوان", theme: .travel, subtheme: .theRoad),
        Passage(text: "الطريق المرصوف يُبنى طبقاتٍ أخشنها أسفل وأنعمها أعلى، فينتقل الحمل من الأعلى إلى الأسفل موزّعًا.", source: "الهندسة", theme: .travel, subtheme: .theRoad),
        Passage(text: "درب التبّانة اسمٌ عربي للمجرّة، وفي حكايته أن حاملًا للتبن مرّ بها فتساقط منه ما تساقط.", source: "الفلك", theme: .travel, subtheme: .farOff),
        Passage(text: "الثريّا اسم عنقود النجوم؛ ويقال بينهما ما بين الثرى والثريّا، أي بين التراب النديّ وذلك العنقود.", source: "العربية", theme: .travel, subtheme: .farOff),
        Passage(text: "السُّها نجمٌ خافت في بنات نعش، كان العرب يمتحنون به حدّة البصر.", source: "الفلك", theme: .travel, subtheme: .farOff),
        Passage(text: "الخرشنة القطبية تطير من قطبٍ إلى قطب كل سنة، فتقضي عمرها كله في صيفٍ متصل.", source: "علم الطيور", theme: .travel, subtheme: .farOff),
        Passage(text: "الأفق ليس مكانًا: يبعد عن واقفٍ على الشاطئ خمسة كيلومترات، وعن راكب السارية ثلاثة أضعافها.", source: "الجغرافيا", theme: .travel, subtheme: .farOff),
        Passage(text: "الحنين في العربية أصله صوت الناقة إذا اشتاقت إلى ولدها.", source: "العربية", theme: .travel, subtheme: .farOff),
        Passage(text: "البريد في الدولة القديمة خيلٌ مرتّبة على مراحل، كل واحدة تحمل الرسالة إلى التي بعدها ثم تقف.", source: "تاريخ الدولة", theme: .travel, subtheme: .farOff),
        Passage(text: "الإدريسي رسم في صقلية سنة ألف ومئة وأربع وخمسين خريطةً للعالم جعل فيها الجنوب فوق الشمال.", source: "تاريخ الجغرافيا", theme: .travel, subtheme: .farOff),
        Passage(text: "الشوق والاشتياق من ش و ق، وأصل الشوق نزوع النفس إلى ما ليس بحاضر.", source: "العربية", theme: .travel, subtheme: .farOff),
        Passage(text: "أبعد ما يُرى بالعين المجردة مجرّة المرأة المسلسلة، وضوءها يصل بعد نحو مليونين ونصف من السنين.", source: "الفلك", theme: .travel, subtheme: .farOff),
        Passage(text: "صوت الحوت الأزرق ينتقل في الماء مئات الكيلومترات، وهو أخفض من أن تسمعه أذن الإنسان.", source: "علم البحار", theme: .travel, subtheme: .farOff),
        Passage(text: "الأفق واحد والآفاق جمعه، وتُقال الآفاق للبلاد البعيدة كلها؛ الحدّ الذي ينتهي عنده النظر اسمٌ لما وراءه.", source: "العربية", theme: .travel, subtheme: .farOff),
        // MARK: Meeting
        Passage(text: "اللقاء من لقي يلقى، ومنه الملتقى: موضع اجتماع طريقين أو نهرين.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "الاستقبال في العربية كلمتان في واحدة: أن تستقبل ضيفًا، وأن تستقبل زمنًا لم يأت بعد. كلاهما مواجهةٌ لما يُقبل عليك.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "الموعد اسم مكان وزمان من الوعد؛ اللقاء المتفق عليه في العربية وعدٌ له موضع.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "التعارف على وزن تفاعل، وهذا الوزن لا يصحّ إلا من اثنين فأكثر: لا يتعارف واحد.", source: "النحو العربي", theme: .meeting, subtheme: .theMoment),
        Passage(text: "الاقتران اسمٌ لاجتماع كوكبين في السماء ولاجتماع اثنين في زواج؛ لفظٌ واحد للحالين.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "دجلة والفرات يلتقيان عند القرنة فيصيران شطّ العرب؛ الاسم يتغير عند نقطة الالتقاء لا قبلها.", source: "الجغرافيا", theme: .meeting, subtheme: .theMoment),
        Passage(text: "النحلة التي تجد مرعى تعود إلى الخلية وترقص رقصةً تصف بها الجهة والمسافة معًا.", source: "علم الحشرات", theme: .meeting, subtheme: .theMoment),
        Passage(text: "المصافحة من الصفح، وهو وجه الشيء وعرضه؛ أن تصافح أحدًا هو أن تعطيه صفح كفّك.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "الفطر والشجرة يلتقيان تحت الأرض في جذورٍ مشتركة، يبادل فيها كلٌّ منهما ما ليس عند الآخر.", source: "علم النبات", theme: .meeting, subtheme: .theMoment),
        Passage(text: "المصادفة من صدف أي مال؛ وأصلها أن يميل شيءٌ إلى شيء فيلقاه على غير قصد.", source: "العربية", theme: .meeting, subtheme: .theMoment),
        Passage(text: "زهرة الليل تنفتح في دقائق معدودة عند اصفرار الضوء، والفراشة التي تلقّحها لا تطير قبل ذلك بساعة.", source: "علم النبات", theme: .meeting, subtheme: .theMoment),
        Passage(text: "الأبجدية انتقلت من الفينيقيين إلى اليونان عن طريق التجارة في المتوسط؛ كل حرف نكتبه أثرٌ للقاء تجّار.", source: "تاريخ الكتابة", theme: .meeting, subtheme: .theMoment),
        Passage(text: "النخلة ذكرٌ وأنثى، ولا تحمل الأنثى ما لم يُنقل إليها لقاح ذكرٍ بيد إنسان أو بريح.", source: "الزراعة", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "الزوج في العربية الفصيحة اسمٌ لواحد من اثنين لا للاثنين معًا؛ كلٌّ منهما زوجٌ للآخر.", source: "العربية", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "التين البري لا يُثمر إلا بزنبورٍ صغير يدخل ثمرته ويموت فيها، ولا يعيش ذلك الزنبور إلا في التين.", source: "علم النبات", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "الأشنة كائنان: فطرٌ وطحلبٌ يعيشان معًا حتى صارا يُعدّان نوعًا واحدًا له اسمٌ في المعاجم.", source: "علم الأحياء", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "سمكة المهرّج تعيش بين لوامس شقائق البحر السامّة ولا تُلدغ، وتحرسها في المقابل ممن يقضمها.", source: "علم البحار", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "المثنى في العربية صيغةٌ قائمة بذاتها: لا مفرد ولا جمع، بل عددٌ لا يُقال إلا لاثنين.", source: "النحو العربي", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "القرين من قرن أي جمع بين شيئين؛ والقِران في أصله حبلٌ يُشدّ به بعيران ليسيرا معًا.", source: "العربية", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "النحل والزهر عقدٌ قديم: الزهرة تصنع رحيقًا لا تحتاجه، والنحلة تنقل لقاحًا لا تقصده.", source: "علم الحشرات", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "طائر الدليل في شرق أفريقيا يقود الإنسان إلى خلية النحل البرية، ثم يأكل الشمع بعد أن يأخذ الإنسان العسل.", source: "علم الطيور", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "سنّ المفتاح وسنّ القفل لا معنى لأحدهما وحده؛ الشكل في كليهما وصفٌ للآخر.", source: "الهندسة", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "الحرف في العربية لا يعمل وحده: حرف الجر يحتاج اسمًا بعده، والاسم يحتاجه ليتصل بالفعل قبله.", source: "النحو العربي", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "بعض الزهور تنثر غبار طلعها قبل أن ينضج ميسمها، فلا تستطيع أن تلقّح نفسها ولو أرادت.", source: "علم النبات", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "الجار قبل الدار.", source: "مثل عربي", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "الضيف والضيافة والإضافة من ض ي ف؛ والإضافة في النحو أن يُسند اسمٌ إلى اسم فيصيرا كالواحد.", source: "النحو العربي", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "الضيافة في العرف العربي ثلاثة أيام معلومة، ثم يُسأل الضيف عن حاجته، ولا يُسأل قبلها.", source: "الأعراف العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "صدر المجلس أشرف مواضعه ويُجلس فيه أكبر القوم؛ والصدر من الجسد مقدَّمه.", source: "العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "المجلس اسم مكان من جلس، ثم صار اسمًا لكل هيئة تجتمع للتشاور؛ وبقي الاسم اسمَ فعل الجلوس.", source: "العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "الجِوار في العرف العربي عهد: من استجار بقوم لزمهم أن يمنعوه ولو كان غريبًا عنهم.", source: "الأعراف العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "القهوة العربية تُصبّ ثلث الفنجان لا أكثر، ليبقى قابلًا للإعادة ولا يبرد ما فيه.", source: "الأعراف العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "هزّ الفنجان في الخليج علامة الاكتفاء، وإمساكه ساكنًا طلبٌ للمزيد؛ إشارةٌ تُغني عن الكلام.", source: "الأعراف العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "أهلًا وسهلًا في أصلها جملتان: نزلتَ أهلًا لا غرباء، ووطئتَ سهلًا لا وعرًا.", source: "العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "السلام تحيةٌ ودعاءٌ وأمانٌ في كلمة واحدة، ومن جذرها السلامة والتسليم والاستسلام.", source: "العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "الكرم في الأعراف العربية يُقاس بما يُقدَّم قبل السؤال؛ وأن تسأل الضيف عمّا يريد يُعدّ في بعض البوادي تقصيرًا.", source: "الأعراف العربية", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "مدّ اليد بالكفّ مكشوفة إشارةٌ قديمة في مواضع كثيرة من العالم: يدٌ مفتوحة لا تخفي شيئًا.", source: "علم الأناسة", theme: .meeting, subtheme: .theMannersOfIt),
        // MARK: Kinship
        Passage(text: "غصنان يحتكّان سنين حتى يذهب لحاؤهما، ثم يلتحمان فيصير الخشبان خشبًا واحدًا يحمل الاثنين.", source: "علم الغابات", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "التطعيم: أن يُشقّ ساق شجرة ويُدخل فيه غصنٌ من أخرى، فيتصل نسغهما ويحمل الجذر ما ليس منه.", source: "البستنة", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "غابة الحور الرجراج قد تكون شجرة واحدة: آلاف الجذوع تخرج من جذرٍ واحد تحت الأرض.", source: "علم النبات", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "الوصل والصلة والمواصلة من و ص ل؛ وصلة الرحم اسمٌ لبقاء الخيط بين الأقارب موصولًا.", source: "العربية", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "الرحم موضع الحمل، والأرحام هم الأقارب، ومن الجذر نفسه الرحمة.", source: "العربية", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "المفاغرة في التشريح: قناتان تتصلان فتصيران مجرى واحدًا. يقال ذلك في الأنهار وفي العروق وفي عروق الورقة.", source: "علم التشريح", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "جذور الأشجار في الغابة موصولة بشبكة فطرية تنقل السكر من شجرة قوية إلى فسيلة في الظل.", source: "علم الغابات", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "الحبل السرّي يُقطع مرة واحدة ولا يُعاد، وأثره باقٍ في الجسد ما بقي.", source: "علم التشريح", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "اللحام في المعادن لا يلصق قطعتين، بل يذيب حافتيهما حتى تبردا معدنًا واحدًا.", source: "الهندسة", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "النسيج في العربية من نسج؛ وسُمّي نسيج الجسد بالاسم نفسه لأن خيوطه متداخلة كخيوط الثوب.", source: "العربية", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "النحل يبني الشمع صفوفًا يبدأها من مواضع متفرقة، ثم تلتقي الصفوف فلا يُرى موضع الالتقاء.", source: "علم الحشرات", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "اللبلاب يلتفّ في جهة واحدة لكل نوع، ولا يعكسها ولو أُدير باليد إلى الجهة الأخرى.", source: "علم النبات", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "الطيور على أشكالها تقع.", source: "مثل عربي", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الصديق من الجذر ص د ق نفسه الذي جاء منه الصدق والصداقة؛ الصاحب في اللغة هو الصادق.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الأنس والإنسان والاستئناس من أ ن س؛ وذهب بعض اللغويين إلى أن الإنسان سُمّي بذلك لأنه يأنس بغيره.", source: "فقه اللغة", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الألفة والأليف والتأليف من أ ل ف؛ ومن ألّف كتابًا فقد جمع بين معانٍ متفرقة حتى أنس بعضها ببعض.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "المودّة والودّ من و د د؛ وفرّق بعض اللغويين بينها وبين المحبة بأن المودة ما ظهر منها في الفعل.", source: "فقه اللغة", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "التِّرب من وُلد في زمنك، والأتراب جماعةٌ تشاركوا السنّ نفسها.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "القرابة والقربى من ق ر ب؛ والقريب في العربية قريبٌ في المكان وفي النسب بلفظٍ واحد.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الخليل هو الصديق الذي تخلّلت مودّته المواضع كلها؛ من تخلّل أي دخل في الخِلال.", source: "فقه اللغة", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الصاحب من صحب، ويقال صاحب الدار وصاحب السفر؛ المِلك والرفقة لفظٌ واحد.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "النظير من نظر: من إذا نُظر إليه وُجد مثلك.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "العربية تفرّق بين العمّ والخال، وبين ابن العم وابن الخال؛ ولا كلمة واحدة تجمعهم كما في لغات أخرى.", source: "علم اللغة", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "الرفيق من الرفق؛ ومن الجذر نفسه المِرفق في الذراع، وهو ما يجعلها تلين.", source: "العربية", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "والناسُ للناسِ من بدوٍ وحاضرةٍ، بعضٌ لبعضٍ وإن لم يشعروا خدمُ.", source: "أبو العلاء المعري", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "لكل جوادٍ كبوة.", source: "مثل عربي", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "جبر الخاطر تعبيرٌ عربي حيّ، معناه أن تُصلح ما انكسر في نفس إنسان بكلمة أو بصنيع صغير.", source: "العربية", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "صوت الأمّ يميّزه المولود في يومه الأول من بين كل الأصوات.", source: "الطب", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "التثاؤب يُعدي، وتكون العدوى أشدّ كلما كان المتثائبان أقرب أحدهما إلى الآخر.", source: "علم النفس", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "الغناء الجماعي يجعل نبض المغنّين يتقارب حتى يكاد يتوحّد بعد دقائق من ابتدائه.", source: "الطب", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "المشي جنبًا إلى جنب يوقع الخطوتين على إيقاع واحد بلا اتفاق بين الماشيين.", source: "علم الحركة", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "النظر المتبادل بين اثنين يرفع النبض ويوسّع الحدقة؛ الوجه أقوى ما يستقبله الدماغ من إشارات.", source: "علم النفس", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "الفراغ بين دور المتحدث ودور من يجيبه أقلّ من خُمس ثانية، في كل لغات العالم تقريبًا.", source: "علم اللغة", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "اليد التي تُمسك يدًا أخرى تخفض إحساس الألم قياسًا؛ أُثبت ذلك في تجارب الحرارة.", source: "الطب", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "الابتسامة الصادقة تحرّك عضلةً حول العين لا يستطيع أكثر الناس تحريكها عمدًا.", source: "علم التشريح", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "العربية تجعل للاثنين ضميرًا لا يقبل ثالثًا: أنتما، وهما.", source: "النحو العربي", theme: .kinship, subtheme: .twoPeople),
        // MARK: Peace
        Passage(text: "خير الكلام ما قلّ ودلّ.", source: "مثل عربي", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "السكون في الكتابة العربية علامةٌ تُوضع فوق الحرف لتقول إنه لا حركة فيه؛ إشارةٌ إلى صوتٍ لا يُنطق.", source: "النحو العربي", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الهدوء والمحيط الهادئ من جذر واحد ه د أ؛ أكبر ماءٍ على الأرض اسمه في العربية الساكن.", source: "العربية", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الصفير صوتٌ يُخرج من فمٍ فارغ، ومن الجذر نفسه الصِّفر أي الخالي.", source: "العربية", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "البومة تطير بلا صوت لأن حافة ريشها مسنّنة تفتّت دوّامات الهواء قبل أن تصير صوتًا.", source: "علم الطيور", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الثلج الطريّ يبتلع الصوت: الهواء المحبوس بين بلوراته يمتصّ الموجات، فيصير الشارع بعده أهدأ منه قبله.", source: "علم الأصوات", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الحفيف صوت الشجر إذا مرّت به الريح، والخرير صوت الماء، والهزيز صوت الريح نفسها.", source: "العربية", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "المسكوت عنه اصطلاحٌ في الفقه والقانون: ما لم يتكلم فيه النصّ، وسكوته عنه حكمٌ في ذاته.", source: "القانون", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "أخفض صوتٍ تسمعه الأذن السليمة يحرّك طبلتها مسافةً أصغر من قطر ذرّة الهيدروجين.", source: "علم الأصوات", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الغرفة عديمة الصدى مبطّنة بأوتادٍ تمتصّ كل انعكاس، وفيها يسمع الواقف دقّات قلبه وحركة مفاصله.", source: "علم الأصوات", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "الوجيب اسمٌ لاضطراب القلب، والنبض لضربه المطّرد؛ اسمان لصوتٍ واحد على حالين.", source: "العربية", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "ورق الحور الرجراج يهتزّ في أضعف نسمة لأن عنقه مسطّح لا مستدير؛ الشجرة تُسمع قبل أن تُرى.", source: "علم النبات", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "من الجذر س ل م: السلام والسلامة والتسليم والسُّلَّم. والسلام في العربية أن يبقى الشيء تامًّا لم ينقص.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الهدنة من هدن أي سكن؛ فليست في العربية من ألفاظ الحرب بل من ألفاظ السكون.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الصلح والإصلاح والصالح من أصل واحد؛ فمن أصلح بين اثنين فقد رمّم شيئًا مكسورًا.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "علامات الترقيم تسمى في العربية علامات الوقف؛ النقطة والفاصلة إشاراتٌ إلى مواضع السكوت لا إلى الكلام.", source: "الكتابة العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الأمان في العرف العربي عقد: من أُعطي أمانًا لم يجز التعرّض له، وكان يُعطى بالكلمة وحدها.", source: "الأعراف العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الوفاق والاتفاق والموافقة من و ف ق؛ وأصل الوفق أن يقع الشيء على قدر الشيء تمامًا.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "فصل الخطاب في العربية القول الذي ينهي الخلاف؛ والفصل في أصله قطعٌ بين شيئين.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "التحكيم في الأعراف العربية أن يرضى الخصمان بحَكَمٍ بينهما، وحكمه ملزمٌ لأنهما اختاراه لا لأنه يملك قوة.", source: "الأعراف العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "السكينة من سكن، والمسكن من الجذر نفسه: البيت اسمه ما يحدث فيه من سكون.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "القرار موضع الاستقرار قبل أن يكون حكمًا؛ ومنه قرار الوادي: أخفض ما فيه حيث يقف الماء.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الكفّ في العربية امتناعٌ بإرادة: كفّ عن الشيء أي أمسك عنه وهو قادر عليه.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الإغضاء أن تُغمض عينك عن هفوةٍ رأيتها؛ وله في العربية اسمٌ مستقل لأنه ليس عدم الرؤية.", source: "العربية", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "الراحة اسمٌ للاستجمام ولباطن الكفّ معًا؛ راحة اليد هي موضعها إذا استرخت.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "على مهلك: عبارةٌ عربية حيّة معناها امضِ بالقدر الذي يكفيك من الوقت لا بالقدر الذي يُطلب منك.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "الاطمئنان من اطمأنّ، وأصله سكون الأرض بعد اضطرابها؛ ومنه الأرض المطمئنة: المنخفضة الساكنة.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "الفيء هو الظل الذي يرجع بعد الزوال، من فاء أي رجع؛ ظلّ الصباح ينحسر، وظلّ العصر يعود.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "القيلولة نومٌ قصير في وسط النهار، ولها في العربية اسمٌ مستقل لأنها ليست نوم الليل.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "الظل تحت شجرة أبرد من ظلّ سقفٍ بدرجتين أو ثلاث، لأن الورقة تبخّر الماء وهي تظلّل.", source: "علم الأرصاد", theme: .peace, subtheme: .atEase),
        Passage(text: "القطط تخرخر بتردد بين خمسة وعشرين وخمسين هرتزًا، وهو التردد نفسه المستعمل في تسريع التئام العظم.", source: "علم الحيوان", theme: .peace, subtheme: .atEase),
        Passage(text: "الزفير الأطول من الشهيق يخفض النبض؛ وهذا وحده ما يفعله كل تمرين تنفّس.", source: "الطب", theme: .peace, subtheme: .atEase),
        Passage(text: "الشجرة لا تنفق طاقةً على الحركة، ولذلك تبلغ من الأعمار ما لا يبلغه متحرّك.", source: "علم النبات", theme: .peace, subtheme: .atEase),
        Passage(text: "الاتّكاء أن تُلقي ثقلك على شيء غيرك؛ وله في العربية فعلٌ مستقل لأنه ليس جلوسًا ولا اضطجاعًا.", source: "العربية", theme: .peace, subtheme: .atEase),
        Passage(text: "أوراق كثير من النباتات تُطبق قليلًا في حرّ الظهيرة لتقلّ المساحة التي تصيبها الشمس، ثم تنبسط في العصر.", source: "علم النبات", theme: .peace, subtheme: .atEase),
        Passage(text: "الاستراحة من الجذر ر و ح؛ ومن الجذر نفسه الريح والرَّوح والرائحة.", source: "العربية", theme: .peace, subtheme: .atEase),
    ]
}
