import Foundation

/// The Polish passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
///
/// Polish's *pokój* is one word for peace and for a room — the state and the space you are standing in. Its `orderNamed` is not a metaphor but a calendar: nine of the twelve month names are descriptive etymologies, and only marzec and maj kept their Roman ones.
extension Quotes {
    static let polish: [Passage] = [
        // MARK: Beginnings
        // theFirstAct
        Passage(text: "Mikołaj Rej chose to write in Polish rather than Latin, back when Latin was simply what a serious book was written in — Polish literature dates itself from that choice.", source: "Mikołaj Rej (d. 1569)", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Kiełkowanie is the Polish word for germination — the moment a seed's coat splits and there is no going back to being only a seed.", source: "Polish, Botany", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pąk, a bud, and pękać, to burst, share a root. In Polish, a bud is already described as a thing about to break open.", source: "Polish", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "In Polish villages, a stork seen circling overhead was once reckoned the true start of the farming year, ahead of any date on a calendar.", source: "Ciconia ciconia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "A European bison calf in Białowieża stands within the hour it's born, and by the end of its first day can already keep pace with the herd.", source: "Bison bonasus", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Imbibition: the first thing a dry seed does is drink. Everything else waits on water getting in and swelling the coat from the inside.", source: "Botany", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Radicle: the first root, and the first part of any seedling to appear. Whatever grows above ground has to wait on it.", source: "Botany", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Amber on the Baltic shore began as resin sealing a wound in a tree, tens of millions of years before anyone thought to call it beautiful.", source: "Bursztyn", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pierwszy pokos, the first cut of hay, used to mark early summer across the Polish countryside as plainly as any date could.", source: "Polish, rural custom", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Roztopy, the spring thaw, is the moment a Polish winter admits it's finished — the rivers rise before the trees have so much as budded.", source: "Polish", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Przebiśnieg, the snowdrop, is often the first flower up in a Polish year, breaking through snow that hasn't even finished falling yet.", source: "Galanthus nivalis", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Henryk Sienkiewicz became the first Polish writer to win the Nobel Prize in Literature, in 1905, for Quo Vadis and the trilogy that came before it.", source: "Henryk Sienkiewicz (d. 1916)", theme: .beginnings, subtheme: .theFirstAct),
        // smallToLarge
        Passage(text: "The Vistula begins as snowmelt barely wider than a stream in the Silesian hills, long before it's the river that reaches Gdańsk.", source: "Wisła", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "A young oak in Białowieża can spend its first sixty years no taller than a person, putting everything into roots before it ever reaches for the canopy.", source: "Quercus robur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "A single Białowieża oak can drop upward of ten thousand acorns in a good year — perhaps one of them will ever become a tree its own size.", source: "Quercus robur", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Przysłowie polskie: ziarnko do ziarnka, a zbierze się miarka — grain to grain, until there's enough to fill a measure.", source: "Przysłowie polskie", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "The two thousand-odd lakes of Mazury began as chunks of ice left behind by a retreating glacier, each one melting slowly into a lake of its own size.", source: "Geography", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Wieliczka's mine started as a handful of shallow diggings in the thirteenth century, and has grown, gallery by gallery, into some three hundred kilometres of tunnel.", source: "Wieliczka", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "A stork's nest is added to every spring by the pair that returns to it, until some grow heavy enough — several hundred kilograms — to need a beam underneath.", source: "Ciconia ciconia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Bartnictwo, forest beekeeping in hollowed-out pine trunks, is one of Poland's oldest crafts. A single tended tree could stay in one family for generations, growing busier every year.", source: "Polish, forest craft", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "A single sunflower seed, sown in spring, can come back in autumn carrying up to two thousand more.", source: "Helianthus annuus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "A village lipa can begin as a seed small enough to lose in a coat pocket, and still be standing three hundred years on, wide enough for the whole village to shelter under.", source: "Tilia, linden", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "The peat in the Biebrza marshes has built up at only about a millimetre a year — the deepest parts took something like ten thousand years to lay down.", source: "Biebrza", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Left alone, a cleared patch of Polish forest moves through grasses, then birch and pine, then oak and hornbeam, arriving back at full forest a century and a half later.", source: "Forestry", theme: .beginnings, subtheme: .smallToLarge),
        // whatAStartSettles
        Passage(text: "Przysłowie polskie: czym skorupka za młodu nasiąknie, tym na starość trąci — what a shell soaks up when young, it still carries the smell of when it's old.", source: "Przysłowie polskie", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "A fraszka is over almost as soon as it starts, so Kochanowski had to put the whole point of it in the first line — the form leaves nowhere else to put it.", source: "Jan Kochanowski (d. 1584)", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "A tree's crown tends to keep growing in the direction its seedling first leaned to find the light, even once there's light on every side.", source: "Botany", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "The first nest a stork picks tends to be the nest it keeps for life, added to every spring rather than traded for a new one.", source: "Ciconia ciconia", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "A salt crystal's first few atoms fix the cube it will always grow into. Nothing added later changes the shape, only the size.", source: "Chemistry", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Przysłowie polskie: jaki początek, taki koniec — as the start, so the end. One old saying ties the two together.", source: "Przysłowie polskie", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Henryk Sienkiewicz's Trilogy began as newspaper instalments, and the pace he set in the opening chapters is the pace the whole sprawling saga keeps.", source: "Henryk Sienkiewicz (d. 1916)", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "A flower's petal count is fixed inside the bud long before it opens. Nothing added afterward grows the number, only the size.", source: "Botany", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Whatever is caught in the very first moment of a drop of resin stays there unchanged, however many more layers of amber follow.", source: "Bursztyn", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "The channels linking the Mazurian lakes still follow the paths the retreating ice cut first — the water just kept using the route that was already there.", source: "Geography", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Białowieża has never been entirely cleared since the last ice age. It simply continued being itself, one of the only places in lowland Europe that never had to start over.", source: "Białowieża", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Which end of a seed becomes root and which becomes shoot is decided while it's still inside the fruit — germination only carries out what was already settled.", source: "Botany", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: Waiting
        // heldBack
        Passage(text: "Stratyfikacja: many Polish forest seeds — beech, oak — won't germinate until they've been through a real winter's cold. Warmth alone doesn't convince them.", source: "Polish, Botany", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Przednówek names the weeks before the new harvest, when last year's stores run thinnest — a season English never got round to naming.", source: "Polish", theme: .waiting, subtheme: .heldBack),
        Passage(text: "A seed can lie in the soil for decades, held back by nothing wrong with it — only waiting for the one particular set of conditions that will let it go.", source: "Botany", theme: .waiting, subtheme: .heldBack),
        Passage(text: "In the Bieszczady, a brown bear held up in its den through winter can lose a third of its body weight and still wake in spring able to walk.", source: "Ursus arctos", theme: .waiting, subtheme: .heldBack),
        Passage(text: "A Mazurian lake under winter ice isn't still, exactly — the water underneath keeps moving. The ice only holds back what's on top.", source: "Geography", theme: .waiting, subtheme: .heldBack),
        Passage(text: "The hazel dormouse, orzesznica, spends up to seven months of the year asleep — more of its life held back in torpor than awake.", source: "Muscardinus avellanarius", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Deep in Wieliczka the air holds at a steady few degrees whatever the season's doing above ground — one place in Poland the year can't reach.", source: "Wieliczka", theme: .waiting, subtheme: .heldBack),
        Passage(text: "A late frost can hold a Polish spring planting back by weeks, even after the calendar and the trees have both agreed it's time.", source: "Polish, agriculture", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ozime, winter-sown grain, has to feel real cold before it will flower at all — sown in autumn on purpose, so the frost can do its work on it.", source: "Polish, agriculture", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Przysłowie polskie: co się odwlecze, to nie uciecze — what's put off doesn't get away. A delay, in Polish, isn't counted as a loss.", source: "Przysłowie polskie", theme: .waiting, subtheme: .heldBack),
        Passage(text: "The European bison went extinct in the wild in 1919. The whole species survived only in zoos and reserves, some fifty animals, until it could be brought back to Białowieża.", source: "Bison bonasus", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Some wild orchids won't germinate at all until the right thread of fungus finds their seed in the soil — held back indefinitely if it never turns up.", source: "Botany", theme: .waiting, subtheme: .heldBack),
        // theLongCount
        Passage(text: "A European eel can spend fifteen years or more growing up in a single Polish river before it ever sets out on the long swim back to the sea it hatched in.", source: "Anguilla anguilla", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "An oak in a Polish forest won't produce its first acorns until it's forty, sometimes fifty, years old — a long wait before it does the one thing oaks are for.", source: "Quercus robur", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "A Polish stork spends about half the year away in Africa. The villages it nests in wait out six empty months every single year.", source: "Ciconia ciconia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "A Mazurian lake can stay under ice for four months or more, from December some years clear into April.", source: "Geography", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Obuwik, the lady's-slipper orchid, can take up to sixteen years from seed to its first flower — one of the slowest starts of any plant native to Poland.", source: "Cypripedium calceolus", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "The salt at Wieliczka was laid down as an inland sea dried out roughly thirteen million years ago. Everything mined there since is a fraction of that wait.", source: "Wieliczka", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "The oldest oaks still standing in Białowieża are reckoned at four, five hundred years — old enough to have been saplings before Poland and Lithuania were joined as one state.", source: "Białowieża", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Doczekać się has no clean English equivalent: to wait until, at last, the thing arrives. Polish gives the very end of a long wait its own verb.", source: "Polish", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "The Vistula runs over a thousand kilometres from its source in the Silesian hills to the Baltic — the longest wait any Polish river makes for the sea.", source: "Wisła", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "A Tatra marmot spends around half the year asleep in its burrow, waiting out the mountain winter below the snow line.", source: "Marmota marmota", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "A beech won't put out a full crop of seed most years. Polish foresters wait five, sometimes ten years between what they call a mast year.", source: "Fagus sylvatica", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Advent in Poland runs four full weeks before Wigilia — the longest stretch of waiting the whole year sets aside on purpose.", source: "Polish custom", theme: .waiting, subtheme: .theLongCount),
        // standingAndWatching
        Passage(text: "On Wigilia, supper doesn't start until the first star is seen, so the youngest person in the house is sent out to watch the sky for it.", source: "Polish custom", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Przysłowie polskie: kto czeka, ten się doczeka — whoever waits, gets there in the end.", source: "Przysłowie polskie", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "In some villages, the first stork back each spring was watched for and passed on like news, house to house.", source: "Ciconia ciconia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Fishermen on the Mazurian lakes used to keep track of the exact day the ice broke each year, checking it against the winter before.", source: "Polish, folk record-keeping", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Mikołaj Kopernik tracked the motion of the planets from a tower in Frombork, watching the same sky for decades before he was willing to say what he'd seen.", source: "Mikołaj Kopernik (d. 1543)", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Visitors to Białowieża today watch for bison from wooden hides at dawn — the same patient waiting the animals have always asked of anyone who wants to see one.", source: "Bison bonasus", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "After a storm on the Baltic coast, amber hunters walk the tideline at first light, watching the wrack for anything that catches the sun.", source: "Bursztyn", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "On a good night, the aurora can be seen even from northern Poland — rare enough that people who've watched for it remember exactly where they stood.", source: "Zorza polarna", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Fire towers still stand over the biggest Polish forests, someone posted at the top through the dry months just to watch for smoke.", source: "Polish forestry", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "The Biebrza marshes draw birdwatchers from across Europe every spring, all of them standing in the reeds before dawn for one bird's few minutes of display.", source: "Biebrza", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "In Białowieża, night walks go out just to listen for owls — eight species possible in that one forest, and hearing one is the whole point of standing still.", source: "Białowieża", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Rural Poland, away from city light, still gets a proper view of the Perseids each August — whole families lying out in a field, watching for the next one.", source: "Polish, astronomy", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: Renewal
        // cutAndComeAgain
        Passage(text: "Wiklina, basket willow, is cut back to almost nothing every winter and comes back thicker each spring — a Polish basket is made from the fact that cutting it doesn't kill it.", source: "Salix, Polish craft", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "A traditional Polish hay meadow is cut two or three times in a season, and each time it simply starts again from the roots.", source: "Polish, agriculture", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Village lindens were once pollarded for fodder — cut back hard every few years, and every few years they simply grew the crown back.", source: "Tilia, linden", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "A river crayfish that loses a claw in a fight grows another at its next moult — not the same claw, but a working one.", source: "Astacus astacus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Young ozime rye can be grazed or cut once in autumn without harm. It simply regrows before the frost, thicker for the interruption.", source: "Polish, agriculture", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "A red stag in a Polish forest drops its antlers every winter and grows an entirely new set by autumn — heavier, most years, than the ones before.", source: "Cervus elaphus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "In the Tatra foothills, a sheep is shorn once a year at no cost to it but the wool. By the next spring there's a full fleece again.", source: "Polish, Podhale", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Pokrzywa, nettle, can be cut for spring soup and sends up a fresh, tender growth within weeks. Cutting it back is really the only way to keep eating it.", source: "Urtica dioica", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Reed cut from the Biebrza marshes for thatching is taken in winter, after it's died back on its own. The same roots send up a fresh stand every spring.", source: "Biebrza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "A beekeeper takes the honey a hive has stored, and the hive simply sets about making more — comb and all, from nothing, inside a season.", source: "Polish, beekeeping", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Leszczyna, hazel, cut hard for bean poles and plant stakes, throws up a full new set of shoots by the following summer.", source: "Corylus avellana", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "A grapevine is cut back hard every winter, almost to the trunk. The only wood that fruits is wood that grew fresh that same year.", source: "Polish, viticulture", theme: .renewal, subtheme: .cutAndComeAgain),
        // theTurningYear
        Passage(text: "Wiosna, spring, and the Latin ver share the same distant root — one old word for the turn of the year, worn down two different ways.", source: "Polish, cognate with Latin", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "In parts of Poland, a straw figure called Marzanna is carried to the riverbank each spring and set adrift on the water — the old way of telling winter it's done.", source: "Polish custom", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Władysław Reymont's Chłopi is told in four volumes, one to a season, opening in autumn and coming back around to it by the end.", source: "Władysław Reymont (d. 1925)", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Przysłowie polskie: kwiecień plecień, bo przeplata trochę zimy, trochę lata — April the plaiter, weaving a bit of winter in with a bit of summer.", source: "Przysłowie polskie", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Dożynki, the harvest festival, is built around a wreath woven from the very last sheaf cut — the field's ending turned into something to carry home.", source: "Polish custom", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Przysłowie polskie: na świętego Grzegorza, idzie zima do morza — on St Gregory's day, winter sets off for the sea.", source: "Przysłowie polskie", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "It was the first hard frost, not any date on a calendar, that Polish farmers reckoned as the true start of autumn.", source: "Polish, folk reckoning", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Jan Kochanowski wrote an entire cycle of songs for Sobótka, the midsummer bonfire night — one for each of the young people said to sing around the fire.", source: "Jan Kochanowski (d. 1584)", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "When the storks gather to leave each August, it's taken as the surer sign the year has turned toward autumn, whatever the weather is still doing.", source: "Ciconia ciconia", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Grzybobranie, the start of mushroom season in September, is one of the clearest signals a Polish autumn has properly begun.", source: "Polish custom", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "In a Polish forest, birch turns gold weeks before oak so much as thinks about it. The year turns tree by tree, not all at once.", source: "Botany", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Once the ice on a Mazurian lake is thick enough to trust, the ice-fishing season opens — the clearest marker that winter has properly set in.", source: "Geography", theme: .renewal, subtheme: .theTurningYear),
        // madeWhole
        Passage(text: "Zdrowy, healthy, and drzewo, tree, share a root — to be healthy was, once, to be sound as a tree. English kept the same image in hale and let the tree drop out of it.", source: "Polish, from Proto-Slavic", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "When a storm flattens a stretch of Białowieża, nobody replants it. Left alone, the forest finds its own way back to whole — just not the way it looked before.", source: "Białowieża", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Part of Wieliczka is a working health resort now — the same salt air once dug out for trade is used today to help people breathe easier.", source: "Wieliczka", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Every European bison alive today, some ten thousand of them, is descended from the same fifty or so animals that were all that was left in 1919.", source: "Bison bonasus", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Underground, a forest's roots are laced together by threads of fungus, passing sugar and warning between trees. From below, a forest is less a crowd than one connected thing.", source: "Mycology", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Whatever the Vistula picks up along its thousand kilometres, it carries all the way to the Baltic and sets down there, whole, as the delta at Gdańsk.", source: "Wisła", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Poland has more than forty official uzdrowiska, towns built around a mineral spring reckoned able to put right something plain rest couldn't.", source: "Polish, spa towns", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Poland's forests cover roughly a third of the country now, grown back over decades from under a quarter — replanted, patiently, tree by tree.", source: "Polish forestry", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Całować, to kiss, comes from cały, whole. A kiss was, once, a small wish for someone's wholeness — for them to stay complete.", source: "Polish", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "A break in a tree's bark doesn't get repaired so much as grown over. The callus that forms is new wood, laid down until the gap is closed.", source: "Botany", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Parts of the Biebrza marshes that were once drained for farmland are being let go back to wetland now — the ground finding its way back to what it was.", source: "Biebrza", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Przysłowie polskie: nie ma tego złego, co by na dobre nie wyszło — there's no bad that doesn't turn out, in the end, for the good.", source: "Przysłowie polskie", theme: .renewal, subtheme: .madeWhole),

        // MARK: Light
        // theEdgesOfTheDay
        Passage(text: "Wschód, the Polish word for both east and sunrise, comes from wschodzić, to rise — the same verb used for dough. The sun is doing what bread does.", source: "Polish", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Zachód names both the west and the sunset — and, in another sense entirely, the trouble something takes to arrange. Bez zachodu means without any fuss.", source: "Polish", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "On Kupała night, the shortest of the year, wreaths of flowers are set alight with candles and let go down the river, one for each wish.", source: "Polish custom", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Polish keeps brzask, the first grey before anything else happens, separate from świt, the dawn that properly follows it — two words for two edges of one event.", source: "Polish", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "The reddest sunsets happen when the sun's light has the most air to cross to reach you — which is exactly what's going on at the edges of the day and never at noon.", source: "Physics", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Białowieża is loudest right at the edges of the day: a dawn chorus, and a quieter answering one at dusk, with the hours between comparatively hushed.", source: "Białowieża", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "In Polish villages, church bells once rang out the edges of the day itself — morning, noon and evening — whether or not anyone was near enough to hear them.", source: "Polish custom", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "A Polish summer evening can hold on to its light for hours after sunset. A December one loses it within minutes.", source: "Polish, seasons", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Mist over the Biebrza is thickest right at dawn, burned off within the hour once the sun properly clears the treeline.", source: "Biebrza", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Wieczornica, the evening star — really the planet Venus — was once as good as any farmer needed for knowing it was time to head back from the fields.", source: "Polish, folk astronomy", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Autumn evenings in Poland often carry the sound of cranes long before the birds themselves come into view, crossing high at the edge of the light.", source: "Grus grus", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Shadows are longest at the two edges of the day and shortest in between — the sun is never lower in the sky than right at sunrise or sunset.", source: "Physics", theme: .light, subtheme: .theEdgesOfTheDay),
        // readingTheLight
        Passage(text: "Older Polish churches often carry a scratched sundial on the south wall — no gnomon left now, just the marks for a system that only worked when the sun did.", source: "Polish, church history", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Amber sellers on the Baltic coast still hold a piece up to the light before anything else. Clarity is most of what decides what it's worth.", source: "Bursztyn", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Storks only start gathering to migrate south once the days have shortened past a certain point — the same clock that tells a flower to bloom tells a bird to leave.", source: "Ciconia ciconia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "An owl's eyes are built to make the most of what little light is there, rather than to gather more of it — the same low light, read a different way.", source: "Strigiformes", theme: .light, subtheme: .readingTheLight),
        Passage(text: "In the oldest parts of Białowieża, the canopy is dense enough that only about two percent of daylight reaches the forest floor. Everything down there has learned to read that thin ration.", source: "Białowieża", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Polish farmers once timed planting and cutting by the phase of the moon as much as by the sun — root vegetables sown at the waning moon, so the story went.", source: "Polish, folk practice", theme: .light, subtheme: .readingTheLight),
        Passage(text: "A bee reads the sun's position to tell the rest of the hive which way the flowers are, adjusting the angle of her dance as the sun moves through the day.", source: "Apis mellifera", theme: .light, subtheme: .readingTheLight),
        Passage(text: "The aurora is sunlight's own particles, flung out from the sun and caught by the earth's magnetic field. Colour is just what that collision looks like from below.", source: "Physics", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Rosiczka, sundew, growing in Polish bogs, catches the light in every sticky droplet on its leaves — which is exactly what draws an insect close enough to be caught.", source: "Drosera", theme: .light, subtheme: .readingTheLight),
        Passage(text: "A young sunflower head turns to track the sun through the day, then swings back overnight to face east again, ready for morning.", source: "Helianthus annuus", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Dew only shows itself once there's enough light to catch it. It was there in the dark too, just not visible yet.", source: "Physics", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Zorza is the Polish word for both the colour at dawn or dusk and for the aurora — two very different lights sharing one name.", source: "Polish", theme: .light, subtheme: .readingTheLight),
        // lightItself
        Passage(text: "Słońce, the Polish word for the sun, is grammatically a diminutive — literally a little sun — though there's nothing little about what it means.", source: "Polish", theme: .light, subtheme: .lightItself),
        Passage(text: "Księżyc, the Polish word for the moon, comes from książę, prince — a little prince set beside the sun in the sky.", source: "Polish", theme: .light, subtheme: .lightItself),
        Passage(text: "Robaczek świętojański, the glow-worm, is named for St John's night, when the dark finally gets late enough for its small cold light to show.", source: "Lampyris noctiluca", theme: .light, subtheme: .lightItself),
        Passage(text: "Bursztyn, amber, was called the gold of the north for centuries before anyone worked out it wasn't a mineral at all — just old sunlight, sealed into resin.", source: "Bursztyn", theme: .light, subtheme: .lightItself),
        Passage(text: "On Kupała night, bonfires are lit along the riverbanks — the light that used to stand in for the sun through the shortest dark of the year.", source: "Polish custom", theme: .light, subtheme: .lightItself),
        Passage(text: "The warmest shade of amber is named after honey in Polish — miodowy — the same warm light two entirely different things happen to hold.", source: "Bursztyn", theme: .light, subtheme: .lightItself),
        Passage(text: "Frost on a window catches low winter light and throws it back in every direction at once, which is most of why it looks the way it does.", source: "Physics", theme: .light, subtheme: .lightItself),
        Passage(text: "Fresh snow reflects most of the light that hits it, which is why a short Polish winter day can still feel bright enough to need sunglasses.", source: "Physics", theme: .light, subtheme: .lightItself),
        Passage(text: "Stanisław Wyspiański designed the stained glass for a Franciscan church in Kraków — sunflowers and irises worked out so the light falling through is already the colour of the flower.", source: "Stanisław Wyspiański (d. 1907)", theme: .light, subtheme: .lightItself),
        Passage(text: "On a still evening, a Mazurian lake holds the whole sunset twice — once in the sky, once flat on the water below it.", source: "Geography", theme: .light, subtheme: .lightItself),
        Passage(text: "Widnokrąg, the Polish word for horizon, means literally circle of light — the ring around you as far as brightness reaches.", source: "Polish", theme: .light, subtheme: .lightItself),
        Passage(text: "On rare warm nights, the surf along the Baltic coast can glow faintly blue — tiny plankton lighting up wherever the water's disturbed enough to bother them.", source: "Baltic Sea", theme: .light, subtheme: .lightItself),

        // MARK: Pattern
        // counted
        Passage(text: "Tydzień, a week, comes from ten dzień, this same day — the week is just the day that takes seven turns to come back around.", source: "Polish", theme: .pattern, subtheme: .counted),
        Passage(text: "Miesiąc is both a month and the moon in Polish — one word doing the job English split into two.", source: "Polish", theme: .pattern, subtheme: .counted),
        Passage(text: "Stokrotka, the daisy, means a hundredfold — Polish counted the crowd of petals, where English counted the flower opening and closing with the day.", source: "Polish", theme: .pattern, subtheme: .counted),
        Passage(text: "The scales on a pine cone spiral in two directions at once, and the count of spirals each way is almost always a pair from the same sequence — eight and thirteen, most commonly.", source: "Botany", theme: .pattern, subtheme: .counted),
        Passage(text: "Grzybiarze coming out of the woods with a full basket count in heads, not weight, at the end of a good day — how many, not how much.", source: "Polish, foraging", theme: .pattern, subtheme: .counted),
        Passage(text: "Every winter, rangers in Białowieża go out to count the bison herd by hand, the same census repeated one more year running since 1946.", source: "Bison bonasus", theme: .pattern, subtheme: .counted),
        Passage(text: "Counting a daisy's petals down to the very last one — kocha, nie kocha, loves me, loves me not — is played out in Polish exactly as it is everywhere else the flower grows.", source: "Polish, folk game", theme: .pattern, subtheme: .counted),
        Passage(text: "In villages without clocks, you counted the church bell's strokes to know the hour — the sound doing the arithmetic for you.", source: "Polish custom", theme: .pattern, subtheme: .counted),
        Passage(text: "A tree lays down one ring a year, so plainly that counting them is still the surest way to know exactly how old it is.", source: "Botany", theme: .pattern, subtheme: .counted),
        Passage(text: "A beekeeper checking a frame counts capped cells row by row to work out how the whole colony is doing, without ever having to count every bee.", source: "Polish, beekeeping", theme: .pattern, subtheme: .counted),
        Passage(text: "Przysłowie polskie: ile ludzi, tyle zdań — as many people, that many opinions. Polish counts opinions the way it counts anything else.", source: "Przysłowie polskie", theme: .pattern, subtheme: .counted),
        Passage(text: "Redyk, the spring drive of sheep up into the Tatra pastures, starts with a careful count at the bottom and ends with the same count checked again at the top.", source: "Polish, Podhale", theme: .pattern, subtheme: .counted),
        // fittedTogether
        Passage(text: "Wycinanki, the paper cut-outs of the Łowicz region, are folded before they're cut, so whatever shape the scissors make comes out matched around a centre.", source: "Polish, Łowicz", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "No two snowflakes are exactly alike, but every one is built on the same six-way fit — water molecules only lock together at that one angle.", source: "Physics", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Traditional Kashubian embroidery follows fixed pairings of colour and stitch. A certain flower is always the same shade, so any two pieces of it still read as the same language.", source: "Polish, Kaszuby", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A lichen isn't one organism but two — a fungus and an alga, fitted together so completely that for a long time nobody realised it wasn't just one.", source: "Lichenology", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Two groups of bees can build comb from opposite ends of the same frame and meet exactly in the middle, the cells lining up as if only one map had ever existed.", source: "Apis mellifera", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A dragonfly's wing is a mesh of tiny cells, no two quite the same shape, fitted together just well enough to keep the whole wing rigid in flight.", source: "Odonata", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Salt forms cubes because its two ions pack together in the one arrangement that lets each sit as closely as possible against its neighbours.", source: "Chemistry", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A garden spider's web is spun as one continuous thread, looped and anchored so that every ring depends on the tension of the one before it.", source: "Araneidae", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Two trees of the same species growing close enough can fuse roots underground without either one noticing, sharing water back and forth through what's now one root system.", source: "Botany", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A plane tree's bark peels away in patches that never quite line up the same way twice, and yet somehow the whole trunk stays covered.", source: "Platanus", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A traditional woven fence, płot pleciony, is built from branches bent in and out of a line of uprights, with nothing holding them but the fit of one against the next.", source: "Polish, craft", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "A thatched roof, strzecha, is laid in overlapping courses, each one sitting just over the last, so water is passed down and out without ever finding a gap.", source: "Polish, craft", theme: .pattern, subtheme: .fittedTogether),
        // orderNamed
        Passage(text: "Poniedziałek, Monday, means simply after the not-working — Polish names the start of the week by counting outward from niedziela, the day of rest.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kwiecień, April, is named for kwiat, flower — the only month in the Polish calendar named for what starts blooming in it.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Sierpień, August, is named for sierp, the sickle — the month named for what was in every hand at harvest.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Wrzesień, September, is named for wrzos — the heather that turns whole hillsides purple right as the month begins.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Listopad, November, means leaves falling, quite plainly. One of the few month names anywhere that just says what it sees.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Grudzień, December, is named for gruda, a frozen clod of earth — the month the ground stops giving way underfoot.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Lipiec, July, is named for lipa, the linden — the month the village tree comes into flower.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Czerwiec, June, is named for czerw, a small grub once gathered that month for the red dye made from it.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Styczeń, January, comes from styk, a joining — the point where one year meets the next.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Luty, February, is named for being fierce — the harshest of the winter months, and Polish simply called it what it was.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Only two months in the Polish calendar kept their Roman names outright — marzec and maj. Every other one was renamed for what actually happens in it.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Październik, October, is named for paździerz, the coarse waste left over from working flax — the month that smelled of it.", source: "Polish", theme: .pattern, subtheme: .orderNamed),
        // MARK: Ground

        // theSoilItself
        Passage(text: "Ziemia znaczy po polsku i glebę pod stopami, i cały kraj — jedno słowo, dwie rzeczy naraz.", source: "Polski, etymologia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Czarnoziem to gleba tak żyzna, że tworzyły ją tysiące lat stepowe trawy — jedna z najbogatszych ziem uprawnych na świecie.", source: "Gleboznawstwo", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Miedza to wąski pas ziemi między dwoma polami, którego nie orze żadna ze stron — granica, którą obie zostawiają w spokoju.", source: "Rolnictwo", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Dżdżownica potrafi w ciągu roku przepuścić przez siebie tyle ziemi, że zostawia po sobie warstwę żyznej próchnicy.", source: "Lumbricus terrestris", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Żyto radzi sobie na glebach zbyt ubogich dla pszenicy — przez wieki to ono karmiło Polskę, nie pszenica.", source: "Rolnictwo", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Dożynki to święto po żniwach — wieniec upleciony z ostatnich kłosów, niesiony na czele pochodu i darowany gospodarzowi.", source: "Zwyczaj dożynkowy", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Kopalnia soli w Wieliczce działa od średniowiecza, a jej chodniki ciągną się dziś na kilkaset kilometrów pod ziemią.", source: "Kopalnia Soli Wieliczka", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ziarnko do ziarnka, a zbierze się miarka.", source: "Przysłowie polskie", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Próchnica, w której rośnie większość roślin, bywa grubsza niż dłoń, a bywa cieńsza niż paznokieć — i to ona decyduje, co się przyjmie.", source: "Gleboznawstwo", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ugór to pole zostawione na rok bez zasiewu, żeby ziemia zdążyła odpocząć, zanim znów coś na niej wyrośnie.", source: "Rolnictwo", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Bagna Biebrzańskie to jedne z największych torfowisk Europy, zachowane niemal w naturalnym stanie do dziś.", source: "Biebrzański Park Narodowy", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Skiba to jeden pas ziemi odwrócony pługiem — najmniejsza jednostka, jaką liczy się zaoraną ziemię.", source: "Rolnictwo", theme: .ground, subtheme: .theSoilItself),

        // aPlaceYouAreFrom
        Passage(text: "Ojczyzna pochodzi od ojca — kraj nazwany po tym, kto go dał. Polszczyzna ma też macierz, ten sam kraj nazwany po matce.", source: "Polski, etymologia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Litwo! Ojczyzno moja! ty jesteś jak zdrowie.", source: "Adam Mickiewicz, Pan Tadeusz, 1834", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Co czwarty bocian biały na świecie gniazduje w Polsce, najczęściej na dachu, kominie albo starym słupie, tuż przy ludziach.", source: "Ciconia ciconia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "W niejednej wsi koło albo stara szyna czeka na dachu specjalnie po to, żeby bocian miał na czym uwić gniazdo.", source: "Zwyczaj wiejski", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Jaskółki, podobnie jak bociany, wracają co wiosnę pod ten sam dach — czasem naprawiając stare gniazdo zamiast budować nowe.", source: "Hirundinidae", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Wszędzie dobrze, ale w domu najlepiej.", source: "Przysłowie polskie", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Tęsknota nazywa coś, czego angielski nie ma jednym słowem — nie tylko tęsknotę za osobą, czasem za samym miejscem.", source: "Polski, etymologia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "W małej wsi każdy sąsiad wie, z którego domu pochodzisz, choćby nikt nigdy nie zapytał wprost.", source: "Zwyczaj wiejski", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Puszcza Białowieska to ostatni skrawek lasu, jaki niegdyś pokrywał całą nizinną Europę.", source: "Puszcza Białowieska", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Strony rodzinne to zwrot, który nie wskazuje jednego adresu, tylko całą okolicę naraz — wieś, drogę do niej i pola dookoła.", source: "Polski, zwrot", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Wiele polskich nazwisk kończy się na -ski, co pierwotnie znaczyło po prostu z tego miejsca — Kowalski, ten z Kowalów.", source: "Onomastyka", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kraj lat dziecinnych to zwrot na miejsce, do którego nikt nie wraca dwa razy tą samą drogą, bo pamięć zmienia się szybciej niż droga.", source: "Polski, zwrot", theme: .ground, subtheme: .aPlaceYouAreFrom),

        // aKeptPlace
        Passage(text: "Ogród to ziemia otoczona i utrzymywana — samo słowo pochodzi od ogrodzenia, granicy, która mówi, że ktoś się tym miejscem zajmuje.", source: "Polski, etymologia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Gospodarstwo bywa niewielkie, ale w każdym kącie widać rękę, która je codziennie utrzymuje.", source: "Zwyczaj wiejski", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Sad przydomowy sadzi się zwykle bliżej domu niż pole, żeby można było doglądać go, wychodząc po prostu za próg.", source: "Ogrodnictwo", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Studnia na podwórzu bywała wspólna dla kilku gospodarstw naraz — miejsce, którego pilnowali wszyscy razem.", source: "Zwyczaj wiejski", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Płot niekoniecznie mówi trzymaj się z daleka — czasem mówi tylko tutaj ktoś się tym zajmuje.", source: "Polski, zwrot", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Zagroda to gospodarstwo razem z domem, obejściem i ogrodzeniem — samo słowo obejmuje wszystko naraz, nie tylko budynek.", source: "Polski, etymologia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Przyzba to ziemna ławka pod ścianą domu, ubita i utrzymywana z pokolenia na pokolenie, na której siadano wieczorem.", source: "Budownictwo wiejskie", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kwiaty w oknie mówią przechodniowi, że dom jest zamieszkany i pilnowany, nawet gdy nikogo nie widać na podwórzu.", source: "Zwyczaj miejski", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Miedza, ogród, zagroda — polski ma osobne słowo na prawie każdą granicę, jaką można wyznaczyć wokół ziemi.", source: "Polski, słownictwo", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kapusta i ziemniaki w przydomowym ogródku zwykle rosną najbliżej kuchni — im częściej się po coś sięga, tym bliżej to sadzą.", source: "Ogrodnictwo", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Chata bywała mała, ale zawsze miała kąt, w którym trzymano to, co najcenniejsze — ziarno na następny siew.", source: "Zwyczaj wiejski", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Nie miejsce zdobi człowieka, lecz człowiek miejsce.", source: "Przysłowie polskie", theme: .ground, subtheme: .aKeptPlace),
        // MARK: Travel

        // howASeedGoes
        Passage(text: "Nasiona klonu mają skrzydełko, które kręci je jak śmigło i pozwala im odlecieć dalej, niż spadłyby prosto w dół.", source: "Acer", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rzep łopianu czepia się sierści haczykowatymi kolcami — przyczepia się, jedzie kawałek drogi i odpada gdzie indziej.", source: "Arctium", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Niecierpek strzela nasionami z pękającej torebki, kiedy ktoś jej dotknie — stąd łacińska nazwa Impatiens, niecierpliwy.", source: "Impatiens", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mrówki roznoszą nasiona fiołka, przyciągnięte tłuszczową przynętą przyklejoną z boku — zjadają przynętę, nasiono zostawiają w nowym miejscu.", source: "Myrmekochoria", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kokos potrafi płynąć po morzu tygodniami i wciąż wykiełkować, kiedy fala wyrzuci go na piasek daleko od macierzystej palmy.", source: "Cocos nucifera", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Jemioła leci dalej dzięki ptakowi, który zjada jej lepkie owoce i przenosi nasiona z jednego drzewa na drugie w swoim locie.", source: "Viscum album", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Dmuchawiec został zbudowany tak, żeby najlżejszy podmuch rozniósł go na wszystkie strony naraz — stąd jego polska nazwa.", source: "Taraxacum", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Niektóre nasiona czekają w ziemi na pożar — dopiero żar otwiera ich łuskę i pozwala im wreszcie wyjść na światło.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Wiewiórka zakopuje więcej orzechów, niż zdoła odnaleźć, i to zapomniane właśnie stają się nowymi drzewami.", source: "Sciurus vulgaris", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rzeka niesie nasiona wierzby z prądem, aż osiądą na mulistym brzegu, gdzie znajdą dość wilgoci, żeby wykiełkować.", source: "Salix", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bocian, który co roku leci do Afryki i z powrotem, bywa też mimowolnym przewoźnikiem nasion zaplątanych w błocie na jego nogach.", source: "Ciconia ciconia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Orzech włoski toczy się z górki, aż zatrzyma go pierwsza przeszkoda — nieraz dużo dalej, niż sięga cień drzewa, z którego spadł.", source: "Juglans regia", theme: .travel, subtheme: .howASeedGoes),

        // theRoad
        Passage(text: "Gościniec to stary polski wyraz na główny trakt między miastami — drogę, po której szedł nie tylko gospodarz, ale i gość.", source: "Polski, etymologia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Trakt Warszawsko-Krakowski to jeden z najstarszych i najważniejszych szlaków dawnej Polski, którym wieziono ludzi, pocztę i towary.", source: "Historia dróg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Szlak bursztynowy prowadził przez ziemie dzisiejszej Polski, znad Bałtyku aż nad Morze Śródziemne, którędy bursztyn wędrował, zanim dotarł do Rzymu.", source: "Szlak Bursztynowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Świętego Krzysztofa proszono dawniej o opiekę nad podróżnym, zanim jeszcze wyruszył za próg.", source: "Zwyczaj ludowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Karczma stała zwykle w połowie drogi między dwiema wsiami — nie na początku i nie na końcu, tylko dokładnie tam, gdzie podróżny najbardziej jej potrzebował.", source: "Zwyczaj drogowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kamień graniczny wkopywano głęboko i zakopywano pod nim węgiel albo skorupę, żeby nikt nie mógł go po cichu przesunąć.", source: "Miernictwo dawne", theme: .travel, subtheme: .theRoad),
        Passage(text: "Podkowa przybita nad drzwiami karczmy miała, jak wierzono, przynosić szczęście każdemu, kto właśnie wyruszał w drogę.", source: "Zwyczaj ludowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Odpust łączył niegdyś pielgrzymkę z jarmarkiem — ludzie szli całą drogę pieszo, a przy kościele czekał już handel i muzyka.", source: "Zwyczaj ludowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Droga Mleczna to polska nazwa naszej galaktyki — nazwa, która w wielu kulturach świata też przywołuje obraz drogi, szlaku na niebie.", source: "Astronomia, nazewnictwo", theme: .travel, subtheme: .theRoad),
        Passage(text: "Z każdej strony gościńca sadzono niegdyś drzewa, żeby wędrowiec miał w upale cień, a w zimie linię, która pokazywała, gdzie jeszcze jest droga.", source: "Zwyczaj drogowy", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kto pyta, nie błądzi.", source: "Przysłowie polskie", theme: .travel, subtheme: .theRoad),
        Passage(text: "Krakowska Droga Królewska prowadziła od Bramy Floriańskiej przez Rynek aż na Wawel — tędy szli monarchowie, tędy dziś idzie każdy, kto zwiedza miasto.", source: "Kraków, trakt koronacyjny", theme: .travel, subtheme: .theRoad),

        // farOff
        Passage(text: "Morze Bałtyckie po polsku bywało dawniej nazywane po prostu Morzem — dla ludzi znad Wisły dalej już nie było dokąd płynąć.", source: "Polski, nazewnictwo", theme: .travel, subtheme: .farOff),
        Passage(text: "Za górami, za lasami — dawna formuła otwierająca baśń, mówiąca, że to, co się zaraz wydarzy, jest bardzo, bardzo daleko stąd.", source: "Formuła baśniowa", theme: .travel, subtheme: .farOff),
        Passage(text: "Najdalej od lądu na świecie można się znaleźć w jednym punkcie południowego Pacyfiku, ponad dwa tysiące kilometrów od najbliższego brzegu.", source: "Punkt Nemo, oceanografia", theme: .travel, subtheme: .farOff),
        Passage(text: "Mikołaj Kopernik obliczył względne odległości planet od Słońca, obserwując niebo gołym okiem, bez teleskopu, którego jeszcze nie wynaleziono.", source: "Mikołaj Kopernik, astronomia", theme: .travel, subtheme: .farOff),
        Passage(text: "Antypody to miejsce dokładnie po drugiej stronie Ziemi — tam, gdzie ktoś stoi stopami dokładnie naprzeciw twoich.", source: "Geografia, z greckiego", theme: .travel, subtheme: .farOff),
        Passage(text: "Daleki Wschód dla żeglarzy sprzed wieków zaczynał się tam, gdzie kończyły się znane mapy, a zaczynało białe pole z dopiskiem terra incognita.", source: "Kartografia dawna", theme: .travel, subtheme: .farOff),
        Passage(text: "Najdalszy punkt, jaki człowiek kiedykolwiek odwiedził, to Księżyc — nieco ponad trzysta osiemdziesiąt tysięcy kilometrów od progu domu.", source: "Astronautyka", theme: .travel, subtheme: .farOff),
        Passage(text: "Gwiazda Polarna nie porusza się po niebie, więc wystarczyło ją odnaleźć, żeby wiedzieć, w którą stronę leży dom, choćby się było bardzo daleko.", source: "Astronomia nawigacyjna", theme: .travel, subtheme: .farOff),
        Passage(text: "Radioteleskop odbiera dziś sygnał, który wyruszył w drogę, zanim jeszcze powstała Ziemia — najdalsze, co człowiek potrafi usłyszeć.", source: "Radioastronomia", theme: .travel, subtheme: .farOff),
        Passage(text: "Za horyzontem statek nie znika naprawdę — chowa się tylko za krzywizną Ziemi, kadłub pierwszy, maszty najdłużej.", source: "Żegluga, geometria", theme: .travel, subtheme: .farOff),
        Passage(text: "Bociany, przelatując nad Saharą, potrafią lecieć wiele godzin bez przerwy, bo nad pustynią brakuje wznoszących prądów powietrza, na których zwykle oszczędzają siły.", source: "Ciconia ciconia", theme: .travel, subtheme: .farOff),
        Passage(text: "Jedwabny Szlak łączył Chiny z Europą tysiącami kilometrów lądu — przez niego dotarł do Polski niejeden towar, zanim dotarł tu jakikolwiek podróżny.", source: "Jedwabny Szlak", theme: .travel, subtheme: .farOff),
        // MARK: Meeting

        // theMoment
        Passage(text: "Pierwsze wrażenie w polskim bywa nazywane pierwszym wejrzeniem — jakby oko zdążyło zobaczyć wszystko, zanim ktokolwiek się odezwał.", source: "Polski, zwrot", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Przypadek to po polsku i zbieg okoliczności, i to, co spadło — jakby spotkanie było czymś, co się na kogoś przypadkiem zwaliło.", source: "Polski, etymologia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Pszczoła rozpoznaje inny kwiat tego samego gatunku po zapachu, zanim jeszcze go zobaczy — spotkanie zaczyna się, zanim się zacznie.", source: "Apis mellifera", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Dzień dobry mówi się w Polsce od rana do wczesnego popołudnia, a później już tylko dobry wieczór — sam język dzieli spotkania na pory.", source: "Polski, zwrot", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Motyl wybiera kwiat po barwach niewidocznych dla ludzkiego oka — spotyka go inaczej, niż my widzimy to samo spotkanie.", source: "Lepidoptera", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ziarno pyłku niesione przez wiatr trafia na właściwy słupek raz na wiele tysięcy prób — a jednak wystarczy, że trafi raz.", source: "Botanika, zapylanie", theme: .meeting, subtheme: .theMoment),
        Passage(text: "W polskich wsiach dzwon kościelny obwieszczał południe, i to on, nie zegarek, wyznaczał moment, w którym ścieżki ludzi wracających z pola się krzyżowały.", source: "Zwyczaj wiejski", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Sarny spotykają się na skraju lasu o zmierzchu, w tej samej krótkiej chwili, kiedy dzienne zwierzęta już się chowają, a nocne jeszcze się nie obudziły.", source: "Capreolus capreolus", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Serendipity nie ma jednego polskiego odpowiednika — najbliżej jest szczęśliwy zbieg okoliczności, zdanie zamiast słowa.", source: "Polski, słownictwo", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Pierwsze spotkanie dwojga ludzi trwa w pamięci znacznie dłużej niż samo trwało — mózg zapisuje nowość dokładniej niż powtórkę.", source: "Psychologia poznawcza", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Iskra to słowo, którego polski używa i na to, co przeskakuje między krzesiwem a hubką, i na to, co przeskakuje między dwojgiem ludzi.", source: "Polski, metafora", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Wzrok ludzki potrafi wyłowić znajomą twarz w tłumie kilkudziesięciu obcych w ułamku sekundy, szybciej, niż zdążymy pomyśleć, że kogoś rozpoznajemy.", source: "Psychologia poznawcza", theme: .meeting, subtheme: .theMoment),

        // twoThatNeedEachOther
        Passage(text: "Koniczyna i trzmiel potrzebują siebie nawzajem tak ściśle, że tam, gdzie zabrakło trzmieli, koniczyna przestała wydawać nasiona.", source: "Trifolium i Bombus", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Figowiec i osa figowa są sobie potrzebne do tego stopnia, że niemal każdy gatunek fig ma swoją jedną, jedyną osę.", source: "Ficus i Agaonidae", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Grzyb mikoryzowy oplata korzenie drzewa i wymienia z nim wodę na cukier — żadne z nich osobno nie rosłoby tak dobrze.", source: "Mykoryza", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ptak miodowskaz prowadzi ludzi do gniazda dzikich pszczół, licząc na to, że po miód zostawią mu kawałek plastra.", source: "Indicator indicator", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Porost to grzyb i glon złączone tak dokładnie, że przez wieki uznawano go za jeden, osobny organizm.", source: "Lichenes", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Rafa koralowa i mikroskopijne glony żyjące w jej tkankach wymieniają się światłem i pokarmem — bez glonów koralowiec blednie i głoduje.", source: "Symbioza koralowa", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mrówki pasterskie osłaniają mszyce przed drapieżnikami w zamian za słodką spadź, którą mszyce wydzielają z odwłoka.", source: "Formicidae i Aphidoidea", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ryba-pilot płynie tuż przy rekinie przez całe życie, żywiąc się resztkami jego posiłków, a rekin, mimo że mógłby, prawie nigdy jej nie zjada.", source: "Naucrates ductor", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Storczyk pszczelowaty przypomina kształtem i zapachem samicę pszczoły tak dokładnie, że oszukany samiec zapyla go, próbując się z nim skrzyżować.", source: "Ophrys apifera", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Truflowiec, grzyb tworzący trufle, żyje w ścisłej symbiozie z korzeniami dębu lub leszczyny — bez drzewa nie powstanie ani jedna trufla.", source: "Tuber i Quercus", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Dwoje ludzi, którzy się uzupełniają, po polsku bywa nazywane pasować do siebie jak ulał — jakby jedno było formą odlaną dokładnie na miarę drugiego.", source: "Polski, zwrot", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Storczyk waniliowy potrzebuje dokładnie jednego gatunku pszczoły z Meksyku, żeby dać nasiona — gdziekolwiek indziej trzeba go zapylać ręcznie, kwiat po kwiecie.", source: "Vanilla planifolia", theme: .meeting, subtheme: .twoThatNeedEachOther),

        // theMannersOfIt
        Passage(text: "Gość w dom, Bóg w dom.", source: "Przysłowie polskie", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Gościnność po polsku wywodzi się od tego samego rdzenia co gość — jakby przyjmowanie kogoś było wpisane już w samo słowo na niego.", source: "Polski, etymologia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Chleb i sól podawano dawniej gościowi na progu — chleb, bo było go najwięcej, sól, bo była najdroższa.", source: "Zwyczaj powitalny", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Przy wigilijnym stole zostawia się dodatkowe, puste nakrycie — dla tego, kto zapuka, choć nikt go nie zaprosił.", source: "Zwyczaj wigilijny", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Przyjaciel pochodzi od przyjąć — od tego, kogo się przyjmuje do siebie, nie tylko wpuszcza za próg.", source: "Polski, etymologia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Czym chata bogata, tym rada.", source: "Przysłowie polskie", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Sąsiad to dosłownie ten, kto siedzi obok — sąsiad i siedzieć dzielą w polskim ten sam rdzeń.", source: "Polski, etymologia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Podanie prawej ręki na powitanie ma sięgać czasów, kiedy pokazywano nią, że nie trzyma się broni.", source: "Zwyczaj powitalny", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kiedy gość wchodził do izby, gospodarz pierwszy podawał krzesło najbliżej pieca — najcieplejsze miejsce w domu było zawsze dla niego.", source: "Zwyczaj wiejski", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Częstować kogoś po polsku znaczy dosłownie robić coś częste — nie raz, tylko wielokrotnie podsuwać talerz, aż gość naprawdę odmówi.", source: "Polski, etymologia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Przekraczanie progu z prawej nogi miało dawniej przynosić szczęście całemu spotkaniu, nie tylko temu, kto wchodził.", source: "Zwyczaj ludowy", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kożuch narzucony na ramiona gościa przy wychodzeniu w mróz był w wielu domach tak oczywisty, że nikt nie musiał go o to prosić.", source: "Zwyczaj wiejski", theme: .meeting, subtheme: .theMannersOfIt),
        // MARK: Kinship

        // grownTogether
        Passage(text: "Inosculacja to zrastanie się dwóch gałęzi różnych drzew, kiedy przez lata rosną tak blisko, że kora między nimi w końcu znika.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Szczepienie sadownicze łączy pęd jednej odmiany z korzeniem drugiej — po kilku latach nikt już nie znajdzie granicy między nimi.", source: "Sadownictwo", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Bluszcz piąć się może po drzewie dziesiątkami lat, aż korzenie obu roślin splotą się w ziemi tak, że rosną odtąd jak jedna.", source: "Hedera helix", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Dwa drzewa posadzone zbyt blisko siebie czasem zrastają się pniami, a korona dzieli się na dwoje, jakby to było jedno drzewo o dwóch imionach.", source: "Dendrologia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Korzenie sąsiadujących drzew tego samego gatunku potrafią się zrosnąć pod ziemią, tak że przez wiele lat dzielą między sobą wodę i sole mineralne.", source: "Dendrologia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Rodzeni to po polsku ci, którzy dzielą jedno urodzenie — samo słowo mówi, że zaczęli w tym samym miejscu i czasie.", source: "Polski, etymologia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Splot to węzeł, w którym dwie nitki tak się przeplatają, że nie da się już powiedzieć, która była pierwsza.", source: "Polski, tkactwo", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Dwa pnie, które zrosły się w młodości, poszerzają się później razem, rok po roku, aż słoje przyrostu w obu wyglądają, jakby liczyły ten sam czas.", source: "Dendrologia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Winorośl owija się wokół podpory tak ściśle, że po latach drewno wrasta w metal, jeśli akurat na taką podporę trafiła.", source: "Vitis vinifera", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Dwie rzeki płynące osobno przez wieki, zanim się złączą w jedną, wciąż niosą przez jakiś czas swoje osobne kolory wody, zanim się wymieszają.", source: "Hydrologia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Gniazdo bociana bywa dobudowywane rok po roku, aż stare i nowe gałęzie stworzą jedną konstrukcję, w której nie widać już, co dołożono kiedy.", source: "Ciconia ciconia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Splecione palce dłoni to jeden z najstarszych gestów bliskości, jaki człowiek zna — dwie ręce, które przez chwilę udają jedną.", source: "Gest ludzki", theme: .kinship, subtheme: .grownTogether),

        // theWordsForIt
        Passage(text: "Rodzina po polsku obejmuje też powinowatych — tych, z kim jesteś związany przez małżeństwo, nie przez krew, a mimo to nazywasz ich tym samym słowem.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Krewni dzielą jedno słowo z krwią — jakby pokrewieństwo było czymś, co dosłownie płynie między ludźmi.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Żal w polskim znaczy naraz smutek i tęsknotę i lekką pretensję — jedno słowo robi robotę trzech.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Dziadek i babcia w wielu polskich rodzinach bywają nazywani zdrobnieniem całe życie — dziadziuś, babcia, tak jakby czułość nie miała nigdy wygasnąć.", source: "Polski, zwyczaj językowy", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Rodzeństwo to zbiorowe słowo na wszystkich, którzy dzielą rodziców — liczba, której polski nie rozbija na braci i siostry, dopóki nie musi.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Kuzyn przyszedł do polskiego z francuskiego cousin, ale samo pokrewieństwo, które nazywa, polszczyzna znała już dużo wcześniej pod innymi słowami.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Wuj, stryj — dawna polszczyzna miała osobne słowo na brata matki i osobne na brata ojca, rozróżnienie, które dziś już się zaciera.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Chrzestny i chrzestna wiążą się z dzieckiem węzłem, którego polski prawie nie odróżnia od pokrewieństwa krwi, choć nie ma w nim ani kropli.", source: "Polski, zwyczaj", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Powinowactwo to pokrewieństwo przez ślub, a nie przez krew — słowo, które mówi wprost, że więź może zacząć się decyzją, nie tylko urodzeniem.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Bratanek i siostrzeniec to w polskim dwa różne słowa na syna brata i syna siostry — rozróżnienie, którego angielski nawet nie próbuje robić.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Teść i teściowa, szwagier i szwagierka — polski ma osobne imię niemal na każdą więź, jaką małżeństwo dorzuca do rodziny.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Rodzina pochodzi od rodzić — od tego samego czasownika, co narodziny i przyroda, jakby wszystkie trzy były odmianami jednej sprawy.", source: "Polski, etymologia", theme: .kinship, subtheme: .theWordsForIt),

        // twoPeople
        Passage(text: "Dwoje to najmniejsza liczba, przy której słowo razem w ogóle zaczyna coś znaczyć.", source: "Refleksja", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "My w polskim, użyte o dwojgu ludzi, znaczy już coś innego niż ja i ja obok siebie — trzecie słowo na dwoje, które się dogadały.", source: "Polski, gramatyka", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dawna polszczyzna miała osobną liczbę podwójną, gramatyczną formę tylko na dokładnie dwoje — nie jedno, nie wiele, tylko parę.", source: "Polski, gramatyka historyczna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Żurawie wybierają partnera na całe życie i witają się po każdej rozłące tym samym, rozpoznawalnym tańcem.", source: "Grus grus", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Łabędzie potrafią wygiąć szyje w kształt serca, patrząc na siebie — przypadek geometrii, któremu ludzie nadali znaczenie.", source: "Cygnus", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dwie dłonie złożone razem do powitania mówią więcej niż jedna wyciągnięta samotnie — gest, którego nie da się wykonać w pojedynkę.", source: "Gest ludzki", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Duet po włosku i po polsku znaczy to samo — dwoje, które razem robi coś, czego żadne z nich nie zrobiłoby tak samo osobno.", source: "Muzyka, etymologia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Konwersacja pochodzi od łacińskiego obracać się razem — dwoje ludzi krążących wokół tego samego tematu, każde ze swojej strony.", source: "Łacina, etymologia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dwa echa w górach potrafią się nałożyć tak dokładnie, że brzmią jak jeden głos, mimo że odbiły się od dwóch różnych zboczy.", source: "Akustyka górska", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Wilki w parze polują skuteczniej niż w pojedynkę, ale też skuteczniej niż w zbyt licznej watasze — dwoje bywa liczbą w sam raz.", source: "Canis lupus", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ślubny pierścionek nosi się w Polsce najczęściej na prawej ręce, inaczej niż w wielu innych krajach — mały szczegół, po którym od razu widać parę.", source: "Zwyczaj, Polska", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Dwie osoby idące obok siebie synchronizują nieświadomie także rytm oddechu, jakby chodzenie razem było już rodzajem rozmowy.", source: "Fizjologia chodu", theme: .kinship, subtheme: .twoPeople),
        // MARK: Peace

        // quietAsASound
        Passage(text: "Cisza to brak dźwięku, ale milczenie to decyzja, żeby się nie odzywać — polski ma dwa słowa tam, gdzie inne języki radzą sobie jednym.", source: "Polski, etymologia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Sowa ma na krawędzi lotek miękkie strzępienie, które rozbija powietrze na drobniejsze wiry i tłumi szum lotu niemal do zera.", source: "Strigiformes", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Świeży śnieg pochłania wysokie dźwięki, bo jego luźna, porowata struktura rozprasza fale zamiast je odbijać — stąd wrażenie ciszy tuż po opadach.", source: "Akustyka śniegu", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Komora bezechowa nie ma żadnej powierzchni, od której dźwięk mógłby się odbić — najcichsze miejsce, jakie człowiek potrafił zbudować.", source: "Akustyka", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Cicha noc, święta noc — w tej kolędzie cisza pojawia się jako pierwsze słowo, zanim jeszcze zdąży się pojawić cokolwiek innego.", source: "Kolęda, tłum. z niemieckiego", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Szum i szelest różnią się w polskim tym, co szumi, a co szeleści — liście na wietrze szumią razem, ale szeleści zawsze coś pojedynczego, blisko ucha.", source: "Polski, dźwiękonaśladownictwo", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Korony niektórych drzew tego samego gatunku, rosnące blisko siebie, zostawiają między sobą wąski, nietknięty pas nieba, jakby każda ustępowała miejsca sąsiadce.", source: "Dendrologia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Cisza nocna to w Polsce pojęcie prawne, nie tylko odczucie — między dwudziestą drugą a szóstą rano hałas sąsiada przestaje być tylko niewygodą.", source: "Prawo, cisza nocna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Strefa ciszy bywa oznaczona na mapach szlaków turystycznych w polskich parkach narodowych tam, gdzie chroni się głuszca w okresie toków.", source: "Kartografia, ochrona przyrody", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Spokój różni się od ciszy tym, że może w nim być dźwięk — szum liści albo dalekie szczekanie psa nie psują spokoju, tylko dowodzą, że jest prawdziwy.", source: "Polski, etymologia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Motyle nocne słyszą ultradźwięki nietoperzy i potrafią zmienić kurs w ułamku sekundy — bitwa, którą ludzkie ucho odbiera jako całkowitą ciszę.", source: "Lepidoptera nocne", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "W komorach solnych Wieliczki panuje cisza tak głęboka, że słychać własny oddech odbity od ścian sto metrów pod ziemią.", source: "Kopalnia Soli Wieliczka", theme: .peace, subtheme: .quietAsASound),

        // theWordsForStopping
        Passage(text: "Pokój znaczy po polsku i stan bez wojny, i pomieszczenie w domu — jedno słowo robi za dwa, jakby pokój był zawsze najpierw miejscem, a dopiero potem stanem.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Rozejm to zgoda, żeby na jakiś czas przestać, zanim ktokolwiek zdąży ustalić, czy to już koniec na zawsze.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Zawieszenie broni mówi dosłownie, że broń wisi w powietrzu — ani odłożona, ani użyta, tylko zatrzymana w połowie gestu.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Zgoda buduje, niezgoda rujnuje.", source: "Przysłowie polskie", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Ugoda pochodzi od tego samego rdzenia co godzić — łączyć w jedną całość dwie strony, które przedtem liczyły osobno.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Pojednanie zaczyna się od jednego — od uznania, że po sporze znowu jest jedna sprawa, nie dwie osobne.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Traktat pokojowy w dawnej polszczyźnie nazywano po prostu traktatem, od łacińskiego tractare, prowadzić rozmowy aż do końca.", source: "Łacina, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Spokój i pokój dzielą w polskim ten sam rdzeń — jakby bycie spokojnym było zawsze małym, osobistym rozejmem.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Klepnięcie się po rękach na zgodę było w wielu polskich wsiach ważniejsze niż podpis — świadkowie pamiętali dźwięk dłoni długo po tym, jak zapomniano słowa.", source: "Zwyczaj ludowy", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Kordon sanitarny nazywał pierwotnie linię, którą wyznaczano nie po to, żeby prowadzić wojnę, ale żeby zatrzymać zarazę — granicę postawioną w imię spokoju.", source: "Historia, epidemiologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Rozbrojenie mówi wprost, czego dotyczy — nie serca, nie sporu, tylko broni, którą odkłada się jako pierwszą.", source: "Polski, etymologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "List żelazny gwarantował w dawnej Polsce bezpieczne przejście nawet wrogowi na czas rozmów — papier silniejszy przez chwilę niż miecz.", source: "Prawo dawne", theme: .peace, subtheme: .theWordsForStopping),

        // atEase
        Passage(text: "Wytchnienie to chwila, w której oddech sam zwalnia, zanim jeszcze ktokolwiek zdąży pomyśleć słowo odpoczynek.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Leniuchować różni się od odpoczywać tym, że nikt się z tego nie tłumaczy — samo słowo już zakłada, że nie trzeba usprawiedliwienia.", source: "Polski, zwrot", theme: .peace, subtheme: .atEase),
        Passage(text: "Kot, który śpi w pełnym słońcu na parapecie, wybrał to miejsce z dokładnością termometru, nie przypadku.", source: "Felis catus", theme: .peace, subtheme: .atEase),
        Passage(text: "Kołysanie w hamaku odtwarza rytm bliski temu, jaki zna się jeszcze sprzed urodzenia — dlatego usypia szybciej niż nieruchome łóżko.", source: "Fizjologia snu", theme: .peace, subtheme: .atEase),
        Passage(text: "Popołudniowa drzemka miała w wielu polskich domach swoją porę tak stałą, że nikt nie musiał pytać, czy można — wiedziano po prostu, kiedy dom cichnie.", source: "Zwyczaj domowy", theme: .peace, subtheme: .atEase),
        Passage(text: "Rozluźnić się dzieli rdzeń ze słowem luz — swobodą, miejscem, którego nie zajmuje nic napiętego.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Kot mruczy nie tylko z zadowolenia — częstotliwość jego mruczenia bywa opisywana jako sprzyjająca gojeniu kości i tkanek.", source: "Felis catus, fizjologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Błogostan łączy w sobie błogość i stan — nie chwilę szczęścia, tylko trwałe miejsce, w którym akurat się jest.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Niedziela w dawnej polszczyźnie znaczyła dzień, w którym nic się nie robi — od nie działać, zanim jeszcze została dniem świątecznym.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Cień pod lipą był w niejednej wsi tak stałym miejscem odpoczynku po pracy, że ławkę pod nią stawiano, zanim jeszcze ktokolwiek o to poprosił.", source: "Zwyczaj wiejski", theme: .peace, subtheme: .atEase),
        Passage(text: "Rozgościć się mówi więcej niż usiąść — zawiera w sobie już samo słowo gość, jakby wygoda zaczynała się od poczucia, że wolno tu zostać.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Wygodny dzieli rdzeń ze słowem godzić — wygoda to stan, w którym ciało w końcu przestaje się z czymkolwiek spierać.", source: "Polski, etymologia", theme: .peace, subtheme: .atEase),
    ]
}
