import Foundation

/// The Welsh passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let welsh: [Passage] = [
        // MARK: Beginnings
        Passage(text: "Egino: daw'r gwreiddyn allan o'r hedyn o flaen y ddeilen bob tro, am fod angen dŵr cyn y gellir gwneud dim byd â'r golau.", source: "Llysieueg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Deuparth gwaith ei ddechrau.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Y Ddraig Goch ddyry cychwyn.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Mae blagur y gwanwyn yn cael eu ffurfio yn ystod yr haf o'u blaen. Erbyn y rhew cyntaf mae'r goeden eisoes yn barod, a neb wedi sylwi.", source: "Llysieueg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Oni heuir, ni fedir.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Gorau cam, cam cyntaf.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Buan y dysg mab hwyad nofio.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Torri'r garw: yr ymadrodd Cymraeg am wneud y peth anodd cyntaf, fel bod popeth ar ei ôl yn haws.", source: "Cymraeg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Y funud y glania paill ar stigma, mae'n bwrw tiwb i lawr trwy'r golofnig tuag at yr ofwl. Nid oes tynnu'n ôl wedi hynny.", source: "Llysieueg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Nid yw dail cyntaf eginyn yn debyg i'r rhai a ddaw wedyn. Dail yr hedyn ydynt, a chânt eu colli cyn diwedd yr haf.", source: "Llysieueg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Pan fydd afon yn torri sianel newydd mewn llifogydd, munudau sy'n penderfynu ar lwybr canrifoedd.", source: "Daeareg", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Mae mesen yn bwrw ei gwreiddyn cyn diwedd y gaeaf, ac yn ei yrru'n ddwfn i lawr ymhell cyn i ddim ymddangos uwchben.", source: "Quercus robur", theme: .beginnings, subtheme: .theFirstAct),

        Passage(text: "Bach hedyn pob mawredd.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Y fesen yn dderwen a ddaw.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "O egin y meithrinir das.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Ychydig yn aml a wna lawer.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "O geiniog i geiniog, a'r arian yn bunt.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Daethpwyd o hyd i un hen bren afalau ar Ynys Enlli ym 1998. O'r un pren hwnnw y tyfwyd pob afal Enlli sydd yn y byd.", source: "Garddwriaeth", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Aeth y barcud coch yng Nghymru i lawr i ddyrnaid o barau ar lethrau Pumlumon. Mae poblogaeth heddiw i gyd yn disgyn o'r llond dwrn hwnnw.", source: "Milvus milvus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Un gell yw'r hedyn ar y dechrau, a phopeth a fydd yn goeden wedi ei blygu i mewn iddi.", source: "Llysieueg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Nid oes gan had tegeirian gronfa fwyd o gwbl. Llwch ydyw, ac ni all symud nes cael ffwng i'w fwydo.", source: "Orchidaceae", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Un frenhines mewn twll llygoden yw dechrau nythaid o gacwn. Erbyn canol yr haf gall fod cannoedd ohonynt.", source: "Bombus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Gwnaed calchfaen Cymru o gregyn creaduriaid rhy fân i'w gweld, wedi eu pentyrru dros filiynau o flynyddoedd.", source: "Daeareg", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Crafiad bychan mewn craig oedd Cwm Idwal ar y dechrau. Y rhew a'i cafnodd nes bod lle i lyn orwedd ynddo.", source: "Daeareg", theme: .beginnings, subtheme: .smallToLarge),

        Passage(text: "Rhaid i'r dderwen wrth gysgod yn ieuanc.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ni chel drygtir ei egin.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Cyntaf ei og, cyntaf ei gryman.", source: "Dihareb Gymraeg", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Y modd y tocir coeden yn ei phum mlynedd gyntaf sy'n penderfynu ar ba ochr y bydd hi'n pwyso ymhen hanner canrif.", source: "Coedwigaeth", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Tŷ unnos: yn ôl hen goel, os gellid codi tŷ ar dir comin rhwng machlud a gwawr a chael mwg o'r simnai erbyn y bore, yr adeiladydd biau'r tir.", source: "Arfer gwerin", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "A therfyn y tir hwnnw, medd rhai fersiynau o'r goel, oedd cyn belled ag y gallai gŵr daflu bwyell o bob un o bedair congl y tŷ.", source: "Arfer gwerin", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mae'r cylchoedd yng nghanol boncyff yn cofnodi tywydd blynyddoedd cyn i neb fyw yma, ac ni ellir eu hailysgrifennu.", source: "Coedwigaeth", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Wrth blygu gwrych, torrir y plyg cyntaf i ddau draean a'i wyro i lawr yn fyw. Torri drwyddo, a marw wna'r cyfan.", source: "Crefft y gwrychoedd", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mae afon Dyfrdwy'n llifo i mewn i Lyn Tegid ac allan yr ochr draw, a Dyfrdwy yw hi o hyd. Ni newidir enw dŵr ar ôl ei roi.", source: "Daearyddiaeth", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Pan orffennodd William Morgan ei Feibl Cymraeg ym 1588, gosododd ffurf ar yr iaith y mae ysgrifenwyr yn dal i weithio oddi wrthi.", source: "Hanes yr iaith", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mae had bach a gladdwyd yn rhy ddwfn yn egino'n ffyddlon ac yna'n darfod cyn cyrraedd y golau. Nid gwendid yr had mo hynny ond dyfnder y rhych.", source: "Amaethyddiaeth", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ffosydd dyfrhau a gloddiwyd â rhaw gan y Cymry cyntaf yn Nyffryn Camwy yn y 1860au sy'n dal i benderfynu siâp y caeau yno.", source: "Hanes y Wladfa", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: Waiting
        Passage(text: "Hir pob aros.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Nerth gwenynen, ei hamynedd.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Gall had eithin orwedd yn y pridd am ddegawdau. Tân sy'n ei ddeffro, wrth grasu'r plisgyn nes bod dŵr yn medru mynd i mewn.", source: "Ulex europaeus", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Lili'r Wyddfa: planhigyn a adawyd ar ôl gan oes yr iâ, ac sy'n dal ar ychydig glogwyni yn Eryri ac yn unman arall ym Mhrydain.", source: "Gagea serotina", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Yn y coed y mae hi'n cysgu, yn yr eithin mae hi'n nythu.", source: "Hen bennill", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ni ddaw had celyn i fyny'r flwyddyn gyntaf. Rhaid iddo gael gaeaf, a dau ohonynt yn aml, cyn symud o gwbl.", source: "Ilex aquifolium", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ym mhen ucha'r Hafren mae dros ddeg metr rhwng y trai a'r penllanw, ac nid oes modd brysio'r naill na'r llall.", source: "Llanw a thrai", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Angor diogel yw gobaith.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Wrth aeafgysgu, gall calon ystlum arafu o gannoedd o guriadau'r funud i lai nag ugain, a'i gorff oeri bron at dymheredd yr ogof.", source: "Chiroptera", theme: .waiting, subtheme: .heldBack),
        Passage(text: "O dan y ddaear y treulir y rhan fwyaf o oes cenhinen Bedr. Ychydig wythnosau'n unig y mae'r blodyn yn y golwg.", source: "Narcissus", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ni thawdd dyled er aros.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Cadw dy afraid, ti a'i cei wrth raid.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .heldBack),

        Passage(text: "Pawb yn aros yr amser, a'r amser nid erys neb.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Dyfal donc a dyr y garreg.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Mae mawn Cors Fochno wedi bod yn casglu ers miloedd o flynyddoedd, tua milimetr y flwyddyn, a'r cyfan ohono'n dal yno.", source: "Daeareg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Gall ywen mewn mynwent Gymreig fod yn hŷn na'r eglwys sydd wrth ei hymyl, ac weithiau'n hŷn na'r grefydd a'i cododd.", source: "Taxus baccata", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Amser yw'r meddyg.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Athro da yw amser.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Nid rhy hir aros daioni.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Mae rhai llysiau'n rhoi dwy flynedd i'r gwaith: gwreiddyn yn y gyntaf, blodyn yn yr ail, a dim byd wedyn.", source: "Llysieueg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ceir oed pysgodyn wrth gyfrif y cylchoedd ar yr asgwrn bach yn ei ben, yr un modd yn union â chyfrif modrwyau pren.", source: "Pysgodeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Hwyliodd y Mimosa o Lerpwl ym 1865. Ganrif a hanner yn ddiweddarach mae Cymraeg i'w chlywed o hyd yn nyffrynnoedd Chubut.", source: "Hanes y Wladfa", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Hwy pery clod na hoedl.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Llai na milimetr y flwyddyn y tyf y cen ar greigiau Eryri. Gall llond llaw ohono fod yn hŷn na'r castell islaw.", source: "Cenoleg", theme: .waiting, subtheme: .theLongCount),

        Passage(text: "Clyw a gwêl ac na ddywed ddim.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Gŵyl: benthyciad o'r Lladin vigilia, sef gwylio drwy'r nos. Codwyd y gair Cymraeg am ddathlu ar y gair am aros ar ddi-hun.", source: "Geirdarddiad", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Bugail: gair sy'n disgyn o hen air Celtaidd am wartheg, o'r un gwreiddyn â boukolos y Groegiaid. Gair buchod yw enw ceidwad defaid.", source: "Geirdarddiad", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Wrth wrando y mae tylluan wen yn hela. Mae ei chlustiau ar ddwy lefel wahanol, fel y gall glywed pa mor uchel yw peth yn ogystal â pha mor bell.", source: "Tyto alba", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Da gan ddiog yn ei wely glywed sŵn y droell yn nyddu; gwell gan innau, dyn a'm helpo, glywed sŵn y tannau'n tiwnio.", source: "Hen bennill", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Rhwng tri a chwech y bore y cynhelid y plygain, a'r gynulleidfa'n eistedd yn yr eglwys yn disgwyl am y golau, pob un â'i channwyll ei hun.", source: "Arfer gwerin", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Tri brodyr doethineb: a wrendy, a edrych, a daw.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Mae'r ail gainc yn agor gyda Bendigeidfran yn sefyll ar graig yn Harlech, yn edrych tua'r môr, a llongau'n dynesu.", source: "Pedair Cainc y Mabinogi", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Golwg y perchen yw cynnydd y da.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Pan fydd haid o wyddau'n pori, mae rhai bob amser â'u pennau i fyny. Po fwyaf yr haid, lleiaf o amser sydd raid i bob un ei roi i wylio.", source: "Adareg", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ar ddiwedd y mae barnu.", source: "Dihareb Gymraeg", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ar lonyddwch y mae ysgyfarnog yn dibynnu. Nid yw'n codi nes bod y sawl a'i gwelodd wedi symud gyntaf.", source: "Lepus europaeus", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: Renewal
        Passage(text: "Bu weithiau heb haf; ni bu erioed heb wanwyn.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Daw hindda wedi drycin.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Rhennir yr hen flwyddyn Gymreig yn ddau hanner yn unig: Calan Mai a Chalan Gaeaf, yr haf a'r gaeaf, heb ddim rhyngddynt.", source: "Arfer gwerin", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ar Nos Galan Mai byddid yn casglu canghennau o'r ddraenen wen i'w gosod y tu allan i'r tŷ, yn arwydd fod pethau'n tyfu eto.", source: "Arfer gwerin", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Dwylo Mai a'i hadeila.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Un wennol ni wna wanwyn.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Gaeaf gwyn, ysgubor dynn.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Daw haf i gi.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Cenhinen Bedr yw'r Gymraeg am ddaffodil, a chenhinen yw'r llysieuyn a fwyteir. Dau symbol cenedlaethol Cymru, a'u henwau bron yr un fath.", source: "Cymraeg", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Codi'r fedwen: arferid codi bedwen ar ddechrau'r haf a dawnsio o'i chwmpas, ac roedd yr arfer yn gyffredin ledled Cymru ar un adeg.", source: "Arfer gwerin", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Mae'r gog yn cyrraedd Cymru tua chanol Ebrill ac yn cychwyn yn ôl cyn i'r haf orffen. Hi yw'r cyntaf i ddod a'r cyntaf i fynd.", source: "Cuculus canorus", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Blwyddyn o eira, blwyddyn o lawndra.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .theTurningYear),

        Passage(text: "Hawdd cynnau tân ar hen aelwyd.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Torrwch helygen at y bôn a daw ugain gwialen i fyny o'r un boncyff. Gall y bôn hwnnw fyw'n hwy na choeden na chyffyrddwyd â hi.", source: "Coedwigaeth", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Mae blodau'r ffridd yn dibynnu ar bori. Heb ddafad na cheffyl arni, y glaswellt tal a'r rhedyn sy'n eu tagu o fewn ychydig flynyddoedd.", source: "Amaethyddiaeth", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Gall y gwaethaf ddysgu bod yn orau.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nid yw eithin sydd wedi llosgi'n marw. Erbyn yr ail wanwyn mae'n felyn drosto eto, ac yn drwchus mewn ffordd na fyddai heb y tân.", source: "Ulex europaeus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Mae madfall yn gollwng ei chynffon i ddianc, ac yn tyfu un arall. Nid yw'r ail un byth cystal â'r gyntaf, ond mae hi'n fyw.", source: "Lacerta", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nid gwaradwydd gwellhau.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Wedi i chwarel gau, y planhigion cyntaf i afael yn y rwbel yw'r rhai sy'n gallu byw heb bridd o gwbl: cen, mwsogl, ac wedyn bysedd y cŵn.", source: "Ecoleg", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Torrer y borfa'n fyr yn yr hydref a daw'r blodau bychain yn ôl y gwanwyn wedyn, am nad yw'r glaswellt tal yn cael cyfle i'w cuddio.", source: "Garddwriaeth", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Gwna dda unwaith, gwna dda eilwaith.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Os collir dail newydd coeden i rew hwyr, bydd hi'n bwrw ail set ohonynt allan o flagur wrth gefn a gadwyd yn ôl at hynny'n union.", source: "Coedwigaeth", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Nid da y peth ni phlyco.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .cutAndComeAgain),

        Passage(text: "Aeth y barcud coch o fod bron â darfod yng Nghymru i fod yn aderyn cyffredin uwchben y ffyrdd, o fewn oes un person.", source: "Milvus milvus", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Eli i bob dolur yw amynedd.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Wrth i asgwrn dorri ac ailasio, mae'r man a dorrodd yn tewhau nes bod y darn hwnnw'n gryfach na'r gweddill.", source: "Meddygaeth", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Anodd iacháu hen glefyd.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Gall clwyf mewn rhisgl gau'n llwyr, ond mae'r pren y tu mewn yn cadw'r graith am byth. Tyfu drosti a wna coeden, nid ei dileu.", source: "Coedwigaeth", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Pan lanhawyd afon Taf wedi cau'r pyllau glo, daeth yr eogiaid yn eu holau iddi. Buont yn dal i geisio dod i mewn ar hyd y blynyddoedd budron.", source: "Salmo salar", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Gwell y wialen a blygo na'r wialen a dorro.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Mae'r dyfrgi wedi dychwelyd i bron bob afon o bwys yng Nghymru, ar ôl bod bron â diflannu o fewn cof pobl sy'n dal yn fyw.", source: "Lutra lutra", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Rhoddir gwaed newydd mewn gwrych trwy blygu'r hen, nid trwy blannu o'r newydd. Yr un gwreiddiau sydd yno wedyn.", source: "Crefft y gwrychoedd", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ni cholles mam amynedd.", source: "Dihareb Gymraeg", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Gan fod cregyn gleision yn hidlo'r dŵr wrth fwyta, mae aber lle maent yn ffynnu'n gliriach nag aber lle nad ydynt.", source: "Mytilus edulis", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Aeth y gwyniad, pysgodyn nad yw'n byw yn unman ond Llyn Tegid, i drybini. Symudwyd ei wyau i lyn arall er mwyn cadw ail gopi ohono.", source: "Coregonus pennantii", theme: .renewal, subtheme: .madeWhole),

        // MARK: Light
        Passage(text: "Cyfddydd a chyfnos: enwir dau ben y dydd yn Gymraeg â'r un rhagddodiad, cyf-, sef cyd-fod. Nid gorffen na dechrau, ond cydgyfarfod.", source: "Cymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Llwydnos yw enw arall ar frig y nos: y tywyllwch yn mynd yn llwyd cyn iddo fynd yn ddu.", source: "Cymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Y bore bach: yr enw Cymraeg ar yr oriau ar ôl i'r diwrnod ddechrau ond cyn iddi oleuo.", source: "Cymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Daw plygain, meddir, o'r Lladin pullicantio, sef ar ganiad y ceiliog. Enwyd yr awr ar ôl y sŵn a'i marciai.", source: "Geirdarddiad", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Oriau hydr yr ehedydd a dry fry o'i dŷ bob dydd.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Yn gwarando ddechrau dydd y ceiliog bronfraith celfydd, yn canu englyn alathr.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gorau difyrrwch, cân adar bore.", source: "Dihareb Gymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gyda'r nos y cyfyd malwen.", source: "Dihareb Gymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Yn yr hwyr y mae nabod gweithiwr.", source: "Dihareb Gymraeg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Mae côr y wawr yn canu mewn trefn, ac yn ôl maint llygad: yr adar sy'n gweld orau mewn tywyllwch a ddechreua, a'r rhai lleiaf eu llygaid a orffen.", source: "Adareg", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Mae blodau'r gwyddfid yn arogli gryfaf ar ôl machlud, am mai gwyfynod sy'n eu peillio.", source: "Lonicera periclymenum", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gwynfyd herwr yw hwyrnos.", source: "Dihareb Gymraeg", theme: .light, subtheme: .theEdgesOfTheDay),

        Passage(text: "Taer yw'r gwir am y golau.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Gwaith y nos, y dydd a'i dengys.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Trwy dwll bychan y gwelir goleuni.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Awel y canolddydd a ddwg law yn ebrwydd.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Enfys y bore, aml gawodau.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Haul gwanwyn, gwaeth na gwenwyn.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Mae gan blanhigyn bigment sy'n newid ei ffurf yn y golau ac yn llacio'n ôl yn araf yn y tywyllwch. Hyd y llacio sy'n dweud wrtho pa mor hir fu'r nos.", source: "Llysieueg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Mae glaswellt yn tyfu i ffwrdd oddi wrth y golau coch pell sy'n dod trwy ddail. Dyna sut y gŵyr planhigyn fod un arall yn ei gysgodi.", source: "Llysieueg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ni ellir gweld bwa yn yr awyr oni bai fod yr haul y tu ôl i chi ac yn is na thua deugain gradd uwchben y gorwel.", source: "Ffiseg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Machlud coch: yr awyr yn dweud pa mor bell y bu'n rhaid i'r golau deithio drwyddi cyn ein cyrraedd.", source: "Ffiseg", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Hyd cysgod ffon ar hanner dydd sy'n dweud pa mor bell i'r gogledd yr ydych. Felly y mesurwyd maint y byd am y tro cyntaf.", source: "Seryddiaeth", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Blodau cyn Mai, gorau na bai.", source: "Dihareb Gymraeg", theme: .light, subtheme: .readingTheLight),

        Passage(text: "Llygad y dydd yw enw'r Gymraeg ar Bellis perennis. Mae'n cau gyda'r nos ac yn agor drachefn pan ddaw'r golau'n ôl.", source: "Bellis perennis", theme: .light, subtheme: .lightItself),
        Passage(text: "Cannwyll y llygad yw'r Gymraeg am y twll du yn ei ganol. Y golau sy'n mynd drwyddo a roes yr enw iddo.", source: "Cymraeg", theme: .light, subtheme: .lightItself),
        Passage(text: "Cannwyll: gair benthyg o'r Lladin candela. Daeth y gair i mewn i'r iaith gyda'r peth ei hun.", source: "Geirdarddiad", theme: .light, subtheme: .lightItself),
        Passage(text: "Yn 2023 daeth Ynys Enlli'n Noddfa Awyr Dywyll ryngwladol, y lle cyntaf yn Ewrop i ennill y statws hwnnw.", source: "Seryddiaeth", theme: .light, subtheme: .lightItself),
        Passage(text: "Caer Gwydion yw'r hen enw Cymraeg ar y Llwybr Llaethog, a Chaer Arianrhod ar y goron o sêr i'r gogledd.", source: "Seryddiaeth", theme: .light, subtheme: .lightItself),
        Passage(text: "Nid aur yw popeth melyn.", source: "Dihareb Gymraeg", theme: .light, subtheme: .lightItself),
        Passage(text: "Wyth munud sydd rhyngom a'r haul. Yr hyn a welwn yw'r hyn a oedd yno wyth munud yn ôl.", source: "Seryddiaeth", theme: .light, subtheme: .lightItself),
        Passage(text: "Coch yw'r lliw cyntaf i ddiflannu wrth suddo. Erbyn deg metr o ddyfnder does dim byd coch ar ôl i'w weld yn unman.", source: "Ffiseg", theme: .light, subtheme: .lightItself),
        Passage(text: "Nid yw'r lleuad yn gwneud golau. Bwrw'n ôl y mae, a cholli tua naw rhan o bob deg o'r hyn sy'n disgyn arni.", source: "Seryddiaeth", theme: .light, subtheme: .lightItself),
        Passage(text: "Mae gan bob goleudy ei batrwm fflachio ei hun, fel bod modd dweud pa un ydyw heb weld dim ohono ond y golau.", source: "Morwriaeth", theme: .light, subtheme: .lightItself),
        Passage(text: "Nid oes lliw ar ddim yn y tywyllwch. Yn y llygad y digwydd lliw, ac nid yn y peth ei hun.", source: "Ffiseg", theme: .light, subtheme: .lightItself),
        Passage(text: "Weithiau ar noson ddu bydd ewyn y don yn goleuo. Plancton bychain yn fflachio wrth gael eu troi sy'n gwneud hynny.", source: "Bioleg y môr", theme: .light, subtheme: .lightItself),

        // MARK: Pattern
        Passage(text: "Deunaw: dau naw. Ugeiniau oedd sylfaen yr hen gyfrif Cymreig, a deugain yw dau ugain, a thrigain yn dri ohonynt.", source: "Cymraeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Wyth llythyren ar hugain sydd yn yr wyddor Gymraeg, am fod ch, dd, ff, ng, ll, ph, rh a th yn cyfrif fel un lythyren yr un.", source: "Cymraeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Deg sillaf, chwech, saith a saith: dyna hyd pedair llinell yr englyn unodl union, a thri deg sillaf i gyd.", source: "Cerdd dafod", theme: .pattern, subtheme: .counted),
        Passage(text: "Tri pheth sy'n anodd i mi: cyfri'r sêr pan fyddo'n rhewi, rhoi fy llaw ar gwr y lleuad, gwybod meddwl f'annwyl gariad.", source: "Hen bennill", theme: .pattern, subtheme: .counted),
        Passage(text: "O flewyn i flewyn a'r pen yn foel.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Gwybydd fesur dy droed dy hun.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Gosteg o englynion yw cyfres o ddeuddeg ohonynt ar yr un brifodl. Nid nifer mympwyol mo'r deuddeg ond rhan o'r diffiniad.", source: "Cerdd dafod", theme: .pattern, subtheme: .counted),
        Passage(text: "Amlaf ei gŵys, amlaf ei ysgub.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Mae'r dail ar goesyn yn troi wrth ddringo, ac mewn llawer o blanhigion yr un ongl yn union sydd rhwng pob deilen a'r nesaf, i fyny'r holl goesyn.", source: "Llysieueg", theme: .pattern, subtheme: .counted),
        Passage(text: "Mae gwenynen yn dweud wrth y lleill pa mor bell yw'r bwyd trwy hyd ei dawns. Po hwyaf y rhan syth, pellaf y daith.", source: "Apis mellifera", theme: .pattern, subtheme: .counted),
        Passage(text: "Nid oes bannod amhendant yn y Gymraeg. Mae bannod ar gyfer peth penodol, ond ar gyfer peth amhenodol nid oes dim ond yr enw ei hun yn sefyll yno.", source: "Gramadeg", theme: .pattern, subtheme: .counted),
        Passage(text: "Mwya'r llanw, mwya'r trai.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .counted),

        Passage(text: "Manwl pob rhan, hardd pob cyfan.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Llunio'r gwadn fel bo'r troed.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Cadarnach yw'r edau'n gyfrodedd nag yn ungorn.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Cadarna'r mur po arwa'r garreg.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Clawdd Cymreig: dau wyneb o gerrig yn pwyso i mewn tuag at ei gilydd, pridd rhyngddynt, a gwrych ar ei ben. Y pwyso yw'r cyfan o'r cryfder.", source: "Crefft y clawdd", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ni ddefnyddir morter mewn wal gerrig sych. Pwysau'r cerrig yn erbyn ei gilydd sy'n ei dal, ac mae'n symud ychydig bob gaeaf heb ddisgyn.", source: "Crefft y cerrig", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Mae'r llechen yn hollti'n haenau tenau am fod ei chrisialau i gyd wedi eu troi i'r un cyfeiriad gan bwysau'r mynydd uwch ei phen.", source: "Daeareg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Chwe braich sydd i bluen eira am mai chwe ochr sydd i'r crisial iâ cyntaf. Y tywydd ar y ffordd i lawr sy'n penderfynu ar bopeth arall.", source: "Ffiseg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Gweddw crefft heb ei dawn.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Mewn to gwellt, mae pob haen yn gwarchod yr un oddi tani, a'r glaw yn cael ei drosglwyddo o un i un nes cyrraedd y bondo.", source: "Crefft y to gwellt", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Mae tarddiad Hafren, Gwy a Rheidol o fewn ychydig filltiroedd i'w gilydd ar Bumlumon, a dwy ohonynt yn troi i'r dwyrain a'r llall i'r gorllewin.", source: "Daearyddiaeth", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Cyfyng ac eang yw dewis.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .fittedTogether),

        Passage(text: "Cynghanedd: cyfundrefn o ailadrodd cytseiniaid o fewn llinell. Ers y bedwaredd ganrif ar ddeg nid addurn mohoni ond gofyniad.", source: "Cerdd dafod", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Pedwar math sydd o gynghanedd: croes, traws, sain a llusg. Nid oes pumed, a rhaid i bob llinell gaeth fod yn un ohonynt.", source: "Cerdd dafod", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Ceir cyseinedd trefnus yn llinellau'r beirdd cynnar ganrifoedd cyn i neb roi enw ar y peth. Enwi'r drefn a wnaeth y gramadegwyr, nid ei gwneud.", source: "Cerdd dafod", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Yng Nghaerfyrddin ym 1451 gosododd Dafydd ab Edmwnd drefn ar y pedwar mesur ar hugain, ac ar y drefn honno y bu beirdd yn gweithio wedyn.", source: "Cerdd dafod", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Trioedd Ynys Prydain: cofio pethau fesul tri fel y bo modd eu dal ar gof. Mae naw deg chwech ohonynt wedi goroesi.", source: "Llenyddiaeth Gymraeg", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Treiglo: mae llythyren gyntaf gair Cymraeg yn newid yn ôl yr hyn a ddaw o'i blaen. Tair cyfres o newidiadau sydd, a naw cytsain yn cymryd rhan.", source: "Gramadeg", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Y ferf sy'n dod gyntaf mewn brawddeg Gymraeg, cyn y sawl sy'n gwneud y peth. Y weithred a enwir yn gyntaf bob tro.", source: "Gramadeg", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Hen arfer, hon a orfydd.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Mae gan bob cae a nant a chornel mewn ardal ffermio ei enw ei hun, ac ni ellir dweud dim am y tir wrth rywun nad yw'n eu gwybod.", source: "Enwau lleoedd", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Nid o rym corff y cenir telyn.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Aber, cymer, rhyd a phont: mae enwau lleoedd Cymru'n dweud wrthych sut i groesi dŵr, ac ym mha drefn y daeth pobl at y broblem.", source: "Enwau lleoedd", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Meistr pob gwaith yw ymarfer.", source: "Dihareb Gymraeg", theme: .pattern, subtheme: .orderNamed),

        // MARK: Ground
        Passage(text: "Y mae'r dwfr lle bo brwyn.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "A arddo diroedd a gaiff ddigonedd.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Nid ar redeg mae aredig.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Cig oen morfa heli: mae blas y borfa hallt yn y cig, ac ni ellir ei roi yno mewn unrhyw ffordd arall.", source: "Amaethyddiaeth", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mae blodau hydrangea'n las ar bridd asid ac yn binc ar bridd calchog. Nid y planhigyn sy'n newid ond yr hyn y mae'n ei godi o'r ddaear.", source: "Hydrangea", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Nid yw dŵr yn suddo trwy graig galed. Dyna pam fod cymaint o gorsydd ar dir uchel yng Nghymru sy'n edrych yn rhy serth i fod yn wlyb.", source: "Daeareg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ni fu'r mawn erioed yn bridd. Planhigion sydd ynddo, heb bydru, am nad oes ocsigen yn y dŵr sy'n eu gorchuddio.", source: "Sphagnum", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Llwm yw'r ŷd lle mae'r adwy.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mae pridd iach yn drwm o fywyd nas gwelir. Ceir mwy o greaduriaid byw mewn llond llaw ohono nag sydd o bobl yng Nghymru gyfan.", source: "Pridd-wyddoniaeth", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Adwyog cae anhwsmon.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Aeth calch o Sir Benfro i fyny'r arfordir mewn llongau bychain am ganrifoedd, i felysu tir asid nad oedd modd ei drin hebddo.", source: "Amaethyddiaeth", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Mae mwydod yn codi pridd i'r wyneb yn ddi-baid. Dros ychydig flynyddoedd gall carreg a osodwyd ar gae suddo o'r golwg heb i neb ei symud.", source: "Lumbricus terrestris", theme: .ground, subtheme: .theSoilItself),

        Passage(text: "Cymro, Cymru, Cymraeg: pob un ohonynt o hen air a olygai gyd-bobl y wlad, cyd- a bro. Enw'n golygu pobl yr un fro yw'r cyfan.", source: "Geirdarddiad", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Bro: yr ardal y mae rhywun yn perthyn iddi, ac yn yr un gwynt y terfyn o'i chwmpas. Un gair am y canol a'r ymyl.", source: "Cymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Tecaf bro, bro mebyd.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Canmol dy fro a thrig yno.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Cynefin: y darn o fynydd y mae diadell yn ei gadw ohoni ei hun. Ni ddysgir ef; caiff ei drosglwyddo o'r mamogiaid i'r ŵyn.", source: "Amaethyddiaeth", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ac o'r un gair y daw cynefino, sef dod i arfer â lle nes iddo beidio â bod yn newydd.", source: "Cymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Nid oes gwyniad yn unman yn y byd ond yn Llyn Tegid. Cafodd ei wneud yn bysgodyn ar wahân gan y llyn hwnnw, ac nid oes ffordd allan iddo.", source: "Coregonus pennantii", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Cais ddedwydd yn ei gartref.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Mae hen wlad fy nhadau yn annwyl i mi.", source: "Evan James, 1856", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Cenedl heb iaith, cenedl heb galon.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Y tu draw i Glawdd Offa: y ffordd Gymraeg o ddweud Lloegr. Mae'r clawdd dros fil o flynyddoedd oed a'r ymadrodd yn dal ar lafar.", source: "Cymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Cais ddoeth yn ei dyddyn.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aPlaceYouAreFrom),

        Passage(text: "Cadw dy ardd, ceidw dy ardd dithau.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Llan: hen air am gae caeedig cyn ei fod yn air am eglwys. Mae'r un gair yng nghorlan y defaid, gwinllan y grawnwin a pherllan yr afalau.", source: "Geirdarddiad", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Perth hyd fogel, perth ddiogel.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Cymydog da yw clawdd.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "I dŷ dail a wnaeth Duw Dad.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Y Gaseg Fedi: y twffyn olaf o ŷd yn y cae, wedi ei blethu gan y gwas hynaf, a'r medelwyr yn taflu cryman ato yn eu tro.", source: "Arfer gwerin", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ac wedyn rhaid oedd ei chario i'r tŷ a'i chrogi uwch y bwrdd bwyd heb adael i neb ei gwlychu, a'i chadw yno tan y cynhaeaf nesaf.", source: "Arfer gwerin", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Castell pawb, ei dŷ.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ffridd yw'r llain rhwng y caeau caeedig a'r mynydd agored. Nid tir gwyllt na thir gwâr mohoni, ond y ddau'n cyffwrdd.", source: "Amaethyddiaeth", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ni bydd perllan yn ffrwytho'n dda oni bydd un pren afalau surion ynddi at y paill. Y pren nad yw'n werth ei fwyta sy'n cadw'r gweddill.", source: "Garddwriaeth", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Mewn coedlan a dorrwyd bob deg mlynedd ers canrifoedd, y blodau prin yw'r rhai a arferodd gael golau'n rheolaidd. Peidio â thorri sy'n eu colli.", source: "Coedwigaeth", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Chwynnwch eich gardd eich hun yn gyntaf.", source: "Dihareb Gymraeg", theme: .ground, subtheme: .aKeptPlace),

        // MARK: Travel
        Passage(text: "Gan bwyll y mae mynd ymhell.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Deuparth taith ymbarotoi.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ni ddaeth y porthmyn â'u gwartheg ar hyd y ffyrdd tyrpeg. Osgoi'r tollau a wnaent, a dilyn hen lwybrau dros y mynydd, tua ugain milltir y dydd.", source: "Hanes y porthmyn", theme: .travel, subtheme: .theRoad),
        Passage(text: "Pedolid y gwartheg cyn cychwyn am Lundain, a rhaid oedd eu pedoli eto sawl gwaith cyn diwedd y daith.", source: "Hanes y porthmyn", theme: .travel, subtheme: .theRoad),
        Passage(text: "Sefydlodd porthmon o'r enw David Jones fanc yn Llanymddyfri ym 1799, am fod yn rhaid i rywun gario'r arian adref yn ddiogel.", source: "Hanes y porthmyn", theme: .travel, subtheme: .theRoad),
        Passage(text: "Sarn Helen: y ffordd Rufeinig o Gaerhun yn y gogledd i Gaerfyrddin yn y de, tua chant a thrigain o filltiroedd, a rhannau ohoni'n dal i'w cerdded.", source: "Daearyddiaeth", theme: .travel, subtheme: .theRoad),
        Passage(text: "Nid oes allt heb oriwaered.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Y ci a gysgo a newyna; y ci a gerddo a gaiff.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Hawdd dweud dacw'r Wyddfa; nid eir drosti ond yn ara.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Canmoled pawb y bont a'i dyco drosodd.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Pob llwybr mewn ceunant, i'r unffordd a redant.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),
        Passage(text: "Bydd olaf i fyned drwy ddŵr dwfn.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .theRoad),

        Passage(text: "Mae hedyn masarn yn troi wrth ddisgyn, a'r troi'n ei ddal yn yr awyr yn ddigon hir i'r gwynt fynd ag ef oddi wrth y fam.", source: "Acer pseudoplatanus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mae blew ci a chnu dafad yn cario hadau'n bellach na'r gwynt. Nid oes gan lawer o blanhigion Cymru ffordd well o symud.", source: "Ecoleg", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mae hadau'r wernen yn nofio ar afon nes taro glan. Dyna pam y ceir rhes o goed ar hyd un ochr yn unig weithiau.", source: "Alnus glutinosa", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rhaid i had ysgawen fynd trwy aderyn cyn egino'n dda. Mae'r gwaith treulio'n gwneud yr hyn na all glaw ei wneud i'r plisgyn.", source: "Sambucus nigra", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mae sgrech y coed yn cuddio miloedd o fes bob hydref ac yn anghofio digon ohonynt i blannu coedwig heb fwriadu dim.", source: "Garrulus glandarius", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ffrwydro y mae codau'r banadl ar ddiwrnod poeth. Mae'r ddwy ochr yn sychu ar gyfraddau gwahanol nes bod y goden yn troi'n sydyn a thaflu'r hadau ohoni.", source: "Cytisus scoparius", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mae bachau ar bennau'r cyngaf, a hwythau'n gafael mewn gwlân dafad am filltiroedd cyn gollwng.", source: "Arctium", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mae rhai hadau'n troi eu hunain i'r pridd. Wrth i'r tywydd sychu a gwlychu, mae blewyn ar yr had yn dirwyn ac yn ei ddrilio i lawr.", source: "Erodium", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Aed ag eithin o Brydain i Seland Newydd i wneud gwrychoedd. Erbyn hyn mae'n chwyn ar filoedd o hectarau yno, ymhell o'r un gwrych a fwriadwyd.", source: "Ulex europaeus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "A geir yn rhad, a gerdd yn rhwydd.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Weithiau bydd hadau o goedwigoedd trofannol yn cyrraedd traethau gorllewin Cymru, wedi eu cario ar draws y cefnfor gan y ceryntau.", source: "Ecoleg", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rheded maen oni chaffo wastad.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .howASeedGoes),

        Passage(text: "Gwyn ei fyd na fedrwn hedeg bryn a phant a goriwaered; mynnwn wybod er eu gwaetha lle mae'r gog yn cysgu'r gaea.", source: "Hen bennill", theme: .travel, subtheme: .farOff),
        Passage(text: "Hwyliodd y Mimosa o Lerpwl ar yr wythfed ar hugain o Fai 1865 gyda thua chant a thrigain ar ei bwrdd, a glanio ym Mhorth Madryn ddeufis union wedyn.", source: "Hanes y Wladfa", theme: .travel, subtheme: .farOff),
        Passage(text: "Roedd tri deg saith o filltiroedd o dir anial rhwng y glanfa a Dyffryn Camwy, a bu'n rhaid cerdded pob un ohonynt.", source: "Hanes y Wladfa", theme: .travel, subtheme: .farOff),
        Passage(text: "Alltud: y gair all am arall a'r gair tud am wlad. Nid oes yn y gair unrhyw awgrym o fai, dim ond o bellter.", source: "Geirdarddiad", theme: .travel, subtheme: .farOff),
        Passage(text: "Hiraeth: hir ac aeth. Yn ei wraidd, enw ar hyd yw'r gair, ac ar hyd sydd wedi mynd yn rhy hir.", source: "Geirdarddiad", theme: .travel, subtheme: .farOff),
        Passage(text: "Mae adar drycin Manaw yn gaeafu oddi ar arfordir Brasil a'r Ariannin, dros ddeng mil o gilometrau o'r tyllau lle magasant.", source: "Puffinus puffinus", theme: .travel, subtheme: .farOff),
        Passage(text: "Ac maent yn dod yn ôl at yr un twll, ar yr un ynys, ar ôl y daith honno, ac yn cyrraedd yn y nos.", source: "Puffinus puffinus", theme: .travel, subtheme: .farOff),
        Passage(text: "Gorau Cymro, Cymro oddi cartref.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .farOff),
        Passage(text: "Eang yw'r byd i bawb.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .farOff),
        Passage(text: "Yn yr Oesoedd Canol, cyfrifid tair pererindod i Ynys Enlli'n gyfwerth ag un i Rufain, a hithau ond dwy filltir o'r tir mawr.", source: "Hanes", theme: .travel, subtheme: .farOff),
        Passage(text: "Gwân dy bawl yn Hafren, Hafren fydd hi fel cynt.", source: "Dihareb Gymraeg", theme: .travel, subtheme: .farOff),
        Passage(text: "Mae tua phum mil o bobl yn siarad Cymraeg yn nhalaith Chubut heddiw, a channoedd wrthi'n ei dysgu.", source: "Hanes y Wladfa", theme: .travel, subtheme: .farOff),

        // MARK: Meeting
        Passage(text: "Cynt y cwrdd dau ddyn na dau fynydd.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Cwrdd: talfyriad o gyhwrdd, sy'n cynnwys cy- a hwrdd, sef gwth. Yn y gair Cymraeg am gyfarfod mae dau beth yn taro yn erbyn ei gilydd.", source: "Geirdarddiad", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ac mae'r un gair yn enw ar wasanaeth capel. Yn y de, y cwrdd yw'r peth a'r cwrdd yw'r bobl.", source: "Cymraeg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Aber: y man lle mae afon yn cyrraedd dŵr arall. Mae'r gair ar ddechrau enwau degau o leoedd yng Nghymru, a phob un ohonynt yn enwi cyfarfyddiad.", source: "Enwau lleoedd", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Cymer: y gair arall am yr un peth, sef y man lle daw dwy afon yn un. Ceir Cymer ym Meirionnydd, ac Abercynon lle mae Cynon yn cyrraedd Taf.", source: "Enwau lleoedd", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Nid yw dwy afon yn cymysgu ar unwaith. Gellir gweld dau liw'n rhedeg ochr yn ochr am gryn bellter ar ôl y cymer.", source: "Daearyddiaeth", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Adar o'r unlliw a hed i'r unlle.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Cennad hwyr, drwg ei neges.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Y foment y bydd dwy don o wahanol gyfeiriad yn croesi, mae'r dŵr yn codi'n uwch nag y gallai'r naill na'r llall ei godi ar ei phen ei hun.", source: "Ffiseg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Cyntaf i'r felin caiff falu.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Rhwng y trai a'r llanw ceir cyfnod byr pan nad yw'r dŵr yn symud i unman. Dŵr llonydd yw'r enw arno, ac fe ddaw ddwywaith bob dydd.", source: "Llanw a thrai", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Hwde i ti, moes i minnau.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMoment),

        Passage(text: "A fo ben, bid bont.", source: "Pedair Cainc y Mabinogi", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Gorweddodd Bendigeidfran ar draws yr afon a'i lu'n cerdded drosto, a dyna'r tro cyntaf, meddir, y dywedwyd y ddihareb honno.", source: "Pedair Cainc y Mabinogi", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mae pont i groesi pob anhawster.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ni all cen fyw ar ei ben ei hun. Ffwng ac algâu ydyw, a'r naill yn dal y llall wrth y graig fel bod y ddau'n cael byw yno.", source: "Cenoleg", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mae gwreiddiau bron pob coeden yng Nghymru wedi eu lapio mewn ffwng nad yw'n weladwy. Y ffwng sy'n nôl y dŵr; y goeden sy'n talu â siwgr.", source: "Mycoleg", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ni chaiff celynnen fenyw aeron oni bydd celynnen wryw o fewn cyrraedd gwenyn iddi. Dau bren sydd eu hangen i wneud un gangen goch.", source: "Ilex aquifolium", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Nes penelin nag arddwrn.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mae adar drycin Manaw yn paru am oes, a'r ddau'n rhannu'r deor. Mae un yn eistedd wythnosau ar y tro tra bo'r llall ar y môr.", source: "Puffinus puffinus", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Mae gwenynen yn cario paill un rhywogaeth ar y tro. Y ffyddlondeb hwnnw, ac nid ei chwant am fêl, sydd o werth i'r blodyn.", source: "Apis mellifera", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Gwell cymydog yn agos na brawd ymhell.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Cadwyno englynion: cymryd gair o linell olaf un englyn a'i osod yn llinell gyntaf y nesaf, nes bod y gyfres gyfan ynghlwm wrth ei gilydd.", source: "Cerdd dafod", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ceisied pawb ddwfr i'w long.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .twoThatNeedEachOther),

        Passage(text: "Y Fari Lwyd: penglog caseg ar bolyn yn dod at y drws ar ganol gaeaf, a'r criw a'r teulu'n canu penillion yn erbyn ei gilydd.", source: "Arfer gwerin", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Y pwnco yw enw'r ddadl honno, a rhaid i'r criw y tu allan ennill cyn cael dod i mewn at y tân a'r bwyd.", source: "Arfer gwerin", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Nid rhodd rhodd oni bydd o fodd.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ni fawr ddiolchir am rodd gymell.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Os rhoi barch, ti gei barch.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Gwna dda, ni waeth i bwy.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "A ranno i liaws, rhanned yn hynaws.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Mae dwy ffordd o ddweud ti yn Gymraeg: ti wrth un person cyfarwydd, a chi wrth ddieithryn neu wrth fwy nag un. Symud o'r naill i'r llall sy'n dweud rhywbeth.", source: "Gramadeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Shwmae yn y de a sut mae yn y gogledd: y ddau'n dalfyriad o'r un cwestiwn, sef sut y mae hi arnoch.", source: "Cymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Na ddos i'r cyngor oni'th alwer yno.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Na wrthod dy barch pan y'i cynigier.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Nid uniaith bronfraith a brân.", source: "Dihareb Gymraeg", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: Kinship
        Passage(text: "Cyfaill: gair sy'n disgyn o hen ffurf Geltaidd a olygai wedi ei fagu gyda. Perthynas o gyd-fagu, nid o waed, sydd yn y gair.", source: "Geirdarddiad", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Adnabod a nabod sydd ar bobl; gwybod sydd ar bethau. Nid oes modd dweud yn Gymraeg eich bod yn gwybod rhywun.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Cydnabod: yr un gair ag adnabod, a chyd- ar ei flaen. Rhywun rydych yn ei adnabod gyda phobl eraill yw eich cydnabod.", source: "Geirdarddiad", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Tylwyth yw'r gair Cymraeg am deulu estynedig, a Thylwyth Teg yw'r enw ar y bobl fach. Teulu, nid llwyth, sydd yno.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ap ac ab, o fab: felly y gwneid enw dyn o enw ei dad, a Dafydd ap Gwilym yn golygu Dafydd fab Gwilym, dim mwy na hynny.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Nain a thaid yn y gogledd, mam-gu a thad-cu yn y de. Nid oes gan y Gymraeg un gair y cytunir arno am rieni rhieni.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Cariad: y gair am y teimlad a'r gair am y person. Un gair sy'n enwi'r serch a'r sawl a'i cafodd.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ail fam, modryb dda.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Perthyn: benthyciad o'r Lladin pertineo. Yn Gymraeg mae'n golygu bod yn eiddo i rywun a bod yn berthynas iddo, y ddau ar unwaith.", source: "Geirdarddiad", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Cymwynas: gair am y tro da a wneir heb ei ofyn, ac mae'r sawl sy'n enwog amdano'n cael ei alw'n gymwynaswr.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Gair mam a bery'n hir.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Cyfeillach: yr un gwreiddyn â chyfaill, ond enw ar y cwmnïa ei hun ydyw, ac nid ar y bobl sy'n ei gadw.", source: "Cymraeg", theme: .kinship, subtheme: .theWordsForIt),

        Passage(text: "Yng Nghyfraith Hywel, nid un person a dalai am ladd ond ei genedl gyfan, a hynny yn ôl pa mor agos oedd pob un.", source: "Cyfraith Hywel", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Traean y galanas a ddôi oddi wrth y llofrudd, ei rieni a'i frodyr a'i chwiorydd; rhennid y gweddill ymhlith y perthnasau pellach.", source: "Cyfraith Hywel", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Ac o'r gweddill hwnnw, dwy ran o dair a ddôi o ochr y tad ac un rhan o dair o ochr y fam. Roedd y gyfraith yn cyfrif dwy ochr ym mhawb.", source: "Cyfraith Hywel", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Pan fo dwy gangen yn rhwbio yn erbyn ei gilydd am flynyddoedd, mae'r rhisgl yn treulio i ffwrdd ac mae'r pren yn asio'n un.", source: "Coedwigaeth", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Impio: rhoi blaguryn un pren mewn hollt ym mhren arall a'i rwymo nes bod y ddau'n tyfu fel un. Felly y lledaenir pob math o afal sydd ag enw arno.", source: "Garddwriaeth", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Mae gwreiddiau ffawydd cyfagos yn ymuno o dan y ddaear, a gall boncyff a dorrwyd aros yn fyw am ddegawdau am fod ei gymdogion yn ei fwydo.", source: "Fagus sylvatica", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Tebyg i ddyn fydd ei lwdwn.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Natur yr hwch fydd yn y porchell.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Lle crafa'r iâr y piga'r cyw.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Anodd dwyn dyn oddi ar ei dylwyth.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Mae rhedyn yn lledaenu wrth ei wreiddgyffion yn fwy nag wrth ei sborau, felly gall llethr cyfan ohono fod yn un planhigyn.", source: "Pteridium aquilinum", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Ni all neb ddwyn ei geraint ar ei gefn.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .grownTogether),

        Passage(text: "Drych i bawb ei gymydog.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Câr cywir, yn yr ing fe'i gwelir.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Adwaenir dyn wrth ei gyfeillion.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Byw i arall yw byw yn iawn.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Cydblannu bedw, gwaith dedwydd.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Trech serch nag arfau dur.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Cof gan bawb a gâr.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "O, f'anwylyd, tyrd ar gais i wrando llais yr adar.", source: "Hen bennill", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Oer yw'r cariad a ddiffydd ar un chwa o wynt.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Gwae cymdogaeth heb gariad.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Gwell bendith y tlawd na meistrolaeth y cadarn.", source: "Dihareb Gymraeg", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Pan oeddwn gyfoethog cyn mynd yn dlawd, yr oeddwn yn gâr ac yn gefnder i bawb.", source: "Hen bennill", theme: .kinship, subtheme: .twoPeople),

        // MARK: Peace
        Passage(text: "Yn seremonïau'r Orsedd, gofynnir A oes heddwch dair gwaith, a'r dorf yn ateb Heddwch bob tro cyn y caiff y cleddyf fynd yn ôl i'w wain.", source: "Eisteddfod Genedlaethol Cymru", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Heddwch: hedd a'r terfyniad -wch, sef yr un terfyniad ag sydd mewn tawelwch a llonyddwch. Enw ar gyflwr yw'r cyfan ohonynt.", source: "Geirdarddiad", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Tangnefedd yw'r gair dyfnach na heddwch, ac oddi wrtho y daw tangnefeddwr, sef un sy'n gwneud heddwch rhwng dau arall.", source: "Cymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Cymod: y gair am ddau'n dod yn ôl at ei gilydd, ac yn yr hen gyfraith yr enw ar y setliad a roddai ddiwedd ar gynnen.", source: "Cymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "A ddigio heb achos, cymoded heb iawn.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Hawdd cymod lle bo cariad.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Gwell yr heddwch gwaethaf na'r rhyfel gorau.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Noswylio: gorffen gwaith y dydd a throi am adref. Daw o noswyl, sef y noson cyn gŵyl, fel petai diwedd pob diwrnod yn ŵyl fach.", source: "Cymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Rhoi'r gorau iddi: y ffordd Gymraeg o ddweud peidio. Rhoi'r gorau, nid y gwaethaf, sydd yn y geiriau.", source: "Cymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Nid doeth a ymryson.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Ni bydd doeth yn hir mewn llid.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Cadoediad: cad ac oediad, sef gohirio'r ymladd. Nid yw'r gair yn honni bod y peth wedi ei setlo, dim ond ei fod wedi ei atal.", source: "Geirdarddiad", theme: .peace, subtheme: .theWordsForStopping),

        Passage(text: "Gosteg: gair sy'n golygu tawelwch, ac sy'n golygu hefyd y llonyddu a ddaw ar wynt neu law wrth iddo ostegu. Y ddau'n un peth.", source: "Cymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Clywed sŵn yw ystyr arferol y ferf, ond ar lafar mewn rhannau o Gymru fe glywir arogl a chlywir blas hefyd. Un gair am bopeth ond gweld.", source: "Cymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Sisial, sibrwd, siffrwd, sio: mae'r cyfan ohonynt yn dynwared y sŵn a enwant, ac maent i gyd yn dechrau â'r un sain.", source: "Cymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Dywedir ar hyd arfordir Bae Ceredigion fod modd clywed clychau Cantre'r Gwaelod ar ddiwrnod digon tawel.", source: "Chwedl", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Basaf dwfr, mwyaf llafar.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Po ddyfnaf yr afon, lleiaf ei thrwst.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Mwyaf eu trwst, llestri gweigion.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Mae eira ffres yn llyncu sŵn. Mae'r aer rhwng y grisialau'n dal y tonnau nes bod pentref cyfan yn distewi mewn awr.", source: "Ffiseg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Mae ymyl pluen tylluan yn ddanheddog fel crib, ac mae hynny'n torri'r awyr yn ffrydiau bychain fel na cheir chwiban o gwbl.", source: "Strigiformes", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Chwarddiad dŵr dan iâ.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Doeth pob tawgar.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Mae galwadau'r rhan fwyaf o ystlumod yn rhy uchel eu traw i glust ddynol. Nid ydynt yn dawel; yn dawel i ni yn unig y maent.", source: "Chiroptera", theme: .peace, subtheme: .quietAsASound),

        Passage(text: "Lle digrif y bûm heddiw, dan fentyll y gwyrddgyll gwiw.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .peace, subtheme: .atEase),
        Passage(text: "Bodlon wyf i'r ganiadaeth.", source: "Dafydd ap Gwilym (c. 1315–1350)", theme: .peace, subtheme: .atEase),
        Passage(text: "Gorau o'r campau, bod yn llonydd.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Asgre lân, diogel ei pherchen.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Cyfoethog pob bodlon.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Harddwch pob hardd, tangnefedd.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Diofal cwsg potes maip.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Balch yw hwyaid ar y glaw.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Gwell digon na gormod.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "A chwilio fwyaf am fodlondeb a fydd bellaf oddi wrtho.", source: "Dihareb Gymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Llonydd: gadael llonydd i rywbeth yw'r peth caredicaf y gellir ei wneud iddo yn Gymraeg. Nid esgeuluso mohono ond peidio â phwyso.", source: "Cymraeg", theme: .peace, subtheme: .atEase),
        Passage(text: "Mae gwartheg yn gorwedd i lawr pan fyddant wedi bwyta digon, ac nid cyn hynny. Dyna'r arwydd y mae ffermwr yn edrych amdano.", source: "Amaethyddiaeth", theme: .peace, subtheme: .atEase),
    ]
}
