import Foundation

/// The Basque passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let basque: [Passage] = [
        // MARK: Beginnings
        Passage(text: "Ernetzea: haziak bere azala barrutik hausten duen unea. Ordu arte gordailu bat zen; hortik aurrera landare bat da.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Euskaraz inprimatu zen lehen liburua latinezko lerro batekin ixten da: hasiera ahula izan arren, zorte hobea etor dadila ondotik.", source: "Bernat Etxepare, Linguae Vasconum Primitiae, 1545", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Irulegiko eskua brontzezkoa da eta atarian zintzilikatzeko egina zegoen. Bere lehen hitza sorioneku irakurtzen da, gaurko zorioneko-ren antzekoa.", source: "Arkeologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Txitoak mokoan darama arrautza barrutik hausteko hortz txiki bat. Jaio eta egun gutxira erortzen zaio, ez baitu berriro beharko.", source: "Zoologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Hegazti asko ez dira berotzen hasten habia bete arte, kume guztiak egun berean jaio daitezen.", source: "Ornitologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Sumendi-uharte bat luzaro hazten da itsaspean, inork ikusi gabe. Ura gainditzen duen egunean bakarrik hartzen du izena.", source: "Geologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Bi erreka elkartzen diren tokian aldatzen da askotan ibaiaren izena. Handik behera beste ur bat da, nahiz eta iturri berak eman.", source: "Geografia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Lehen hitzak bi gauza esaten ditu euskaraz: ordenako aurrena eta aspaldiko garaia. Aurrena izatea eta antzina izatea hitz berak biltzen ditu.", source: "Euskara", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Tximeleta kokoitik ateratzen denean, hegoak busti eta zimurtuta ditu. Ordu batzuk behar ditu zabaltzeko, eta gero betiko daude zabalik.", source: "Entomologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Landareak bere lehen bi hostoak haziaren barruan ditu jada eginak. Lurpean irekitzen dira, argirik ikusi baino lehen.", source: "Botanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Jaioberriaren lehen arnasak birikak zabaltzen ditu, eta handik aurrera beti geratzen da haietan aire pixka bat.", source: "Fisiologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Urtarrila urte eta hil hitzez egina dago: urtearen hilabetea. Hamabietako bati urte osoaren izena eman zaio.", source: "Etimologia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Erleak, hain gauza ttipiak, eta flakoak, bethatzen du mundua eztiz eztitzeko, eta ezkoz argitzeko.", source: "Axular, Gero, 1643", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Haritz baten ezkurra esku batean sartzen da. Hirurehun urte geroago, enborrari besarka egiteko bost lagun behar dira.", source: "Botanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Zeta-harrak hari bakar bat ateratzen du kokoia egiteko. Kilometro bat baino luzeagoa izan daiteke, eta hatz batean biltzen da.", source: "Entomologia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kilo bat ezti egiteko, erleek lau milioi lore inguru bisitatzen dituzte, banan-banan, eta beti itzultzen dira erlauntza berera.", source: "Erlezaintza", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Iratzearen esporak hautsa bezain arinak dira. Haizeak kilometroak eramaten ditu, eta harkaitzeko arrakala batean hasten da basoa.", source: "Botanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Leizeetan, ur tanta bakoitzak kareharri izpi bat uzten du atzean. Metro bateko estalaktita hazteko milaka urte joan behar dira.", source: "Geologia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Orkideen haziak dira txikienetakoak, hauts finaren modukoak. Ez daramate ia janaririk, eta onddo baten laguntzaz bakarrik ernetzen dira.", source: "Botanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Perretxikoa ikusten dena da, baina lurpean onddo beraren hariek hektarea osoak josten dituzte. Fruitua txikia da, landarea ez.", source: "Mikologia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Elur maluta bakoitza hauts izpi baten inguruan hazten da: hodeian dagoen zerbait begiz ikusteko txikiegia.", source: "Meteorologia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Anboto eta Gorbeia kareharrizkoak dira, eta kareharri hori itsas hondoko izaki txiki-txikien maskorrez osatua dago.", source: "Geologia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Basurdeak lurra iraultzen duenean, ezkurrak eta haziak sartzen ditu lurpean nahi gabe. Hala jaiotzen dira basoko zuhaitz berri asko.", source: "Basogintza", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Hitz bat askotan atzizki bakar batekin hazten da: -tegi leku esan nahi du, eta hortik datoz liburutegia, sagardotegia eta ikastegia.", source: "Euskara", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Gizonak zer ere ereiten baitu, hura biltzen ere du.", source: "Axular, Gero, 1643", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Zuhaitz baten lehen urteko eraztuna erdi-erdian geratzen da beti. Enborra zenbat eta lodiago, orduan eta gordeago dago, aldatu gabe.", source: "Basogintza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Baserri bat non eraiki erabakitzeko, iturria non zegoen begiratzen zen lehenik. Urak aukeratzen zuen lekua, eta etxeak hantxe iraun.", source: "Etnografia", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Bildotsak amaren ahotsa lehen egunetan ikasten du, eta artalde oso baten artean ere hark deitzen duenean bakarrik altxatzen da.", source: "Artzaintza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mahatsondo bat beste zuztar batean txertatzen denean, fruituak adaxkarena izaten jarraitzen du. Zuztarrak indarra ematen dio, izena ez.", source: "Nekazaritza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Sagar mota bat gorde nahi bada, hazitik ereitea ez da bidea: hazi bakoitzak beste sagar bat ematen du. Txertoa da lehengoari eusteko modua.", source: "Nekazaritza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Hitzeman aditza hitz eta eman dira elkarrekin. Zerbait agintzea hitza ematea da euskaraz, eta emandakoa ez da atzera hartzen.", source: "Euskara", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Zorion hitza zori eta on dira: patu ona. Zorionak esatean, norbaiti erori zaion zoria goraipatzen da.", source: "Etimologia", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Haziak zein sakon jartzen den, hark erabakitzen du landarea. Sakonegi, argia berandu iristen zaio; azalegi, egun batean lehortzen da.", source: "Nekazaritza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Bertso-saioan gaia jarri ondoren ez da aldatzen. Hasitako neurriari eta doinuari eutsi behar zaie azken puntura arte.", source: "Bertsolaritza", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mendi-lerro batean tanta bat non erortzen den, hark erabakitzen du Kantauri itsasora ala Ebrora joango den. Aldea metro batzuena da.", source: "Geografia", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Etxe baten izena aldatzea zaila zen: paperek, hilarriek eta auzoek izen berari eusten zioten, maizterrak aldatu arren.", source: "Toponimia", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: Waiting
        Passage(text: "Lozorroa: haziak ez du ernetzen, giroa ona izanik ere. Barrutik dago geldi, zerbait aldatu arte.", source: "Botanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Bethi bihar, bethi gero, bethi luzamendu.", source: "Axular, Gero, 1643", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Lan baratza, lan aratza.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Zenbait hazik hotza behar du lehenik. Negurik gabe ez dira ernetzen, eta lorezainek hozkailuan sartzen dituzte negua asmatzeko.", source: "Nekazaritza", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Sagarra urrian jotzen da, eta gero sagardoa upelean egoten da isilik hilabeteak. Urtarrilera arte inor ez da hurbiltzen.", source: "Euskal ohitura", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Iratzeak ez du lorerik. Esporak prest daudenean bakarrik askatzen ditu, eta ordu arte hosto azpian daude gordeta.", source: "Botanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Karstean sartzen den euri-urak urteak eman ditzake harkaitzaren barruan, iturri batean berriro agertu aurretik.", source: "Geologia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Azak eta porruak neguan geratzen dira lurrean sartuta. Izozteak gozatu egiten ditu, eta horregatik ez dira lehenago ateratzen.", source: "Baratzezaintza", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Elur azpiko belarra ez dago hilda: bost gradutan hazten hasten da berriro, eta elurra kentzean berde dago jada.", source: "Botanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Ardiak mendian ematen du uda eta behean negua. Jaisteko eguna ez du egutegiak esaten, elurrak baizik.", source: "Artzaintza", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Mahatsa noiz bildu ez da egutegian erabakitzen. Azukrea neurtzen da, eta egun batzuk gehiago itxaroteak urte osoa alda dezake.", source: "Nekazaritza", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Iparraldean iguriki erabiltzen da itxaron esateko. Euskarak hitz bat baino gehiago du zain egoteko, eta bakoitzak bere kutsua darama.", source: "Euskara", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Denborak badohazi, eta urthe batzuez, hotsik eta habarrotsik egin gabe zahartzen gara.", source: "Axular, Gero, 1643", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Euskarak hitz bana du hurrengo bi egunetarako, bihar eta etzi, eta hirugarrenerako ere bai: etzidamu.", source: "Euskara", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Herenegun atzo baino lehenagoko eguna da, eta heren hitzak hirugarrena esan nahi du. Atzera ere hiruraino kontatzen da.", source: "Etimologia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Haritz batek berrogei bat urte behar ditu ezkur ugari emateko, eta gero berrehun urtez segitzen du ematen.", source: "Basogintza", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Azaroak hazi-aroa dakar barruan: ereiteko sasoia. Hilabeteari lanaren izena eman zaio, ez eguraldiarena.", source: "Etimologia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Hilabete-izen zaharrek landarea daramate askotan: iraila iratzearena da, urria hurrarena. Bildu beharrak jartzen zien izena.", source: "Euskara", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Duela bi mila urte harrian idatzitako izen batzuek gaurko euskal hitzak dituzte barruan. Hitz horiek ez dute ia mugitu behar izan ordutik.", source: "Arkeologia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Zohikaztegiek polena gordetzen dute geruzaz geruza. Euskal mendietako aintzira batzuek hamar mila urteko baso-kontakizuna dute azpian.", source: "Geologia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ardiaren adina hortzetan irakurtzen da, ez artzainaren oroimenean: bi hortz urtero, lauzpabost urte bete arte.", source: "Artzaintza", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Legarrezko ibaiak mendeak behar ditu harri bat biribiltzeko. Eskuan hartzen den harri leun bakoitza denbora luze horren neurria da.", source: "Geologia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Bertsolarien txapelketa nagusia lau urtean behin egiten da. Tartean plazaz plaza ibiltzen dira, txapelketarik gabe.", source: "Bertsolaritza", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Gernikako haritza belaunaldika berritzen da. Zaharra agortzen denean, haren ezkurretatik hazitako kimu bat jartzen da leku berean.", source: "Historia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Talaia itsasoari begiratzeko lekua zen. Norbait egoten zen han balea noiz agertuko zain, eta ikusi orduko sua pizten zuen abisatzeko.", source: "Itsas historia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Artzainak ez du artaldea aurretik gidatzen: atzetik doa, begira, eta txakurrak egiten du gainerakoa.", source: "Artzaintza", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Itsasargi bakoitzak bere errepikapena du, hainbat segundotan behin piztu eta itzali. Hori da haren izena, eta ez argiaren indarra.", source: "Itsas historia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Koartzak ordu erdiz iraun dezake geldi-geldi ur ertzean, hanka batean. Ez mugitzeak balio dio arrainari hurbiltzeak baino gehiago.", source: "Ornitologia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Zaindu aditzak begiratzea eta babestea esan nahi ditu batera. Artzaina ardi-zaina da, eta atezaina atearena.", source: "Euskara", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Lotan dagoen txoriak hanka bat tolestu eta burua hegalpean sartzen du. Behatzek adarra estutuz jarraitzen dute, indarrik egin gabe.", source: "Ornitologia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ilargiaren aldiak begiz neurtzen ziren baserrian: ilbeheran ez zen egurrik mozten, eta ereiteko ilberria hobetsi ohi zen.", source: "Herri-jakintza", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Arratsaldeko zeru gorriak biharko giro ona iragartzen du: eguzkiak mendebaldetik datorren aire lehorra argitzen duelako.", source: "Meteorologia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Erlauntzaren atean beti dago erle bat edo bi zaintzan. Sartzen den bakoitza usainetik ezagutzen dute, banaka.", source: "Erlezaintza", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Bertso-saioan entzuleen isiltasunak balio du gehien. Azken puntua non eroriko den entzuteko dago plaza osoa.", source: "Bertsolaritza", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Basoan, zuhaitz baten adarrek argia non dagoen erakusten dute: luzeenak beti argi gehien duen aldera hazi dira.", source: "Botanika", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Itsasgorak sei ordu eta erdi behar ditu. Kostaldeko arrantzaleek uraren markari begira erabakitzen zuten noiz atera portutik.", source: "Itsas historia", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: Renewal
        Passage(text: "Iratzea urtero mozten zen ganadu-azpitarako, eta urtero itzultzen zen. Sustraia lurpean dago, eta hori ez du igitaiak ukitzen.", source: "Nekazaritza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Lizarrak eta haritzak inausita hazten dira hobeto. Adarrak mozteak ez du zuhaitza amaitzen: berriro hastera behartzen du.", source: "Basogintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Zuhaitz motzak deitzen zaie enborretik behin eta berriro moztu direnei. Batzuek bostehun urte dituzte, eta enborra beti gaztea.", source: "Basogintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Belarra bi edo hiru aldiz biltzen da udan. Segak mozten duen bakoitzean, landarea sustraitik hasten da berriro, ez ebakitik.", source: "Nekazaritza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Sagarrondoa neguan inausten da, hoztuta dagoenean. Zauriak orduan ez du izerdirik galtzen, eta udaberrian adar berriak ateratzen ditu.", source: "Nekazaritza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ardiak urtean behin mozten dira, eta ilea berriro hasten zaie egun berean. Larruazalak ez daki mozketaren berri.", source: "Artzaintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Muskerrak isatsa uzten du eskuan geratzen bazaio, eta beste bat hazten zaio gero, motzagoa eta kartilagozkoa.", source: "Zoologia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ezpelak eta ereinotzak moztuta hartzen dute forma. Baratze zaharretako hesiak horrela egin ziren, urteroko ebakiaz.", source: "Baratzezaintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Porruak eta tipulak berriro ateratzen dira sustraia lurrean utziz gero. Beheko zati zuria nahikoa da hurrengoa hasteko.", source: "Baratzezaintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Sua ez da inoiz itzaltzen etxe zaharretan: gauean hautsez estaltzen zen txingarra, eta goizean hantxe zegoen berriro pizteko.", source: "Etnografia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Etxeko sua etxeko hautsez estal.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Baso batean sua pasatu ondoren, lehenengo agertzen dena iratzea eta ainarra izaten dira: haien haziak lurpean zeuden zain.", source: "Basogintza", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Uraren izena bethi da bat, ez ordea ura.", source: "Axular, Gero, 1643", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Euskarak bi sasoi ditu oinarrian, uda eta negua. Udaberria uda berria da, eta udazkena udaren azkena.", source: "Euskara", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Izotzondoko iguzki, neguaren parre.", source: "Xabier Lizardi, Biotz-begietan, 1932", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Santa Luzia egunean, abenduaren hamahiruan, esaten zen gaua laburtzen hasten dela eta eguna hazten. Egutegi zaharraren oroitzapena da.", source: "Herri-jakintza", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Enarak martxoan itzultzen dira, eta askotan aurreko urteko habia berera. Bidea ez dute ikasi: jaiotzetik dakarte.", source: "Ornitologia", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Basoak kolorez aldatzen duenean, ez du pigmenturik gehitzen: berdea kentzen du, eta azpian zegoen horia agertzen da.", source: "Botanika", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Zuhaitzek negurako prestatzen dute udan bertan. Kimu berriak uztailean eginak daude jada, kanpoko azal gogor batez bilduta.", source: "Botanika", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Sanjoan gauean sua pizten da herrietan, urteko egunik luzeenaren inguruan. Handik aurrera argia gutxitzen hasten da, egunez egun.", source: "Euskal ohitura", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Olentzero ikazkina da, mendian ikatza egiten zuena. Urteko azken egunetan bakarrik jaisten zen herrira, eta gero itzuli.", source: "Herri-jakintza", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Landare batzuek bigarren urtean bakarrik loratzen dute. Lehenengoan sustraia eta hostoak bakarrik egiten dituzte, eta hurrengoa itxaroten.", source: "Botanika", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Elur-uraren ondoren datorren udaberri-uholdeak lurra berritzen du ibarrean: mendiko lurra behera ekartzen du, geruza mehe batean.", source: "Geografia", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Aratusteak neguaren erdian egiten dira, garizuma hasi baino lehen. Mozorroak jantzita, urtean behin dena buruz behera jartzen zen.", source: "Etnografia", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ordun baratza leeneratu zan, mugak berriro zabaliz.", source: "Xabier Lizardi, Biotz-begietan, 1932", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Hezur hautsi bat sendatzean, lodiagoa geratzen da hausturaren tokia hasieran. Urteetan leuntzen da, harik eta marka ia ezabatu arte.", source: "Fisiologia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Zuhaitz batek ez du zauria ixten: inguratu egiten du. Azal berria ertzetik hasten da hazten, eta erdian zaharra hor geratzen da.", source: "Basogintza", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ontzi hautsiak grapaz josten ziren: zuloak eginda, metalezko kakoek bi zatiak lotzen zituzten. Konpontzea merkeagoa zen berria erostea baino.", source: "Etnografia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Sarea konpontzea arrantzaren parte zen, ez atzerapena. Portuko lehorrean egiten zen, eserita, eta askotan lagun batek baino gehiagok hartzen zuen parte.", source: "Itsas historia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Harresi zaharrak mortairurik gabe eraikitzen ziren: harri bakoitza besteen artean kokatzen zen. Bat erortzen bazen, hutsune horretan sartzen zen berria.", source: "Etnografia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Osatu aditzak sendatzea eta osorik egitea esan nahi ditu batera. Osasuna ere hortik dator: osoa izatea.", source: "Etimologia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Berritu, berriro, berrogei: ber- aurrizkiak bigarren aldia dakar. Euskaraz berritzea ez da beste bat egitea, bera berriro egitea baizik.", source: "Euskara", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ur zikina harearen artetik pasatzean garbitzen da: harea ez da aldatzen, eta ura bai. Iturri askok mendi osoa dute iragazki.", source: "Geologia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Larre bat gehiegi bazkatzen bada, urtebete atseden hartzea nahikoa izaten da belarra itzultzeko. Sustraiak han daude oraindik.", source: "Artzaintza", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Perretxikoak eta bakterioak dira basoko hosto hilak lurra bihurtzen dituztenak. Hosto batek urtebete behar du bidea egiteko.", source: "Mikologia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Kaiku bat egurrezko pieza bakarretik ateratzen zen, hustuz. Pitzatzen bazen, uretan sartzen zen egurra hantu eta arrakala ixteko.", source: "Etnografia", theme: .renewal, subtheme: .madeWhole),

        // MARK: Light
        Passage(text: "Zein eder den arratsean izar arte garbia, ipharretik agertzean marinelen argia!", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Egunsentia hitzak eguna sentitzea dakar barruan: argia ikusi baino lehen sumatzen den zerbait.", source: "Euskara", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ilunabarra ilun eta abar hitzez egina dagoela uste da: ilunaren adarrak, argiaren azken adaxkak.", source: "Etimologia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Goiz gorri, euri dagi; arrats gorri, eguraldi.", source: "Isastiren atsotitzak, 1620 ingurua", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Eguzkia sartu ondoren, hogeita hamar minutuz irakur daiteke kanpoan oraindik. Argi hori ez dator eguzkitik, goiko airetik baizik.", source: "Astronomia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Txantxangorria da goizean lehen kantatzen duena eta arratsean azken isiltzen dena. Kale-argiek engainatzen dute batzuetan.", source: "Ornitologia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gaua eta eguna berdin diren bi egun daude urtean. Ekinozioa esaten zaie, eta baserrian San Jose eta San Migel inguruko egunak ziren markak.", source: "Astronomia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Gaur hitza gau eta haur dira jatorriz: gau hau. Eguna izendatzeko, euskarak gauetik hasi zuen kontua.", source: "Etimologia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Mendiz inguratutako ibar batean, eguzkia gailurraren atzean sartzen da eta ez zeruertzean. Eguna laburragoa da han, eta ilunabarra luzeagoa.", source: "Geografia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Arratsalde hitza arrats eta alde dira: iluntzearen aldea. Bazkalondoko orduek gauaren izena daramate jada.", source: "Euskara", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Baserri gehienak ekialdera edo hego-ekialdera begira daude: goizeko eguzkia hartzen dute aurrez aurre, eta ipar-mendebaldeko haizeari bizkarra ematen.", source: "Etnografia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Lore batzuk arratsean bakarrik zabaltzen dira, sitsa dabilenean. Usaina orduan botatzen dute, eta ez egun osoan.", source: "Botanika", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Eguzkilorea atarian iltzatzen den kardu bat da. Hezetasunaren arabera ixten eta irekitzen da, eta hala urteak ematen ditu, giroari erantzuten.", source: "Herri-jakintza", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Landareak gaua neurtzen du, ez eguna. Iluntasunak zenbat irauten duen kontatzen du, eta horrek esaten dio noiz loratu.", source: "Botanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ilargi eta laino, sorginentzat giro.", source: "Euskal atsotitza", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Hilarri biribilek eguzki-arrosa bat daramate maiz alde batean, eta gurutzea bestean. Bi zeinu, harri berean, eta biak biribilaren barruan.", source: "Etnografia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Erleek zeruko argiaren norabidea ikusten dute hodeien azpitik ere. Horregatik dabiltza laino artean ere lekua galdu gabe.", source: "Erlezaintza", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Elur berriak eguzkiaren argi ia guztia itzultzen du; belar hezeak bostetik bat besterik ez. Mendi berean bi giro daude aldi berean.", source: "Fisika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Basoko argia berdea da behetik begiratuta: hostoek gorria eta urdina hartzen dituzte, eta erdikoa uzten dute pasatzen.", source: "Fisika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Itsasoko urak kolorea aldatzen du sakoneraren arabera. Arrantzaleek hortik igartzen zuten hondoa harria zen ala hondarra.", source: "Itsas historia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ilargiaren adarrak nora begira dauden begiratzen zen: gora bada, ontzia beteta dagoela esaten zen, eta euririk ez.", source: "Herri-jakintza", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ortzadarra beti eguzkiaren aurkako aldean agertzen da. Ikusten duenak badaki, hura begiratzean, eguzkia bizkarrean duela.", source: "Meteorologia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Egurra noiz moztu jakiteko, izerdiari begiratzen zitzaion. Neguan enborra lehorrago dago, eta orduan moztutakoak gehiago irauten du.", source: "Basogintza", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Etxeko hormak karez zuritzen ziren udaberrian. Kareak eguzkiaren beroa itzultzen du, eta horrez gain onddoak eta zomorroak uxatzen ditu.", source: "Etnografia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Zeruba dagon oztiña!", source: "Lauaxeta, Arrats beran, 1935", theme: .light, subtheme: .lightItself),
        Passage(text: "Argi hitzak ulermena ere izendatzen du: zerbait argi ikustea ulertzea da euskaraz, eta argibidea azalpen bat.", source: "Euskara", theme: .light, subtheme: .lightItself),
        Passage(text: "Ilargia argi hitzaz egina dago, hil hitzarekin batera. Hil hilabetea da euskaraz, eta hala ilargia hilabetearen argia da.", source: "Etimologia", theme: .light, subtheme: .lightItself),
        Passage(text: "Eguzki hitza egun hitzaren familiakoa da: eguna egiten duena. Eguerdia ere hortik dator, egunaren erdia.", source: "Etimologia", theme: .light, subtheme: .lightItself),
        Passage(text: "Ordun eguzkiz yantzi zan asaba zaarren baratza.", source: "Xabier Lizardi, Biotz-begietan, 1932", theme: .light, subtheme: .lightItself),
        Passage(text: "Itsasoko argi urdina plankton txikiek egiten dute: uraren mugimenduak pizten ditu, eta udako gauetan ikus daiteke olatuen ertzean.", source: "Itsas biologia", theme: .light, subtheme: .lightItself),
        Passage(text: "Ipurtargiaren argiak ez du berorik. Erreakzio hotz bat da, eta energia ia guztia argi bihurtzen du.", source: "Entomologia", theme: .light, subtheme: .lightItself),
        Passage(text: "Argizaria erleek egiten dute eztiaz elikatuz, eta gero kandelak hortik atera ziren. Argia eta eztia zeregin beraren bi aldeak dira.", source: "Erlezaintza", theme: .light, subtheme: .lightItself),
        Passage(text: "Zerua urdina da aireak argi urdina alde guztietara sakabanatzen duelako. Gorria zuzenago dator, eta horregatik ikusten dugu eguzkia horia.", source: "Fisika", theme: .light, subtheme: .lightItself),
        Passage(text: "Izarren argia iraganekoa da: gaur ikusten duguna aspaldi atera zen bidean. Zerura begiratzea atzera begiratzea da.", source: "Astronomia", theme: .light, subtheme: .lightItself),
        Passage(text: "Ilargiak ez du argi propiorik. Ikusten duguna eguzkiarena da, gure gainera islatua, eta hilabete oso bat behar du aldi guztiak igarotzeko.", source: "Astronomia", theme: .light, subtheme: .lightItself),
        Passage(text: "Kandelaren sugarra beroagoa da ertzetan erdian baino. Horregatik da urdinxka behealdean eta horia goian, gauza bera erretzen ari bada ere.", source: "Fisika", theme: .light, subtheme: .lightItself),

        // MARK: Pattern
        Passage(text: "Hamaika zenbaki bat da euskaraz, hamar eta bat, baina kontaezina ere esan nahi du. Hamaika aldiz esateak ez ditu hamaika aldi esan nahi.", source: "Euskara", theme: .pattern, subtheme: .counted),
        Passage(text: "Euskarak hogeitik kontatzen du: berrogei bi hogei dira, hirurogei hiru hogei, eta laurogei lau. Ehunera arte hogeinaka doa kontua.", source: "Euskara", theme: .pattern, subtheme: .counted),
        Passage(text: "Ehun zaldik ehun zela behar du.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .pattern, subtheme: .counted),
        Passage(text: "Zortziko handia zortzi lerrokoa da, hamar eta zortzi silabakoak txandaka. Txikiak zazpi eta sei ditu. Neurria aukeratzea da lehen erabakia.", source: "Bertsolaritza", theme: .pattern, subtheme: .counted),
        Passage(text: "Asteko hiru izen aste hitzaz hasten dira: astelehena lehena da, asteartea artekoa eta asteazkena azkena. Gero beste lau datoz, beste erro batzuekin.", source: "Euskara", theme: .pattern, subtheme: .counted),
        Passage(text: "Saroia zirkulu bat zen: erdian harri bat, eta inguruan beste batzuk denak distantzia berean. Larrea horrela neurtzen zen mendian.", source: "Etnografia", theme: .pattern, subtheme: .counted),
        Passage(text: "Erlauntzako gelaxkak sei aldekoak dira. Hori da azalera bat zatikatzeko modurik merkeena: hormarik gutxien eta hutsunerik ez.", source: "Geometria", theme: .pattern, subtheme: .counted),
        Passage(text: "Pinaburuaren ezkatak bi noranzkotan biratzen dira, eta bi espiral kopuruak segida ezagun bateko zenbaki hurrenak izaten dira: bost eta zortzi, edo zortzi eta hamahiru.", source: "Botanika", theme: .pattern, subtheme: .counted),
        Passage(text: "Bederatzi zenbakiaren izena bat eta hamar lotuz azaltzen saiatu dira hizkuntzalariak: hamarretik bat kenduta geratzen dena.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .counted),
        Passage(text: "Baserrian eguna otorduka zatitzen zen: gosaria, hamaiketakoa, bazkaria, askaria eta afaria. Hamaiketakoak ordua darama izenean.", source: "Etnografia", theme: .pattern, subtheme: .counted),
        Passage(text: "Marrazoen hortzak lerrotan daude, atzean beti ilara berri bat prest. Bat erori eta hurrengoa aurreratzen da, zintaren gisara.", source: "Itsas biologia", theme: .pattern, subtheme: .counted),
        Passage(text: "Aizkolarien apustuetan enborraren neurria kanatan ematen da, eta enbor kopurua aldez aurretik adosten. Denbora gero neurtzen da, ez lehenago.", source: "Herri kirolak", theme: .pattern, subtheme: .counted),
        Passage(text: "Orratzak baino hariak luzeago behar du.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Nola soinu, hala dantza.", source: "Isastiren atsotitzak, 1620 ingurua", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Txalaparta bi lagunek jotzen dute, eta ezin da bakarrik jo. Batak erritmoari eusten dio, eta besteak tarteak betetzen ditu.", source: "Musika", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Trikitixa bi tresna da beti: soinu txikia eta panderoa. Bata bestearen kontra jotzen da, eta biak batera entzuten.", source: "Musika", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Bertsolariak azken hitza aukeratzen du lehenengo, eta handik atzeraka eraikitzen du gainerakoa, errimak eskatzen duenari jarraituz.", source: "Bertsolaritza", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Bi bertsolari puntutan ari direnean, batak utzitako errimari erantzun behar dio besteak. Neurria komuna da, eta hori da adostasun bakarra.", source: "Bertsolaritza", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Harresi lehorrean, harri bakoitzak hiru ukitze-puntu izan behar ditu gutxienez. Hala eusten dio bere lekuari, morterorik gabe.", source: "Etnografia", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Athea bere erroetan eta uhaletan ongi iarria eta pausatua dagoenean erraxki hertsten da eta idekitzen da.", source: "Axular, Gero, 1643", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Lauburuak lau besoko forma bat da, bakoitza kurbatua eta guztiak norabide berean. Hilarrietan eta ateburuetan agertzen da.", source: "Etnografia", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Baserriaren egurrezko egitura iltzerik gabe josten zen: zulo bat eta mihi bat, eta ziri batek lotzen zituen biak.", source: "Etnografia", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Upel batek ez du kolarik. Ohol bakoitza alboetakoen kontra estutzen da burdinazko uztaiez, eta egurra hantzen denean ixten da zirrikitua.", source: "Etnografia", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Sokatiran, indarrik handiena ez du talde astunenak: aldi berean tira egiten duenak baizik. Denak batera edo bakarka, hori da aldea.", source: "Herri kirolak", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Badakit halaber ezin heda naitekeiela euskarako minzatze molde guztietara.", source: "Axular, Gero, 1643", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Euskara batua 1968an hasi zen finkatzen, Arantzazun bildutako batzar batean. Ordu arte bakoitzak bere euskalkian idazten zuen.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Bonaparte printzeak zortzi euskalki bereizi zituen 1863ko mapa batean, herriz herri galdetuta. Gaur bost bereizten dira.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Euskarazko lehen atsotitz-bilduma inprimatua 1596koa da, Iruñean argitaratua: bostehun eta hogeita hemeretzi esaera, gaztelaniara itzuliak.", source: "Refranes y Sentencias, 1596", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Bilduma horren ale bakarra Darmstadtko liburutegian zegoen, eta gerran galdu zen. Argazki batzuk gelditu ziren, eta horiek dira liburua orain.", source: "Refranes y Sentencias, 1596", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Oihenartek zazpiehun esaera baino gehiago bildu zituen 1657an, Parisen argitaratuak, frantsesezko azalpen banarekin.", source: "Arnaut Oihenart, Atsotitzak, 1657", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Ergatiboa deitzen zaio egilearen izenari eransten zaion -k horri. Aditzak berak esaten du nork, nori eta zer.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Aizkora hitza latinetik datorrela erakutsi zuten hizkuntzalariek, eta ez harria esan nahi duen haitz hitzetik. Aitzurraren kasua ez dago hain garbi.", source: "Etimologia", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Euskaltzaindia 1919an sortu zen, lau probintziatako ordezkariekin, hizkuntzaren arauak nork emango zituen erabakitzeko.", source: "Historia", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Larramendik euskararen lehen gramatika osoa argitaratu zuen 1729an, eta izenburua bera erronka bat zen: ezinezkoa garaitua.", source: "Historia", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Euskaraz ez dago hitz maskulinorik eta femeninorik. Hika hizketan bakarrik bereizten da, eta hor solaskidea bera markatzen da, ez izena.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Hizkuntzalariek ez diote euskarari senide bizirik aurkitu. Bere kabuz osatzen du familia oso bat, eta inguruko hizkuntza guztiak beranduago iritsi ziren.", source: "Hizkuntzalaritza", theme: .pattern, subtheme: .orderNamed),

        // MARK: Ground
        Passage(text: "Lurra hitzak lurra eta mundua esaten ditu euskaraz. Oinen azpian dagoena eta guztia biltzen duena hitz berak izendatzen ditu.", source: "Euskara", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Buztina, hondarra eta legarra dira lur baten hiru neurriak. Nahasketak esaten du zer hazi daitekeen han, eta ez lurraren koloreak.", source: "Nekazaritza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Zentimetro bat lur egiteko mendeak behar dira; euri gogor batek ordu batean eraman dezake, landarerik gabeko soro batetik.", source: "Nekazaritza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Zizareek beren gorputzetik pasarazten dute soroko lurra, urtean tona batzuk hektareako. Iraulitako lur hori beste bat da gainera datorrenean.", source: "Zoologia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ibarreko lurra mendikoa da, behera ekarria. Ibaiek mendeetan eraman dute goitik behera, eta hori da lurrik emankorrena.", source: "Nekazaritza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Euskal Herriko lur gehiena kareharri gainean dago, eta kareharri hori itsasoak utzi zuen. Mendia hondo zaharra da, altxatua.", source: "Geologia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Lur azido batean hortentsiak urdinak ateratzen dira, eta lur karetsuan arrosak. Landare bera da; azpikoak aldatzen du kolorea.", source: "Baratzezaintza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Sagarrondoak lur sakona eta hezea nahi du; mahatsondoak, harria eta lehorra. Bakoitzak bere gosea du, eta hortik dator alde guztia.", source: "Nekazaritza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Simaurra ez da ongarria bakarrik: lurra biguntzen du eta ura eusteko gai egiten. Horregatik ematen zitzaion belarrari ere.", source: "Nekazaritza", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Laiak bi hortzeko tresna dira, binaka erabiltzen zirenak. Lurra iraultzen dute goldeak baino sakonago eta geruzak nahastu gabe.", source: "Etnografia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Zohikaztegia ur azpian geratu den landaredia da, usteldu gabe. Bertan sartzen den guztiak mendeak irauten ditu, koloreak barne.", source: "Geologia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Lurpeko sustraiek onddoekin trukatzen dute: landareak azukrea ematen du, eta onddoak ura eta gatzak. Biek hobeto egiten dute elkarrekin.", source: "Botanika", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Nahiz ez den gaztelua, maite dut nik sor-lekhua, aiten aitek hautatua.", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Orhiko xoria Orhin laket.", source: "Arnaut Oihenart, Atsotitzak, 1657", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Orhi mendia Nafarroaren eta Zuberoaren mugan dago, eta ia beti dago elurpean. Oihenartek berak azaldu behar izan zuen non zegoen.", source: "Geografia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Herriak bere lege, etxeak bere aztura.", source: "Euskal atsotitza", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Haitzean jaioak haitzera nahi.", source: "Isastiren atsotitzak, 1620 ingurua", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Herri hitzak jendea, herrixka eta lurraldea biltzen ditu batera. Ez dago bereizterik non amaitzen den bata eta non hasten bestea.", source: "Euskara", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Baserri baten izena etxeari dagokio, ez familiari. Familiak etxearen izena hartzen zuen, eta ez alderantziz.", source: "Etnografia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Euskal deitura askok etxe bat izendatzen dute oraindik: Etxeberria etxe berria da, Etxegarai goikoa, eta Elizalde elizaren ondokoa.", source: "Toponimia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Iparraldea eta Hegoaldea esaten zaie euskaraz mugaren bi aldeei. Izenak norabidea dio, ez estatua.", source: "Geografia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Sortu aditzak jaiotzea eta sorraraztea biltzen ditu, eta sorlekua jaioterria da. Norbait nongoa den galdetzea non sortu zen galdetzea da.", source: "Euskara", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Landare berak beste gustu bat hartzen du beste lur batean. Idiazabalgo gazta ardiak jandako larrearen araberakoa da, eta ez esnearena bakarrik.", source: "Nekazaritza", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Hiru Erregeen Mahaia deitzen zaio hiru lurraldek bat egiten duten gailurrari: Nafarroa, Aragoi eta Bearno. Bi mila metro baino gorago dago.", source: "Geografia", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Asaba zaarren baratza, untzadun ormek esia, eguzkiak leen maitea...", source: "Xabier Lizardi, Biotz-begietan, 1932", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Zure etxea, egon eta ibili zaren lekhu guztietan, bethiere izatu da, euskaldunen etxea, pausalekhua eta portua.", source: "Axular, Gero, 1643", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Auzolana auzoen artean egiten den lana da: bidea, iturria edo zubia. Ez da ordaintzen, txandaka egiten baita.", source: "Etnografia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Baratzea jateko landatzen den lekua da euskaraz, eta lorategia beste hitz bat. Etxeari lotuta egoten zen beti baratzea, ez urrun.", source: "Euskara", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Etxeko andreak gordetzen zituen giltzak eta haziak. Hazi-kutxa sukaldean egoten zen, lehor, hurrengo urterako gordeta.", source: "Etnografia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Gernikako haritzaren azpian ematen zuten zina Bizkaiko jaunek, foruak gordeko zituztela. Zuhaitz bat zen agiria.", source: "Historia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Mairubaratz esaten zaie Pirinioetako harrizko biribilei: mairuen baratzeak. Hilobiak dira, eta baratzearen izena eman zaie hala ere.", source: "Arkeologia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Trikuharria da dolmenaren euskal izena: trikuaren harria. Barruan lurperatutakoak bost mila urte dituzte batzuetan.", source: "Arkeologia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Etxe zaharretako ateburuan urtea eta izena idazten ziren, harrian. Etxeak hala esaten zuen noizkoa zen eta norena.", source: "Etnografia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Sagardotegia sagardoa egiten den tokia da, eta -tegi atzizkiak lekua esan nahi du. Liburutegian liburuak daude, eta ardandegian ardoa.", source: "Euskara", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Hesola bat lurrean sartzeak muga bat egiten du, baina hesi bizi batek bi gauza egiten ditu: muga eta aterpe. Txoriek bigarrena aukeratzen dute.", source: "Baratzezaintza", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ikastolak gurasoek sortu zituzten, etxeetan eta lokal txikietan hasita, euskaraz irakasteko lekurik ez zegoenean.", source: "Historia", theme: .ground, subtheme: .aKeptPlace),

        // MARK: Travel
        Passage(text: "Inurriek haziak eramaten dituzte etxera, gaineko koipe-puska batengatik. Hura jan eta gainerakoa zabor-metan uzten dute, oso-osorik.", source: "Entomologia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Lapa-belarraren haziak kako txikiz inguratuta daude. Ardiaren ileari itsatsi eta hurrengo mendian jausten dira, artaldeak eramanda.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Astigarraren haziak hegal bat du, eta biraka erortzen da. Biraketak denbora luzatzen dio, eta denborak haizeari lekua ematen.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Masustaren haziak txoriaren barrutik osorik pasatzen dira, eta hobeto ernetzen dute gero. Bidaia bera da ereitearen parte.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kokoak itsasoan hilabeteak eman ditzake bizirik. Euskal kostaldera iristen den hazi arrotz bakoitzak hori egin du, oharkabean.", source: "Itsas biologia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mihuriak ez du lurra ukitzen: txoriak mokoa adarrean garbitzen duenean geratzen da itsatsita, eta han hasten da.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ur-ertzeko landare askoren haziak korronteak eramaten ditu ibaian behera. Erreka bakoitzak bere landareak zabaltzen ditu itsasoraino.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Basurdearen ilean eta ardiaren larruan hamar landare motaren haziak bil daitezke aldi berean. Animaliak ez daki zer daraman.", source: "Basogintza", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Zenbait pinuren pinaburuak suarekin bakarrik irekitzen dira: erretzen den egunean askatzen dituzte urtetako haziak, denak batera.", source: "Botanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Txori batek ezkur bat mokoan eramaten duenean, gehienetan gordetzen du eta gero ahazten. Ahaztea da ereitea.", source: "Ornitologia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Hazi txiki batzuk lokatzari itsatsita bidaiatzen dute, hegaztien hanketan. Aintzira batetik bestera hala pasatzen dira, kilometroak eginda.", source: "Ornitologia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ereitea eskuz botatzea zen luzaroan: haziak airera botatzen ziren eta goldeak estaltzen zituen gero. Zulo bakoitzean bat jartzea beranduagokoa da.", source: "Euskara", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Bidaide bidean kide dena da, eta gogaide gogoan kide dena. Bidean doazenek elkarri gogokoak esaten dizkiotela zioen bilduma zahar batek.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .travel, subtheme: .theRoad),
        Passage(text: "Bide hitzak modua ere esan nahi du: zerbait egiteko bidea eta oinez egiteko bidea hitz berak izendatzen ditu.", source: "Euskara", theme: .travel, subtheme: .theRoad),
        Passage(text: "Artzainek mendira igotzeko erabiltzen zituzten bideak artalde-bideak dira, eta batzuek milaka urte dituzte. Ardiek aukeratu zuten trazadura.", source: "Artzaintza", theme: .travel, subtheme: .theRoad),
        Passage(text: "Erreka oro itsasorat ari.", source: "Euskal atsotitza", theme: .travel, subtheme: .theRoad),
        Passage(text: "Korrika hamaika egunez eta hamaika gauez ibiltzen da, gelditu gabe, herriz herri. Barruan mezu bat daraman lekukoa eskuz esku pasatzen da.", source: "Euskal ohitura", theme: .travel, subtheme: .theRoad),
        Passage(text: "Donejakue bidea Orreagatik sartzen da Nafarroan, eta beste adar bat kostaldetik doa. Bien artean, mendia gurutzatu behar da.", source: "Historia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Mandazainek gatza eta burdina eramaten zituzten mendiz mendi, karriketan barrena. Mandoak bidea zekien, eta gizonak bidearen ordua.", source: "Historia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Zubi zaharrak beti daude ibaia estuen den lekuan, eta ez herritik hurbilen dagoenean. Herria zubiaren ondoan hazi zen, ez alderantziz.", source: "Etnografia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ibili aditzak joatea eta jardutea biltzen ditu: lanean ibili eta mendian ibili aditz berbera dira euskaraz.", source: "Euskara", theme: .travel, subtheme: .theRoad),
        Passage(text: "Gurdiaren gurpilek kirrinka egiten zuten, eta bakoitzak bere hotsa zuen. Auzoak jakiten zuen nor zetorren bidean, ikusi baino lehen.", source: "Etnografia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Mendiko bidexketan harri-metak jartzen dira bidea markatzeko. Pasatzen den bakoitzak harri bat gehitzen dio, eta hala hazten dira.", source: "Herri-jakintza", theme: .travel, subtheme: .theRoad),
        Passage(text: "Bide bat bi aldiz ez da berdina: joatean gora eta itzultzean behera. Distantzia bera da, eta orduak ez.", source: "Geografia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Heuskara, habil mundu guzira.", source: "Bernat Etxepare, Kontrapas, 1545", theme: .travel, subtheme: .farOff),
        Passage(text: "Euskal baleazaleak Ternuara joaten ziren hamaseigarren mendean, eta Labradorren negua igarotzen zuten. Han utzitako teilak oraindik ageri dira.", source: "Itsas historia", theme: .travel, subtheme: .farOff),
        Passage(text: "Islandian euskal hitzez betetako hiztegi batzuk gorde dira, baleazaleek eta bertakoek elkar ulertzeko sortu zuten mintzairarenak.", source: "Hizkuntzalaritza", theme: .travel, subtheme: .farOff),
        Passage(text: "Elkano Getariakoa zen, eta 1522an itzuli zen munduari bira emanda. Hemezortzi lagun besterik ez ziren iritsi hasierako berrehunetik.", source: "Historia", theme: .travel, subtheme: .farOff),
        Passage(text: "Enarak Afrikan igarotzen du negua, eta hurrengo udaberrian etxe berera itzultzen da. Bi mundu ditu, eta bidea da hirugarrena.", source: "Ornitologia", theme: .travel, subtheme: .farOff),
        Passage(text: "Angulak Sargazoen itsasoan jaiotzen dira, eta urteak behar dituzte Bidasoaraino iristeko. Handitzean, itsaso berera itzultzen dira erruteko.", source: "Itsas biologia", theme: .travel, subtheme: .farOff),
        Passage(text: "Amerikara joandako artzain askok Nevadan eta Idahon eman zituzten urteak, eta haietako batzuek zuhaitzen azalean idatzi zuten euskaraz.", source: "Historia", theme: .travel, subtheme: .farOff),
        Passage(text: "Hondarrezko hauts finak Saharatik iristen dira batzuetan euskal zerura. Egun horietan eguzkia laranja ateratzen da.", source: "Meteorologia", theme: .travel, subtheme: .farOff),
        Passage(text: "Urrun eta urruti bi hitz dira gauza bererako, eta biak erabiltzen dira. Euskalkiak erabakitzen du zein entzungo den.", source: "Euskara", theme: .travel, subtheme: .farOff),
        Passage(text: "Kanpotik ekarritako landare batzuk hemengoak dirudite jada: artoa Amerikatik etorri zen, eta arto hitzak hemen artatxikia izendatzen zuen lehen.", source: "Nekazaritza", theme: .travel, subtheme: .farOff),
        Passage(text: "Itsasargi baten irismena ez dago indarrean bakarrik, altueran ere bai. Zenbat eta gorago egon, orduan eta urrunago ikusten da, lurra biribila delako.", source: "Fisika", theme: .travel, subtheme: .farOff),
        Passage(text: "Belaontzi batek ez du haizearen norabidean bakarrik nabigatzen: alboka joanez, haizearen kontra ere aurrera egin dezake, bihurka.", source: "Itsas historia", theme: .travel, subtheme: .farOff),

        // MARK: Meeting
        Passage(text: "Heuskara, ialgi adi plazara.", source: "Bernat Etxepare, Kontrapas, 1545", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Elkar da euskarak elkarrekikoa adierazteko duen izenordaina: bata bestea. Elkar ikusi gabe ezin da esan bi lagun topatu direnik.", source: "Euskara", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Bi erreka elkartzen diren tokiari ur-elkargunea esaten zaio, eta hortik aurrera bakarra da. Bien izena galtzen da eta hirugarren bat sortzen.", source: "Geografia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Eguzki-eklipse oso batean, ilargiaren itzalak zerrenda estu bat marrazten du lurrean, eta puntu batean minutu gutxi batzuk irauten du.", source: "Astronomia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ezti-erlea lorean pausatzen denean, biak aldatzen dira: lorea ernaltzen da, eta erleak besteei esango die dantzan non dagoen lorea.", source: "Erlezaintza", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Irrintzia ibarraren beste aldera iristeko botatzen zen. Zorrotza eta luzea izateak eramaten du urrunera, ozena izateak baino gehiago.", source: "Herri-jakintza", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ibai batek beste bat hartzen duenean, urak abiadura galtzen du elkargunean eta harea bertan uzten. Ibaiko uharteak horrela hazten dira.", source: "Geografia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Aurkitu aditzak aurre hitza duela barruan uste da: zerbait aurkitzea begien aurrera ekartzea da, hitzez hitz hartuta.", source: "Etimologia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Soka-dantzan denak esku emanda doaz, eta katearen buruan doanak erabakitzen du bidea. Azkenak beti ikusten du non hasi den ilara.", source: "Musika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Muga-harriak bi aldetatik ditu markak, bakoitza bere herrirakoa. Harri bat da, eta bi izen ditu.", source: "Etnografia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Itsasoak eta ibaiak bat egiten duten tokian, gazia eta geza geruzatan geratzen dira zenbait ordu. Arrainek geruza bat aukeratzen dute.", source: "Itsas biologia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Bi bertsolari plazan elkartzen direnean, ez dakite zer gai emango zaien. Gaia entzun eta hurrengo hamar segundoak dira saioaren gunea.", source: "Bertsolaritza", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Txalaparta jotzeko bi lagun behar dira nahitaez: batak hutsuneak uzten ditu, eta besteak haiek betetzen. Bakarrik jota ez da txalaparta.", source: "Musika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Lore askok hautsa lehenago askatzen dute beren burua hartzeko prest egon baino. Hala, ezin dute beren buruarekin topo egin.", source: "Botanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ilarrak eta babarrunak sustraietan bakterioak hartzen dituzte, eta haiek airetik nitrogenoa ekartzen diete. Bakoitzak ez luke bakarrik egingo.", source: "Botanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Likena bi izaki da bat eginda: onddo bat eta alga bat. Harrian bizi daitezke horrela, eta ez batak ez besteak bakarrik.", source: "Mikologia", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Idi-parea uztarri berean lotzen da, eta biek pauso bera eman behar dute. Pare bat egiteko urtebete behar izaten zen.", source: "Nekazaritza", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Pilotan, hormak ez du inoiz huts egiten. Bi jokalarik horma bera dute lagun eta epaile, eta bien artean ez dago sarerik.", source: "Herri kirolak", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Trikitilariak eta panderojoleak elkarri begiratzen diote, ez jendeari. Doinuaren aldaketa keinu batez esaten da, ez hitzez.", source: "Musika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Adiskidea zaharrik, kontua berririk.", source: "Arnaut Oihenart, Atsotitzak, 1657", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Zenbait sagarrondok ezin du bere buruarekin fruiturik eman: beste mota bateko zuhaitz bat behar du inguruan. Baratze zaharretan beti dago bikotea.", source: "Nekazaritza", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Aurresku batean, dantzariak eskua ematen dio hurrengoari zapi baten bidez. Katea horrela osatzen da, eta inor ez da bakarrik geratzen.", source: "Etnografia", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Sokatiran, alde bat hutsik geratuz gero, bestea lurrera erortzen da. Indarrak beste indar bat behar du zutik egoteko.", source: "Herri kirolak", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Lagundu aditzak norbaitekin joatea eta norbaiti eskua ematea esan nahi ditu batera. Laguntza hitza laguna hitzetik dator.", source: "Euskara", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Hartu-emanak du gustua.", source: "Isastiren atsotitzak, 1620 ingurua", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ez dugu behar lurrean, ongi bizirik etxean, utzi laguna gosean.", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Agur hitza latinetik dator, aztiek hegaztiei begiratuz emandako seinaletik. Etortzean eta joatean esaten da, biak batera.", source: "Etimologia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ongi etorri esatea ez da bakarrik agurra: etorria ontzat ematea da hitzez hitz, eta erantzuna eskerrik asko izaten da.", source: "Euskara", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Gabon bi gauza dira euskaraz: gau on opa izatea eta Eguberri bezpera. Urteko gau bati gau guztien agurra jarri zaio izena.", source: "Euskara", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Sagardotegian txotx esaten da upela zabaltzen denean, eta hori da denak zutitzeko dei bakarra. Txotxa egurrezko ziri bat da.", source: "Euskal ohitura", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Mahaian esertzean on egin esaten da, jaten ari denari zuzenduta. Ez da eskerrik ematea, opa egitea baizik.", source: "Euskal ohitura", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Santa Ageda bezperan, taldeak etxez etxe ibiltzen dira makilaz lurra joz eta kantuan. Etxekoek ateratzen dituzte ogia eta txorizoa.", source: "Etnografia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Euskaraldian bi rol daude: ahobizi, beti euskaraz egiten duena, eta belarriprest, ulertzen duena eta besteari euskaraz egiteko eskatzen diona.", source: "Euskal ohitura", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Hika hizketan solaskidea markatzen da aditzean bertan. Norbaiti hika egitea hurbiltasunaren aitorpena da, eta ez da denekin egiten.", source: "Hizkuntzalaritza", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Islandiako hiztegietan galdera eta erantzun batzuk osorik gorde dira, elkarri eskaintzeko eta trukatzeko esaldiak. Salerosketak ekarri zuen hizkuntza.", source: "Hizkuntzalaritza", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Bertsolariak entzuleari agurra egiten dio lehen bertsoan, beti. Ez da ohitura hutsa: lehen bertsoak esaten du zer neurritan ariko den.", source: "Bertsolaritza", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: Kinship
        Passage(text: "Ene asaben lokarri zaarra, Yaunari zor, etzan eten!", source: "Xabier Lizardi, Biotz-begietan, 1932", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Bi zuhaitz elkarren kontra hazten badira, azalak ukitzen dira eta enborrak bat egiten du. Handik aurrera izerdi bera dute biek.", source: "Basogintza", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Txertoa egiterakoan, azal biziak elkar ukitu behar du. Lotura ez da kolatzea: bi landare bakar bat egitea da.", source: "Nekazaritza", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Hostoaren zainak banatu eta berriro elkartzen dira. Bidea eteten bada, ura beste adar batetik pasatzen da eta hostoak eusten dio.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Lezka-sail oso bat sustrai bakar batetik ateratzen da askotan. Kanpotik ehun landare dira, eta lurpean bat.", source: "Botanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Basoko zuhaitzek sustraiak lotzen dituzte onddoen bidez, eta motz geratu den bati azukrea iristen zaio auzokoengandik.", source: "Basogintza", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Harresi bat eraikitzean, kate-harriak zeharka jartzen dira tarteka, bi aldeak josteko. Ikusten ez den harri horrek eusten dio guztiari.", source: "Etnografia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Bi ibai elkartzen direnean, urak kilometro batzuetan bereizita joan daitezke, tenperatura eta kolorea desberdinak badira. Marra ikusi egiten da.", source: "Geografia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Soka bat egiteko, hariak alde batera bihurritzen dira eta sokak bestera. Bakoitza bere aldera tiraka dago, eta horrek eusten dio guztiari.", source: "Etnografia", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Erlauntza bat izaki bakar bat balitz bezala berotzen da neguan: erleek elkarren kontra bola bat egiten dute, eta txandaka sartzen dira erdira.", source: "Erlezaintza", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Upel zaharrak baliotsuagoak dira sagardogilearentzat: egurrean geratzen diren legamiek hurrengo urteko hartzidura abiarazten dute.", source: "Euskal ohitura", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Ezkur batetik jaiotako haritz batek amaren zuhaitzaren onddo berak hartzen ditu lurpean, hurbil badago. Herentzia lurrean dago, ez haziaren barruan.", source: "Basogintza", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Euskaraz anaia eta arreba mutil batek dituenak dira; neska batek neba eta ahizpa ditu. Hitzak nork esaten duen markatzen du.", source: "Euskara", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Senide hitzak -ide atzizkia darama, kidetasunarena. Anai-arrebak izatea zerbaiten kide izatea da euskaraz.", source: "Etimologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Kide atzizkiak laguna ateratzen du hitzetik: lankidea lanean, ikaskidea eskolan, auzokidea auzoan. Hitzak berak dio non elkartu diren.", source: "Euskara", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Elkar hitzetik elkartu, elkarte, elkartasun eta elkarrizketa datoz. Solasaldia bera bi lagunen arteko elkar-hizketa da izenez.", source: "Euskara", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Akitaniako harrietan andere emakume esan nahi zuen, eta gaur andrea da. Sembe semea zen, eta cison gizona.", source: "Arkeologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Aitona eta amona aita eta ama dira, on hitza erantsita. Belaunaldi bat gehiago aditzera emateko, ona gehitu zaio hitzari.", source: "Etimologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Zahar hitzak, zuhur hitzak.", source: "Euskal atsotitza", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Etxekoandre eta etxekojaun etxearenak dira, ez ezkontzarenak. Etxeak ematen die izena, eta ez elkarri.", source: "Etnografia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ume, haur eta seme-alaba hiru hitz dira eta ez dute gauza bera esan nahi: azkenak gurasoari begiratzen dio, eta besteek adinari.", source: "Euskara", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Hitz bat txikiagoa egiteko, euskarak soinua aurreratzen du ahoan: zakurra txakur bihurtzen da, eta Mikel Mikeltxo. Samurtasuna hotsean dago.", source: "Hizkuntzalaritza", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Osaba eta izeba aitaren edo amaren aldekoak izan daitezke, bereizi gabe. Euskarak ez du bi aldeak banatzen hitzez.", source: "Euskara", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Lehengusu hitzak lehen darama aurrean: lehen mailako ahaidea. Hurrengo mailakoari bigarren lehengusu esaten zaio, eta hala segitzen du kontuak.", source: "Etimologia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Irri batentzat badut etxean nik behar dudan guzia.", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Adiskide onekin orduak labur.", source: "Euskal atsotitza", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Koadrila urteetan batera ibiltzen den lagun taldea da, eta askotan eskolakoa. Hirurogei urterekin ere koadrila esaten zaio berdin.", source: "Etnografia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Auzolanean, bakoitzak bere tresnak eramaten ditu eta inork ez du kontatzen zenbat orduz aritu den. Kontua hurrengo baterako gelditzen da.", source: "Etnografia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Bi lagunek elkarri eskua ematean, bostekoa ematen diote: bost atzamarrak. Zenbakia bera da agurra.", source: "Euskara", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Erretiroan dauden marinelak portuan biltzen dira oraindik, eguraldiaz hitz egiteko. Portua ez zen lantokia bakarrik.", source: "Itsas historia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Bertso bat bakarka egin daiteke, baina saio bat ez. Beste bertsolari batek erantzuten duenean bakarrik osatzen da elkarrizketa.", source: "Bertsolaritza", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Bi hegazti dabiltzanean, aurrekoak airea urratzen du eta atzekoak indar gutxiago behar du. Horregatik aldatzen dute lekua txandaka.", source: "Ornitologia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Idi-probetan bi gizonek gidatzen dituzte idiak, bata aurrean eta bestea alboan. Ez dute elkarri deitzen: keinuz ari dira.", source: "Herri kirolak", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Bi lagunek elkarrekin egindako lana euskaraz elkarlana da, eta hitz horrek berak balio du lantegian eta baratzean.", source: "Euskara", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Laguntzaile, saltzaile, irakasle: euskarak egilearen izena aditzetik ateratzen du. Laguntzaileak, ordea, beti norbait behar du ondoan.", source: "Etimologia", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Igitaiaz belarra mozten denean, esku batek moztu eta besteak biltzen du. Horregatik da lan hori arinagoa bikoteka eginda.", source: "Nekazaritza", theme: .kinship, subtheme: .twoPeople),

        // MARK: Peace
        Passage(text: "Isilunea hizketan gelditzen den tartea da: -une atzizkiak leku edo bitarte txiki bat esan nahi du. Isiltasuna ez, isilune bat.", source: "Euskara", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Zurrumurrua bi gauza da euskaraz: apal hitz egitearen hotsa eta esaten den hitza bera. Marmarrak ere bietarako balio du.", source: "Euskara", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Hontzak lumen ertzak orrazi baten antzekoak ditu, eta horrek airea zatitzen du zaratarik egin gabe. Harrapakinak ez du entzuten gainera datorrenik.", source: "Ornitologia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Kanpai-hotsak berria ematen zuen, ez ordua bakarrik: kolpe kopuruak esaten zuen nor hil zen, eta noizkoa zen hileta.", source: "Etnografia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Elur berria erori den gauean, dena isilago entzuten da. Maluten arteko hutsuneek soinua hartzen dute, eta ez dute itzultzen.", source: "Fisika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Barre-dagigun leunkiro, barre auxe dan ixilla!", source: "Lauaxeta, Arrats beran, 1935", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Xuxurlatu aditzak berak esaten du zer den: hotsa hitzaren barruan dago, eta ez esanahian bakarrik.", source: "Euskara", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Pil-pil olioak eta urak elkartzean egiten duten hotsa da, eta saltsa baten izena ere bai. Hotsak jarri zion izena jakiari.", source: "Sukaldaritza", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Belarriprest esaten zaio ulertzen duenari eta besteari euskaraz egiteko eskatzen dionari. Parte hartzeko modu bat da entzutea.", source: "Euskal ohitura", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Hots soinua da euskaraz, eta hots egin norbaiti deitzea. Deitzeko, hotsa botatzen zaio norbaiti.", source: "Euskara", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Entzun eta isil, baiezko borobil.", source: "Euskal atsotitza", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Gauez basoan entzuten diren kirrinka batzuk ez dira animalienak: egurra hoztean uzkurtu egiten da, eta hotsa ateratzen du.", source: "Basogintza", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Bakea ez da diruz erosia.", source: "Isastiren atsotitzak, 1620 ingurua", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Bake hitza latinetik hartu zuen euskarak, eliza eta errege hitzekin batera. Latinezko erroak lotzea esan nahi zuen: bakea bi alde elkarri lotzea zen.", source: "Etimologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Su-etena su eta eten dira: sua etetea. Ez da bakea, tartea baizik, eta hitzak berak hala dio.", source: "Euskara", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Hitzarmena hitz eta eman hitzez egina dago: elkarri hitza ematea. Tratu bat sinatu aurretik, ahoz lotzen zen.", source: "Etimologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Gerlaren ondoan estimatzen da bakea: tormenta iragan denean, prezatzen da denbora ederra.", source: "Axular, Gero, 1643", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Baretu aditzak haizea, itsasoa eta gogoa lasaitzen ditu, hirurak hitz berarekin. Itsaso barea eta gogo barea gauza bera dira izenez.", source: "Euskara", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Etenaldia eten eta aldi hitzez egina dago: haustura bat eta denbora-tarte bat. Gelditzeak berak irauten du.", source: "Euskara", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Baketu, adiskidetu eta elkartu: hiru aditzek bi alde biltzen dituzte, eta hirurek eskatzen dute biak egotea.", source: "Euskara", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Fazeriak Pirinioetako herrien arteko itunak dira, larreak eta urak elkarrekin erabiltzeko. Batzuk sei mende dituzte, eta urtero berritzen dira egun jakin batean.", source: "Historia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Hala bada koleraren iraungitzeko eta sosegatzeko ere, da, hitz ona, errepuesta emea eta eztia.", source: "Axular, Gero, 1643", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Gelditu aditzak bertan geratzea eta zerbait bertan behera uztea esan nahi ditu. Egotea eta amaitzea hitz berak biltzen ditu.", source: "Etimologia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Herri askotan bake-epailea dago oraindik: auzitara jo aurretik bi aldeak adiskidetzen saiatzen dena. Izenak dio zertarako den.", source: "Historia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Han bizi naiz ni bakean.", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .peace, subtheme: .atEase),
        Passage(text: "Aise da, alegera da, bake handian da halakoa.", source: "Axular, Gero, 1643", theme: .peace, subtheme: .atEase),
        Passage(text: "Atseden, atsegin eta atsekabe hirurak hats hitzetik datoz, arnasa. Atseden hartzea arnasa hartzea da hitzez hitz.", source: "Etimologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Hasperena ere hats hitzetik dator: arnasa luze bat botatzeak bere izena du euskaraz.", source: "Etimologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Patxada presarik gabe aritzea da, eta ez geldirik egotea. Patxadaz lan egin daiteke, eta askotan hobeto egiten da hala.", source: "Euskara", theme: .peace, subtheme: .atEase),
        Passage(text: "Lasai hitzak soka bat tenkatu gabe dagoela ere esaten du. Arropa lasaia eta gogo lasaia hitz berak izendatzen ditu.", source: "Euskara", theme: .peace, subtheme: .atEase),
        Passage(text: "Pausa adi! lo egizak, xori maitea bakean.", source: "Jean Baptiste Elizanburu (1828–1891)", theme: .peace, subtheme: .atEase),
        Passage(text: "XVII. mendeko ohar batek dio sutondoan bazela ordena bat: etxeko nagusiak suaren aurrean eta txikienak alboan, eta denek entzuten zutela.", source: "Zalgizeren atsotitzak, XVII. mendea", theme: .peace, subtheme: .atEase),
        Passage(text: "Goxo hitzak gozoa eta epela esan nahi ditu batera. Leku goxo bat ez da gozoa: epela eta babestua da.", source: "Euskara", theme: .peace, subtheme: .atEase),
        Passage(text: "Zer da iustuki bizitzea, bakean eta soseguan bizitzea baizen?", source: "Axular, Gero, 1643", theme: .peace, subtheme: .atEase),
        Passage(text: "Lo hartu aurretik, gorputzaren tenperatura erdi gradu jaisten da. Logura arratsean etortzea horri lotuta dago, eta ez nekeari bakarrik.", source: "Fisiologia", theme: .peace, subtheme: .atEase),
        Passage(text: "Lurpetik ateratzen den urak tenperatura bera izaten du urte osoan. Horregatik dago iturri baten ondoa fresko udan eta epel neguan.", source: "Geologia", theme: .peace, subtheme: .atEase)
    ]
}
