import Foundation

/// The Estonian passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let estonian: [Passage] = [
        // MARK: - Beginnings
        Passage(text: "Idanemine algab siis, kui seeme joob endasse vett ja paisub. Kest praguneb, ja tagasiteed sealt enam ei ole.", source: "Botaanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Seemnest tuleb esimesena välja juureke, alles seejärel leht. Taim otsib kõigepealt vett ja alles siis valgust.", source: "Botaanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Eesti keeles ei ole tuleviku vormi. Kui öeldakse, et miski algab, öeldakse seda oleviku ajas.", source: "Eesti keel", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Alustama ja algus on ühest tüvest, mis on siin vanem kui ükski siinmail kirja pandud lause.", source: "Etümoloogia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Laena mulle kannelt, Vanemuine! Kaunis lugu mõlgub meeles.", source: "F. R. Kreutzwald, Kalevipoeg, 1862", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Tibu murrab munakoore lõhki väikese hambaga noka otsas. Hammas ei ole talle enam tarvis ja kaob mõne päevaga.", source: "Zooloogia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Kaali kraater Saaremaal tekkis ühe hetkega, kui meteoriit maasse lõi. See juhtus ajal, mil inimesed juba seal elasid.", source: "Geoloogia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Vanim eestikeelne trükitud lause on säilinud 1535. aasta katekismuse katketes, mis leiti ühe teise raamatu köitest.", source: "Raamatulugu", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Põdravasikas tõuseb jalgadele esimese tunni jooksul. Tema kõige esimene tegu on püsti saamine.", source: "Zooloogia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Allikas on koht, kus põhjavesi jõuab pinnale ja hakkab jooksma. Enne seda oli ta juba olemas, aga liikumata.", source: "Geograafia", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Sinilill õitseb Eesti metsas enne, kui puudele tulevad lehed. Ta jõuab ära õitseda valguses, mida hiljem seal enam ei ole.", source: "Botaanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Idulehed ei ole päris lehed. Need olid seemnes juba valmis, ja nende ainus töö on teha ruumi järgmistele.", source: "Botaanika", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Tõru idaneb esimesel aastal peaaegu ainult allapoole. Maa peal ei paista midagi, all on juba jalapikkune juur.", source: "Botaanika", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Turvas kasvab rabas umbes millimeetri aastas. Meetripaksune kiht on tuhande aasta jagu vihma ja sammalt.", source: "Ökoloogia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Eesti läänerannik tõuseb merest praegugi paari millimeetri võrra aastas. Nõnda sünnivad Väinamerre uued laiud.", source: "Geoloogia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Kuklasepesa männimetsas võib olla kahe meetri kõrgune. Ta on ehitatud okas okka haaval, ühe suve jooksul lisandub sentimeeter.", source: "Putukateadus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Rukkilill kasvas siin algul rukki sees umbrohuna. Nüüd on ta Eesti rahvuslill.", source: "Taimeteadus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Iga vihmapiisk on tekkinud ümber tolmutera. Ilma selle terata jääks pilves olev vesi kokku tõmbumata.", source: "Meteoroloogia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Üks pääsuke ei tee veel kevadet.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Täks täna, täks homme, kord ikka suur puu langeb.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Liivatera veereb tuulega. Kui neid on küllalt, veereb kogu luide ja mets jääb tema alla.", source: "Geograafia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Mesilaspere korjab ühe kilo mett ligikaudu neljalt miljonilt õielt.", source: "Mesindus", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Sammal kasvab paeplaadil ilma mullata ja teeb mulda. Loopealse õhuke muld on tema töö.", source: "Ökoloogia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Peraküla luitevall on kokku kantud tuulega. Ükski tera ei tulnud koos teisega, aga nad on nüüd üks mägi.", source: "Geograafia", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Külva head, siis kasvab head.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kuidas külvad, nõnda lõikad.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Maad küntakse mitu korda, seemet külvatakse üks kord.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Mida noorelt külvad, seda vanalt lõikad.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Paks seeme kaotab, harv seeme kasvatab.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Sõrme otsast külvad, sõrme otsast lõikad.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Esimene lumi, mis maha jääb, otsustab, kui sügavale maa talveks külmub. Vara tulnud lumi hoiab mulla soojana.", source: "Ilmateadus", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Rahvakalendris ennustati jaanipäeva ilmast kogu heinaaega. Üks päev pidi ütlema, milline tuleb kuu.", source: "Rahvakalender", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Kelle laps, selle nimi.", source: "Eesti vanasõna", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Eesti kirjakeele aluseks võeti põhjaeesti murre. Lõunaeesti kirjakeel oli olemas varem, kuid jäi kõrvale.", source: "Keeleajalugu", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Talirukis külvatakse sügisel ja peab talve üle elama. Kevadel ei ole tema puhul enam midagi parandada.", source: "Põllumajandus", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Järv hakkab kinni külmuma sealt, kus vesi on kõige vaiksem. Esimene plaat ütleb ette, kuidas läheb ülejäänu.", source: "Füüsika", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: - Waiting
        Passage(text: "Puhkeseisund: seeme, mis ei idane, kuigi kõik on paras. Miski hoiab teda seestpoolt tagasi, kuni see miski muutub.", source: "Botaanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Külm paneb lindude aidaukse lukku.", source: "Eesti vanasõna", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Talv ajab karu pesasse.", source: "Eesti vanasõna", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Osastav kääne on lõpetamata asja kääne. Ma söön leiba tähendab, et leiba on veel alles.", source: "Eesti keel", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Karu talveuni ei ole päris uni. Süda lööb aeglasemalt, aga loom kuuleb, ja ta võib üles ärgata.", source: "Zooloogia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Osa siinseid metsataimi ei idane enne, kui nad on läbi teinud ühe külma talve. Soe kevad üksinda neid ei ava.", source: "Botaanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Konn talvitub järvemudas ja hingab läbi naha. Pinnale ta enne ei tule, kui jää on läinud.", source: "Zooloogia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Külm ajab käed põue.", source: "Eesti vanasõna", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Rabamänd võib olla sada aastat vana ja ulatuda vaevu õlani. Puu ei ole noor, vaid kinni hoitud.", source: "Botaanika", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Kannatama ja kandma on eesti keeles sama tüvi. Kannatlikkus tähendab siin kandmist, mitte vaikimist.", source: "Etümoloogia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Talvel jää all liigub kala aeglaselt ja sööb vähe. Ta elab läbi terve pimeda aja sellest, mis suvel korjatud.", source: "Zooloogia", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Sügisel näed orast küll, aga vili ei ole veel salves.", source: "Eesti vanasõna", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Aeg annab arutust.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Aeg küpsetab asju.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Aegamööda saab härg jänesele järele.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Kaua tehakse kaunikene, pea tehtud pilla-palla.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Olgu päev pikem kui pikk, läheb ta ometigi õhtule.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Parem aasta oodata kui kaks kahetseda.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Aeg aitab konna mättäle ja kehva kannikale.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ülemiste vanake küsib igal aastal, kas Tallinn on juba valmis. Vastata tuleb, et ei ole, sest valmis linna ta uputaks.", source: "Eesti rahvajutt", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Tamm hakkab tõrusid kandma alles neljakümne aasta paiku. Enne seda ta ainult kasvab.", source: "Botaanika", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Läänemeri on noor. Kümme tuhat aastat tagasi oli siin jääpaisjärv, ja soolane meri on ta olnud alles pool sellest ajast.", source: "Geoloogia", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Loopealse kadakas kasvab õhukesel mullal nii pikkamisi, et jämedad tüved on tihti vanemad kui neid ümbritsev mets.", source: "Botaanika", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Küll pikk päev jõuab õhtule.", source: "Eesti vanasõna", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Hommik on õhtust targem.", source: "Eesti vanasõna", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Vares vara sadu vaagub, õhtu hilja head ilma.", source: "Eesti vanasõna", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Ega töö jänes ole, et eest ära jookseb.", source: "Eesti vanasõna", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Pime kana leiab ka tera.", source: "Eesti vanasõna", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Öökull leiab hiire lume alt kuulmise järgi ja istub enne allalaskumist täiesti liikumata. Jahi pikem osa on paigalseis.", source: "Linnuteadus", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Kõpu tuletorn Hiiumaal on põlenud ligi viissada aastat. Ta ehitati selleks, et madalikku vaadataks ka öösel.", source: "Ajalugu", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Toonekurg seisab pesal ühel jalal tundide viisi. Teine jalg on sel ajal sulgede all soojas.", source: "Linnuteadus", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Metsavahi töö ei olnud puid raiuda, vaid teada, mis metsas parajasti toimub.", source: "Metsandus", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Inimsilm märkab hämaras liikumist kõige paremini silmanurgast. Otse vaadates kaob see ära.", source: "Füsioloogia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Tartus on ilma üles kirjutatud üle saja viiekümne aasta järjest. Iga päev on üks rida, ka siis, kui midagi ei juhtunud.", source: "Meteoroloogia", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Kalur vaatab kajakaid. Kus linnud kobaras keerlevad, seal on kala; kala ise ei ole näha, lindu saab vaadata.", source: "Kalandus", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Karjapoisi töö oli terve päev vaadata. Ta ei ajanud loomi, vaid hoolitses selle eest, et nad vilja ei läheks.", source: "Rahvakombed", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: - Renewal
        Passage(text: "Kase, lepa ja haava känd ajab pärast raiet uued võsud. Puu ei lõppenud, vaid algas sealtsamast otsast uuesti.", source: "Metsandus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Ädal on heinamaa teine kasv, mis tuleb pärast niitmist. Ta on lühem ja pehmem kui esimene.", source: "Põllumajandus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Raiesmikule tuleb esimesena vaarikas ja pajuvõsa. Alles nende varjus hakkab kasvama kuusk.", source: "Metsandus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Lõpeb üks töö, algab teine töö.", source: "Eesti vanasõna", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Sisalik jätab saba vaenlasele ja kasvatab uue. Uus saba on lühem ja ilma luudeta.", source: "Zooloogia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Vikatit tuli luisata iga poole tunni tagant. Niitmine oli pooleks teritamine.", source: "Rahvakombed", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Kanarbikunõmme hoiti noorena niitmise ja põletamisega. Pärast lühikeseks võtmist kasvab kanarbik tihedamalt.", source: "Ökoloogia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Korvivitsad lõigati pajult igal talvel. Sama põõsas andis materjali aastakümneid ega saanud sellest otsa.", source: "Käsitöö", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Kevadel puuritud kask jookseb mahla umbes nädala. Auk kasvab ise kinni ja puu kasvab edasi.", source: "Rahvakombed", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Karjamaa rohi kasvab uuesti just sellepärast, et teda süüakse. Söömata jäänud karjamaa läheb võssa.", source: "Ökoloogia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Uudis ja uudsevili tulevad ühest sõnast uus. Uudsevili on selle aasta esimene leib, ja seda söödi eraldi.", source: "Etümoloogia", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Vana paju lõigati talvel ladvast maha ja ta ajas kevadel uue võra. Sama puud sai nõnda lõigata kümneid kordi.", source: "Metsandus", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Kevad kutsub adrad põllule ja linnud laulule.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ega talv taevasse jää.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Kurg toob kevadel uued saapad.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Kured lähvad, kurjad ilmad. Haned lähvad, hallad maas. Luiged lähvad, lumi taga.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Lõoke toob lõunasooja, pääsuke päevasooja, ööbik öösooja.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Suvi kogub, talv sööb.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Vanad eesti kuunimed käivad töö järgi: künnikuu, lehekuu, heinakuu, lõikuskuu. Kuu nimi ütleb, mida siis tehakse.", source: "Rahvakalender", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Vastlapäeval lasti mäest liugu ja usuti, et mida pikem sõit, seda pikemad linad.", source: "Rahvakalender", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Jaaniöö on aasta lühim öö. Põhja-Eestis ei lähe taevas siis üldse päris pimedaks.", source: "Astronoomia", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Ööbik lõpetab laulmise jaanipäeva paiku. Ta laulab ainult seni, kuni pojad on koorunud.", source: "Linnuteadus", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Kase kollane värv on lehes kogu suve olemas. Ta paistab välja alles siis, kui roheline laguneb.", source: "Botaanika", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Tõnisepäeval murtakse talve selg.", source: "Eesti vanasõna", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Aeg parandab haavad, aga jätab armid.", source: "Eesti vanasõna", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Eesti keeles on arm kaks eri sõna: üks tähendab armastust, teine haavajälge. Kirjapilt on neil üks ja seesama.", source: "Eesti keel", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Puu ei saa haavast lahti, ta kasvab talle ümber. Oksakoht jääb tüvesse sisse ja on näha ka valmis lauas.", source: "Puiduteadus", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Murtud luu kasvab kokku nii, et paranenud koht on tükk aega tugevam kui luu tema ümber.", source: "Arstiteadus", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Sammal katab vana kännu kümne aastaga ja teeb temast mulla. Metsas ei jää lõikekoht lahti.", source: "Ökoloogia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Saun oli koht, kus sünnitati, pesti ja ravitseti. Haigust aeti välja leili ja vihtlemisega.", source: "Rahvakombed", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Vana Võromaa suitsusaun on siiani kasutusel ja kantud UNESCO nimistusse. Leil tehakse ilma korstnata.", source: "Rahvakombed", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Nahk uueneb alt üles. Kiht, mida sa katsud, on juba surnud, ja ta vahetatakse mõne nädalaga välja.", source: "Füsioloogia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Vikerkaar on alati terve ring. Maa peal seistes on näha ainult ülemine pool.", source: "Füüsika", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Katkine savinõu parandati vanasti puuritud aukude ja traadiga. Nõu jäi terveks, aga õmblus jäi näha.", source: "Arheoloogia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Rabavees ei lagune puu ega nahk. Turbast on välja tulnud tuhandeaastaseid esemeid, mis on peaaegu puutumata.", source: "Arheoloogia", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ammepuu on pehkinud tüvi, mille peal kasvavad noored kuused. Langenud puu ei ole kadu, vaid järgmine kasvukoht.", source: "Metsandus", theme: .renewal, subtheme: .madeWhole),

        // MARK: - Light
        Passage(text: "Faehlmanni muistendis annab Hämarik loojuva päikese Koidu kätte. Suve lühimatel öödel puutuvad nende käed kokku.", source: "F. R. Faehlmann, Koit ja Hämarik, 1840", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Neid ei lastud abielluda, vaid nad jäid igaveseks kihlatuiks. Kord aastas on nad neli nädalat koos.", source: "F. R. Faehlmann, Koit ja Hämarik, 1840", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pime õues, piits peos; koit õues, kott seljas; valge õues, vagu taga.", source: "Eesti vanasõna", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ööbik laulab öölaulu, kuldnokk laulab koidulaulu, lõoke laulab lõunalaulu.", source: "Eesti vanasõna", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Pääsuke päeva alustab, ööbik lõpetab.", source: "Eesti vanasõna", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Kukk talupoja kell, päike peremehe kubjas, lõuna saksa ärkamise aeg.", source: "Eesti vanasõna", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Ehal käimine oli noormehe õhtune minek tüdruku juurde. Ehatund oli selleks paras aeg, sest oli juba küllalt hämar.", source: "Rahvakombed", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Suve keskel ei lasku päike siin kuigi sügavale silmapiiri alla. Taevas jääb terve öö hämaraks, aga mitte mustaks.", source: "Astronoomia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Detsembri lõpus tõuseb päike Tallinnas üheksa paiku ja loojub enne nelja. Päev on kuus tundi pikk.", source: "Astronoomia", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Koidueelne tund on ööst kõige külmem, sest maa on kogu öö oma soojust ära andnud ja päike ei ole veel tulnud.", source: "Ilmateadus", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Kaste tekib kõige rohkem selge taeva ja tuulevaikse öö järel. Märg hommikurohi on eelmise öö vaikuse märk.", source: "Ilmateadus", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Õhtu vara õhtule, hommiku vara teele.", source: "Eesti vanasõna", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Võilill sulgeb õie õhtul ja pilvise ilmaga. Ta avaneb valguse, mitte kellaaja järgi.", source: "Botaanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Päevalille noor nupp pöördub päeva jooksul päikese järgi. Õitsele puhkenud õis jääb hommiku poole seisma.", source: "Botaanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Silm ei saa täis nägemisest, kõrv kuulmisest.", source: "Eesti vanasõna", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Kuidas karjane, nõnda kari; kuidas valgus, nõnda vari.", source: "Eesti vanasõna", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Silm kuningas, käsi tegija.", source: "Eesti vanasõna", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Peotäis näha on enam kui sületäis kuulda.", source: "Eesti vanasõna", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Männi roheline sammet, üksik metsatee: pedak heleroheline, kask kuldkollane.", source: "Juhan Liiv, Sügise", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Vastsadanud lumi näitab ära terve öö. Metsas loetakse jälgi valge maa pealt, mitte pimedas.", source: "Jahindus", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Sammal kasvab tüvel seal, kus on niiskem ja varjulisem. Metsas on see enamasti, aga mitte alati, põhjakülg.", source: "Botaanika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Vikerkaart näeb ainult siis, kui päike on selja taga ja vihm ees. Ta seisab alati vastu valgust.", source: "Füüsika", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Hämaras kaovad esimesena värvid, sest värvi tundvad rakud vajavad rohkem valgust kui need, mis näevad heledust.", source: "Füsioloogia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Läänemere vesi on pruunikas, sest sood ja jõed toovad sisse huumust. Vee värv ütleb, kust ta on tulnud.", source: "Merebioloogia", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Ükski öö ei ole ilma täheta.", source: "Eesti vanasõna", theme: .light, subtheme: .lightItself),
        Passage(text: "Valgus naerab pimeduse tööd.", source: "Eesti vanasõna", theme: .light, subtheme: .lightItself),
        Passage(text: "Sina vanaks, mina nooreks, kuu kullakarvaline!", source: "Eesti vanasõna", theme: .light, subtheme: .lightItself),
        Passage(text: "Virmalised on päikeselt tulnud osakesed, mis põrkuvad õhu vastu saja kilomeetri kõrgusel. Neid näeb mõnel selgel talveööl.", source: "Astronoomia", theme: .light, subtheme: .lightItself),
        Passage(text: "Küünal annab valgust umbes ühe kandela. Ühiku nimi on ladina keeles lihtsalt küünal.", source: "Füüsika", theme: .light, subtheme: .lightItself),
        Passage(text: "Jaaniussi valgus on külm. Peaaegu kogu energia läheb valguseks ja peaaegu midagi ei lähe soojuseks.", source: "Putukateadus", theme: .light, subtheme: .lightItself),
        Passage(text: "Tuli hoiti talus alati alles. Hommikul otsiti eilsed söed tuha alt üles ja puhuti uuesti leegile.", source: "Rahvakombed", theme: .light, subtheme: .lightItself),
        Passage(text: "Päikesevalgus jõuab siia kaheksa minutiga. See, mida sa praegu näed, lahkus enne, kui sa vaatama hakkasid.", source: "Astronoomia", theme: .light, subtheme: .lightItself),
        Passage(text: "Lumi ei ole valge sellepärast, et jää oleks valge. Kristallid on läbipaistvad ja peegeldavad valgust igasse suunda.", source: "Füüsika", theme: .light, subtheme: .lightItself),
        Passage(text: "Kuul ei ole oma valgust. Täiskuu paistab umbes nelisada tuhat korda nõrgemalt kui päike.", source: "Astronoomia", theme: .light, subtheme: .lightItself),
        Passage(text: "Detsembris paistab siin päike kokku vaid mõnikümmend tundi terve kuu peale. Ülejäänu on pilv.", source: "Ilmateadus", theme: .light, subtheme: .lightItself),
        Passage(text: "Küünlapäev on veebruari alguses ja tema nimi tuleb küünaldest. Sealtpeale on päev nii pikk, et õhtul enam tuld vaja ei ole.", source: "Rahvakalender", theme: .light, subtheme: .lightItself),

        // MARK: - Pattern
        Passage(text: "Üheksa korda mõtelda, üks kord teha.", source: "Eesti vanasõna", theme: .pattern, subtheme: .counted),
        Passage(text: "Üheksa mehe jõud ja ühe mehe nõu on üks.", source: "Eesti vanasõna", theme: .pattern, subtheme: .counted),
        Passage(text: "Ühe muna sisse ei mahu kaks rebu.", source: "Eesti vanasõna", theme: .pattern, subtheme: .counted),
        Passage(text: "Eesti keeles on neliteist käänet. Kuus neist ütlevad ainuüksi seda, kus miski on või kuhu ta läheb.", source: "Eesti keel", theme: .pattern, subtheme: .counted),
        Passage(text: "Aastarõngad on heal aastal laiemad ja põua-aastal kitsamad. Puu on üles kirjutanud iga suve, mille ta on üle elanud.", source: "Dendrokronoloogia", theme: .pattern, subtheme: .counted),
        Passage(text: "Männi oksad kasvavad korruste kaupa, üks korrus aastas. Noore puu vanust saab lugeda korruseid mööda.", source: "Metsandus", theme: .pattern, subtheme: .counted),
        Passage(text: "Regivärsi rida on kaheksa silpi. See on nii lühike, et sama asi tuleb kohe uuesti öelda, teiste sõnadega.", source: "Regilaul", theme: .pattern, subtheme: .counted),
        Passage(text: "Vanad mõõdud käisid keha järgi. Küünar on küünarnukist sõrmeotsani, vaks pöidlast keskmise sõrme otsani.", source: "Mõõdulugu", theme: .pattern, subtheme: .counted),
        Passage(text: "Vakamaa oli nii suur maatükk, mille külvamiseks kulus üks vakk seemet. Põldu mõõdeti seemnega, mitte sammudega.", source: "Mõõdulugu", theme: .pattern, subtheme: .counted),
        Passage(text: "Kuusekäbi soomused seisavad kahes vastassuunalises spiraalis, ja mõlema spiraali arv on Fibonacci jada liige.", source: "Botaanika", theme: .pattern, subtheme: .counted),
        Passage(text: "Nädala neli esimest päeva on eesti keeles lihtsalt loetud: esmaspäev, teisipäev, kolmapäev, neljapäev. Alles siis tulevad nimed.", source: "Eesti keel", theme: .pattern, subtheme: .counted),
        Passage(text: "Eesti keeles on kolm välteastet. Koli, kooli ja kooli on kolm eri sõna, mis erinevad üksnes kestuselt.", source: "Eesti keel", theme: .pattern, subtheme: .counted),
        Passage(text: "Seto leelot lauldakse mitmel häälel. Sõnolinõ alustab üksi, koor tuleb järele ja killõ tõuseb kõige kõrgemale.", source: "Rahvamuusika", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Regilaulus alustab eeslaulja rea ja koor kordab selle üle. Keegi ei laula päris üksi ega kõik korraga.", source: "Regilaul", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Rookatuse pilliroog seoti vihkudeks ja vihud laoti üksteise peale nii, et vesi jookseb pealt alla ega pääse sisse.", source: "Ehituslugu", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Saaremaa kiviaiad on laotud ilma lubjata. Kivid hoiavad üksteist ainult raskuse ja kuju abil.", source: "Ehituslugu", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Kindakiri loetakse silmade kaupa. Muster ei ole joonistatud, vaid arvutatud, ja iga muutus on täpselt üks silm.", source: "Käsitöö", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Vöökirjas oli igal kihelkonnal oma muster. Kandja päritolu oli mustri järgi näha ka siis, kui ta ise vaikis.", source: "Rahvakunst", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Paekivi murtakse plaatidena, sest ta on ladestunud kihiti. Müüri jaoks pole vaja teda lõigata, vaid õigest kohast lahti võtta.", source: "Geoloogia", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Kalevipoja värsimõõt ei ole riim, vaid alliteratsioon: rida seotakse sõnadega, mis algavad sama häälikuga.", source: "Kirjandusteadus", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Roigasaed pandi kokku ilma naelteta: teivas, roigas ja vits. Aed püsis nii kaua, kui vitsad pidasid.", source: "Käsitöö", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Puulaeva plangud tihiti takuga ja tõrvaga. Laeva ei tehtud tihedaks üks kord, vaid iga aasta uuesti.", source: "Laevaehitus", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Palkmaja nurk raiuti nii, et palgid haakusid üksteise sisse. Nurgaseotis hoidis maja koos ilma ühegi naelata.", source: "Ehituslugu", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ühes vaadis ei või kahesugust õlut olla.", source: "Eesti vanasõna", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Nii mitu meest, nii mitu meelt.", source: "Eesti vanasõna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Igal nõmmel isenimi, igal marjal isemagu.", source: "Eesti vanasõna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Igal talul oma taar, igal perel oma viis.", source: "Eesti vanasõna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kohus on kolm päeva vanem kui maailm.", source: "Eesti vanasõna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Heal lapsel mitu nime.", source: "Eesti vanasõna", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Kohanimede lõpud on siin maastik ise: mäe, saare, oja, soo, nurme. Nimi ütleb, mille kõrval elatakse.", source: "Kohanimeteadus", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Eesti taimenimed on tihti kaks sõna, mis ütlevad, kus taim kasvab ja mille moodi ta on: nurmenukk, karukell, maikelluke.", source: "Eesti keel", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Regilaulus öeldakse iga mõte kaks korda, teist korda teiste sõnadega. Seda kordamist nimetatakse parallelismiks.", source: "Regilaul", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Eesti murded jagunevad põhja- ja lõunaeesti rühma. Võru ja seto keelel on olemas oma kirjaviis.", source: "Keeleteadus", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Eestis loetakse üle kahe tuhande saare ja laiu. Suurem osa neist on väiksemad kui üks hektar.", source: "Geograafia", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Lõuna tähendab eesti keeles nii ilmakaart kui ka keskpäeva. Põhi tähendab nii ilmakaart kui ka millegi kõige alumist osa.", source: "Eesti keel", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Vana rahvakalender ei loe kuupäevi, vaid nimesid: jüripäev, jaanipäev, mihklipäev, mardipäev. Aasta on jaotatud inimeste vahel.", source: "Rahvakalender", theme: .pattern, subtheme: .orderNamed),

        // MARK: - Ground
        Passage(text: "Loopealne on õhuke muld paeplaadi peal, kohati vaid mõne sentimeetri paksune. Sellel kasvab rohkem liike kui heal põllul.", source: "Ökoloogia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Paekivi on Eesti rahvuskivi. Ta on tehtud mereloomade kodadest, mis vajusid põhja üle nelja saja miljoni aasta tagasi.", source: "Geoloogia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Sõnnik põllumehe kuld.", source: "Eesti vanasõna", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Põld põllumehe piimalehm.", source: "Eesti vanasõna", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Leib vanem kui meie.", source: "Eesti vanasõna", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Turvas ei ole muld, vaid taimed, mis ei ole ära lagunenud. Raba on iseenda ajalugu, mis on alles jäänud.", source: "Ökoloogia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Suur osa siinsest pinnasest on jää toodud. Liiv, kruus ja rändrahnud pärinevad Soome ja Rootsi kaljudelt.", source: "Geoloogia", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Männimetsa all on ülemine mullakiht valge nagu tuhk, sest vihm on värvi temast alla pesnud.", source: "Mullateadus", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Ühes peotäies metsamullas on rohkem elusolendeid kui inimesi kogu maailmas.", source: "Mullateadus", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Vihmauss veab lehed maa alla ja teeb neist mulla. Ilma temata jääks metsa alla paks lagunemata kiht.", source: "Mullateadus", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Siinsetelt põldudelt on kive korjatud nii kaua, et neist on laotud aiad. Kivihunnik põllu servas on põlvkondade töö.", source: "Põllumajandus", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Muld tekib umbes sentimeetri jagu saja aasta jooksul. See, mida ader läbi lõikab, on tuhandete aastate töö.", source: "Mullateadus", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Oma maa maasikas, võõras maa mustikas.", source: "Eesti vanasõna", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Igal pool hea, kodus kõige parem.", source: "Eesti vanasõna", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Parem kämblalaius kodu kui vakamaa võõral maal.", source: "Eesti vanasõna", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Oma kodu koeradki tunnevad.", source: "Eesti vanasõna", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kus saun, seal eestlased.", source: "Eesti vanasõna", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Mu isamaa on minu arm.", source: "Lydia Koidula (1843–1886)", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Sind surmani küll tahan ma kalliks pidada.", source: "Lydia Koidula, Sind surmani", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kihelkond oli see ring, mille sees inimene tundis kõiki. Rahvariided ütlesid vaatajale, kust keegi pärit on.", source: "Rahvakultuur", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Kodumurre püsib kõnes kaua pärast ärakolimist. Üksikud häälikud jäävad alles ka siis, kui sõnad on juba vahetunud.", source: "Keeleteadus", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Emajõgi tähendab ema jõge. Tartu seisab tema kaldal, ja jõgi on linnast tükk maad vanem.", source: "Kohanimeteadus", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Hiis oli püha metsatukk, kust ei tohtinud oksagi murda. Mõned hiiepuud seisavad tänini seal, kus ümberringi on põld.", source: "Rahvausund", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ruhnu puukirik on vanim säilinud puitehitis Eestis. Ta ehitati XVII sajandil ja ta seisab endiselt oma saarel.", source: "Ehituslugu", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Põllu nägu näitab põllumehe tegu.", source: "Eesti vanasõna", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kapsad ei kasva kastmata.", source: "Eesti vanasõna", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kosuta põldu, siis annab leiba.", source: "Eesti vanasõna", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Rehielamu on vana eesti elumaja, kus pere elas sama katuse all vilja kuivatusruumiga. Reheahi soojendas mõlemat.", source: "Ehituslugu", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kiviaia ehitamine ei saanud kunagi otsa. Kevadel tõstis külm uued kivid pinnale ja neid tuli jälle korjata.", source: "Põllumajandus", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Puisniit on niidetud metsaalune, kus puid on jäetud harvalt seisma. Ilma niitmata kaob ta paarikümne aastaga.", source: "Ökoloogia", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Mahajäetud talukoha leiab sireli järgi. Maja on kadunud, aga õue ääres istutatud põõsas õitseb ikka veel.", source: "Aiandus", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ait ehitati eluruumidest eraldi, sest seal hoiti vili ja pidurõivad. Tuli ei tohtinud võtta mõlemat korraga.", source: "Ehituslugu", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kaev tuli aeg-ajalt tühjaks ammutada ja põhi puhtaks teha. Hoitud kaev annab selget vett, hooletusse jäetu kasvab kinni.", source: "Talutöö", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kolmeväljasüsteemis jäeti kolmandik maast igal aastal kesaks. Puhkav põld oli osa tööst, mitte selle katkestus.", source: "Põllumajandus", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Lahemaa sai rahvuspargiks 1971. aastal. Ta loodi selleks, et rannakülad ja nende mets jääksid alles.", source: "Ajalugu", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Kirikuaia pärnad istutati sajandeid tagasi ja neid pügatakse siiani. Pärna võib paarikümne aasta tagant lõigata ja ta ajab uue võra.", source: "Aiandus", theme: .ground, subtheme: .aKeptPlace),

        // MARK: - Travel
        Passage(text: "Võilille seeme ripub varju all, mis on tehtud karvadest. Ta ei lenda, vaid vajub aeglaselt, ja tuul kannab teda vahepeal edasi.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Takjas haakub konksudega koera karva külge ja tuleb maha alles kodus. Nõnda on ta läinud üle maa mööda koerte selga.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Vaarikaseeme läheb linnust läbi ja idaneb pärast seda paremini. Lind on korraga nii vedaja kui väetaja.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Jõhvikas ujub. Rabavesi kannab marja uude kohta ja koor on nii tihe, et seeme jõuab terve pärale.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ehalkivi Letipeal on jää siia toonud. Ta kaalub üle kahe tuhande tonni ja on sõitnud sadu kilomeetreid.", source: "Geoloogia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kuuseseemnel on tiib, mis paneb ta langedes keerlema. Keerlemine hoiab teda õhus kauem ja tuul jõuab ta kaugemale viia.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Kobras veab oksi vee peal kilomeetrite kaugusele. Pajuoks, mis jääb mudasse, ajab juure ja saab uueks puuks.", source: "Zooloogia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Rukkilill tuli siia koos rukkiseemnega. Ta on rännumees, kes jäi püsima ja keda enam kuidagi tulnukaks ei peeta.", source: "Taimeteadus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Mõne rannataime seeme ujub kuude kaupa ja idaneb alles siis, kui laine ta liivale jätab.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Murumuna puistab vajutades tolmu välja. Iga tolmutera on eos, mis võib tuulega minna kilomeetreid kaugele.", source: "Seeneteadus", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ka jää veab. Kevadise suurvee ajal läheb jäätükiga kaasa pilliroo juurikas, mis jääb maha juba teisel kaldal.", source: "Ökoloogia", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Lepaseeme on nii kerge, et ta ujub. Kevadine üleujutus viib terve lepiku järglased uude kohta.", source: "Botaanika", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Tasa sõuad, kaugele jõuad.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kus õhtu, seal öömaja.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Vana tee, vana sõber.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Tasa ja targu, madalasti ja märgu.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Iga sammu vaata ette, enne kui astud.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Veerevale kivile ei kasva sammalt.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Pikem jalg astub pikemad sammud.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Liikuv vesi läheb selgemaks, seisev vesi pahemaks.", source: "Eesti vanasõna", theme: .travel, subtheme: .theRoad),
        Passage(text: "Ta lendab mesipuu poole.", source: "Juhan Liiv, Ta lendab mesipuu poole", theme: .travel, subtheme: .theRoad),
        Passage(text: "Talvel avatakse Väinamerel ametlikud jääteed. Saaremaale ja Hiiumaale on sõidetud üle jää nii kaua, kui keegi mäletab.", source: "Geograafia", theme: .travel, subtheme: .theRoad),
        Passage(text: "Jääteel ei tohi kinnitada turvavööd ja ei tohi sõita kiirusega kolmekümne ja nelikümne kilomeetri vahel. See kiirus paneb jää lainetama.", source: "Liikluskord", theme: .travel, subtheme: .theRoad),
        Passage(text: "Vanadel maanteedel olid postijaamad üksteisest ühe hobusepäeva kaugusel. Sõitja jäi samaks, hobune vahetus.", source: "Ajalugu", theme: .travel, subtheme: .theRoad),
        Passage(text: "Kes kaugel käib, palju näeb.", source: "Eesti vanasõna", theme: .travel, subtheme: .farOff),
        Passage(text: "Kaugelt kägu kuulus.", source: "Eesti vanasõna", theme: .travel, subtheme: .farOff),
        Passage(text: "Hulgusel kodu kõikjal.", source: "Eesti vanasõna", theme: .travel, subtheme: .farOff),
        Passage(text: "Meretagune tuleb, ei tule maa-alune.", source: "Eesti vanasõna", theme: .travel, subtheme: .farOff),
        Passage(text: "Suitsupääsuke, Eesti rahvuslind, lendab talveks Aafrikasse ja tuleb kevadel tagasi samasse lauta.", source: "Linnuteadus", theme: .travel, subtheme: .farOff),
        Passage(text: "Rändluik lendab siit üle nii kõrgelt, et teda ei näe. Hääl jõuab kohale enne, kui silm ta leiab.", source: "Linnuteadus", theme: .travel, subtheme: .farOff),
        Passage(text: "Põhjarannikul võeti Nõukogude ajal vastu Soome telesaateid. Terve põlvkond õppis nõnda ära keele, mida koolis ei antud.", source: "Ajalugu", theme: .travel, subtheme: .farOff),
        Passage(text: "Ruhnu saar jääb Läti rannikule lähemale kui Eesti mandrile.", source: "Geograafia", theme: .travel, subtheme: .farOff),
        Passage(text: "Läänemeri on nii madal, et keskmine sügavus jääb alla kuuekümne meetri. Ta on suur ainult pealtvaates.", source: "Geograafia", theme: .travel, subtheme: .farOff),
        Passage(text: "Vaindloo laid on Eesti põhjapoolseim maapunkt. Seal ei ela kedagi peale lindude ja ühe tuletorni.", source: "Geograafia", theme: .travel, subtheme: .farOff),
        Passage(text: "Eesti keelt kõneleb umbes miljon inimest, ja osa neist on terve elu elanud väljaspool Eestit.", source: "Keeleteadus", theme: .travel, subtheme: .farOff),
        Passage(text: "Maailm on eesti keeles kokku pandud sõnadest maa ja ilm. Terve ilmaruum on siin maa pluss see, mis tema kohal liigub.", source: "Etümoloogia", theme: .travel, subtheme: .farOff),

        // MARK: - Meeting
        Passage(text: "Koht, kohtuma ja kohus on eesti keeles ühest tüvest. Kohtumine tähendab siin sõna-sõnalt ühte paika saamist.", source: "Etümoloogia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Tere tulemast tähendab sõna-sõnalt tere sinu tulemisele. Tervitatakse mitte inimest, vaid tema saabumist.", source: "Eesti keel", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kiigemägi oli küla kokkusaamise koht. Suveõhtutel mindi kiige juurde laulma, ja kiik ehitati ühiselt.", source: "Rahvakombed", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Jaanituli tehti kõrgele kohale, et teda kaugelt näeks. Naabrid vaatasid, kas teine tuli on juba üleval.", source: "Rahvakombed", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Esimene üldlaulupidu peeti 1869. aastal Tartus. Sinna tuli kokku üle kaheksasaja laulja ja mitu tuhat kuulajat.", source: "Ajalugu", theme: .meeting, subtheme: .theMoment),
        Passage(text: "23. augustil 1989 seisis Tallinnast Vilniuseni ligi kaks miljonit inimest käest kinni. Kett oli üle kuuesaja kilomeetri pikk.", source: "Ajalugu", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Munad veerevad pesas üksteise vastu, miks siis mitte inimesed?", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kus palju koos, sinna kogub veel juurde.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kaks jõge hoiavad kokkusaamise järel oma värvi veel tükk aega kõrvuti. Segunemine ei juhtu selle koha peal.", source: "Geograafia", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kaks kella ühel seinal jäävad aja jooksul ühte takti. Nad annavad võnke üksteisele üle läbi puidu.", source: "Füüsika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Ristteed olid rahvausundis piiripaigad, kus kaks ilma teineteist puudutavad. Sinna viidi ja sealt ei toodud.", source: "Rahvausund", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kaks veepiiska, mis teineteist puudutavad, saavad üheks nii kiiresti, et keegi ei näe, kumb oli kumb.", source: "Füüsika", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Kaks silma ulatuvad kaugemale kui üks.", source: "Eesti vanasõna", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Neli silma näevad rohkem kui kaks.", source: "Eesti vanasõna", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Käsi peseb kätt ja kaks kätt pesevad palet.", source: "Eesti vanasõna", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ega üksi lauldes või elada.", source: "Eesti vanasõna", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Ega abi kännust ja kivist saa, vaid inimestest.", source: "Eesti vanasõna", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Rukis ei viljasta iseennast. Tolm peab tulema teiselt taimelt, ja selle toob kohale tuul.", source: "Botaanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Samblik ei ole üks olend, vaid kaks. Seen annab kuju ja vee, vetikas annab toidu, ja eraldi ei ela paekivil kumbki.", source: "Botaanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Männi juurte ümber on seeneniidistik, mis toob vett ja toitaineid. Puu maksab selle eest suhkruga.", source: "Botaanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Õis maksab magusaga selle eest, et keegi ta tolmu ära viiks. Kummalgi poolel ei ole teist varianti.", source: "Botaanika", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Tõmbesaag lõikab ainult siis, kui teine mees tõmbab. Üks inimene ei saa temaga midagi teha.", source: "Käsitöö", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Talgud: naabrid tulid kokku tööle, mida üks pere ei jõudnud. Palka ei makstud, vaid söödeti, ja järgmine kord mindi ise.", source: "Rahvakombed", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Purjelaeval on tarvis nii tuult kui kiilu. Tuul üksinda paneks ta külili, kiil üksinda ei liigutaks teda kohalt.", source: "Meresõit", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Tere tuleb sõnast terve. Teretades öeldakse teisele, et ta oleks terve.", source: "Etümoloogia", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Tööd tegevale inimesele öeldi Jõudu, ja vastuseks tuli Jõudu tarvis. Tervitus käis töö kohta, mitte inimese kohta.", source: "Rahvakombed", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Söögilauas istujale öeldi Jätku leiba. Vastati Jätku tarvis, ja sellega oli tulija juba peaaegu lauas.", source: "Rahvakombed", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Külaline on kaks korda armas: kui tuleb ja kui läheb.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Peremehe hea sõna kutsub külalisi sisse.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Ega küsija suu peale ei lööda.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kuule palju, räägi pisut.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kaks kõnelevad, kolmas olgu vait.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Andja käsi ei alane.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Parem suuga paluda kui käega võtta.", source: "Eesti vanasõna", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Kuulaja peab mõtlema, mitte kõneleja.", source: "A. H. Tammsaare, Tõde ja õigus", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Teietamiselt sinatamisele minnakse üle korraga, ja selle kohta on oma sõna: sinasõprus. Ta algab ühest lausest.", source: "Eesti keel", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: - Kinship
        Passage(text: "Käbi ei kuku kännust kaugele.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kuidas känd, nõnda käbi.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kuidas tamm, nõnda tõru.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Ega lapsed kännust kasva ega puust pudene.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kask ei kasva kuuse kännu peale.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Puu ei kasva oksata ega liha kondita.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Veri paksem kui vesi.", source: "Eesti vanasõna", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Maasikas ajab välja väädi ja uus taim jääb emataimega ühendusse seni, kuni ta on ise juurdunud.", source: "Botaanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kaks tihedasti koos kasvavat puud võivad kokku kasvada. Koor kaob nende vahelt ära ja mahlateed lähevad ühte.", source: "Botaanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Haavik on tihti üksainus taim. Puud on ühe juurestiku võsud ja lähevad sügisel kollaseks kõik ühel päeval.", source: "Botaanika", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Pookimine: võõras oks pannakse teise puu tüve sisse ja nad kasvavad kokku. Ülalt tuleb sort, alt tuleb juur.", source: "Aiandus", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Kuuse juured on madalad ja lähevad naabri omadega läbisegi. Tuulega hoiavad puud üksteist püsti, üksik kuusk murdub kergemini.", source: "Metsandus", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Eesti keeles on tema üks sõna nii mehe kui naise kohta. Keel ei ütle, kummast on jutt, ja seda tuleb küsida.", source: "Eesti keel", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Nii ligidalt sugulane kui viies vesi taari peal.", source: "Eesti vanasõna", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Armul ei ole põhja.", source: "Eesti vanasõna", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ema arm igaks ajaks.", source: "Eesti vanasõna", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Õde sooja saunaleili, vend on vilu põhjatuuli.", source: "Eesti vanasõna", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Hõim tähendab eesti keeles nii suguvõsa kui rahvast. Hõimurahvad on need, kelle keel on meie keele sugulane.", source: "Eesti keel", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Kas siis selle maa keel laulu tuules ei või taevani tõustes üles igavikku omale otsida?", source: "Kristjan Jaak Peterson (1801–1822)", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Emakeel on sõna-sõnalt ema keel. Emakeelepäeva peetakse 14. märtsil, Kristjan Jaak Petersoni sünnipäeval.", source: "Eesti keel", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Kaasaütlev kääne lõpuga ga tähendab ainult ühte asja: koos kellegagi. Kaaslane ja kaasa on samast tüvest.", source: "Eesti keel", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Suguvõsa on kokku pandud sõnadest sugu ja võsa. Pere on selle sõna sees metsaalune, mis kasvab ühest kohast mitmeks.", source: "Etümoloogia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Sõber on eesti keelde tulnud laensõnana ja tähendas algselt kaaslast ühises majapidamises.", source: "Etümoloogia", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Meelespea tähendab sõna-sõnalt hoia meeles. Nime sees on palve, mida lill ise öelda ei oska.", source: "Eesti keel", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Südamel ei ole akent sisse vaadata.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ei mina tea, mis sinu toa peal, ega sina, mis minu südames.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Parem üks vana sõber kui kaks uut.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Vana sõber nagu kuld, mis ei roosteta.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Õige sõber kaalub enam kui kuld.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Sõpra tuntakse häda-ajal.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Mida harvem näed, seda armsam oled.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kus haige, seal käsi; kus arm, seal silm.", source: "Eesti vanasõna", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kaim on inimene, kellel on sinuga sama nimi. Sõna ütleb, et nime jagamine on omaette side.", source: "Eesti keel", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ristivanemad võeti lapsele väljastpoolt peret. Nõnda sai laps omakseid, keda tal sünni järgi ei olnud.", source: "Rahvakombed", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kaks kannelt ühes toas: kui ühel keelt näpistada, hakkab teisel sama keel ise kaasa helisema.", source: "Akustika", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Kühmnokk-luik hoiab sama paarilist aastaid. Talve veedavad nad koos ja kevadel tulevad tagasi samale järvele.", source: "Linnuteadus", theme: .kinship, subtheme: .twoPeople),

        // MARK: - Peace
        Passage(text: "Kaja oskab iga keelt.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Kuidas metsa hõigatakse, nõnda mets vastu kostab.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Vaga vesi, sügav põhi.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Merel silmad, metsal kõrvad.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Rääkimine hõbe, vaikimine kuld.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Rääkimine kopik, vaitolemine kaks.", source: "Eesti vanasõna", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Tuulevaikus on meremeeste sõna. Ta ei tähenda vaikust, vaid tuule puudumist, ja siis kuuleb purjelaeva pealt kõike.", source: "Meresõit", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Videvik on omaette sõna päeva ja öö vahelise aja kohta. Videvikku peeti: tuld ei võetud ja tööd ei tehtud.", source: "Rahvakombed", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Värske lumi on täis õhuruume ja neelab heli. Pärast sadu on väljas vaiksem kui enne seda.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Külmal ööl paindub heli alumises õhukihis maa poole tagasi. Üle jäätunud järve on siis kuulda kõnet teiselt kaldalt.", source: "Akustika", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Raba on suvel üks vaiksemaid paiku: puid on hõredalt, tuul ei leia lehti, ja jalge all on sammal, mis ei krõbise.", source: "Ökoloogia", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Öökull lendab hääletult. Tema sulgede serv on kammikujuline ja lõhub õhukeerise enne, kui see jõuab heliks saada.", source: "Linnuteadus", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Rahuleping ütleb sama asja kaks korda. Leping tuleb sõnast leppima, mis tähendab teisega ära leppimist.", source: "Etümoloogia", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Vallakohus mõistis külas väiksemaid tülisid. Kohtunikud olid samast külast ja tundsid mõlemat poolt juba enne.", source: "Ajalugu", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Tartu rahu sõlmiti 1920. aasta veebruaris. See oli Eesti esimene leping, mille all seisis tema oma nimi.", source: "Ajalugu", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Kaubale löödi käsi, ja kokkulepe kehtis sellest hetkest. Kirjapandut ei olnud tarvis, sest käepigistus oli nähtud.", source: "Rahvakombed", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Aeg võidab viimaks vaenu.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Aeg jahutab tuska ja kustutab vihatuju.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Head sõnad jahutavad rohkem kui külm vesi.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Hea sõna sööb võõra väe.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Parem lahja rahu kui rasvane riid.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Parem lammas rahuga kui nuumhärg tüliga.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Rahu kasvatab, tüli kaotab.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Pööra sõna suus enne kolm korda ümber, kui välja ütled.", source: "Eesti vanasõna", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Õhtu paneb hooled ukse peale, mured musta parre peale, vaeva valge varva peale.", source: "Eesti vanasõna", theme: .peace, subtheme: .atEase),
        Passage(text: "Töö tehtud, hea hingata.", source: "Eesti vanasõna", theme: .peace, subtheme: .atEase),
        Passage(text: "Kui töö tehtud, magus puhata.", source: "Eesti vanasõna", theme: .peace, subtheme: .atEase),
        Passage(text: "Parem pingi all rahuga kui pingi peal rahuta.", source: "Eesti vanasõna", theme: .peace, subtheme: .atEase),
        Passage(text: "Kõht täis, meel hea; mis vaja, see varna otsas.", source: "Eesti vanasõna", theme: .peace, subtheme: .atEase),
        Passage(text: "Hingama ja hing on üks tüvi. Puhkamine on eesti keeles sõna otseses mõttes hinge tõmbamine.", source: "Etümoloogia", theme: .peace, subtheme: .atEase),
        Passage(text: "Saunapäev oli laupäev. Pärast leili enam tööle ei mindud, ja see õhtu kuulus ainult istumisele.", source: "Rahvakombed", theme: .peace, subtheme: .atEase),
        Passage(text: "Sauna sees ei kõneldud valjusti ega vaieldud. Vana kombe järgi oli see püha koht ja seal oldi tasa.", source: "Rahvakombed", theme: .peace, subtheme: .atEase),
        Passage(text: "Kass keerab magades saba ümber ja katab sellega ninaotsa. Nõnda hingab ta oma soojust endale tagasi.", source: "Zooloogia", theme: .peace, subtheme: .atEase),
        Passage(text: "Hobune magab enamasti seistes ja heidab pikali ainult siis, kui ta ennast kindlalt tunneb.", source: "Zooloogia", theme: .peace, subtheme: .atEase),
        Passage(text: "Kanad lähevad õrrele ise, kui hakkab hämarduma. Kutsuda ei ole vaja, ja hiljem nad ei tule.", source: "Zooloogia", theme: .peace, subtheme: .atEase),
        Passage(text: "Tuulevaikne järv annab teise kalda täpselt tagasi. Peegeldus kaob esimese iiliga ja tuleb ise tagasi.", source: "Füüsika", theme: .peace, subtheme: .atEase),
    ]
}
