import Foundation

/// The Belarusian passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let belarusian: [Passage] = [
        // MARK: - Beginnings
        Passage(text: "Праклёўванне: момант, калі зародак разрывае абалонку і выходзіць вонкі. Насеннем яно ўжо не будзе ніколі.", source: "Батаніка", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Гуканне вясны: вясну тут не чакаюць, а клічуць. Выходзяць на пагорак і спяваюць, пакуль яна не адгукнецца.", source: "Беларускі народны каляндар", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Зажынкі: першы сноп жніва жалі ўрачыста і неслі ў хату. Пакуль ён не зжаты, поле яшчэ некранутае.", source: "Этнаграфія", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Шостага жніўня 1517 года ў Празе Францыск Скарына выдаў Псалтыр — і на свеце з'явілася першая друкаваная кніга ва ўсходніх славян.", source: "Гісторыя кнігадрукавання", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Птушаня прабівае шкарлупіну яйцавым зубам — маленькім нарастам на дзюбе, які адпадае праз некалькі дзён пасля вылуплення.", source: "Арніталогія", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Бяроза гоніць сок раней, чым распусціцца хоць адна пупышка. Дрэва прачынаецца знутры, а не зверху.", source: "Батаніка", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Ледаход: рака ўскрываецца не паволі, а разам. Тое, што стаяла ўсю зіму, за адну ноч робіцца плытамі і рушыць.", source: "Гідралогія", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Пад першае бервяно новай хаты клалі жменю жыта і манету — каб у доме вялося ад самага пачатку.", source: "Этнаграфія", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Стары рой пакідае вулей разам з маткай і паловай сям'і. Дзверы за імі не зачыняюцца, але назад ніхто не ляціць.", source: "Пчалярства", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Дзеяслоў пачаць у беларускай мове ўжываюць і пра бохан: пачаць хлеб — гэта зрабіць першы надрэз, пасля якога цэлым ён ужо не будзе.", source: "Беларуская мова", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "На талаку не наймалі. Гаспадар абыходзіў суседзяў і клікаў, і работа пачыналася з таго, што нехта пастукаў у дзверы.", source: "Этнаграфія", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "Першы гром паводле павер'я будзіў зямлю. Да яго не капалі і не аралі: лічылася, што зямля яшчэ спіць.", source: "Народныя павер'і", theme: .beginnings, subtheme: .theFirstAct),

        Passage(text: "Зерне жыта важыць каля трыццаці міліграмаў. З аднаго куста, які з яго вырас, збіраюць жменю такіх жа.", source: "Земляробства", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Жолуд бярэцца ў жменю. Дуб з яго расце ўгору сто гадоў, а потым яшчэ дзвесце проста таўсцее.", source: "Дэндралогія", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Белавежская пушча — апошні вялікі кавалак раўніннага лесу, які калісьці стаяў праз усю Еўропу без перапынку.", source: "Лесаводства", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Торф нарастае прыкладна на міліметр за год. Пяціметровая тоўшча пад Прыпяццю — гэта пяць тысяч вёсен, складзеных адна на адну.", source: "Балотазнаўства", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Нёман пачынаецца ручаём, які пераступаюць, не заўважыўшы, а канчаецца портам на Балтыцы.", source: "Геаграфія", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "У адным граме бярозавага насення каля пяці тысяч крылатак. Ветру хапае аднаго дня, каб засеяць імі гары пяску.", source: "Батаніка", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Жменя ў беларускай мове — і мера, і колькасць: жменя жыта, жменя солі, жменя людзей на ўсю вёску.", source: "Беларуская мова", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Грыбніца пад мохам цягнецца гектарамі і жыве дзесяцігоддзямі. Наверх выходзяць толькі капелюшы, і толькі на тыдзень.", source: "Мікалогія", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Гектар квітнеючага ліпняку дае пчолам да тоны мёду, і ўсё гэта збіраецца па кроплі, якая менш за макава зерне.", source: "Пчалярства", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Мурашнік вышынёй з чалавека складзены з ігліцы, і кожную іглінку прынеслі паасобку, у зубах.", source: "Заалогія", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Адна каробачка маку трымае тысячы зярнят, а сама змяшчаецца пад пазногцем.", source: "Батаніка", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "Полацк запісаны ў летапісе пад 862 годам — раней за большасць гарадоў, якія цяпер за яго куды большыя.", source: "Гісторыя", theme: .beginnings, subtheme: .smallToLarge),

        Passage(text: "Першы блін сабаку.", source: "Беларуская прыказка", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Корань з насення заўсёды ідзе ўніз, а парастак угору, і перакуленае зерне гэтага не мяняе. Пра бок яны не пытаюцца.", source: "Батаніка", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Азімае жыта сеюць у жніўні, і які будзе ўраджай наступным летам, вырашаецца ў тыя тры-чатыры дні.", source: "Земляробства", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Дзяжу не мылі. Кавалак учарашняга цеста, што застаўся на сценках, вырашаў смак сённяшняга хлеба і хлеба праз год.", source: "Этнаграфія", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Першае гадавое кольца дрэва — самае вузкае і самае схаванае. Усе астатнія кладуцца вакол яго.", source: "Дэндралогія", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Араць пачыналі з сярэдзіны загона, і ўсё поле потым клалася вакол той адной баразны.", source: "Земляробства", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Ластаўка, што раз звіла гняздо пад страхой, вяртаецца пад яе кожную вясну. Месца выбіраецца адзін раз.", source: "Арніталогія", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Талака не аплачвалася і нідзе не запісвалася. Яна вярталася тым, што наступным разам клікалі цябе.", source: "Этнаграфія", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Дно возера пасля ледавіка легла раз і назаўсёды: форма Нарачы — гэта форма ямы, якую пакінуў лёд.", source: "Геалогія", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Прывой прырастае за адно лета, і далей яблыня родзіць тое, што далі ёй у той адзін дзень, а не сваё.", source: "Садоўніцтва", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Памалу едучы, далей будзеш.", source: "Беларуская прыказка", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "Пупышкі на галінцы закладваюцца летам, а раскрыюцца толькі праз зіму. Наступная вясна ўжо напісана на дрэве зараз.", source: "Батаніка", theme: .beginnings, subtheme: .whatAStartSettles),

        // MARK: - Waiting
        Passage(text: "Спакой насення: зерне, якое не ўзыходзіць, хоць вады, цяпла і святла хапае. Трымае яго не поле, а нешта ўнутры.", source: "Батаніка", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Стратыфікацыя: некаторае насенне прарасце толькі пасля таго, як пераляжыць зіму ў холадзе. Мароз для яго не перашкода, а ўмова.", source: "Батаніка", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Азімае жыта, пасеянае вясной, вырасце травой і не выкіне коласа. Яму патрэбны холад, каб дазволіць сабе квітнець.", source: "Земляробства", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Брунька стаіць пад лускай усю зіму, заклееная смалой. Тое, што ў ёй, гатова з жніўня і не спяшаецца.", source: "Батаніка", theme: .waiting, subtheme: .heldBack),
        Passage(text: "За куццю не сядалі, пакуль у небе не запалілася першая зорка, колькі б ні было наварана і як бы позна яна ні ўзышла.", source: "Беларускі народны каляндар", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Скуру дубілі карой па паўгода, і хутчэй не выходзіла: дубільныя рэчывы ўваходзяць у яе паволі і роўна.", source: "Рамяство", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Паспех — людзям на смех.", source: "Беларуская прыказка", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Спець і паспець у беларускай мове аднаго кораня. Тое, што выспела, і тое, што прыйшло ў свой час, — адно слова з двух бакоў.", source: "Беларуская мова", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Вусень у кокане не спіць, а перарабляецца цалкам. Разрэзаўшы кокан завучасна, не знойдзеш ні вусеня, ні матылька.", source: "Энтамалогія", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Лён слалі на луг і пакідалі на тры тыдні: раса і сонца самі аддзяляюць валакно ад кастрыцы, а рукі тут нічога не паскораць.", source: "Ільнаводства", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Рыба пад лёдам не спіць, але амаль не рухаецца: пры чатырох градусах карась стаіць у муле і не есць да красавіка.", source: "Іхтыялогія", theme: .waiting, subtheme: .heldBack),
        Passage(text: "Мёд у калодзе не бяруць увесну, хоць ён там ёсць. Пчолам ён патрэбны да першага ўзятку больш, чым чалавеку.", source: "Пчалярства", theme: .waiting, subtheme: .heldBack),

        Passage(text: "Дуб у пушчы стаіць пяцьсот гадоў, а бывае і болей. Жолуд, з якога ён пайшоў, упаў да таго, як тут надрукавалі першую кнігу.", source: "Лесаводства", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Пераначуем — болей пачуем.", source: "Беларуская прыказка", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Торф кладзе пылок кожнага лета асобным слоем. Пад Прыпяццю чытаецца, які лес стаяў тут дзесяць тысяч гадоў таму.", source: "Палеабатаніка", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Раз на некалькі гадоў у пушчы бывае жалудовы год, калі дубы родзяць усе разам. Паміж такімі гадамі яны маўчаць.", source: "Лесаводства", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Слуцкі пояс ткалі на адным станку месяцамі. Ткач сядаў за яго, ведаючы, што сёлета наўрад ці скончыць.", source: "Ткацтва", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Сафійскі сабор у Полацку паставілі ў адзінаццатым стагоддзі. Ён гарэў, яго перакладалі і надбудоўвалі, і ён стаіць далей.", source: "Гісторыя", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Бурштын — смала хвояў, што раслі сорак мільёнаў гадоў таму. Кропля цякла хвіліну і засталася назаўжды.", source: "Геалогія", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Ад сяўбы азімага да яго жніва праходзіць адзінаццаць месяцаў, і адзін з іх поле праводзіць пад снегам, жывое.", source: "Земляробства", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Буслянка на страсе перажывае гаспадароў. Адно гняздо дабудоўваюць дзесяцігоддзямі, і важыць яно сотні кілаграмаў.", source: "Арніталогія", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Мох нарастае па міліметры за год. Валун, зарослы ім да самай зямлі, ляжыць тут даўжэй, чым помніць вёска.", source: "Батаніка", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Кнігу перапісвалі ад рукі год і болей. У канцы пісар ставіў, у якім месце і ў якім годзе скончыў, — і больш пра сябе нічога.", source: "Кніжная справа", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "Зубрыха носіць цяля дзевяць месяцаў і водзіць яго пры сабе яшчэ год і другі. У пушчы гэта лічыцца хуткім.", source: "Заалогія", theme: .waiting, subtheme: .theLongCount),

        Passage(text: "Купалінка, купалінка, цёмная ночка, цёмная ночка, дзе ж твая дочка?", source: "Беларуская народная песня", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Папараць-кветка цвіце адну ноч у годзе, кажуць. Хто хоча яе ўбачыць, стаіць у лесе да самага світання.", source: "Народныя павер'і", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Пакуль адзін бусел носіць корм, другі стаіць над гняздом на адной назе і не варушыцца гадзінамі.", source: "Арніталогія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Начное: хлопцы вадзілі коней пасвіць на ўсю ноч і не клаліся зусім, седзячы вакол вогнішча да світання.", source: "Этнаграфія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Сава палюе слыхам. Яна сядзіць нерухома і знаходзіць мыш пад снегам па гуку, ні разу яе не ўбачыўшы.", source: "Арніталогія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Азірнуцца робяць адзін раз, азірацца — увесь час. Розніца паміж імі толькі ў суфіксе.", source: "Беларуская мова", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Раса не падае з неба, яна выступае з паветра. За ноч трава робіцца мокрай без дажджу, і ўбачыць гэта можна, толькі стоячы побач.", source: "Метэаралогія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Даглядаць — не проста глядзець, а глядзець да канца: за дзіцем, за хворым, за агнём у печы.", source: "Беларуская мова", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Аглядзіны: радня нявесты ехала паглядзець гаспадарку жаніха. Нічога не вырашалі і нічога не казалі — толькі глядзелі.", source: "Этнаграфія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Дня дажынак не прызначалі загадзя. Глядзелі на неба і на калоссе, і ён выбіраўся сам.", source: "Беларускі народны каляндар", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Прыдарожныя крыжы ставілі на скрыжаваннях, каб падарожны спыніўся. Ехаць міма было можна, але ніхто не ехаў.", source: "Этнаграфія", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "Загартоўка расады: яе выносяць на двор ранкам і ўносяць на ноч, дзень за днём, пакуль яна не прывыкне да ветру.", source: "Садоўніцтва", theme: .waiting, subtheme: .standingAndWatching),

        // MARK: - Renewal
        Passage(text: "Ляда: высечаны і выпалены кавалак лесу, які засявалі жытам. Праз колькі ўраджаяў яго пакідалі, і лес вяртаўся сам.", source: "Земляробства", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Лаза, зрэзаная пад самы корань, дае за лета пруты ў рост чалавека. Кошык плятуць з таго, што вырасла пасля сякеры.", source: "Лозапляценне", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Атава — трава, што адрастае на скошаным лузе. Другі пакос бывае мякчэйшы за першы.", source: "Лугаводства", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Дуб, зрэзаны пад корань, дае параснь з пня. Дзесяць новых ствалоў, і ўсе дзесяць — той самы дуб.", source: "Лесаводства", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Крапіва пасля касы адрастае за два тыдні і робіцца мякчэйшая, чым была да яе.", source: "Батаніка", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Пажарышча зарастае найперш іван-чаем. Ён прыходзіць туды, дзе згарэла, і сыходзіць, калі вяртаецца лес.", source: "Батаніка", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Абрэзка: галіну здымаюць, каб яблыня пусціла новыя. Неабрэзаная родзіць з году ў год усё драбней.", source: "Садоўніцтва", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Воўну здымаюць з авечкі раз на год, у чэрвені. Да халадоў яна абрастае зноў і ў зіму ідзе цёплая.", source: "Гаспадарка", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Разбурыце бабровую плаціну — і рака за месяц вернецца ў рэчышча, а бабёр за той жа месяц паставіць новую.", source: "Заалогія", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "На Тройцу падлогу ў хаце слалі аерам і галінкамі, а праз тыдзень вымяталі і слалі свежае. Пах у доме быў работай.", source: "Этнаграфія", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Пчаліная сям'я за лета мяняецца цалкам: ніводнай з майскіх пчол у жніўні ўжо няма, а вулей той самы.", source: "Пчалярства", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "Скошаны луг у верасні зацвітае другі раз, і пчолы бяруць з яго апошні ўзятак перад зімой.", source: "Пчалярства", theme: .renewal, subtheme: .cutAndComeAgain),

        Passage(text: "Плакала лета, зямлю пакідаючы; ціха ліліся слязінкі на поле, але прыгожаю восенню яснаю там, дзе ўпалі яны, вырасталі кветкі.", source: "Максім Багдановіч, «Вянок», 1913", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Каляды стаяць на самым кароткім дні. Далей, кажуць, дзень прыбывае на курыны крок — і так да самага Вялікадня.", source: "Беларускі народны каляндар", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "На Саракі пяклі сорак жаваранкаў з цеста і выносілі дзецям на двор — клікаць птушак дадому.", source: "Беларускі народны каляндар", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Дажынкі: апошні сноп прыбіралі і неслі ў хату, дзе ён стаяў на покуці да наступнай сяўбы.", source: "Этнаграфія", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Бараду завівалі з жменькі нязжатага жыта, што пакідалі стаяць на полі: дачыста тут не жалі ніколі.", source: "Этнаграфія", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Багач: скрыначка з жытам і свечкай, якую восенню неслі па вёсцы і па полі, а потым яна на цэлы год заставалася ў адной хаце.", source: "Беларускі народны каляндар", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Двойчы на год дзень і ноч роўныя, і роўныя адразу ўсюды — над Мінскам гэтак жа дакладна, як над экватарам.", source: "Астраномія", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Вёска лічыла вясну не ад календара, а ад бусла: прыляцеў — значыць, пачалося.", source: "Этнаграфія", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Беларускія назвы месяцаў гавораць пра поле, а не пра імператараў: лістапад — гэта проста тое, што ў ім робіцца.", source: "Беларуская мова", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Верасень названы верасам, які зацвітае тады, калі ўжо амаль нішто не цвіце.", source: "Беларуская мова", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Кастрычнік — ад кастрыцы: у гэтым месяцы мялі лён, і кастрыца ляжала па ўсіх дварах.", source: "Беларуская мова", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "Снежань, студзень, люты — снег, сцюжа і лютасць марозу. Тры месяцы, названыя тым, што яны робяць.", source: "Беларуская мова", theme: .renewal, subtheme: .theTurningYear),

        Passage(text: "Жывіца: смала, якой сасна залівае рану. Слова тое ж, што жывіць, і зацвярдзелая яна мацнейшая за само дрэва.", source: "Батаніка", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Калус: наплыў, якім дрэва зацягвае зрэз. Праз дзесяць гадоў ад сучка застаецца толькі валік пад карой.", source: "Дэндралогія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Гаіць — прычынны дзеяслоў ад жыць. Загаіць рану літаральна значыць прымусіць яе жыць далей.", source: "Этымалогія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ясень з абламанай верхавінай выводзіць новую з бакавой галіны. Праз дваццаць гадоў ствол зноў просты, толькі з каленцам.", source: "Дэндралогія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Зруб не збіваюць цвікамі. Бярвенні кладуцца ў чашкі, і хату можна разабраць, перавезці і скласці цэлай на новым месцы.", source: "Дойлідства", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ліпа цвіце тыдзень у годзе, і той тыдзень вырашае, ці будзе ў хаце чым паіць кашаль усю зіму.", source: "Народная медыцына", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Раскіданы мурашнік мурашкі складаюць нанова за некалькі дзён і на іншае месца яго не пераносяць.", source: "Заалогія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Талакою хату ставілі за некалькі дзён: што аднаму на цэлае лета, тое грамадзе на тыдзень.", source: "Этнаграфія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Ручнік у хаце трымалі не для рук. На ім падавалі хлеб, на ім вязалі рукі маладым і на ім жа неслі абраз.", source: "Этнаграфія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Спрамленая рака за дзесяцігоддзі вяртае сабе выгіны, калі ёй не замінаць. Прамая вада не трымаецца доўга.", source: "Гідралогія", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Асушанае балота робіцца балотам зноў, як толькі перастаць чысціць канавы. Мох вяртаецца першы.", source: "Балотазнаўства", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "Воск і смалу тапілі разам у адным гаршку. Гэта была ўся вясковая аптэка для парэзу і апёку.", source: "Народная медыцына", theme: .renewal, subtheme: .madeWhole),

        // MARK: - Light
        Passage(text: "Добрай ночы, зара-зараніца! Ужо імгла над зямлёю лажыцца, пылам зор небасхіл абсявае.", source: "Максім Багдановіч, «Вянок», 1913", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Месяц круглы ўстаў на небе, блішчыць нявысока, увесь чырвона-жоўты.", source: "Максім Багдановіч, «Вечар»", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Золак — тая гадзіна, калі яшчэ не відно, але ўжо не цёмна. Устаць на золку значыць устаць раней за святло.", source: "Беларуская мова", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Змярканне, прыцемак, шарая гадзіна — тры словы на адзін вечар, і кожнае пра іншы яго кавалак.", source: "Беларуская мова", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Досвітак кажа сам за сябе: да світання. У беларускай мове ёсць назва і для таго часу, калі яшчэ нічога не пачалося.", source: "Беларуская мова", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Цецярукі пачынаюць такаваць яшчэ ў поўнай цемры і змаўкаюць, як толькі паказваецца сонца.", source: "Арніталогія", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "На гэтай шыраце ў чэрвені поўнач не бывае зусім цёмнай: паўночны край неба застаецца шэра-сінім да раніцы.", source: "Астраномія", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "У пушчы світанне спускаецца зверху ўніз: верхавіны стаяць у сонцы, калі ўнізе яшчэ ноч.", source: "Лесаводства", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Вячоркі пачыналіся тады, калі на працу ў хаце пераставала хапаць дня, і сядзелі пры лучыне да позняга.", source: "Этнаграфія", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Лучына — сасновая трэска, што гарыць хвілін дзесяць. Хтосьці адзін увесь вечар мяняў яе ў свяцец, каб астатнія пралі.", source: "Этнаграфія", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Трэція пеўні — так у вёсцы называлі гадзіну перад світаннем. Гадзінніка не трэба было, дастаткова прачнуцца і палічыць.", source: "Этнаграфія", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "Зара бывае вячэрняя і ранішняя, і мова дае ім адно слова. Сонца сыходзіць і ўзыходзіць у тое самае.", source: "Беларуская мова", theme: .light, subtheme: .theEdgesOfTheDay),

        Passage(text: "Калісь глядзеў на сонца я, мне сонца асляпіла вочы. Ды што мне цемень вечнай ночы?", source: "Максім Багдановіч, «Трыялет»", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Малады сланечнік водзіць галавой за сонцам. Расквітнеўшы, ён спыняецца і глядзіць на ўсход да канца.", source: "Батаніка", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Кажуць, мох на камені гусцейшы з поўначы, і ў пушчы па ім шукаюць бок, калі неба зацягнута на цэлы дзень.", source: "Лесаводства", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Сонечны гадзіннік паказвае не тую гадзіну, што кішэнны. Ён паказвае гадзіну гэтага месца, а не гадзіну поясу.", source: "Астраномія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Пчала бачыць ультрафіялет. Кветкі, аднастайна жоўтыя для нас, для яе размечаныя сцяжынкамі проста да нектару.", source: "Пчалярства", theme: .light, subtheme: .readingTheLight),
        Passage(text: "З вышыні на жытнім полі відаць плямы там, дзе пад зямлёй старыя равы: збожжа над імі вышэйшае і цямнейшае.", source: "Археалогія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Печ гатовая, калі яе скляпенне з чорнага робіцца белым: сажа выгарае, і меры тут ніякай не трэба.", source: "Этнаграфія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Лёд, які трымае, — цёмны і празрысты. Белы, поўны бурбалак паветра, глядзіцца надзейней і трымае горш.", source: "Гідралогія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Неба сіняе таму, што паветра рассейвае кароткія хвалі мацней. Чым вышэй падняцца, тым яно цямнейшае.", source: "Фізіка", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Густая раса на світанні абяцае пагодны дзень: яна і выпадае толькі тады, калі за ноч неба было чыстае.", source: "Метэаралогія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Гадавое кольца складаецца з дзвюх палос: светлая — вясна, цёмная — позняе лета. Дрэва запісвае, колькі яму было дадзена.", source: "Дэндралогія", theme: .light, subtheme: .readingTheLight),
        Passage(text: "Вока прывыкае да цемры паўгадзіны, а губляе гэта за адзін міг святла. Цярпення тут патрабуе не цемра, а мы самі.", source: "Фізіялогія", theme: .light, subtheme: .readingTheLight),

        Passage(text: "Навакол усё паветра ў струнах сонца залатых.", source: "Максім Багдановіч, «Маёвая песня»", theme: .light, subtheme: .lightItself),
        Passage(text: "Загляне сонца і ў наша ваконца.", source: "Беларуская прыказка", theme: .light, subtheme: .lightItself),
        Passage(text: "Блішчыць у небе зор пасеў; у полі — рунь, і ў небе — рунь.", source: "Максім Багдановіч, «Вянок», 1913", theme: .light, subtheme: .lightItself),
        Passage(text: "Зорка Венера ўзышла над зямлёю, светлыя згадкі з сабой прывяла.", source: "Максім Багдановіч, «Раманс», 1912", theme: .light, subtheme: .lightItself),
        Passage(text: "Сонечнае святло ідзе сюды восем хвілін. Тое, што грэе твар цяпер, выйшла ў дарогу да таго, як ты выйшаў з хаты.", source: "Астраномія", theme: .light, subtheme: .lightItself),
        Passage(text: "Паўночнае ззянне даходзіць і сюды — раз у некалькі гадоў, і тады паўночны край неба стаіць чырвоны над самым лесам.", source: "Астраномія", theme: .light, subtheme: .lightItself),
        Passage(text: "Самка светляка не лятае. Яна сядзіць у траве і свеціць, і святло гэтае халоднае: на цяпло не ідзе амаль нічога.", source: "Энтамалогія", theme: .light, subtheme: .lightItself),
        Passage(text: "Трухлявае дрэва ў пушчы часам свеціцца ўначы зеленаватым. Гэта грыбніца апенькі, і бачна яе толькі ў поўнай цемры.", source: "Мікалогія", theme: .light, subtheme: .lightItself),
        Passage(text: "Грамнічную свечку свяцілі ў лютым і трымалі цэлы год. Яе запальвалі не для святла, а каб у хаце было спакойна.", source: "Этнаграфія", theme: .light, subtheme: .lightItself),
        Passage(text: "Маланка награвае паветра мацней, чым паверхня Сонца, і трымаецца тысячную долю секунды.", source: "Фізіка", theme: .light, subtheme: .lightItself),
        Passage(text: "Белы — гэта ўсе колеры разам. Кроплі дажджу разбіраюць яго назад і вешаюць над полем усе па чарзе.", source: "Фізіка", theme: .light, subtheme: .lightItself),
        Passage(text: "Свежы снег адбівае амаль усё, што на яго падае. У зімовую ноч пры поўні над ім можна чытаць.", source: "Фізіка", theme: .light, subtheme: .lightItself),

        // MARK: - Pattern
        Passage(text: "Капа — старая мера ў шэсцьдзесят: капа снапоў, капа яек. Лічылі тут не дзясяткамі, а шасцідзесяткамі.", source: "Меры і вагі", theme: .pattern, subtheme: .counted),
        Passage(text: "У пудзе сорак фунтаў, а ў фунце дзевяноста шэсць залатнікоў. Тры тысячы восемсот сорак залатнікоў у адным пудзе.", source: "Меры і вагі", theme: .pattern, subtheme: .counted),
        Passage(text: "Тры — мера казкі і абраду: тры сястры, тры дарогі, тры разы абысці вакол. Два было б мала, чатыры — ужо лік.", source: "Фалькларыстыка", theme: .pattern, subtheme: .counted),
        Passage(text: "Каляды доўжацца дванаццаць дзён, і кожны з іх, кажуць, паказвае свой месяц наступнага года. Увесь год прачытваецца загадзя.", source: "Беларускі народны каляндар", theme: .pattern, subtheme: .counted),
        Passage(text: "Пчол у сям'і дзесяткі тысяч і адна матка. Ніхто не лічыць пчол — лічаць рамкі, а рамак бывае дваццаць.", source: "Пчалярства", theme: .pattern, subtheme: .counted),
        Passage(text: "У старой мове побач з адзіночным і множным быў лік для пары. Ад яго засталіся вочы, вушы, плечы — тое, чаго заўсёды два.", source: "Мовазнаўства", theme: .pattern, subtheme: .counted),
        Passage(text: "Дзіцячая лічылка лічыць не да дзесяці, а да таго, на кім спыніцца. Патрэбна не сума, а той, на каго выпадзе.", source: "Фалькларыстыка", theme: .pattern, subtheme: .counted),
        Passage(text: "У вярсце пяцьсот сажняў, і на гасцінцы кожную адзначалі слупом. Дарогу мералі слупамі, а не картаю.", source: "Меры і вагі", theme: .pattern, subtheme: .counted),
        Passage(text: "Гадавыя кольцы лічацца не толькі на пні. У бервяне старой хаты яны тыя ж, і па іх відаць, у якім годзе яе секлі.", source: "Дэндрахраналогія", theme: .pattern, subtheme: .counted),
        Passage(text: "Каляндар лічыць месяцы, а вёска лічыла работы: сяўба, сенажаць, жніво, малацьба. Гэта дванаццаць зусім іншых месяцаў.", source: "Этнаграфія", theme: .pattern, subtheme: .counted),
        Passage(text: "Пяць пялёсткаў у яблыні, у грушы, у рабіны, у шыпшыны і ў суніц. Уся гэтая радня лічыцца на пяць і ніяк іначай.", source: "Батаніка", theme: .pattern, subtheme: .counted),
        Passage(text: "Восем ног у павука і шэсць у мурашкі, і гэта не дробязь: менавіта па колькасці ног іх і разбіраюць на групы.", source: "Заалогія", theme: .pattern, subtheme: .counted),

        Passage(text: "Вугал у чашку і вугал у лапу — два спосабы злучыць бярвенні. Ні ў адным з іх няма ніводнага цвіка.", source: "Дойлідства", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Ячэйка ў сотах шасцівугольная, бо шасцівугольнікі кладуцца без прамежкаў і патрабуюць найменш воску на сценкі.", source: "Пчалярства", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Аснова нацягнута ўздоўж, уток ходзіць упоперак, і палатно — гэта проста тое месца, дзе яны сустракаюцца.", source: "Ткацтва", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Слуцкі пояс двухбаковы: тварам лічацца абодва бакі, і ткач мусіў трымаць у галаве два ўзоры адначасова.", source: "Ткацтва", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Саламяны павук вісіць пад столлю, і кожная саломінка ў ім трымаецца толькі за суседнюю. Выцягні адну — не будзе нічога.", source: "Народнае мастацтва", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "У плоце з жэрдак нічога не прыбіта. Кожная жэрдка ўшчэмлена паміж двума коламі, і плот стаіць сам сабою.", source: "Рамяство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Дзеканне і цеканне: перад мяккімі гукамі д гучыць як дз, а т як ц. Дзве літары там, дзе была адна, і язык не спатыкаецца.", source: "Беларуская мова", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Лямец звальваюць без ніткі. Воўну мнуць у гарачай вадзе, пакуль лусачкі валаскоў не счэпяцца між сабой назаўсёды.", source: "Рамяство", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Вянок пляцецца так, што апошняя кветка трымае першую. Пакуль кола не замкнулася, ён рассыпаецца ў руках.", source: "Народнае мастацтва", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "У бочцы няма ні клею, ні цвіка. Яе трымае адно тое, што клёпкі ціснуць адна на адну, а абруч не дае разысціся.", source: "Бондарства", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Снежынка заўсёды шасцівугольная, бо малекула вады чапляецца да суседак пад адным і тым жа вуглом.", source: "Фізіка", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "Печ ставілі так, каб ад яе грэліся ўсе чатыры куты. Хата будавалася вакол печы, а не печ уносілася ў хату.", source: "Дойлідства", theme: .pattern, subtheme: .fittedTogether),

        Passage(text: "І бачу я ў канцы няхітрую прыпіску, што кнігу гэтую раб божы, дзяк Гапон, дзеля душы спісаў у месту Ваўкавыску.", source: "Максім Багдановіч, «Кніга»", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Статут Вялікага Княства Літоўскага 1588 года напісалі і надрукавалі на тутэйшай мове, і дзейнічаў ён потым яшчэ два з паловай стагоддзі.", source: "Гісторыя права", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Скарына даў кожнай кнізе сваёй Бібліі ўласную прадмову і растлумачыў у ёй, для каго і навошта друкуе.", source: "Гісторыя кнігадрукавання", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Аканне: ненаціскное о гучыць як а — і тут яго так і пішуць. Правапіс запісвае тое, што вуха чуе, а не тое, што было раней.", source: "Беларуская мова", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "У Полацку з 2003 года стаіць помнік літары ў: стэла з яе рэльефамі на гранях, якая служыць яшчэ і сонечным гадзіннікам.", source: "Гісторыя", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Пішы, як чуеш — не жарт, а прынцып, пакладзены ў аснову беларускага правапісу і выпісаны ў правілах.", source: "Мовазнаўства", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Кірылічныя літары служылі і лічбамі: а — адзін, в — два. Лік у старой кнізе пісаўся тымі ж знакамі, што і словы.", source: "Кніжная справа", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Летапіс лічыў гады ад стварэння свету. Каб атрымаць наш год, ад летапіснага адымаюць пяць тысяч пяцьсот восем.", source: "Летапісанне", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Герб апісвалі словамі так дакладна, што па адным апісанні мастак у іншым горадзе мог намаляваць яго нанова.", source: "Геральдыка", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Кожная расліна мае імя з двух слоў: першае кажа, чыя яна радня, другое — чым яна ў гэтай радні асаблівая.", source: "Батаніка", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Узор на ручніку чытаўся: рамб азначаў поле, рамб з кропкай — засеянае поле. Гэта пісьмо, якое ткалі, а не пісалі.", source: "Народнае мастацтва", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "Мноства беларускіх прозвішчаў канчаецца на -іч. Гэта старая форма, што азначала сына: Багдановіч, Пашкевіч, Хадкевіч.", source: "Анамастыка", theme: .pattern, subtheme: .orderNamed),

        // MARK: - Ground
        Passage(text: "Малако ў каровы на языку.", source: "Беларуская прыказка", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Падзол: шэрая, як попел, зямля пад хвойным лесам. Дождж вымыў з яе амаль усё, што расліне патрэбна.", source: "Глебазнаўства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Дзярнова-падзолістая глеба ляжыць пад большасцю тутэйшых палёў. Яна кіслая, і таму сюды спрадвеку вазілі вапну.", source: "Глебазнаўства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Торф — гэта расліны, якія не паспелі згніць. У балоце няма кіслароду, і мох ляжыць цэлы тысячагоддзямі.", source: "Балотазнаўства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Палессе — не зямля з вадой, а вада з зямлёй: пад нагамі там торф, а пад торфам пясок.", source: "Геаграфія", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Валуны на мяжы прынёс ледавік са Скандынавіі. Кожны такі камень ехаў сюды тысячу кіламетраў і прыехаў.", source: "Геалогія", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Гумус: чорнае ў зямлі — гэта не бруд, а рэшткі жывога, перапрацаваныя да таго, што іх ужо нельга апазнаць.", source: "Глебазнаўства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Дажджавыя чарвякі прапускаюць праз сябе дзясяткі тон зямлі на гектар за год. Поле перакопваецца само, без нікога.", source: "Глебазнаўства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Попел на лядзе быў самай багатай зямлёй, якую ведала вёска: ён аддаваў жыту тое, што лес збіраў стагоддзямі.", source: "Земляробства", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Клевер і лубін бяруць азот проста з паветра — не самі, а праз бактэрый, што жывуць у клубеньках на іх карэнні.", source: "Агранамія", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Пах зямлі пасля дажджу дае рэчыва, якое вылучаюць глебавыя бактэрыі. Нос чуе яго ў колькасці, якую цяжка нават змерыць.", source: "Хімія", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "Мяжа — незараная паласа паміж загонамі. Яна не радзіла нічога і была самым важным месцам на ўсім полі.", source: "Этнаграфія", theme: .ground, subtheme: .theSoilItself),

        Passage(text: "І тчэ, забыўшыся, рука заміж персідскага ўзору цвяток радзімы васілька.", source: "Максім Багдановіч, «Слуцкія ткачыхі»", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Ад прадзедаў спакон вякоў мне засталася спадчына; паміж сваіх і чужакоў яна мне ласкай матчынай.", source: "Янка Купала, «Спадчына», 1918", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Знай каток свой куток.", source: "Беларуская прыказка", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Тутэйшы: слова, якім тут доўга называлі саміх сябе, калі пыталіся, хто вы. Яно значыць проста — адсюль.", source: "Гісторыя", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Радзіма і радня — адзін корань. Месца, дзе ты нарадзіўся, і людзі, з якімі ты ў родзе, названы адным словам.", source: "Этымалогія", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Бацькаўшчына значыць і край, і бацькоўскую спадчыну: і тое, што перадалі, і тое месца, дзе яно ляжыць.", source: "Беларуская мова", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Хутар — адна хата з зямлёй вакол, без вуліцы і без суседа за плотам. Такіх тут было поўна, пакуль іх не звялі разам.", source: "Этнаграфія", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Назвы вёсак часцей за ўсё пра ваду ці дрэва: Дуброва, Бярозаўка, Лозкі, Крынічка. Людзі называліся тым, што расло побач.", source: "Тапаніміка", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Радзіны — так тут завуць самы дзень, калі дзіця з'явілася. Слова з таго ж кораня, што і назва краю, дзе гэта здарылася.", source: "Этнаграфія", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Вярбу садзілі каля вады, ліпу — каля ганка. Дрэва пры двары казала здалёк, чый гэта двор.", source: "Этнаграфія", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Загон — палоска зямлі, якую адзін чалавек абрабляў за адзін дзень. Поле дзялілася не на квадраты, а на дні.", source: "Земляробства", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "Прымак ішоў жыць у хату жонкі і вёў яе гаспадарку. Для гэтага ёсць асобнае слова, бо здаралася гэта нярэдка.", source: "Этнаграфія", theme: .ground, subtheme: .aPlaceYouAreFrom),

        Passage(text: "Рабі пільна — і тут будзе Вільня.", source: "Беларуская прыказка", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Сядзіба — гэта хата, гумно, хлеў, лазня і сад за адным плотам. Не дом, а ўсё, што трымаеш у парадку.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Гумно ставілі наводдаль ад жылля: у ім сушылі і малацілі, і адна іскра магла забраць увесь двор.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Лазню рубілі як мага далей ад хаты і як мага бліжэй да вады, і тапілі яе ў суботу, а не калі спатрэбіцца.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Свіран — камора для збожжа, зробленая так, каб было суха і каб мыш не дастала. Яго часта рабілі лепш за жыллё.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Сад пры хаце садзілі не на продаж: пяць-шэсць дрэў, кожнае свайго тэрміну, каб яблыкі былі ад ліпеня да замаразкаў.", source: "Садоўніцтва", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Борць — пчолы ў жывым дрэве. Дрэва пры гэтым належала не таму, хто яго знайшоў, а таму, чый знак быў выразаны на кары.", source: "Бортніцтва", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Бортны знак рэзалі на кары сякерай. У кожнага роду ён быў свой і пераходзіў ад бацькі да сына нязменны.", source: "Бортніцтва", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Талака чысціла крыніцу, лаціла масток і касіла грамадскі луг. Гэта была работа не на кагосьці, а на месца.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Плот стаяў не супраць людзей, а супраць жывёлы. Ён трымаў карову з поля, а не суседа з двара.", source: "Этнаграфія", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Ствол яблыні бяліць вапнай трэба не для прыгажосці: зімовае сонца награвае кару з поўдня, і без пабелкі яна трэскаецца.", source: "Садоўніцтва", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "Студня з жураўлём: доўгае плячо з проціважарам, што падымае вядро само. Такая студня стаяла на цэлую вуліцу.", source: "Рамяство", theme: .ground, subtheme: .aKeptPlace),

        // MARK: - Travel
        Passage(text: "Бабіна лета: ніці павуціння, што ляцяць у верасні праз усё поле. На канцы кожнай сядзіць маленькі павучок і так вандруе.", source: "Заалогія", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Крылатка клёна круціцца ў падзенні не дзеля прыгажосці: круцячыся, яна падае павольней і паспявае адляцець ад дрэва.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Парашут з валаскоў у асоту важыць менш за само зярнятка, якое нясе, і даносіць яго за некалькі кіламетраў.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Насенне гарлачыка выходзіць з плода ў слізі, некалькі дзён трымаецца на вадзе і чапляецца за пер'е качкі.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Галінкі вярбы, уваткнутыя бабром у плаціну, пускаюць карэнні. Ён будаваў сабе дом, а пасадзіў лазняк.", source: "Заалогія", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Дзядоўнік і ліпучка: насенне з кручкамі, што едзе на поўсці і на нагавіцах. Дазволу яно не пытаецца.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Верас сее сабе пад ногі: зярняты яго такія дробныя, што далёка не ляцяць, і таму верас расце суцэльным дываном.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Сасновая шышка раскрываецца ў сухі дзень і закрываецца ў дождж. Крылатае зярнё выпадае толькі ў той дзень, калі яно паляціць далёка.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "У вольхавага зярняці ёсць коркавыя берагі з паветрам. Яно плыве, пакуль яго не прыб'е да чужога берага.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Ягада амялы ліпкая. Дрозд выцірае дзюбу аб галіну, і амяла застаецца там, дзе птушка спынілася прыбрацца.", source: "Арніталогія", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "Вясной сасновы пылок ляціць так густа, што калюжыны жаўцеюць. Знаходзяць яго за сотні кіламетраў ад бліжэйшага бору.", source: "Батаніка", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "У торфе зярнё ляжыць стагоддзе і ўзыходзіць, калі балота разварушаць. Яно вандруе не ў прасторы, а ў часе.", source: "Балотазнаўства", theme: .travel, subtheme: .howASeedGoes),

        Passage(text: "Гасцінец — вялікая дарога, і слова гэта ад госця, бо госцем звалі падарожніка. Гасцінцам жа завуць і падарунак з дарогі.", source: "Беларуская мова", theme: .travel, subtheme: .theRoad),
        Passage(text: "Шпарка коні імчацца ў полі, сумна бомы гудзяць пад дугой, запяваюць аб долі і волі.", source: "Максім Багдановіч, «Зімовая дарога»", theme: .travel, subtheme: .theRoad),
        Passage(text: "Не пытайся ў таго, хто ў хаце сядзіць, спытайся ў таго, хто ходзіць.", source: "Беларуская прыказка", theme: .travel, subtheme: .theRoad),
        Passage(text: "Малая падарожная кніжка — так Скарына назваў кнігу памерам з далонь, зробленую дзеля таго, каб яе бралі ў дарогу.", source: "Гісторыя кнігадрукавання", theme: .travel, subtheme: .theRoad),
        Passage(text: "Валачобнікі на Вялікдзень абыходзілі вёску ад хаты да хаты і спявалі пад кожным акном. Ішлі ўсю ноч і да раніцы канчалі.", source: "Этнаграфія", theme: .travel, subtheme: .theRoad),
        Passage(text: "Вялікую дарогу з абодвух бакоў абсаджвалі дрэвамі — каб зімой было відаць, дзе яна, калі ўсё замяце.", source: "Дарожная справа", theme: .travel, subtheme: .theRoad),
        Passage(text: "Карчму ставілі праз кожныя некалькі вёрст. Конь ішоў свой дзень, і трэба было мець, дзе яго накарміць і напаіць.", source: "Этнаграфія", theme: .travel, subtheme: .theRoad),
        Passage(text: "Зімовы шлях ішоў не гасцінцам, а ракой: замерзлая Дзвіна была раўнейшая і карацейшая за любую дарогу па сушы.", source: "Гісторыя", theme: .travel, subtheme: .theRoad),
        Passage(text: "Плытагоны спускалі лес па Нёмане да самага мора, а назад ішлі пехатой: плыт прадаваўся разам з лесам.", source: "Гісторыя", theme: .travel, subtheme: .theRoad),
        Passage(text: "У дарогу абувалі лапці, бо яны лёгкія. Пары хапала прыкладна на тыдзень хады, і запасныя вязалі да пояса.", source: "Этнаграфія", theme: .travel, subtheme: .theRoad),
        Passage(text: "Дняпроўска-Бугскі канал звязаў дзве ракі, а з імі два моры. З Пінска можна дайсці вадой і ў Балтыку, і ў Чорнае.", source: "Геаграфія", theme: .travel, subtheme: .theRoad),
        Passage(text: "Правесці — не развітацца, а прайсці разам частку шляху. Госця праводзілі да плота, а добрага госця — да наступнай вёскі.", source: "Беларуская мова", theme: .travel, subtheme: .theRoad),

        Passage(text: "І лятуць мае лёгкія сані, унашуся я ў сінюю даль.", source: "Максім Багдановіч, «Зімовая дарога»", theme: .travel, subtheme: .farOff),
        Passage(text: "Вырай — тое месца, куды адлятаюць птушкі. Слова азначае не поўдзень і не краіну, а проста тое, што за небакраем.", source: "Беларуская мова", theme: .travel, subtheme: .farOff),
        Passage(text: "Бусел, што вывеўся тут, зімуе ў Афрыцы. Ляціць ён кругам праз Левант, бо над морам няма цёплага паветра, што ўзнімаецца ўгору.", source: "Арніталогія", theme: .travel, subtheme: .farOff),
        Passage(text: "Зубры жывуць цяпер і ў Іспаніі, і ў Карпатах, і ўсе яны — нашчадкі жменькі жывёл, што засталіся ў свеце пасля вайны.", source: "Заалогія", theme: .travel, subtheme: .farOff),
        Passage(text: "Скарына вучыўся ў Кракаве, доктарам стаў у Падуі, друкаваў у Празе і ў Вільні. Дарогі яго былі даўжэйшыя за яго кнігі.", source: "Гісторыя", theme: .travel, subtheme: .farOff),
        Passage(text: "Балтыйскі бурштын знаходзяць у мікенскіх магілах. Ён ішоў туды праз усю Еўропу з рук у рукі, і ніхто не прайшоў шляху цалкам.", source: "Археалогія", theme: .travel, subtheme: .farOff),
        Passage(text: "Слуцкія паясы прадавалі ў Варшаве і ў Парыжы, а ўзор іх называўся персідскім, хоць ткалі яго тут, у Слуцку, сярод жытніх палёў.", source: "Гісторыя", theme: .travel, subtheme: .farOff),
        Passage(text: "Ластаўка за сваё жыццё пралятае дзясяткі тысяч кіламетраў і кожную вясну вяртаецца пад тую самую страху.", source: "Арніталогія", theme: .travel, subtheme: .farOff),
        Passage(text: "Даль, далеч, далячынь — тры словы на адно і тое ж, і ўсе тры пра тое, што бачна, але да чаго не дайсці.", source: "Беларуская мова", theme: .travel, subtheme: .farOff),
        Passage(text: "Вадападзел праходзіць праз сярэдзіну краю. Тое, што ўпала па адзін бок узгорка, будзе ў Балтыцы, што па другі — у Чорным моры.", source: "Геаграфія", theme: .travel, subtheme: .farOff),
        Passage(text: "Дробныя птушкі ляцяць у вырай уначы і трымаюцца зорак. Тое, па чым яны знаходзяць дарогу, вісіць за светлавыя гады адсюль.", source: "Арніталогія", theme: .travel, subtheme: .farOff),
        Passage(text: "Тутэйшая сасна ішла на карабельныя мачты. Дрэва, што вырасла над балотам, канчала свой век у Атлантыцы.", source: "Гісторыя", theme: .travel, subtheme: .farOff),

        // MARK: - Meeting
        Passage(text: "Помніш, калі я спаткаўся з табою, зорка Венера ўзышла.", source: "Максім Багдановіч, «Раманс», 1912", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Спатканне і сустрэча — два словы на адно. Першае пра тое, што дамовілі, другое пра тое, што проста здарылася.", source: "Беларуская мова", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Куй жалеза, пакуль гарачае.", source: "Беларуская прыказка", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Кірмаш: дзень, калі вёска рабілася горадам. Хто нічога не купляў і не прадаваў, усё роўна ішоў туды.", source: "Этнаграфія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Дарогу вясельнаму поезду перагароджвалі вяроўкай і патрабавалі выкуп. Спыніцца было часткай абраду, а не перашкодай.", source: "Этнаграфія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "На Купалле скакалі праз агонь удвох, за рукі. Ці разышліся рукі ў паветры — за гэтым сачылі ўсе.", source: "Этнаграфія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Вянкі на Купалле пускалі па плыні, а лавілі іх ніжэй за паваротам. Чый вянок хто злавіў, той да таго і ішоў пытацца.", source: "Этнаграфія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Дождж ідзе на самай мяжы двух паветраных патокаў. Усё астатняе неба пры гэтым можа стаяць чыстае.", source: "Метэаралогія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Дзве ракі, зліўшыся, некалькі кіламетраў ідуць адным рэчышчам двух колераў, пакуль вада не пераканае ваду.", source: "Гідралогія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Цень Месяца прабягае па зямлі паласу ў сотні кіламетраў, а стаіш ты ў ім дзве хвіліны.", source: "Астраномія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Знаёмства ў вёсцы пачыналася не з таго, як цябе завуць, а з таго, чый ты. Імя ішло другім.", source: "Этнаграфія", theme: .meeting, subtheme: .theMoment),
        Passage(text: "Спаткаць значыць і сустрэць, і напаткаць. Адно слова на тое, што шукаў, і на тое, што знайшло цябе само.", source: "Беларуская мова", theme: .meeting, subtheme: .theMoment),

        Passage(text: "Мурашкі пасуць тлю: адны бароняць, другія кормяць салодкім. Дамове гэтай дзясяткі мільёнаў гадоў.", source: "Заалогія", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Лішайнік — гэта грыб і водарасць, што жывуць адным целам. Паасобку на голым камені не пратрымаецца ні той, ні тая.", source: "Батаніка", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Мікарыза: ніці грыба абкручваюць сасновы корань, аддаюць яму ваду і бяруць цукар. На чыстым пяску без гэтага не расце нічога.", source: "Батаніка", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Вярба цвіце раней, чым распусціць лісце, і робіць гэта дзеля пчол: у красавіку ёй больш няма каго прасіць.", source: "Батаніка", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Буслы вядуцца там, дзе людзі косяць. Зарослы луг ім без карысці — патрэбна нізкая трава, у якой відаць жабу.", source: "Арніталогія", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Жыта і васілёк раслі побач тысячу гадоў. Калі поле пачалі чысціць дачыста, сінія кветкі зніклі разам з мяжой.", source: "Батаніка", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Пчала не адрознівае чырвонага, і кветка, што кліча менавіта яе, чырвонай не бывае. Пра колер яны дамовіліся даўно.", source: "Пчалярства", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Каса без бруска рэжа паўгадзіны. Касец носіць брусок пры сабе, у ражку з вадой на поясе, і спыняецца часцей, чым хоча.", source: "Рамяство", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Без цягі печ не гарыць, а без агню комін не цягне. Пачынаць даводзіцца з жмені саломы, якая не варта нічога.", source: "Дойлідства", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Зруба аднаму не скласці: бервяно трэба падняць з двух канцоў у адзін і той жа момант.", source: "Этнаграфія", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Хлеб і соль зрасліся ў мове ў адно слова, і слова гэта значыць ужо не ежу, а гасціннасць.", source: "Беларуская мова", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "Сфагнум трымае ў сабе вады ў дваццаць разоў болей за сваю вагу. Без мху не было б балота, а без балота — мху.", source: "Балотазнаўства", theme: .meeting, subtheme: .twoThatNeedEachOther),

        Passage(text: "Што душа мае, тым і прыймае.", source: "Беларуская прыказка", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Покуць — кут пад абразамі, дзе стаяў стол. Госця садзілі туды, і адмаўляцца было не прынята.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Хлеб і соль выносілі насустрач на ручніку, дзвюма рукамі. Выйсці да чалавека з пустымі рукамі лічылася няёмкім.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Клічны склон: мова трымае асобную форму для звароту — браце, сынку, дружа. Яна ні на што больш не патрэбна.", source: "Мовазнаўства", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Прывітанне тут — пажаданне дню, а не чалавеку: добры дзень, добры вечар, добрай ночы. Пра самога чалавека — потым.", source: "Беларуская мова", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Дзякуй прыйшло сюды здалёк, праз некалькі моў. Слова для падзякі не вырасла само — яго прынеслі і прынялі.", source: "Этымалогія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "На вячоркі прыходзілі са сваёй работай: з кудзеляй, з вязаннем, з дратвай. Сесці без нічога было няёмка.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Талака канчалася сталом. Гаспадар не плаціў нікому, але карміў усіх, і гэта важыла больш за плату.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Кум і кума — радня не па крыві, а па выбары. Іх бяруць сабе самі, і разабраць гэта назад ужо нельга.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Як маецеся — так тут пытаюцца пра здароўе. Дзеяслоў у гэтым пытанні той самы, што і ў слове мець.", source: "Беларуская мова", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Змовіны: дамовіўшыся, бакі білі па руках. З таго моманту справа лічылася зробленай, хоць нічога не запісвалася.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "Добры дзень у хату — так вітаўся той, хто ўвайшоў. Спярша вітаюцца з домам, а ўжо потым з людзьмі ў ім.", source: "Этнаграфія", theme: .meeting, subtheme: .theMannersOfIt),

        // MARK: - Kinship
        Passage(text: "Прышчэпка: два кавалкі жывога дрэва, прыціснутыя адзін да аднаго, за некалькі тыдняў робяцца адным. Разняць іх пасля нельга.", source: "Садоўніцтва", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Дзве сасны, што стаялі ўшчыльную, часам зрастаюцца галінай і далей растуць з адным сукам на дваіх.", source: "Дэндралогія", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Асіннік звычайна ўвесь — адно дрэва. Асіна пускае параснь ад каранёў, і цэлы гай можа быць адной раслінай.", source: "Батаніка", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Карэнні суседніх соснаў у бары зрастаюцца. Зрэзаны пень можа жыць дзесяцігоддзямі, бо яго корміць сусед.", source: "Лесаводства", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Яблык ад яблыні недалёка падае.", source: "Беларуская прыказка", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Пчаліная сям'я — не сход асобных пчол. Адна пчала, вынятая з яе, не пражыве і сутак, хоць з ёй усё ў парадку.", source: "Пчалярства", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Талака, грамада, суполка — тры словы пра людзей, што робяць нешта разам, і ні ў адным з іх няма начальства.", source: "Беларуская мова", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Пасля зліцця дзве ракі носяць адно імя, і не заўжды імя большай. Часам застаецца тое, якое людзі ведалі даўжэй.", source: "Гідралогія", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Зяць, нявестка, швагер, залоўка — на кожнага, хто прыйшоў у сям'ю збоку, тут маецца сваё слова.", source: "Беларуская мова", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Тры лісточкі канюшыны сядзяць на адным чаранку, і адарваць адзін, не крануўшы двух астатніх, не выходзіць.", source: "Батаніка", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Хата на дзве палавіны: два браты пад адной страхой, з адным комінам пасярэдзіне і двума ганкамі па баках.", source: "Дойлідства", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "Дзярніна на мяжы трымаецца пераплеценымі карэннямі дзясятка траў. Такі пласт трымае бераг лепш за камень.", source: "Глебазнаўства", theme: .kinship, subtheme: .grownTogether),

        Passage(text: "Сябар ідзе са старажытнага сѧбръ. Суседзі за Дзвіной пазычылі гэтае слова даўно і кажуць яго дагэтуль.", source: "Этымалогія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Сусед значыць таго, хто сядзіць побач. Не таго, хто побач жыве, а таго, хто побач сеў.", source: "Этымалогія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Дзяды: асенні вечар, калі на стол ставяць лішнюю міску і клічуць па імёнах тых, каго няма. Гэта не жалоба, а вячэра.", source: "Этнаграфія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Стрыечны, дваюрадны, траюрадны — мова лічыць, на колькі каленаў чалавек табе радня, і на трэцім яшчэ не спыняецца.", source: "Беларуская мова", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Пабрацімства: людзі без агульнай крыві маглі стаць братамі па дамове, і сваяцтва гэтае лічылася сапраўдным.", source: "Этнаграфія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Матчына мова — так тут кажуць пра родную. Не мова бацькоў і не мова краю, а мова адной канкрэтнай жанчыны.", source: "Беларуская мова", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Дзядзіна — жонка дзядзькі, і слова для яе асобнае. Радня, што прыйшла праз шлюб, называецца тут гэтак жа дакладна.", source: "Беларуская мова", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Ласкавае імя тут даўжэйшае за само імя: Ганна робіцца Гануляй, Янка — Яначкам. Далей ад імя і бліжэй да чалавека.", source: "Беларуская мова", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Сваяк — ад слова свой. Гэта не той, хто нарадзіўся тваім, а той, хто тваім стаў.", source: "Этымалогія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Грамада азначае і вясковы сход, і проста людзей разам. У гэтым слове няма ні спісу, ні старшыні.", source: "Беларуская мова", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "Дзеці звярталіся да ўсіх старэйшых «дзядзька» і «цётка», і ад гэтага ўся вуліца рабілася раднёй, нікога не пытаючыся.", source: "Этнаграфія", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "На вы ў вёсцы пачыналі гаварыць не з чужымі, а з бацькамі. Пашана ішла найперш у свой бок.", source: "Этнаграфія", theme: .kinship, subtheme: .theWordsForIt),

        Passage(text: "Як баба да дзеда, так і дзед да бабы.", source: "Беларуская прыказка", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Кожнаму сваё дзіця міла.", source: "Беларуская прыказка", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Ярмо робяць пад пару валоў, а не пад аднаго. Калі адзін вышэйшы, яго не мяняюць — падганяюць ярмо.", source: "Рамяство", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "На сенажаці адзін косіць, другі варушыць. Гэта дзве розныя работы, і адначасова іх адным чалавекам не зробіш.", source: "Гаспадарка", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Падгалосак — другі голас у песні, які не паўтарае першы, а ходзіць вакол яго і сыходзіцца з ім у канцы радка.", source: "Этнамузыказнаўства", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Невад цягнуць удвух: адзін берагам, другі па вадзе. Сетка ідзе толькі тады, калі абодва ідуць роўна.", source: "Рыбалоўства", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Хросных бралі заўсёды двух — кума і куму. Аднаго не лічылася, як не лічыцца адна рука ў далоні.", source: "Этнаграфія", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "У народнай песні пастаянна двое: дзве сястрыцы, дзве дарожкі, два галубы. Адзін і трое трапляюцца значна радзей.", source: "Фалькларыстыка", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Малады і маладая — адно слова ў двух родах. Ніхто з іх граматычна не галоўны, і ў абрадзе таксама.", source: "Беларуская мова", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Плацэнта вырастае з дзіцяці, а не з маці, хоць і корміцца ад яе. Орган, які належыць абаім, робіць толькі адзін.", source: "Фізіялогія", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Лебедзі трымаюцца парай круглы год, і на зімоўку ляцяць разам, хоць у чарадзе іх сотні.", source: "Арніталогія", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "Жорны круцяць удзвюх: адна сыпле зерне, другая круціць, і мяняюцца праз кожныя некалькі жменяў.", source: "Гаспадарка", theme: .kinship, subtheme: .twoPeople),

        // MARK: - Peace
        Passage(text: "Бачу я, з прыродай зліўшыся душой, як дрыжаць ад ветру зоркі нада мной, чую ў цішы, як расце трава.", source: "Максім Багдановіч, «Вянок», 1913", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ціха срэбрам грукае крыніца.", source: "Максім Багдановіч, «Вянок», 1913", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Зацішак — месца, куды не дастае вецер. Слова гэта пра паветра, а тлумачаць яго заўсёды праз цішыню.", source: "Беларуская мова", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Бусел не спявае зусім. Замест голасу ў яго клёкат дзюбай, і чуваць той клёкат праз усю вёску.", source: "Арніталогія", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Свежы снег глытае гук: ён увесь у порах, і поры з'ядаюць высокія тоны. Пасля начнога снегу вёска чуе сама сябе.", source: "Акустыка", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Сава ляціць бязгучна. Пярэдняе пяро ў яе з грабеньчыкам па краі, і той разбівае віхор, які ў іншых птушак свішча.", source: "Арніталогія", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Гоман — гук многіх галасоў разам, калі слоў ужо не разабраць. Гоман бывае і ў лесе, і там ён гучыць гэтак жа.", source: "Беларуская мова", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Шолах, шамаценне, шапаценне, шэлест — чатыры словы на адзін гук сухога лісця, і кожнае крыху іншае.", source: "Беларуская мова", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Дэркач крычыць уначы па два разы на секунду і не змаўкае да раніцы. Чуваць яго за кіламетр, а сам ён велічынёй з далонь.", source: "Арніталогія", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ціха па мяккай траве сінявокая ноч прахадзіла; конікі суха звінелі.", source: "Максім Багдановіч, «Вянок», 1913", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Мох пад нагой не хрумсціць і не шамаціць. Той, хто ідзе балотам, не чуе сваіх крокаў і таму ідзе павольней.", source: "Акустыка", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "Ціхмяны кажуць пра чалавека, які ціхі не таму, што маўчыць, а таму, што ён такі і ёсць.", source: "Беларуская мова", theme: .peace, subtheme: .quietAsASound),

        Passage(text: "Уціхамірыць — слова, у якім разам сядзяць ціша і мір. Супакоіць кагосьці тут значыць літаральна ўвесці яго ў ціхі мір.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Памірыцца нельга аднаму: дзеяслоў патрабуе дваіх. Мова тут строгая і выключэнняў не робіць.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Перамір'е складзена з пера- і мір. Гэта не мір, а прамежак, зроблены з яго, і слова само кажа, што ён часовы.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Згода — і лад паміж людзьмі, і проста адказ «так». Пагадзіцца з чалавекам і памірыцца з ім тут амаль адно.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Лад — гэта і парадак, і сугучча, і мір у хаце. Жыць у ладзе і спяваць у лад сказана адным і тым жа словам.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Наладзіць значыць зрабіць так, каб было ў ладзе. Ад аднаго кораня ідуць і рамонт касы, і замірэнне суседзяў.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Улагодзіць — суняць, нікога не пераканаўшы. Слова роднаснае лагоднаму, і гвалту ў ім няма ніякага.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Дараваць значыць і прабачыць, і падарыць. Даецца пры гэтым тое самае, і называецца яно адным дзеясловам.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Годзе — тутэйшае слова для «хопіць». Гэта не загад і не адмова, а проста мяжа: далей ужо не трэба.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Супынак — калі спыніўся сам. Прыпынак — месца, дзе спыняюцца ўсе. Дзве прыстаўкі, і два розныя віды спакою.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Перадышка зроблена з дыхання, а не з гадзінніка. Яна доўжыцца столькі, колькі трэба, каб аддыхацца.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "Скончыць — давесці да краю. Суняць — спыніць, пакуль да краю не дайшло. Мова адрознівае гэта старанна.", source: "Беларуская мова", theme: .peace, subtheme: .theWordsForStopping),

        Passage(text: "Цёплы вечар, ціхі вецер, свежы стог — улажылі спаць мяне вы на зямлі.", source: "Максім Багдановіч, «Вянок», 1913", theme: .peace, subtheme: .atEase),
        Passage(text: "Ад цяплосці не баляць косці.", source: "Беларуская прыказка", theme: .peace, subtheme: .atEase),
        Passage(text: "Прызба — земляны насып уздоўж сцяны, які і грэе хату, і служыць лаўкай. На ёй сядзелі вечарам і глядзелі на вуліцу.", source: "Этнаграфія", theme: .peace, subtheme: .atEase),
        Passage(text: "Самае цёплае месца ў хаце — на печы, і належала яно старым ды дзецям, а зусім не гаспадару.", source: "Этнаграфія", theme: .peace, subtheme: .atEase),
        Passage(text: "Заварожаны вячэрняй цішынёй — я не цямлю, дзе рука, дзе галава.", source: "Максім Багдановіч, «Вянок», 1913", theme: .peace, subtheme: .atEase),
        Passage(text: "Утульны ідзе ад дзеяслова туліцца, прыціскацца бліжэй. Утульная хата — не прыгожая, а такая, да якой туляцца.", source: "Этымалогія", theme: .peace, subtheme: .atEase),
        Passage(text: "Стог грэецца сам першыя дні пасля складання, і спаць на свежым сене цёпла нават у халодную жнівеньскую ноч.", source: "Гаспадарка", theme: .peace, subtheme: .atEase),
        Passage(text: "У лазні мыццё было толькі пачаткам. Далей сядзелі ў прыцемках і астывалі, і гэтая частка была не карацейшая.", source: "Этнаграфія", theme: .peace, subtheme: .atEase),
        Passage(text: "Ліпавы цвет заварвалі на вечар, і піўся ён паволі. Кубак такога чаю — гэта паўгадзіны, якія нікуды не вядуць.", source: "Народная медыцына", theme: .peace, subtheme: .atEase),
        Passage(text: "Дрымота — не сон і не ява. Асобнае слова на стан, у якім чалавек яшчэ чуе, але ўжо не думае.", source: "Беларуская мова", theme: .peace, subtheme: .atEase),
        Passage(text: "На Мядовы Спас у жніўні першы раз бралі свежы мёд. Елі яго проста так, седзячы, і больш нічога ў той дзень не рабілі.", source: "Беларускі народны каляндар", theme: .peace, subtheme: .atEase),
        Passage(text: "Наеўшыся, зубр кладзецца і жуе гадзіны чатыры запар. За гэты час ён не робіць болей зусім нічога.", source: "Заалогія", theme: .peace, subtheme: .atEase),
    ]
}
