import Foundation

/// The Hebrew passages.
///
/// Written rather than translated: about sixty of the English passages
/// are etymologies of English words and are simply false in any other
/// language, so this bank comes from its own word histories, its own
/// literature and its own proverbs.
extension Quotes {
    static let hebrew: [Passage] = [
        // MARK: Beginnings
        Passage(text: "נביטה: הקליפה נסדקת והשורשון יוצא ראשון, לפני העלה ולפני האור. הצמח מחפש מים לפני שהוא מחפש שמש.", source: "בוטניקה", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "אל פני ערוגה גחנתי לראות, אל פני ערוגה בגן: צבא אחים קטנים, נבטי אילנות, לב בוטח ושכם סבלן.", source: "רחל המשוררת, נבט", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "הנץ הוא הרגע שבו הפרח נפתח, ונץ החמה הוא הרגע שבו השמש עולה. הניצן הוא מה שעדיין לא הספיק להנץ.", source: "עברית", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "בשעה טובה: מה שאומרים למי שמשהו אצלו מתחיל – דירה, עבודה, תינוק. לא איחול להצלחה אלא איחול לתזמון.", source: "ניב עברי", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "לאפרוח יש על קצה המקור שן קטנה וקשה, ובה הוא שובר את הקליפה מבפנים. השן נושרת ימים אחדים אחרי הבקיעה ואינה חוזרת.", source: "זואולוגיה", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "חלל, חליל והתחלה יושבים כולם על אותן שלוש אותיות, ח־ל־ל. בכל אחד מהם משהו נפתח ומשהו עובר דרכו.", source: "עברית", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "בנובמבר 1963 ראו דייגים מול חופי איסלנד עשן עולה מן המים. כמה ימים אחר כך הופיעה שם אדמה, ולאי החדש נתנו שם.", source: "גאולוגיה", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "בקיעה: אותה מילה לאפרוח שיוצא מן הביצה ולסדק שנפתח בסלע. בשני המקרים משהו נפתח ואינו נסגר בחזרה.", source: "עברית", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "המילה הראשונה שחידש אליעזר בן־יהודה הייתה מילון. עד אז אמרו ספר מילים.", source: "תולדות הלשון", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "פתיחה: פתיחת דלת, המשפט הראשון של נאום, והמהלכים הראשונים במשחק שחמט. אותה מילה לשלושתם.", source: "עברית", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "האות א הייתה בכתב הקדום ציור של ראש שור, קרניים ומצח. אלפי שנים אחר כך היא עדיין ראשונה בשורה.", source: "תולדות הכתב", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "כשקרחון נסוג ומשאיר סלע חשוף, הראשונות שמגיעות אליו הן חזזיות. הן מפוררות את פני הסלע עד שיש בו די עפר לאחוז בו זרע.", source: "אקולוגיה", theme: .beginnings, subtheme: .theFirstAct),
        Passage(text: "זרע של סחלב קטן מגרגר אבק ואין בו מזון כלל. הוא נובט רק אם פגש בקרקע פטרייה מתאימה שתאכיל אותו בשנותיו הראשונות.", source: "בוטניקה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "שורש הוא גם החלק של הצמח שמתחת לאדמה וגם שלוש האותיות שמהן נבנית מילה עברית. שניהם קטנים, ושניהם מחזיקים את כל מה שצומח מהם.", source: "עברית", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "מן השורש כ־ת־ב צומחות כתב, מכתב, כתובת, מכתבה, כתבה, הכתיב והתכתב. שלוש אותיות ומהן משפחה שלמה.", source: "דקדוק עברי", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "עץ זית מתחיל לתת פרי אחרי כמה שנים ויכול להוסיף אלף. הגזע מתפורר מבפנים והעץ ממשיך לחיות בטבעת החיצונה שלו.", source: "בוטניקה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "בן־יהודה חידש כמאתיים ועשרים מילים, וכשלושה רבעים מהן נקלטו. רשימה קצרה של אדם אחד, ומיליונים מדברים בהן היום.", source: "תולדות הלשון", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "מה שנראה ביער כפטריות נפרדות הוא לרוב הגוף הפורה של רשת חוטים אחת מתחת לקרקע, הפרושה לפעמים על פני קילומטרים.", source: "מיקולוגיה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "מן המילה עת נגזר עיתון, ומן המילה מילה נגזר מילון. שתי מילים ישנות שהולידו שני דברים שלא היו קודם.", source: "עברית", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "דבורה פועלת אחת מייצרת בכל ימיה פחות מכפית דבש. הצנצנת שעל השולחן היא סכום של אלפי חיים קצרים.", source: "גידול דבורים", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "פיקוס בנגלי משלח שורשים אוויריים מן הענפים, וכשהם נוגעים באדמה הם מתעבים לגזעים. עץ אחד יכול להיראות בסוף כמו חורשה.", source: "בוטניקה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "כל פתית שלג מתחיל מגרגר אבק אחד שעליו נקרשים אדי מים. בלי הגרגר האוויר יכול להיות קר הרבה מתחת לאפס ולא יקרה דבר.", source: "מטאורולוגיה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "דיונה מתחילה מאבן או משיח שעוצרים את החול. החול נערם מאחוריהם, הערמה עוצרת עוד חול, וכך היא הולכת וגדלה מעצמה.", source: "גאוגרפיה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "בהלקט אחד של פרג יכולים להיות אלפי זרעים, כל אחד קטן מנקודה. הרוח מנערת אותם החוצה דרך חרכים קטנים, כמו ממלחייה.", source: "בוטניקה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "תא אחד שמתחלק פעמיים ביממה מגיע בשבוע לרבבות ובחודש למספר שקשה לכתוב. זו כל הסיבה שעובש מופיע פתאום.", source: "ביולוגיה", theme: .beginnings, subtheme: .smallToLarge),
        Passage(text: "עומק הזריעה קובע לשארית החיים. זרע שהוטמן עמוק מדי יכול לנבוט ולכלות את כל מזונו לפני שראה אור.", source: "חקלאות", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "יסוד: השכבה שנוצקת ראשונה ואינה נראית אחר כך. כל מה שנבנה מעליה עומד בדיוק במקום שהיא סימנה.", source: "הנדסת בניין", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "בעץ נשארת לנצח הדרך שבה גזמו אותו בשנותיו הראשונות. גנן מכריע בשלוש דקות איך ייראה העץ בעוד שישים שנה.", source: "גננות", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "טבעת צמיחה נקבעת בשנה שבה נוצרה ואינה משתנה עוד. שנה שחונה נשארת בגזע קו דק ודחוס, גם מאה שנה אחריה.", source: "בוטניקה", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "זרעים שנוצרו בשנה שחונה נובטים אחרת מזרעים של אותו צמח בשנה גשומה. מזג האוויר שבו נוצר הזרע נשאר בתוכו.", source: "בוטניקה", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "נהר חורץ את אפיקו באלף השנים הראשונות ואחר כך זורם בו עוד עשרות אלפים. הבחירה נעשתה מזמן, והמים רק ממשיכים בה.", source: "גאוגרפיה", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "מנהג: מה שקהילה עושה מפני שכך עשתה בפעם הראשונה. מאותו שורש גם נהיגה – מי שנוהג מוליך, וכולם נוסעים אחריו.", source: "עברית", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "הטבעה: אפרוח אווז שבקע רואה יצור נע וקובע שזו אמו. החלון פתוח לשעות ספורות, ומה שנכנס בו נשאר.", source: "התנהגות בעלי חיים", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "המשפט הראשון של ספר נכתב לרוב אחרון. אי אפשר להחליט מהיכן יוצאים לפני שיודעים לאן מגיעים.", source: "מלאכת הכתיבה", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "צלקת בגזע נשארת תמיד באותו גובה. העץ מוסיף טבעות מבחוץ ומתארך רק בקצוות, ולכן מסמר שנתקע בגובה מטר יישאר שם גם בעוד חמישים שנה.", source: "בוטניקה", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "המילה עגבנייה ניתנה לירק בידי הרב יחיאל מיכל פינס, מן השורש ע־ג־ב, כדי להקביל לשם שקראו לו באירופה: תפוח אהבה.", source: "תולדות הלשון", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "בן־יהודה התנגד למילה עגבנייה בשל אופייה והציע במקומה בדורה. הציבור בחר אחרת, והצעתו של מחיה השפה לא נקלטה.", source: "תולדות הלשון", theme: .beginnings, subtheme: .whatAStartSettles),
        Passage(text: "בכוורת חדשה בונות הדבורים תא ראשון, וכל התאים הבאים נבנים בזווית קבועה ממנו. הכיוון של החלה כולה נקבע בתא אחד.", source: "גידול דבורים", theme: .beginnings, subtheme: .whatAStartSettles),
        // MARK: Waiting
        Passage(text: "תרדמת זרעים: הזרע אינו נובט אף שיש לו מים, חום ואוויר. העיכוב בא מבפנים, ורק שינוי בתוכו יתיר אותו.", source: "בוטניקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "סבלנות באה מן השורש ס־ב־ל, לשאת משא. בעברית להמתין אינו לעמוד בלי לעשות דבר – זו עבודה שנושאים על הכתף.", source: "עברית", theme: .waiting, subtheme: .heldBack),
        Passage(text: "המתין ומתון חולקים שורש. מי שממתין אינו עצל אלא מאט, ואלה שני דברים שונים לגמרי.", source: "עברית", theme: .waiting, subtheme: .heldBack),
        Passage(text: "חצב פורח בלב הקיץ בלי עלה אחד. את העלים הוא יוציא רק אחרי הגשם, ואת כוחו הוא שומר עד אז בבצל שמתחת לאדמה.", source: "בוטניקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "גאופיט: צמח שמעביר את העונה הקשה כבצל או כפקעת מתחת לפני הקרקע, בלי עלה שייראה למעלה. רקפת וכלנית עושות כך כל קיץ.", source: "בוטניקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "כבש: לשמר ירק במלח ובמים, ולעצור רגש שביקש לצאת. אותו פועל לשניהם, ובשניהם הדבר נשמר דווקא בכך שלא ניתן לו לזוז.", source: "עברית", theme: .waiting, subtheme: .heldBack),
        Passage(text: "השהיית השרשה: אצל חלק מן היונקים העובר מפסיק להתפתח ונח ברחם שבועות או חודשים, עד שהעונה תתאים ללידה.", source: "זואולוגיה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "מים נקיים יכולים לרדת הרבה מתחת לאפס בלי לקפוא. חסר להם גרעין להתגבש עליו, ורגע אחרי שהוא מגיע כולם קופאים בבת אחת.", source: "פיזיקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "טמון, מטמון וטמיר יוצאים משורש אחד. מה שהוטמן אינו אבוד, והשפה מחזיקה את זה בשלוש מילים שונות.", source: "עברית", theme: .waiting, subtheme: .heldBack),
        Passage(text: "התאפקות: לעצור בעצמך מה שאיש אינו עוצר. השורש א־פ־ק נותן גם אפיק – התעלה שבתוכה המים מוכרחים לזרום.", source: "עברית", theme: .waiting, subtheme: .heldBack),
        Passage(text: "זרעי צמחים ממדבריות נובטים רק אחרי כמות גשם מסוימת. פחות מזה והזרע יישאר סגור, מפני שגשם קטן מדי לא יספיק לו עד הפריחה.", source: "בוטניקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "ניצן חורף עטוף בקשקשים קשים והוא מוכן כבר בסתיו. כל האביב כבר ארוז בו, ומחכה רק לאורך היום הנכון.", source: "בוטניקה", theme: .waiting, subtheme: .heldBack),
        Passage(text: "זרעי לוטוס שנמצאו בקרקעית אגם בסין נבטו אחרי כמה מאות שנים. הקליפה עבה כל כך שכמעט שום דבר אינו חודר דרכה.", source: "בוטניקה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "מילון בן־יהודה יצא בהמשכים משנת 1908 ועד 1959, שישה עשר כרכים. המחבר מת ב־1922, ואחרים סיימו את מה שהתחיל.", source: "תולדות הלשון", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "לוח השנה העברי מוסיף חודש שלם שבע פעמים בכל תשע עשרה שנה, וכך החגים נשארים בעונה שלהם. החשבון סוגר את עצמו בדיוק.", source: "לוח השנה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "נטיף במערה מתארך בסנטימטר אחד במאות שנים. מי שנכנס למערה רואה טיפה שנופלת, ולא רואה כלום ממה שהיא עושה.", source: "גאולוגיה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "יש מיני אגבה שגדלים עשרות שנים בלי לפרוח, מוציאים גבעול פריחה אחד בגובה כמה מטרים, ומתים אחריו.", source: "בוטניקה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "ציקדות מחזוריות נשארות באדמה שלוש עשרה או שבע עשרה שנה, שני מספרים ראשוניים, ואז יוצאות כולן יחד באותו שבוע.", source: "אנטומולוגיה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "בהרים הגבוהים של מערב אמריקה גדלים אורנים על סלע עני ובקור, לאט מאוד. בכמה מהם נספרו קרוב לחמשת אלפים טבעות.", source: "בוטניקה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "אלבטרוס דוגר קרוב לשמונים יום, ושני ההורים מתחלפים. מי שתורו לשבת יושב שבועות בלי לאכול, עד שהאחר חוזר מן הים.", source: "זואולוגיה", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "בבנק גנים שומרים זרעים בקור עמוק, יבשים ואטומים. הם אינם מתים ואינם נובטים, ופשוט ממתינים לשנה שבה יבקשו אותם.", source: "חקלאות", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "ותיק: מי שהיה במקום זמן רב. המילה אומרת בבת אחת כמה זמן עבר ומה הזמן הזה עשה בו.", source: "עברית", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "אלמוגי מים עמוקים גדלים כמה מאות מיקרונים בשנה. שיח בגודל כף יד יכול להיות בן כמה מאות שנים.", source: "ביולוגיה ימית", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "אמפורה של יין ששקעה בקרקעית הים נשארת שם בטמפרטורה קבועה ובחושך. תנאי האחסון הטובים ביותר שיש הם תאונה.", source: "ארכאולוגיה ימית", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "עונה שלמה עוברת בין הפריחה של עץ אגוז לבין הפרי. העץ פורח לפני שיצאו העלים, כשעדיין קר, ואינו ממהר אחר כך.", source: "חקלאות", theme: .waiting, subtheme: .theLongCount),
        Passage(text: "ציפייה באה מן השורש צ־פ־ה, להביט. בעברית לקוות למשהו זה לעמוד ולהסתכל לכיוון שממנו הוא אמור לבוא.", source: "עברית", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "ואוזן להטות לקול רשרוש עלים, ולפלל לנס, וליחל לאות.", source: "רחל המשוררת, ציפייה", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "מצפה הוא גם ראש גבעה שממנו רואים למרחוק וגם הבניין שבו יושבים ומביטים בכוכבים. שתי הסתכלויות, מילה אחת.", source: "עברית", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "שומרה: סוכת אבן או ענפים שבנו בקצה הכרם, ובה ישבו לילות שלמים בעונת הפרי ולא עשו דבר מלבד להביט.", source: "חקלאות מסורתית", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "אנפה יכולה לעמוד ברגל אחת במים דקות ארוכות בלי לזוז כלל. הציד שלה הוא כמעט כולו עמידה, והתנועה נמשכת שבריר שנייה.", source: "זואולוגיה", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "מן החלון פרח עציץ כל היום הגנה יציץ. כל חבריו – שם בגן, הוא לבדו עומד כאן.", source: "חיים נחמן ביאליק, עציץ פרחים", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "כלב מזהה את הרעש של מכונית אחת מתוך כל המכוניות ברחוב, ועובר אל הדלת כמה שניות לפני שמישהו בבית שמע משהו.", source: "התנהגות בעלי חיים", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "בצילום אסטרונומי ארוך המצלמה נשארת פתוחה שעות. התמונה אינה מתקבלת מפני שהוסיפו אור אלא מפני שלא מיהרו לסגור.", source: "אסטרונומיה", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "משמרת, שמורה ומשמר יוצאים כולם מן השורש ש־מ־ר. בעברית לשמור על משהו זה בעיקר להישאר לידו.", source: "עברית", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "צופה בעברית הוא גם מי שיושב בראש גבעה ומביט למרחוק וגם מי שיושב בסלון ומביט במסך. אותה מילה לשני סוגי הישיבה.", source: "עברית", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "פינגווין קיסר עומד בחושך החורף האנטארקטי כשלושה חודשים עם ביצה על הרגליים, מכונס עם אלפים אחרים בעיגול שמסתובב לאט.", source: "זואולוגיה", theme: .waiting, subtheme: .standingAndWatching),
        Passage(text: "בעונת הנדידה עומדים סופרי ציפורים בשדות משעות לפני אור ראשון, וסופרים את מה שעובר מעליהם עד שהאור חזק מדי.", source: "אורניתולוגיה", theme: .waiting, subtheme: .standingAndWatching),
        // MARK: Renewal
        Passage(text: "הן לא חרשתי, גם לא זרעתי, לא התפללתי על המטר. ופתע, ראה נא! שדותיי הצמיחו דגן ברוך שמש במקום דרדר.", source: "רחל המשוררת, ספיח", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "ספיח: התבואה שעולה מאליה בשנה שאחרי הקציר, מגרגרים שנשרו ולא נאספו. איש לא זרע אותה ואיש אינו יודע כמה תעלה.", source: "חקלאות", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "כורתים אקליפטוס סמוך לאדמה והגדם מוציא נצרים חדשים. אפשר לחזור על זה עשרות פעמים, והשורש שמתחת רק מתעבה.", source: "ייעור", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "נצר הוא הענף שיוצא מגדם כרות. מאותו שורש גם צאצא – מה שיוצא ממי שכבר היה.", source: "עברית", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "גפן שאיש אינו גוזם מוציאה עלים רבים וענבים מעטים. הגיזום החורפי נראה אכזרי, והוא כל מה שהופך שיח לכרם.", source: "גידול גפנים", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "אחרי שרפה בחורש הים־תיכוני חוזר האלון לצמוח מן השורש ולא מן הזרע. מה שנשרף למעלה נשאר שלם למטה.", source: "אקולוגיה", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "נחש משיל את עורו בחתיכה אחת, מן החוטם ולאחור, כמו גרב שמתהפכת. גם העדשות שעל עיניו יוצאות עם העור.", source: "זואולוגיה", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "לטאה שמשילה את זנבה מגדלת אחר כך זנב אחר, מסחוס ולא מעצם. הוא דומה למדי, ובכל זאת אחר.", source: "זואולוגיה", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "חידוש בלשון הוא כמעט תמיד מילה חדשה מחומר ישן: לוקחים שורש שכבר קיים ויוצקים אותו למשקל אחר.", source: "האקדמיה ללשון העברית", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "מדשאה נשארת מדשאה רק מפני שכוסחים אותה. הדשא צומח מן הבסיס ולא מן הקצה, ולכן חיתוך הראש אינו פוגע בו כלל.", source: "גננות", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "עצי פרי רבים אינם נותנים אותה כמות בכל שנה. שנה של שפע מרוקנת את המאגרים, ובשנה שאחריה העץ נח כמעט לגמרי.", source: "חקלאות", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "מרעה שאין בו בעלי חיים כלל הופך לשיחים ואז ליער. עדר שעובר בו פעם בעונה משאיר אותו שדה פתוח לדורות.", source: "אקולוגיה", theme: .renewal, subtheme: .cutAndComeAgain),
        Passage(text: "יד אביב בקשר הזה... אדם מקיץ משנה ורואה: מול חלונו עץ אגס מלבלב. ובן רגע: ההר זה רבץ על הלב התפורר ואינו.", source: "רחל המשוררת, עץ אגס", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "יורה הוא שם הגשם הראשון של העונה ומלקוש שם האחרון. שתי מילים שאינן אומרות כמה ירד אלא היכן אנחנו בשנה.", source: "עברית", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "בתל גזר נמצא ב־1908 לוח אבן קטן ועליו שמונה עונות של שנת עבודה: חודשי אסיף, חודשי זרע, חודש קציר, חודש זמיר.", source: "ארכאולוגיה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "השקדייה פורחת בשבט, כשעדיין קר וכל השאר עוד סגור. היא פורחת לפני שיצאו לה עלים, ולכן העץ נראה כולו לבן.", source: "בוטניקה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "שלכת: העץ אינו מאבד את עליו אלא משליך אותם. הוא בונה שכבת פקק בבסיס כל עלה ומנתק אותו בעצמו, לפני שהקור יעשה זאת.", source: "בוטניקה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "ציפורים נודדות יוצאות בערך באותו שבוע בכל שנה, גם כשהיא חמה מן הרגיל. הן מודדות את אורך היום, ואורך היום אינו משקר.", source: "אורניתולוגיה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "היום הקצר בשנה אינו היום הקר בשנה. הים והאדמה מאחרים בכמה שבועות אחרי השמש, ולכן השיא של הקור בא כשכבר מאיר יותר.", source: "מטאורולוגיה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "תתחדש: מה שאומרים למי שלבש בגד חדש או קנה משהו. לא ברכה לחפץ אלא לאדם – שאתה תהיה חדש, לא רק המעיל.", source: "ניב עברי", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "המילה אביב הייתה קודם שם של שיבולת בשלב מסוים של הבשלה, ורק אחר כך נעשתה שם של עונה. העונה קרויה על שם מה שקורה בה.", source: "עברית", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "אין מים חדשים. כל טיפה שיורדת הייתה כבר ים, נהר וענן, וכל מה שקורה במחזור הזה הוא שהיא עוברת שוב באותו מסלול.", source: "הידרולוגיה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "שרב: רוח יבשה וחמה שבאה מן המזרח באביב ובסתיו ומייבשת הכול ביום אחד. אחריה, לרוב, משהו במזג האוויר משתנה.", source: "מטאורולוגיה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "עונות המעבר בארץ קצרות מאוד, ולפעמים נמשכות שבועיים. שאר השנה מחולקת בין שני מצבים ברורים, ואין הרבה באמצע.", source: "אקלים", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "רקפת נובלת בכל אביב ונעלמת לגמרי מפני השטח. הפקעת נשארת באותו סדק בסלע, ובאותו סדק בדיוק היא תופיע גם בעוד עשר שנים.", source: "בוטניקה", theme: .renewal, subtheme: .theTurningYear),
        Passage(text: "רפואה שלמה: מה שמאחלים לחולה. שלמה היא מאותו שורש כמו שלום – להבריא בעברית הוא לחזור להיות שלם.", source: "ניב עברי", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "השלמה ותשלום יוצאים מאותו שורש. לשלם חוב אינו למסור כסף אלא להחזיר משהו למצב שלם, ולכן זה נגמר.", source: "עברית", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "איחוי: תפירת פצע, וגם הצמיחה שמחברת שני חלקים של עצם שנשברה. בשבר שהתאחה נבנה עיבוי, ולעיתים הוא חזק שם מכפי שהיה.", source: "רפואה", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "פצע בגזע נסגר מן השוליים פנימה, טבעת אחרי טבעת. העץ אינו מרפא את החור אלא גדל סביבו עד שלא רואים אותו.", source: "בוטניקה", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "פיוס והתפייסות יוצאים משורש אחד. להתפייס אפשר רק בשניים, וזה כתוב בצורת הפועל עצמה.", source: "עברית", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "הכבד הוא האיבר היחיד בגוף האדם שגדל בחזרה כמעט לגמרי אחרי שחתכו ממנו חלק. הוא מגיע לגודלו הקודם תוך שבועות.", source: "רפואה", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "כתובת השילוח נשברה לחתיכות כשעקרו אותה מן הקיר ב־1890. את השברים הדביקו זה לזה, וכך היא עומדת עד היום.", source: "ארכאולוגיה", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "מוסיפים לבטון גרגרים של חיידקים רדומים ואבן גיר. כשנסדק הבטון נכנסים מים, החיידקים מתעוררים, והסדק נסתם מבפנים.", source: "הנדסת חומרים", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "בשחזור של ציור מקפידים שכל תוספת תהיה הפיכה. מי שמתקן היום חייב להשאיר למי שיבוא בעוד מאה שנה את האפשרות לפרק.", source: "שימור אמנות", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "מים עכורים בבריכה נעשים צלולים אם רק מניחים להם. החלקיקים אינם נעלמים – הם שוקעים, וזה כל ההבדל.", source: "פיזיקה", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "שבר של אלמוג שנשמט מן השונית ונח על קרקעית מתאימה ממשיך לגדול משם. אותו יצור בדיוק, במקום אחר.", source: "ביולוגיה ימית", theme: .renewal, subtheme: .madeWhole),
        Passage(text: "מרפא בעברית הוא גם מי שמרפא וגם המקום שאליו נוסעים כדי להבריא. עיר מרפא, מי מרפא, צמח מרפא.", source: "עברית", theme: .renewal, subtheme: .madeWhole),
        // MARK: Light
        Passage(text: "על בוקר טוב עונים בעברית בוקר אור. התשובה מוסיפה לברכה משהו שלא היה בה.", source: "ניב עברי", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "אור ראשון בא לפני הזריחה. השמש עדיין מתחת לקו האופק, והאוויר כבר מכופף את האור מעליה ומאיר את השמיים.", source: "אופטיקה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "דמדומים: שם אחד לשתי שעות שונות – זו שלפני הזריחה וזו שאחרי השקיעה. השפה נותנת לשתיהן את אותו שם.", source: "עברית", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "ערב, עירבוב ומערב נכתבים באותן שלוש אותיות: ע־ר־ב. הצד שאליו האור הולך, והשעה שבה הוא מתערבב בחושך.", source: "עברית", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "מקהלת השחר מתחילה כשעדיין חשוך. הציפורים בעלות העין הגדולה פותחות ראשונות, מפני שהן רואות מוקדם יותר.", source: "אורניתולוגיה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "בבוקר ובערב האור עובר דרך שכבת אוויר עבה פי כמה מאשר בצהריים. זו כל הסיבה שהוא צהוב אז, ואדום עוד קודם.", source: "אופטיקה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "הצל הארוך ביותר של אדם נמדד בדקות הראשונות ובדקות האחרונות של האור. באמצע היום כמעט אין לו צל בכלל.", source: "אסטרונומיה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "צהריים נושאת את סיומת הזוגי, כמו עיניים ואוזניים. שני חצאי היום נפגשים בדיוק שם.", source: "עברית", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "בין הערביים: הזמן שבין השקיעה לחשכה. שעה העומדת בפני עצמה, ובעברית יש לה שם משלה.", source: "עברית", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "שחר ושחור יושבים על אותן שלוש אותיות, ש־ח־ר: הרגע שבו החושך נגמר, והמילה לחושך עצמו.", source: "עברית", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "רוב הצמחים פותחים את הפיוניות שבעלים בבוקר וסוגרים אותן בחום היום. העלה נושם בקצוות היום ועוצר באמצע.", source: "בוטניקה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "עטלפים יוצאים בערך באותן דקות אחרי השקיעה בכל ערב. הם אינם מודדים שעה אלא את קצב הדעיכה של האור.", source: "זואולוגיה", theme: .light, subtheme: .theEdgesOfTheDay),
        Passage(text: "משחירה אדמה נחרשת, פני המים – תכלת ואור, מוריקה בשורת הדשא בחגווי הגבעות, במסתור.", source: "רחל המשוררת, צבעים", theme: .light, subtheme: .readingTheLight),
        Passage(text: "המון גשם חדל, אך נטפי הגשם עוד נוצצים בין חציר כספיר ולשם.", source: "חיים נחמן ביאליק, קשת", theme: .light, subtheme: .readingTheLight),
        Passage(text: "הצהוב שבעלה בסתיו היה שם כל הקיץ. הוא פשוט היה מוסתר מתחת לירוק, ורק כשהירוק נמשך החוצה אפשר לראות אותו.", source: "בוטניקה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "טבעת חיוורת סביב הירח נוצרת מגבישי קרח בעננים גבוהים. במקומות רבים ראו בה סימן שגשם מתקרב, ולעיתים קרובות צדקו.", source: "מטאורולוגיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "צמח פונה אל האור מפני שהתאים בצד המוצל מתארכים יותר. הוא אינו נמשך אל השמש אלא גדל מן הצל.", source: "בוטניקה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "לינאוס הציע לשתול ערוגה שבה כל פרח נפתח בשעה אחרת, וכך יהיה אפשר לקרוא את השעה מן הגינה בלי שעון.", source: "תולדות הבוטניקה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "לדבורה יש קולטן לאור אולטרה־סגול. פרחים שנראים לנו חלקים ולבנים נראים לה מסומנים בקווים שמובילים אל הצוף.", source: "אנטומולוגיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "גם ביום מעונן אור השמיים מקוטב בתבנית קבועה סביב השמש. דבורים קוראות את התבנית הזאת ויודעות היכן השמש בלי לראותה.", source: "אנטומולוגיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "העין האנושית רגישה יותר לירוק־צהוב מלכל צבע אחר. לכן אפודי הבטיחות בצבע הזה, ולא באדום שנראה בוער יותר.", source: "פיזיולוגיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "בזמן ליקוי חמה, הכתמים שבין עלי העץ על הרצפה מקבלים צורת סהר. כל פרצה קטנה בין העלים היא מצלמת חור־סיכה.", source: "אופטיקה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "צבע הים אינו של המים אלא של השמיים שמעליו ושל מה שתלוי בו. ים ירוק לרוב עשיר באצות, וים כחול עמוק ריק יחסית.", source: "אוקיינוגרפיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "כשהאוויר יבש רואים את ההרים הרחוקים בבירור. חדות הראייה למרחוק אינה סימן לאור טוב אלא לכך שאין לחות בדרך.", source: "מטאורולוגיה", theme: .light, subtheme: .readingTheLight),
        Passage(text: "אשמורת: חלוקת הלילה לפי משמרות שמירה, ולא לפי שעות. הזמן נמדד לפי מי שהיה ער ושמר, ולא לפי מחוגים.", source: "עברית", theme: .light, subtheme: .readingTheLight),
        Passage(text: "לא זכיתי באור מן ההפקר, אף לא בא לי בירושה מאבי, כי מסלעי וצורי ניקרתיו וחצבתיו מלבבי.", source: "חיים נחמן ביאליק", theme: .light, subtheme: .lightItself),
        Passage(text: "אביט אל על: האור מה רב! וגם בלב כבילדות אף צל של עב.", source: "רחל המשוררת, שבת", theme: .light, subtheme: .lightItself),
        Passage(text: "מאור פנים הוא הארשת של אדם ששמח לראות אותך. בעברית נתנו לזה שם של אור.", source: "ניב עברי", theme: .light, subtheme: .lightItself),
        Passage(text: "המילה חשמל הייתה שם של זוהר עתיק, ובעברית החדשה ניתנה לכוח שמדליק את הנורה. ארבע אותיות, אלפי שנים, שני דברים.", source: "עברית", theme: .light, subtheme: .lightItself),
        Passage(text: "פוטון עובר מפני השמש עד לכאן בכשמונה דקות, אבל את הדרך מגרעין השמש אל פניה הוא עושה במשך אלפי שנים.", source: "אסטרופיזיקה", theme: .light, subtheme: .lightItself),
        Passage(text: "אור הירח הוא אור השמש. הירח מחזיר רק חלק קטן ממה שנופל עליו, וזה עדיין די כדי לקרוא לאורו בחוץ.", source: "אסטרונומיה", theme: .light, subtheme: .lightItself),
        Passage(text: "גחלילית מייצרת אור כמעט בלי חום. זו התאורה היעילה ביותר שיש, ואיש עוד לא הצליח לבנות נורה שתשווה לה.", source: "אנטומולוגיה", theme: .light, subtheme: .lightItself),
        Passage(text: "בעומק הים, שאין בו שמש כלל, רוב היצורים מייצרים אור בעצמם. החושך הגדול ביותר שיש הוא גם המקום המואר ביותר מבפנים.", source: "ביולוגיה ימית", theme: .light, subtheme: .lightItself),
        Passage(text: "העין צריכה כחצי שעה בחושך כדי להגיע לרגישות מלאה, ורגע אחד של אור לבן מבטל את כל ההסתגלות הזאת.", source: "פיזיולוגיה", theme: .light, subtheme: .lightItself),
        Passage(text: "שנת אור אינה זמן אלא מרחק: הדרך שהאור עובר בשנה. כשמודדים מרחק בין כוכבים, מודדים אותו בזמן.", source: "אסטרונומיה", theme: .light, subtheme: .lightItself),
        Passage(text: "נר של שעווה שורף בעצם את הפתילה ואת האוויר סביבה. הלהבה אינה על הפתילה אלא בשוליה, ובאמצע יש חלל קר יחסית.", source: "כימיה", theme: .light, subtheme: .lightItself),
        Passage(text: "בעברית קוראים לחלון מסוג מסוים צוהר, ומאותו שורש גם צהריים. פתח בגג שנקרא על שם השעה שבה הוא מכניס הכי הרבה אור.", source: "עברית", theme: .light, subtheme: .lightItself),
        // MARK: Pattern
        Passage(text: "בעברית המספרים מקבלים מין הפוך למה שהם סופרים: שלושה ילדים אבל שלוש ילדות. אין לזה הסבר טוב, ואיש אינו טועה בזה.", source: "דקדוק עברי", theme: .pattern, subtheme: .counted),
        Passage(text: "לאותיות העבריות יש ערך של מספר, ובהן כותבים תאריכים עד היום. חמש עשרה ושש עשרה נכתבות בסדר אחר מכל השאר, ט״ו וט״ז.", source: "עברית", theme: .pattern, subtheme: .counted),
        Passage(text: "לעברית יש צורת זוגי משלה, לדברים שבאים בשניים: אופניים, משקפיים, מספריים, נעליים. גם שעתיים ויומיים נבנו כך.", source: "דקדוק עברי", theme: .pattern, subtheme: .counted),
        Passage(text: "בעברית ימי השבוע נקראים במספרים – ראשון, שני, שלישי – ורק לשביעי יש שם. שישה ימים סופרים, ואחד קוראים בשמו.", source: "לוח השנה", theme: .pattern, subtheme: .counted),
        Passage(text: "שבע אותיות בעברית יכולות להיצמד לראש מילה ולשנות את משמעה: ו, ב, כ, ל, מ, ש, ה. אות אחת עושה את מה ששפות אחרות עושות במילה.", source: "דקדוק עברי", theme: .pattern, subtheme: .counted),
        Passage(text: "אמה: מידת האורך שנמדדה מן המרפק ועד קצה האצבע. בניין שלם היה נמדד לפי זרוע של אדם אחד, ולכן אין לה גודל אחד בכל מקום.", source: "מידות עתיקות", theme: .pattern, subtheme: .counted),
        Passage(text: "החודש הירחי אורכו כתשעה ועשרים יום וחצי. לכן חודשי הלוח העברי מתחלפים בין תשעה ועשרים לשלושים, כדי לסגור על החצי.", source: "לוח השנה", theme: .pattern, subtheme: .counted),
        Passage(text: "בכל בני משפחת הוורדיים – שקד, תפוח, אגס, שזיף, ורד – יש חמישה עלי כותרת. אפשר לזהות משפחה שלמה בספירה אחת.", source: "בוטניקה", theme: .pattern, subtheme: .counted),
        Passage(text: "מספר ראשוני הוא מספר שאי אפשר לסדר בשורות שוות. שלושה עשר חפצים יסתדרו רק בשורה אחת ארוכה, או אחד־אחד.", source: "מתמטיקה", theme: .pattern, subtheme: .counted),
        Passage(text: "שעה זמנית: בשיטה עתיקה חילקו את היום לשתים עשרה שעות בכל עונה. לכן שעת קיץ ארוכה משעת חורף, וזה בסדר גמור.", source: "מדידת זמן", theme: .pattern, subtheme: .counted),
        Passage(text: "לאלפבית העברי עשרים ושתיים אותיות, וכולן עיצורים. חמש מהן לובשות צורה אחרת כשהן עומדות בסוף מילה.", source: "תולדות הכתב", theme: .pattern, subtheme: .counted),
        Passage(text: "כשסופרים גרעינים ברימון אחד מקבלים כמה מאות, וכמעט תמיד מספר אחר. הסדר הפנימי קבוע, המספר לא.", source: "בוטניקה", theme: .pattern, subtheme: .counted),
        Passage(text: "בבנייה יבשה מניחים אבן על אבן בלי מלט. כל אבן נבחרת לפי החלל שנשאר, והקיר עומד מכוח החיכוך והמשקל בלבד.", source: "בנייה מסורתית", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "מילה עברית נוצרת כששורש נכנס לתוך תבנית. אותן שלוש אותיות בתבנית אחת נותנות מכתב, ובאחרת מכתבה.", source: "דקדוק עברי", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "תא הדבש הוא משושה מפני שזו הצורה שממלאת מישור בלי חורים ומבזבזת הכי מעט שעווה על הדפנות.", source: "גאומטריה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "פסיפס נעשה מאבנים קטנות שכל אחת נחתכת לפי שכנתה. המרווח ביניהן הוא חלק מן הציור ולא פגם בו.", source: "אמנות", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "המילה תשבץ נלקחה משיבוץ – הושבת אבן בתוך טבעת. פתרון תשבץ הוא הכנסת מילה למקום שנחתך בדיוק לפי מידתה.", source: "עברית", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "עצמות הגולגולת מחוברות בקווים משוננים כמו שיני מסור. הן אינן מודבקות אלא נעוצות זו בזו, ולכן אינן זזות.", source: "אנטומיה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "קשת אבן עומדת רק אחרי שהונחה האבן האחרונה באמצע. עד אז היא ערמה שנתמכת בפיגום, ומאז היא נושאת את עצמה.", source: "הנדסת בניין", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "סמיכות: שתי מילים נצמדות עד שהראשונה משנה צורה. בית ועוד ספר נעשים בית ספר, ואי אפשר לתחוב ביניהם דבר.", source: "דקדוק עברי", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "מבין המצולעים המשוכללים רק שלושה מרצפים מישור בלי להשאיר חלל: משולש, ריבוע ומשושה. השאר תמיד ישאירו פער.", source: "גאומטריה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "רעפים מונחים בחפיפה כך שכל אחד מכסה את התפר של השניים שמתחתיו. הגג אטום לא בגלל הרעף אלא בגלל הסדר.", source: "בנייה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "באצטרובל של אורן הקשקשים סדורים בשני כיווני לוליינים המצטלבים. אפשר לספור אותם לשני הכיוונים ולקבל שני מספרים שונים.", source: "בוטניקה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "שני חלקים של סרגל חישוב, של מנעול או של מפרק עובדים רק אם עשו אותם יחד. חלק חלופי שנעשה בנפרד כמעט תמיד ישאיר מרווח.", source: "מכניקה", theme: .pattern, subtheme: .fittedTogether),
        Passage(text: "האקדמיה ללשון העברית הוקמה בחוק ב־1953 והיא ממשיכתו של ועד הלשון משנת 1890. החלטותיה מחייבות משרדים, ולא אנשים.", source: "תולדות הלשון", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "לכל מין של צמח ובעל חיים נקבע גם שם עברי, ולא רק שם מדעי. יש ועדות שיושבות ובוחרות אותם, מין אחר מין.", source: "האקדמיה ללשון העברית", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "שם מדעי בנוי משתי מילים: הסוג ואחריו המין. הראשונה אומרת עם מי הוא קרוב, והשנייה במה הוא נבדל מהם.", source: "מיון ביולוגי", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "כדורגל, כדורסל וכדוריד נבנו כולם באותה דרך: כדור ועוד המילה למה שעושים בו. שלושה משחקים, תבנית אחת.", source: "עברית", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "שמות החודשים העבריים – ניסן, אייר, תמוז, תשרי – נלקחו מן הלוח הבבלי. שפה אחת שמרה על מניין הזמן של שפה אחרת.", source: "לוח השנה", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "הכינרת קרויה כך, לפי ההסבר המקובל, על שם הכינור: מלמעלה צורתה דומה לכלי הזה. שם של אגם שנלקח מכלי נגינה.", source: "גאוגרפיה", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "המילה ורוד קרויה על שם הוורד: הצבע לובש את שמו של הפרח שהוא נראה כמותו.", source: "עברית", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "שמות בעלי המקצוע בעברית נבנים כמעט כולם בתבנית אחת: נגר, סנדלר, חייט, טבח, ספר. שומעים את המשקל ויודעים שזה מקצוע.", source: "דקדוק עברי", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "סימני הניקוד הומצאו כדי שאפשר יהיה לקרוא אותו טקסט פעמיים באותו אופן. הם אינם אותיות אלא הוראות הפעלה.", source: "תולדות הכתב", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "כתיב מלא: הכללים שקובעים מתי מוסיפים יוד או וו כשאין ניקוד. בלעדיהם אותה מילה יכולה להיקרא בכמה דרכים.", source: "האקדמיה ללשון העברית", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "מיון: הצבת יצור בתוך קבוצה שמכילה אותו, שמונחת בתוך קבוצה גדולה יותר. השם הוא הכתובת, לא התיאור.", source: "מיון ביולוגי", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "בן־יהודה הציע שם לפסנתר, שם לגפרור ושם לפטיפון, ואף אחד מהם לא נקלט. השפה קיבלה ממנו מאות מילים ודחתה עשרות.", source: "תולדות הלשון", theme: .pattern, subtheme: .orderNamed),
        Passage(text: "לרוב הכוכבים הבהירים יש שם ערבי, מפני שאירופה קיבלה אותם מספרי אסטרונומיה בערבית. השמות נסעו עם הידע.", source: "אסטרונומיה", theme: .pattern, subtheme: .orderNamed),
        // MARK: Ground
        Passage(text: "אדם ואדמה יושבים על אותן שלוש אותיות, ושתיהן היו בשפה מן ההתחלה. אי אפשר להגיד את האחת בלי לשמוע את השנייה.", source: "עברית", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "חמרה: האדמה האדמדמה של מישור החוף, חול דק שברזל צבע אותו. השם בא מן המילה הערבית לאדום.", source: "קרקעות", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "לס: אבק שהרוח נשאה ממדבר והשקיעה בשכבות. הוא פורה מאוד, ובגשם הוא נאטם מלמעלה, ולכן המים זורמים ממנו ואינם נכנסים.", source: "קרקעות", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "אדמת החרסית מתבקעת בקיץ לסדקים עמוקים ונסגרת בחורף. השדה נושם, וכל שנה הוא בולע לתוכו קצת ממה שנשאר עליו.", source: "קרקעות", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "שכבת האדמה הפורייה נבנית בקצב של סנטימטר אחד בכמה מאות שנים, מעלים שנופלים ומיצורים קטנים שאוכלים אותם.", source: "קרקעות", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "תולעת אדמה מעבירה דרך גופה בשנה כמות עפר שגדולה ממשקלה פי כמה. הגן מתהפך לאט מלמטה, ואיש אינו רואה את זה קורה.", source: "אקולוגיה", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "מיקוריזה: פטרייה שנכרכת סביב שורש ומרחיבה אותו פי כמה. רוב הצמחים בעולם אינם אוכלים לבד, והגן שלמטה גדול מזה שלמעלה.", source: "בוטניקה", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "הריח שעולה מאדמה יבשה בגשם הראשון בא משמנים שהצמחים הפרישו בקיץ ומחיידקי קרקע שמתעוררים ברטיבות.", source: "כימיה", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "בסלע גיר הגשם אינו נשאר על פני השטח אלא נכנס לסדקים ומרחיב אותם. אחרי אלפי שנים ההר עשוי חורים, והמים כולם בפנים.", source: "גאולוגיה", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "השקיה בלי ניקוז משאירה מלח באדמה, שנה אחרי שנה. שדות שהתמלחו כך יצאו מכלל שימוש עוד בעולם העתיק.", source: "חקלאות", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "רגב: גוש אדמה שנשבר מן המחרשה. גוש עפר אחד, ולו מילה משלו בעברית.", source: "עברית", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "בכף אחת של אדמת גן יש יותר יצורים חיים מבני אדם על פני כדור הארץ. רובם עדיין ממתינים למי שיספור אותם וייתן להם שם.", source: "מיקרוביולוגיה", theme: .ground, subtheme: .theSoilItself),
        Passage(text: "חצב קשה מאוד לעקירה, בצלו יורד עמוק והוא רעיל לחיות. לכן שתלו שורה של חצבים כדי לסמן גבול שדה, וזה החזיק דורות.", source: "חקלאות מסורתית", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "שכן, שכונה ומשכן יוצאים כולם מן השורש ש־כ־ן, לשבת במקום. שכן הוא מי ששוכן, כמוך, וזה כל מה שהמילה אומרת עליו.", source: "עברית", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "איני רואה אותו. אבל אני זוכרת. זוכרת אל נכון: הוא כאן, ישנו.", source: "רחל המשוררת, שכן", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "משעולי השדות ושבילים החוצים, מפרידים, מגבילים; לא יוכר מקומם, יטושטש – בשפעת האביב החדש.", source: "רחל המשוררת", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "אנדמי: מין שגדל במקום אחד ובשום מקום אחר בעולם. אין זה שהוא נדיר – הוא פשוט מכאן.", source: "אקולוגיה", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "כמעט לכל אזור בארץ יש מין אירוס משלו, וכל אחד מהם גדל שם ולא במקום אחר. אפשר לדעת היכן אתה לפי הפרח.", source: "בוטניקה", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "כתובת בעברית היא גם המקום שבו גרים וגם משהו שנחרת באבן. מילה אחת לשניהם, ושתי המשמעויות אומרות: כאן.", source: "עברית", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "טעם מי הבאר משתנה לפי הסלע שדרכו עברו. אותו גשם בדיוק, ושתי בארות במרחק קילומטר נותנות שני טעמים.", source: "הידרולוגיה", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "ציפורי שיר לומדות את השיר מן המבוגרים שסביבן. לאותו מין יכולים להיות ניבים שונים בשני עמקים שכנים.", source: "אורניתולוגיה", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "סיקול: הוצאת האבנים משדה והנחתן בשוליו. ערמות האבנים שבקצה חלקה ישנות לרוב מכל מה שגדל בה מאז.", source: "חקלאות מסורתית", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "בית בעברית הוא גם מבנה וגם בית בשיר, וגם שמה של האות השנייה. מבנה, שורה ואות – שלושתם נקראים בשם של מגורים.", source: "עברית", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "שן הארי מייצרת זרעים בלי הפריה, ולכן כל אוכלוסייה היא כמעט העתק של עצמה. בוטנאים סופרים בה מאות זנים זעירים, כל אחד מקומי.", source: "בוטניקה", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "דבורים אוספות ברדיוס של כמה קילומטרים סביב הכוורת. טעם הדבש הוא בעצם רשימה של מה שפרח באותו רדיוס באותו חודש.", source: "גידול דבורים", theme: .ground, subtheme: .aPlaceYouAreFrom),
        Passage(text: "פרדס בא מפרסית עתיקה ופירושו גן מוקף חומה. אותה מילה נדדה ליוונית ומשם לשפות אירופה, ונעשתה שמו של גן העדן.", source: "גזרון", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "יש לי גן ובאר יש לי, ועלי בארי תלוי דלי.", source: "חיים נחמן ביאליק, יש לי גן", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "בין שורות ערוגות ותלמים נערה תבוא, הברז יגעש. היא מזה רסיסי חיים, אף גבעול בצמאו לא נשכח, לא נוטש.", source: "רחל המשוררת, בגינה", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "את מתחת לעץ עומדת ואני על בד, כציפור; בצמרת זית מכספת ענפים משחירים נזמור.", source: "רחל המשוררת, גננו", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "בוסתן: גן של עצי פרי מעורבים, לא מטע של מין אחד. המילה באה מפרסית דרך הערבית, כמו רוב מה שגדל בו.", source: "גזרון", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "טרסה היא קיר אבן שתפקידו לעצור אדמה, לא לעצור אנשים. במדרונות רבים הקירות ממשיכים להחזיק את הקרקע גם בלי איש.", source: "חקלאות מסורתית", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "שמורת טבע: שטח שמנוהל בעיקר בכך שמניחים לו. השמירה כולה רשימה של דברים שנשארים כמו שהם.", source: "שמירת טבע", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "ערוגה: פס אדמה מוגבה שסביבו שביל, כדי שאפשר יהיה לטפל בצמחים בלי לדרוך על השורשים. הצורה כולה עניין של גישה.", source: "גננות", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "אמת מים היא תעלה בשיפוע קבוע ועדין מאוד. סטייה של סנטימטרים לאורך קילומטר מכריעה אם המים יגיעו לגן או לא.", source: "הנדסה עתיקה", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "שורת ברושים נשתלת בקצה חלקה כדי לשבור את הרוח. היא ממשיכה לעמוד באותו קו גם שנים אחרי שהפסיקו לעבד את החלקה.", source: "חקלאות", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "גנן שמשאיר בגינה ערמת עלים ואבנים מקבל בתוך עונה קיפודים, לטאות וחיפושיות. הפינה המוזנחת היא לרוב הפינה החיה.", source: "גננות", theme: .ground, subtheme: .aKeptPlace),
        Passage(text: "חממה עובדת מפני שהזכוכית מכניסה אור ומעכבת חום. אין בה מקור חימום כלל, והיא מחזיקה קיץ שלם בתוך חורף.", source: "פיזיקה", theme: .ground, subtheme: .aKeptPlace),
        // MARK: Travel
        Passage(text: "עכובית הגלגל מתייבשת בסוף הקיץ, נשברת מן השורש ומתגלגלת עם הרוח על פני שדות שלמים, ומפזרת זרעים בכל גלגול.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "לזרע של עץ האדר שני להבים לא שווים, ולכן הוא מסתובב בנפילה במקום ליפול ישר. הסיבוב מאט אותו, והרוח מספיקה לקחת אותו.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "מעל המצנח של זרע שן הארי נוצרת טבעת מערבולת קטנה ויציבה. היא מחזיקה אותו באוויר זמן ארוך בהרבה ממה שנראה אפשרי.", source: "אווירודינמיקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "שועל שאכל פרי מפזר את הזרעים כמה קילומטרים משם, ובתוך גוש מזון. הצמח משלם על ההסעה בפרי, ומקבל גם דישון.", source: "אקולוגיה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "בנחל אכזב זורמים מים כמה ימים בשנה בלבד. בימים האלה נעים בו זרעים עשרות קילומטרים במורד, ואחר כך שוב שנה של יובש.", source: "אקולוגיה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "תרמילים של כמה מיני קטניות מתייבשים ומתפתלים עד שהם נפתחים בפתאומיות ויורים את הזרעים כמה מטרים מן הצמח.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "דרווין גידל עשרות שתילים מן הבוץ שדבק ברגלי ציפורי מים. הוא לא זרע דבר – הוא רק שם את הבוץ בעציץ וחיכה.", source: "תולדות הבוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "אבקת אורן צפה על שלוליות ומצהיבה אותן. לכל גרגר שתי כיסות אוויר, ובהן הרוח מרימה אותו מאות קילומטרים מן העץ.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "אונייה שמזרימה מי נטל בנמל אחד ומרוקנת אותם בנמל אחר מעבירה איתם יצורים שלמים. כך הגיעו מינים לימים שלא היו בהם.", source: "אקולוגיה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "אגוז קוקוס צף חודשים במי ים בלי להיפגע, מפני שהסיבים סביבו לוכדים אוויר והקליפה אוטמת מים. הוא מגיע ונובט על החוף.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "זרע שנופל מתחת לעץ שממנו בא מתחרה באמו על אור ומים. רוב מנגנוני ההפצה קיימים כדי שזה לא יקרה.", source: "אקולוגיה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "לזרעים רבים יש קוצים זעירים שנתפסים בפרווה ובבגד. הם משתחררים רק אחרי שעות של הליכה, וזה בדיוק העניין.", source: "בוטניקה", theme: .travel, subtheme: .howASeedGoes),
        Passage(text: "דרך בעברית היא גם הכביש וגם האופן: הדרך הביתה והדרך שבה עושים משהו. אותה מילה למקום ולשיטה.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "כביש בא מן השורש כ־ב־ש, ללחוץ ולדחוס. כביש נקרא על שם הפעולה שעשתה אותו: לחצו את הקרקע עד שנעשתה דרך.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "ציפור חן, מאן ולאן? מן הקן אל תוך הגן. לילדיי אלקטה מן, גרגר שם וגרגר כאן.", source: "חיים נחמן ביאליק, ציפור בגן", theme: .travel, subtheme: .theRoad),
        Passage(text: "ערב אשובה ובפי לך שי: ברכת ההרים וברכת הגיא.", source: "חיים נחמן ביאליק, הפרפר לפרח", theme: .travel, subtheme: .theRoad),
        Passage(text: "שביל נוצר מרגליים, לא ממתכננים. הוא הולך תמיד במסלול הקל ביותר, ולכן הוא מתעקל דווקא במקומות שנראים ישרים.", source: "גאוגרפיה", theme: .travel, subtheme: .theRoad),
        Passage(text: "משעול הוא שביל צר בין שדות, נתיב הוא דרך שנקבעה, ושביל הוא מה שנדרך. שלוש מילים לשלוש דרגות של החלטה.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "דרך הבשמים חצתה את המדבר בשיירות גמלים, ולאורכה נבנו תחנות במרחק יום הליכה זו מזו. המרחק בין תחנה לתחנה נמדד ברגליים, לא בקילומטרים.", source: "ארכאולוגיה", theme: .travel, subtheme: .theRoad),
        Passage(text: "אבני מיל הוצבו לאורך דרכים רומיות במרחק קבוע, ועליהן נכתב כמה נותר. המילה מיל נשארה בעברית מאז.", source: "ארכאולוגיה", theme: .travel, subtheme: .theRoad),
        Passage(text: "צידה לדרך: מה שאורזים לפני היציאה. בעברית זו מילה נפרדת מאוכל, מפני שאוכל לדרך אינו אותו דבר כמו אוכל בבית.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "בקע הירדן הוא מסדרון נדידה בין אירופה לאפריקה. כחצי מיליארד ציפורים עוברות בו מדי שנה, פעמיים, באותו קו.", source: "אורניתולוגיה", theme: .travel, subtheme: .theRoad),
        Passage(text: "צומת: המקום שבו שתי דרכים נפגשות ונפרדות שוב. בעברית אותה מילה משמשת גם לצומת עצבים בגוף.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "נמלים מסמנות מסלול בריח, וכל נמלה שחוזרת מחזקת אותו. השביל הקצר מתחזק מהר יותר, וכך הוא נבחר בלי שאיש בחר בו.", source: "אנטומולוגיה", theme: .travel, subtheme: .theRoad),
        Passage(text: "אורח בעברית הוא גם דרך וגם מי שבא בדרך. אורח חיים ואורח בבית – אותן שלוש אותיות.", source: "עברית", theme: .travel, subtheme: .theRoad),
        Passage(text: "כשמביטים בכוכב מביטים באור שיצא ממנו לפני שנים רבות. כל מבט בשמיים הוא מבט בעבר.", source: "אסטרונומיה", theme: .travel, subtheme: .farOff),
        Passage(text: "בעברית הכיוונים נקראים על שם השמש: מזרח הוא המקום שבו היא זורחת, ומערב הוא הצד שאליו היא הולכת בערב.", source: "עברית", theme: .travel, subtheme: .farOff),
        Passage(text: "געגועים בנויה מהכפלה של שתי אותיות, כמו קול שחוזר על עצמו. הצורה של המילה עושה בדיוק את מה שהיא אומרת.", source: "עברית", theme: .travel, subtheme: .farOff),
        Passage(text: "קול של לווייתן כחול נמוך כל כך שהוא נושא מאות קילומטרים במים. שני יצורים יכולים לדבר בלי שאף אחד מהם יראה את השני.", source: "ביולוגיה ימית", theme: .travel, subtheme: .farOff),
        Passage(text: "יש ציפור חוף שעפה מאלסקה לניו זילנד ברצף אחד, יותר משבוע בלי לנחות ובלי לאכול, ומגיעה בחצי ממשקלה.", source: "אורניתולוגיה", theme: .travel, subtheme: .farOff),
        Passage(text: "המילה קינמון עברה מן העברית ליוונית ומשם לשפות אירופה. התבלין והשם שלו נסעו יחד באותה ספינה.", source: "גזרון", theme: .travel, subtheme: .farOff),
        Passage(text: "מן החללית הרחוקה ביותר שיצאה מכאן אות מגיע אחרי כיממה. שיחה אפשרית, אבל התשובה מגיעה רק למחרת.", source: "אסטרונומיה", theme: .travel, subtheme: .farOff),
        Passage(text: "מן החוף רואים עד האופק כמה קילומטרים בלבד, וממגדל בגובה עשרה מטרים רואים כפליים. המרחק תלוי בגובה ולא בעין.", source: "גאוגרפיה", theme: .travel, subtheme: .farOff),
        Passage(text: "סנונית חוזרת בכל אביב לאותו קן ממש, אחרי שעברה יבשת. עדיין חוקרים איך היא מוצאת אותו.", source: "אורניתולוגיה", theme: .travel, subtheme: .farOff),
        Passage(text: "רחוק בעברית מתאר גם מרחק וגם קרבה משפחתית: קרוב רחוק. אותה מילה למרחק בקילומטרים ולמרחק בין אנשים.", source: "עברית", theme: .travel, subtheme: .farOff),
        Passage(text: "פרפר הדנאית עובר את המסלול בכמה דורות. אף פרפר אינו עושה את הדרך כולה, והמסלול נשמר בכל זאת.", source: "אנטומולוגיה", theme: .travel, subtheme: .farOff),
        Passage(text: "מטען שנשלח באונייה נוסע חודשיים ומגיע בזול, ואותו מטען במטוס מגיע ביומיים. הזמן והמרחק נמכרים בנפרד.", source: "לוגיסטיקה", theme: .travel, subtheme: .farOff),
        // MARK: Meeting
        Passage(text: "פגישה, חצי פגישה, מבט אחד מהיר, קטעי ניבים סתומים – זה די...", source: "רחל המשוררת, פגישה, חצי פגישה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "בנקבה שנחצבה מתחת לירושלים חפרו שתי קבוצות זו מול זו. הכתובת שהשאירו שם מספרת שהכו איש לקראת רעו, גרזן לקראת גרזן.", source: "ארכאולוגיה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "להכיר מישהו ולהיות נוכרי יוצאים משורש אחד, נ־כ־ר. אותן שלוש אותיות לזר ולרגע שבו הוא כבר לא.", source: "עברית", theme: .meeting, subtheme: .theMoment),
        Passage(text: "פרפר, פרפר, פרח חי, רד נא מהר, שב עליי.", source: "חיים נחמן ביאליק, הפרח לפרפר", theme: .meeting, subtheme: .theMoment),
        Passage(text: "כששני נהרות מתאחדים אפשר לראות לפעמים קילומטרים של קו ברור ביניהם. הם זורמים יחד זמן רב לפני שהם באמת מתערבבים.", source: "הידרולוגיה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "בהרכבה מניחים ענף על גזע כך שהשכבה הדקה שמתחת לקליפה תיגע בשכבה המקבילה. אם הן נגעו, שני העצים נעשים אחד.", source: "גננות", theme: .meeting, subtheme: .theMoment),
        Passage(text: "מנעול נפתח ברגע שכל הגלילים שבו עומדים בדיוק על קו אחד. עד אז לא קרה כלום, ומאז הוא כבר לא נעול.", source: "מכניקה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "לפעמים, בשנייה האחרונה של השקיעה מעל ים נקי, נראה הבזק ירוק. הוא נמשך פחות משנייה, ורוב האנשים לא ראו אותו מעולם.", source: "אופטיקה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "שתי בועות סבון שנוגעות נצמדות בקיר משותף אחד, וכל שלוש דפנות שנפגשות עושות זאת תמיד בזווית שווה. אין לזה יוצא מן הכלל.", source: "פיזיקה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "חזית: הקו שבו גוש אוויר חם פוגש גוש קר. הענן נבנה בדיוק על הקו הזה, ולכן אפשר לראות מלמטה היכן הם נוגעים.", source: "מטאורולוגיה", theme: .meeting, subtheme: .theMoment),
        Passage(text: "רגע והרגעה יוצאים מאותן שלוש אותיות. בעברית פרק הזמן הקצר ביותר והשקט קרויים בשם אחד.", source: "עברית", theme: .meeting, subtheme: .theMoment),
        Passage(text: "בעברית יש בניין שלם למה ששניים עושים זה לזה: נפגשו, התכתבו, התיידדו, התחבקו. אי אפשר להטות אותו ליחיד.", source: "דקדוק עברי", theme: .meeting, subtheme: .theMoment),
        Passage(text: "המילה זוג הגיעה לעברית מיוונית, ושם פירושה היה עול של שני שוורים. הרעיון של שניים שנרתמו לאותה עבודה נשאר בה.", source: "גזרון", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "שנינו פרחים – אח ואח, פרחך לי ופרחי לך.", source: "חיים נחמן ביאליק, הפרח לפרפר", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "לתאנה יש צרעה משלה, ולצרעה יש רק את התאנה. הפרח נמצא כולו בתוך הפרי, והצרעה נכנסת דרך פתח שרוחבו כרוחבה.", source: "אנטומולוגיה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "חזזית אינה יצור אחד אלא שניים: פטרייה שמחזיקה את המבנה ואצה שמייצרת את המזון. לבד אף אחד מהם לא היה גדל שם.", source: "ביולוגיה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "עצי תמר נחלקים לזכרים ולנקבות. במטע שלם של נקבות לא יהיה פרי, ולכן משאירים תמיד כמה עצים שאינם נותנים דבר.", source: "חקלאות", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "רוב זני התפוח אינם קושרים פרי מאבקת עצמם. במטע שותלים תמיד עץ מזן אחר, לפעמים אחד לכל עשרה, רק כדי שיהיה פרי.", source: "חקלאות", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "דרווין ראה סחלב שצופו בתחתית צינור באורך שליש מטר, ואמר שחייב להיות עש עם לשון כזאת. מצאו אותו עשרות שנים אחר כך.", source: "תולדות הבוטניקה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "לשורשי קטניות יש פקעיות ובהן חיידקים שקושרים חנקן מן האוויר. הצמח נותן סוכר, החיידק נותן דשן, ואין להם דרך אחרת.", source: "בוטניקה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "אלמוג בונה שלד ואצה זעירה שגרה בתוכו מייצרת לו מזון. כשהמים מתחממים האצה עוזבת, והאלמוג מלבין ורעב.", source: "ביולוגיה ימית", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "כנה ורוכב: החלק התחתון של עץ מורכב נבחר לפי הקרקע והחלק העליון לפי הפרי. שני עצים שונים לגמרי, גזע אחד.", source: "גננות", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "בורג ואום נחתכים באותו תבריג בדיוק, ורק בזכות זה הם אוחזים. שניים שנעשו בנפרד יסתובבו זה על זה לריק.", source: "מכניקה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "שני מיתרים שמכוונים לאותו צליל: אם פורטים על האחד, השני מתחיל לרעוד לבדו. שום דבר לא נגע בו מלבד האוויר.", source: "אקוסטיקה", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "בערוגת הגינה מסביב לחבית עמדו לרקד כרוב עם כרובית.", source: "חיים נחמן ביאליק, בגינת הירק", theme: .meeting, subtheme: .twoThatNeedEachOther),
        Passage(text: "ברוך הבא משנה צורה לפי מי שנכנס: ברוכה הבאה, ברוכים הבאים. בעברית אי אפשר לקבל מישהו בלי להגיד מי הוא.", source: "ניב עברי", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "האני אכלים את היד המושטת לי לשלום?", source: "רחל המשוררת, אביב", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "להתראות אינו פרידה אלא הבטחה: עד שנתראה. הוא הנפוץ מבין הפרידות בעברית, וכל מי שאומר אותו אומר שיהיה עוד משהו.", source: "עברית", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "דרך ארץ: המילה העברית לנימוס. לא כלל ולא חוק אלא הדרך שנוהגים בה במקום שאתה נמצא בו.", source: "ניב עברי", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "שלום לך, פרח, וברכה בלי די, שלום וברכה, מהר ומגיא!", source: "חיים נחמן ביאליק, הפרפר לפרח", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "נעים מאוד: מה שאומרים בעברית ברגע שמכירים מישהו. לא שאלה ולא הצהרה אלא דיווח קצר על מה שקורה כרגע.", source: "ניב עברי", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "אעולל כגפן שארית הרחש ואשלח מנחה לך מזמרת ליבי.", source: "רחל המשוררת, שי", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "קומי שימי פיך עם פי, גרגר לך וגרגר לי.", source: "חיים נחמן ביאליק, ציפורים ודובדבן", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "בבקשה בעברית עושה שלוש עבודות: מבקשים בה, מגישים בה, ועונים בה לתודה. מילה אחת לשלושה צדדים של אותו מעמד.", source: "עברית", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "כיבוד: מה שמניחים על השולחן לפני אורח. אותן אותיות כמו כבוד, ובעברית ההגשה והכבוד הם מילה אחת.", source: "עברית", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "אהלן נכנס לעברית מן הערבית, ושם הוא אומר בערך: אתה בין משפחה. זה הפך לשלום היום־יומי ביותר שיש.", source: "גזרון", theme: .meeting, subtheme: .theMannersOfIt),
        Passage(text: "בעברית פונים לאדם אחד בלשון זכר או בלשון נקבה, ואין צורה שלישית. כל פנייה מחייבת לבחור, וכל בחירה נשמעת.", source: "עברית מדוברת", theme: .meeting, subtheme: .theMannersOfIt),
        // MARK: Kinship
        Passage(text: "כששני ענפים נשענים זה על זה שנים ארוכות, הקליפה נשחקת והרקמות מתאחות. אחר כך אי אפשר להפריד ביניהם בלי לחתוך.", source: "בוטניקה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "חבר וחיבור יוצאים משורש אחד, ומאותו שורש גם מחברת. בעברית ידיד הוא בראש ובראשונה מי שמחובר אליך.", source: "עברית", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "עם אבני השדה בריתי, לי רעים בסתר הים, ושיחת אילנות אבין.", source: "רחל המשוררת, אביב", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "עצים סמוכים מאותו מין מאחים לפעמים את שורשיהם. גדם שנכרת יכול להישאר חי שנים מפני שהשכנים ממשיכים להזין אותו.", source: "בוטניקה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "פטריות הקרקע קושרות את שורשי היער לרשת אחת. סוכר שנוצר בעץ אחד נמצא כעבור ימים בעץ אחר שאין לו די אור.", source: "אקולוגיה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "חבל חזק מסכום החוטים שבו. החוזק כולו בחיכוך בין הגדילים, כלומר בכך שהם משוזרים ולא רק מונחים יחד.", source: "מכניקה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "מחמצת נשמרת בבית ומחלקים ממנה לשכנים. כל מחמצת בעיר יכולה להיות שלוחה של אחת, ובכל בית היא נעשית מעט אחרת.", source: "אפייה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "קיסוס מטפס בשורשונים זעירים שנאחזים בקיר ואינם מוצצים ממנו דבר. הוא נשען, לא נטפל, וכשמורידים אותו הסימן נשאר.", source: "בוטניקה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "בקבוצת עצים שגדלים צפוף אין לאף אחד צמרת עגולה. כל אחד נסוג מפני שכנו, ומלמעלה נראים ביניהם קווי רווח מדויקים.", source: "אקולוגיה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "בלהקת זרזירים כל ציפור עוקבת אחרי שבע שכנותיה בלבד. מזה, ורק מזה, נוצרת התנועה של האלפים כאילו הם גוף אחד.", source: "אורניתולוגיה", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "אספסת ותירס שנזרעים יחד בשדה אחד נותנים יבול גדול משהיו נותנים לחוד. אחד לוקח מן העומק והשני מלמעלה.", source: "חקלאות", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "בגפן זקנה מתפתלים כמה גזעים סביב עצמם עד שאין לדעת מי מהם עלה ראשון. הגנן מפסיק לספור ומטפל בכולם כאחד.", source: "גידול גפנים", theme: .kinship, subtheme: .grownTogether),
        Passage(text: "לפרגן נכנס לעברית מיידיש: לשמוח במה שטוב לאדם אחר בלי לגרוע ממנו. לא ויתור ולא נדיבות – פשוט לא לקנא.", source: "עברית מדוברת", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "אח בעברית הוא גם בן להורים שלך וגם הכוך שבקיר שבו בוערת האש. שתי המילים עתיקות, ושתיהן על אותן שתי אותיות.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "רעות היא ידידות בין שווים, ורע הוא מי שנמצא איתך. זו הקרבה שהעברית מציעה מחוץ למשפחה ומחוץ לאהבה.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "לכל קרוב חיתון בעברית יש שם משלו: חם, חמות, גיס, גיסה, חתן, כלה. שפות רבות מסתדרות עם צירוף, ולעברית יש מילה.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "סבא וסבתא הגיעו לעברית מן הארמית, ופירושם שם פשוט: הזקן והזקנה. שתי המילים החמות ביותר בשפה הן מילים שאולות.", source: "גזרון", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "שאר בשר: הביטוי העברי לקרוב דם. שאר פירושו מה שנשאר, וקרבה כאן היא מה שנותר מגוף אחד בשני אנשים.", source: "ניב עברי", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "חבר בעברית של היום הוא ידיד, בן זוג, חבר בארגון וחבר בוועדה. מילה אחת לכל דרך שיש להיות שייך.", source: "עברית מדוברת", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "אחווה נגזרת מאח וידידות מידיד. שם היחס נבנה בעברית מן השם של האדם שעומד בו.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "דוד בעברית הוא גם אחי ההורה וגם אהוב. שתי המשמעויות התקיימו זו לצד זו אלפי שנים ואיש לא התבלבל.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "בן זוג ובת זוג בנויים מן המילה זוג, שבאה במקורה מעול של שני שוורים. השם של החיבור קדם לשם של מי שנמצא בו.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "התיידדות נאמרת בעברית בבניין שמתאר פעולה הדדית, כמו התכתבות והתנגשות. השפה מסרבת לתת לאדם אחד להתיידד לבדו.", source: "דקדוק עברי", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "אמון, אמונה ומשפחת אומנה יוצאים כולם מן השורש א־מ־ן. לסמוך על מישהו ולגדל ילד של אחר נקראים באותן שלוש אותיות.", source: "עברית", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "בעברית מצרפים לשם הפרטי את שם ההורה: בן־ ובת־. שמות משפחה שלמים נבנו כך, וכל אחד מהם הוא בעצם משפט על שני אנשים.", source: "דקדוק עברי", theme: .kinship, subtheme: .theWordsForIt),
        Passage(text: "מה למעלה? מה למטה? רק אני, אני ואתה.", source: "חיים נחמן ביאליק, נדנדה", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "שנינו שקולים במאזניים בין הארץ לשמיים.", source: "חיים נחמן ביאליק, נדנדה", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "שחקי כי גם ברעות אאמין, אאמין כי עוד אמצא לב, לב תקוותיי גם תקוותיו, יחוש אושר, יבין כאב.", source: "שאול טשרניחובסקי, אני מאמין", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "תלולית החול שמש רוותה, על תלולית החול – אני ואתה, ובלב אושר שלו.", source: "רחל המשוררת, אושר שלו", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "מפחד בלילות מגן לי ומשמרת ריבוע אור זהוב של חלונו.", source: "רחל המשוררת, שכן", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "שני אנשים שהולכים יחד מתחילים אחרי דקות ספורות לצעוד באותו קצב. אף אחד מהם לא הציע את זה ולרוב איש לא שם לב.", source: "פסיכולוגיה", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "בשיחה ארוכה שני דוברים מתקרבים זה לזה בקצב הדיבור, במילים ואפילו בהגייה. אנשים מתאימים את עצמם בלי להתכוון.", source: "בלשנות", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "הויגנס שם שני שעוני מטוטלת על אותה קורה וראה שהם מכוונים את עצמם זה לזה. הרעד הקטן שעובר בעץ הוא כל מה שנדרש.", source: "תולדות המדע", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "פיהוק עובר מאדם לאדם, והוא עובר חזק יותר בין אנשים שמכירים זה את זה. המרחק ביניהם נמדד בעצם בכמה מהר הוא עבר.", source: "פסיכולוגיה", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "כשבן־יהודה החליט לדבר עברית בבית, איש לא דיבר בה בבית באותה עת. אחריו הצטרפו ארבע משפחות, ומשם זה כבר לא נעצר.", source: "תולדות הלשון", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "בשניים שנושאים ארגז ארוך, כל אחד מרגיש מיד כל שינוי אצל השני. המשקל מספר להם מה קורה, בלי להסתובב ובלי מילה.", source: "אקוסטיקה", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "לשתי נעליים אומרים זוג, לשני זמרים צמד, ולשתי מילים שהולכות יחד צירוף. אותו מספר, שלוש מילים שונות.", source: "עברית", theme: .kinship, subtheme: .twoPeople),
        Passage(text: "שני חוטרים שיצאו מאותו שורש הם למעשה אותו צמח. אפשר לחפור ולראות שהם מחוברים, ואפשר גם לא לחפור.", source: "בוטניקה", theme: .kinship, subtheme: .twoPeople),
        // MARK: Peace
        Passage(text: "כל העולם ישן – הס! נם תפוח ואגס; אימי נמה, נרדם אבי, ערים רק אני ולבבי.", source: "חיים נחמן ביאליק, יש לי גן", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "קן לציפור בין העצים, ובקן לה שלוש ביצים. ובכל ביצה – הס, פן תעיר – ישן לו אפרוח זעיר.", source: "חיים נחמן ביאליק, קן ציפור", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "התקלוט אוזנך אף מתוך שתיקה את ניבי השח?", source: "רחל המשוררת, ניב", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "אוושה היא רחש קל של עלים ברוח, והיא גם שמו של הקול שמשמיע שסתום בלב שאינו נסגר היטב. אותה מילה לשניהם.", source: "עברית", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "רחש: קול שנמצא בדיוק על הגבול שבו האוזן עוד קולטת. מאותו שורש גם רחשי לב – מה שאדם חושב ואינו אומר.", source: "עברית", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "לעברית ארבעה שקטים: שקט הוא היעדר רעש, דממה היא שקט שמורגש, דומייה היא שקט שנבחר, ושתיקה היא אדם שאינו מדבר.", source: "עברית", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "חרש פירושו בלחש, וחירש הוא מי שאינו שומע, ולהחריש הוא לשתוק. שלושתם על אותן שלוש אותיות, ח־ר־ש.", source: "עברית", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "לתנשמת יש מסרק זעיר בקצה הכנף שמפרק את מערבולות האוויר. לכן היא עפה בלי קול, והעכבר מתחתיה אינו שומע דבר.", source: "אורניתולוגיה", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "הס היא מילה שכל תפקידה לבקש שקט. היא עומדת תמיד באותה צורה אחת, בלי זמן ובלי גוף.", source: "עברית", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "בחדר חסר הדים אין החזר קול כלל, וכעבור דקות אנשים מתחילים לשמוע את זרימת דמם ואת פרקיהם. שקט מוחלט אינו שקט.", source: "אקוסטיקה", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "בחוקי העזר של ערים בארץ נקבעות שעות מנוחה, אחר הצהריים ובלילה. השקט הוא כמעט הדבר היחיד שהחוק מחייב שכן לתת לשכנו.", source: "חוקי עזר", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "שלג טרי בולע קול מפני שבין הפתיתים יש אוויר לרוב. לכן אחרי לילה של שלג העולם נשמע אחרת, ולא רק נראה אחרת.", source: "אקוסטיקה", theme: .peace, subtheme: .quietAsASound),
        Passage(text: "שלום בא מן השורש ש־ל־ם, שממנו גם שלם, השלים ותשלום. שלום בעברית אינו הפסקת רעש אלא מצב שבו שום דבר אינו חסר.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "שלום נאמר בעברית למי שנכנס, למי שיוצא, ולמה ששורר בין שני צדדים. מילה אחת לשלושתם.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "להשלים עם משהו פירושו לקבל אותו כמו שהוא. זה אותו פועל שבו משלימים חסר, ואותו פועל שבו עושים שלום.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "פסיק, פסקה, הפסקה ופסק דין יוצאים כולם מן השורש פ־ס־ק. בעברית לעצור ולהכריע הם אותו פועל.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "הפוגה: הפסקה קצרה בתוך דבר שממשיך אחריה. מאותו שורש גם פג – מה שתוקפו נגמר מעצמו, בלי שאיש ביטל אותו.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "מנוחה, נחת ומנוח יוצאים מן השורש נ־ו־ח. בעברית לנוח אינו להפסיק לעבוד אלא להניח משהו במקומו ולא להזיז אותו עוד.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "שקט תעשייתי: ביטוי מעולם העבודה, הסכמה בין שני צדדים שלא יעשו זה לזה דבר במשך תקופה מוסכמת. שקט שנקבע בכתב.", source: "ניב עברי", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "סוף פסוק: מה שאומרים כשהעניין נגמר. במקורו זהו שמו של סימן פיסוק, ובדיבור הוא סירוב מנומס להמשיך.", source: "ניב עברי", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "די היא הברה אחת שאומרת גם מספיק וגם הפסק. שתי המשמעויות נשמעות בה תמיד יחד.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "הרפיה בנויה מן השורש ר־פ־ה, לשחרר מתח. אותו שורש נותן גם ידיים רפות – והמילה אינה קובעת אם זה טוב או רע.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "חדל בעברית הוא גם ציווי להפסיק וגם תיאור של דבר שנפסק מאליו. אותה מילה למי שביקש ולמה שפשוט נגמר.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "דממת מנועים: הצירוף שאומרים כשמנוע נעצר. השקט שבו אינו היעדר קול אלא הודעה שמשהו הפסיק לעבוד.", source: "ימאות", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "לילה טוב אינו איחול לשינה אלא ללילה עצמו. בעברית מאחלים ליחידת הזמן ולא לאדם שנמצא בה.", source: "עברית", theme: .peace, subtheme: .theWordsForStopping),
        Passage(text: "חצאי צבעים, חצאי קולות, לא צריך לשאול, לא צריך לענות. הבט, הקשב.", source: "רחל המשוררת, אושר שלו", theme: .peace, subtheme: .atEase),
        Passage(text: "חופי ירדן: מלוא זוהר יום. סירת דוגה; אשכב אשתה שיקוי שלום.", source: "רחל המשוררת, שבת", theme: .peace, subtheme: .atEase),
        Passage(text: "רסיסי טללים קיננו לילה בכפתור השושנה.", source: "שאול טשרניחובסקי", theme: .peace, subtheme: .atEase),
        Passage(text: "נחת: לא אושר ולא הקלה אלא שקט של מי שהדברים אצלו מונחים במקומם. אין למילה הזאת מקבילה נוחה ברוב השפות.", source: "עברית", theme: .peace, subtheme: .atEase),
        Passage(text: "צל של עץ קריר בכמה מעלות מצל של גג. העלים מאדים מים ומקררים את האוויר, ולא רק חוסמים שמש.", source: "פיזיקה", theme: .peace, subtheme: .atEase),
        Passage(text: "פרה שרובצת ומעלה גירה היא פרה שהכול אצלה בסדר. רפתנים סופרים כמה מהעדר רובצות, וזו הבדיקה הראשונה שהם עושים.", source: "רפת", theme: .peace, subtheme: .atEase),
        Passage(text: "בים שריכוז המלח בו גבוה מאוד גוף אדם צף מעצמו. אי אפשר לשקוע בו כששוכבים על הגב, ואין צורך לעשות דבר.", source: "פיזיקה", theme: .peace, subtheme: .atEase),
        Passage(text: "כשהנשיפה ארוכה מן השאיפה, קצב הלב יורד מעצמו. זה קורה גם למי שאינו יודע שזה קורה, וזה כל המנגנון.", source: "פיזיולוגיה", theme: .peace, subtheme: .atEase),
        Passage(text: "אבן שספגה שמש כל היום נשארת חמימה שעות אחרי השקיעה. חתולים יודעים על זה הרבה לפני שמישהו מדד את זה.", source: "פיזיקה", theme: .peace, subtheme: .atEase),
        Passage(text: "מנוחת הצהריים היא הרגל של ארצות חמות ולא של אנשים עצלים. בשעות שבהן העבודה בחוץ בזבזנית, מפסיקים אותה.", source: "אנתרופולוגיה", theme: .peace, subtheme: .atEase),
        Passage(text: "כלב שנרדם על הגב חושף את הבטן, החלק הרך ביותר שיש לו. זו הצהרה שהמקום שבו הוא שוכב בטוח.", source: "התנהגות בעלי חיים", theme: .peace, subtheme: .atEase),
        Passage(text: "אחרי גשם הלחות באוויר גבוהה והאבק שקע. זו הסיבה שהאוויר נשמע ונראה נקי יותר, ולא רק מפני שהוא קריר.", source: "מטאורולוגיה", theme: .peace, subtheme: .atEase),
        Passage(text: "בקצה יום עבודה בגן שוטפים את הכלים ומניחים אותם במקומם, ורק אז יושבים. הישיבה טובה יותר כשהכול כבר סגור.", source: "גננות", theme: .peace, subtheme: .atEase),
    ]
}
